# SPDX-License-Identifier: GPL-2.0+
#
# Copyright (c) 2025 Ventana Micro Systems
KBUILD_CFLAGS += -I$(srctree)/lib/rv_etrace/include/
obj-y += rv_etrace_bits.o rv_etrace_display.o rv_etrace_encap.o rv_etrace_itrace.o rv_etrace_payload.o
