/* This file is auto-generated. Do not hand edit this file. */

#ifndef VT1_LWIC_MMR_H
#define VT1_LWIC_MMR_H

#ifndef _ULL

#ifdef __ASSEMBLER__
#define _AC(X,Y) X
#else
#define __AC(X,Y) (X##Y)
#define _AC(X,Y) __AC(X,Y)
#endif

#define _ULL(x)  (_AC(x, ULL))
#endif


#define VT1_LWIC_MMODETIMECMP0_OFFSET _ULL(0x0)

#define VT1_LWIC_MMODETIMECMP0_POS 0
#define VT1_LWIC_MMODETIMECMP0_WID 64
#define VT1_LWIC_MMODETIMECMP0_MSK (((_ULL(1) << VT1_LWIC_MMODETIMECMP0_WID) - _ULL(1)) << VT1_LWIC_MMODETIMECMP0_POS)

#define VT1_LWIC_MMODETIMECMP0_COMPARE_POS 0
#define VT1_LWIC_MMODETIMECMP0_COMPARE_WID 64
#define VT1_LWIC_MMODETIMECMP0_COMPARE_MSK (((_ULL(1) << VT1_LWIC_MMODETIMECMP0_COMPARE_WID) - _ULL(1)) << VT1_LWIC_MMODETIMECMP0_COMPARE_POS)

#define VT1_LWIC_MMODETIMECMP1_OFFSET _ULL(0x1)

#define VT1_LWIC_MMODETIMECMP1_POS 0
#define VT1_LWIC_MMODETIMECMP1_WID 64
#define VT1_LWIC_MMODETIMECMP1_MSK (((_ULL(1) << VT1_LWIC_MMODETIMECMP1_WID) - _ULL(1)) << VT1_LWIC_MMODETIMECMP1_POS)

#define VT1_LWIC_MMODETIMECMP1_COMPARE_POS 0
#define VT1_LWIC_MMODETIMECMP1_COMPARE_WID 64
#define VT1_LWIC_MMODETIMECMP1_COMPARE_MSK (((_ULL(1) << VT1_LWIC_MMODETIMECMP1_COMPARE_WID) - _ULL(1)) << VT1_LWIC_MMODETIMECMP1_COMPARE_POS)

#define VT1_LWIC_MMODETIMECMP2_OFFSET _ULL(0x2)

#define VT1_LWIC_MMODETIMECMP2_POS 0
#define VT1_LWIC_MMODETIMECMP2_WID 64
#define VT1_LWIC_MMODETIMECMP2_MSK (((_ULL(1) << VT1_LWIC_MMODETIMECMP2_WID) - _ULL(1)) << VT1_LWIC_MMODETIMECMP2_POS)

#define VT1_LWIC_MMODETIMECMP2_COMPARE_POS 0
#define VT1_LWIC_MMODETIMECMP2_COMPARE_WID 64
#define VT1_LWIC_MMODETIMECMP2_COMPARE_MSK (((_ULL(1) << VT1_LWIC_MMODETIMECMP2_COMPARE_WID) - _ULL(1)) << VT1_LWIC_MMODETIMECMP2_COMPARE_POS)

#define VT1_LWIC_MMODETIMECMP3_OFFSET _ULL(0x3)

#define VT1_LWIC_MMODETIMECMP3_POS 0
#define VT1_LWIC_MMODETIMECMP3_WID 64
#define VT1_LWIC_MMODETIMECMP3_MSK (((_ULL(1) << VT1_LWIC_MMODETIMECMP3_WID) - _ULL(1)) << VT1_LWIC_MMODETIMECMP3_POS)

#define VT1_LWIC_MMODETIMECMP3_COMPARE_POS 0
#define VT1_LWIC_MMODETIMECMP3_COMPARE_WID 64
#define VT1_LWIC_MMODETIMECMP3_COMPARE_MSK (((_ULL(1) << VT1_LWIC_MMODETIMECMP3_COMPARE_WID) - _ULL(1)) << VT1_LWIC_MMODETIMECMP3_COMPARE_POS)

#define VT1_LWIC_MMODETIMECMP4_OFFSET _ULL(0x4)

#define VT1_LWIC_MMODETIMECMP4_POS 0
#define VT1_LWIC_MMODETIMECMP4_WID 64
#define VT1_LWIC_MMODETIMECMP4_MSK (((_ULL(1) << VT1_LWIC_MMODETIMECMP4_WID) - _ULL(1)) << VT1_LWIC_MMODETIMECMP4_POS)

#define VT1_LWIC_MMODETIMECMP4_COMPARE_POS 0
#define VT1_LWIC_MMODETIMECMP4_COMPARE_WID 64
#define VT1_LWIC_MMODETIMECMP4_COMPARE_MSK (((_ULL(1) << VT1_LWIC_MMODETIMECMP4_COMPARE_WID) - _ULL(1)) << VT1_LWIC_MMODETIMECMP4_COMPARE_POS)

#define VT1_LWIC_MMODETIMECMP5_OFFSET _ULL(0x5)

#define VT1_LWIC_MMODETIMECMP5_POS 0
#define VT1_LWIC_MMODETIMECMP5_WID 64
#define VT1_LWIC_MMODETIMECMP5_MSK (((_ULL(1) << VT1_LWIC_MMODETIMECMP5_WID) - _ULL(1)) << VT1_LWIC_MMODETIMECMP5_POS)

#define VT1_LWIC_MMODETIMECMP5_COMPARE_POS 0
#define VT1_LWIC_MMODETIMECMP5_COMPARE_WID 64
#define VT1_LWIC_MMODETIMECMP5_COMPARE_MSK (((_ULL(1) << VT1_LWIC_MMODETIMECMP5_COMPARE_WID) - _ULL(1)) << VT1_LWIC_MMODETIMECMP5_COMPARE_POS)

#define VT1_LWIC_MMODETIMECMP6_OFFSET _ULL(0x6)

#define VT1_LWIC_MMODETIMECMP6_POS 0
#define VT1_LWIC_MMODETIMECMP6_WID 64
#define VT1_LWIC_MMODETIMECMP6_MSK (((_ULL(1) << VT1_LWIC_MMODETIMECMP6_WID) - _ULL(1)) << VT1_LWIC_MMODETIMECMP6_POS)

#define VT1_LWIC_MMODETIMECMP6_COMPARE_POS 0
#define VT1_LWIC_MMODETIMECMP6_COMPARE_WID 64
#define VT1_LWIC_MMODETIMECMP6_COMPARE_MSK (((_ULL(1) << VT1_LWIC_MMODETIMECMP6_COMPARE_WID) - _ULL(1)) << VT1_LWIC_MMODETIMECMP6_COMPARE_POS)

#define VT1_LWIC_MMODETIMECMP7_OFFSET _ULL(0x7)

#define VT1_LWIC_MMODETIMECMP7_POS 0
#define VT1_LWIC_MMODETIMECMP7_WID 64
#define VT1_LWIC_MMODETIMECMP7_MSK (((_ULL(1) << VT1_LWIC_MMODETIMECMP7_WID) - _ULL(1)) << VT1_LWIC_MMODETIMECMP7_POS)

#define VT1_LWIC_MMODETIMECMP7_COMPARE_POS 0
#define VT1_LWIC_MMODETIMECMP7_COMPARE_WID 64
#define VT1_LWIC_MMODETIMECMP7_COMPARE_MSK (((_ULL(1) << VT1_LWIC_MMODETIMECMP7_COMPARE_WID) - _ULL(1)) << VT1_LWIC_MMODETIMECMP7_COMPARE_POS)

#define VT1_LWIC_MTIME_OFFSET _ULL(0x1ff)

#define VT1_LWIC_MTIME_POS 0
#define VT1_LWIC_MTIME_WID 64
#define VT1_LWIC_MTIME_MSK (((_ULL(1) << VT1_LWIC_MTIME_WID) - _ULL(1)) << VT1_LWIC_MTIME_POS)

#define VT1_LWIC_MTIME_TIME_POS 0
#define VT1_LWIC_MTIME_TIME_WID 64
#define VT1_LWIC_MTIME_TIME_MSK (((_ULL(1) << VT1_LWIC_MTIME_TIME_WID) - _ULL(1)) << VT1_LWIC_MTIME_TIME_POS)

#define VT1_LWIC_TIMERINCEN_OFFSET _ULL(0x200)

#define VT1_LWIC_TIMERINCEN_POS 0
#define VT1_LWIC_TIMERINCEN_WID 1
#define VT1_LWIC_TIMERINCEN_MSK (((_ULL(1) << VT1_LWIC_TIMERINCEN_WID) - _ULL(1)) << VT1_LWIC_TIMERINCEN_POS)

#define VT1_LWIC_TIMERINCEN_ENABLE_POS 0
#define VT1_LWIC_TIMERINCEN_ENABLE_WID 1
#define VT1_LWIC_TIMERINCEN_ENABLE_MSK (((_ULL(1) << VT1_LWIC_TIMERINCEN_ENABLE_WID) - _ULL(1)) << VT1_LWIC_TIMERINCEN_ENABLE_POS)

#define VT1_LWIC_TIMERINCDIV_OFFSET _ULL(0x201)

#define VT1_LWIC_TIMERINCDIV_POS 0
#define VT1_LWIC_TIMERINCDIV_WID 2
#define VT1_LWIC_TIMERINCDIV_MSK (((_ULL(1) << VT1_LWIC_TIMERINCDIV_WID) - _ULL(1)) << VT1_LWIC_TIMERINCDIV_POS)

#define VT1_LWIC_TIMERINCDIV_DIVIDE_POS 0
#define VT1_LWIC_TIMERINCDIV_DIVIDE_WID 2
#define VT1_LWIC_TIMERINCDIV_DIVIDE_MSK (((_ULL(1) << VT1_LWIC_TIMERINCDIV_DIVIDE_WID) - _ULL(1)) << VT1_LWIC_TIMERINCDIV_DIVIDE_POS)
#endif /* VT1_LWIC_MMR_H */
