/* This file is auto-generated. Do not hand edit this file. */

#ifndef VT1_ICS_MMR_H
#define VT1_ICS_MMR_H

#ifndef _ULL

#ifdef __ASSEMBLER__
#define _AC(X,Y) X
#else
#define __AC(X,Y) (X##Y)
#define _AC(X,Y) __AC(X,Y)
#endif

#define _ULL(x)  (_AC(x, ULL))
#endif


#define VT1_ICS_ICSREQCREDITS0_OFFSET _ULL(0x0)

#define VT1_ICS_ICSREQCREDITS0_POS 0
#define VT1_ICS_ICSREQCREDITS0_WID 16
#define VT1_ICS_ICSREQCREDITS0_MSK (((_ULL(1) << VT1_ICS_ICSREQCREDITS0_WID) - _ULL(1)) << VT1_ICS_ICSREQCREDITS0_POS)

#define VT1_ICS_ICSREQCREDITS0_MAXCREDITS_POS 0
#define VT1_ICS_ICSREQCREDITS0_MAXCREDITS_WID 8
#define VT1_ICS_ICSREQCREDITS0_MAXCREDITS_MSK (((_ULL(1) << VT1_ICS_ICSREQCREDITS0_MAXCREDITS_WID) - _ULL(1)) << VT1_ICS_ICSREQCREDITS0_MAXCREDITS_POS)
#define VT1_ICS_ICSREQCREDITS0_OUTSTANDING_POS 8
#define VT1_ICS_ICSREQCREDITS0_OUTSTANDING_WID 8
#define VT1_ICS_ICSREQCREDITS0_OUTSTANDING_MSK (((_ULL(1) << VT1_ICS_ICSREQCREDITS0_OUTSTANDING_WID) - _ULL(1)) << VT1_ICS_ICSREQCREDITS0_OUTSTANDING_POS)

#define VT1_ICS_ICSREQCREDITS1_OFFSET _ULL(0x1)

#define VT1_ICS_ICSREQCREDITS1_POS 0
#define VT1_ICS_ICSREQCREDITS1_WID 16
#define VT1_ICS_ICSREQCREDITS1_MSK (((_ULL(1) << VT1_ICS_ICSREQCREDITS1_WID) - _ULL(1)) << VT1_ICS_ICSREQCREDITS1_POS)

#define VT1_ICS_ICSREQCREDITS1_MAXCREDITS_POS 0
#define VT1_ICS_ICSREQCREDITS1_MAXCREDITS_WID 8
#define VT1_ICS_ICSREQCREDITS1_MAXCREDITS_MSK (((_ULL(1) << VT1_ICS_ICSREQCREDITS1_MAXCREDITS_WID) - _ULL(1)) << VT1_ICS_ICSREQCREDITS1_MAXCREDITS_POS)
#define VT1_ICS_ICSREQCREDITS1_OUTSTANDING_POS 8
#define VT1_ICS_ICSREQCREDITS1_OUTSTANDING_WID 8
#define VT1_ICS_ICSREQCREDITS1_OUTSTANDING_MSK (((_ULL(1) << VT1_ICS_ICSREQCREDITS1_OUTSTANDING_WID) - _ULL(1)) << VT1_ICS_ICSREQCREDITS1_OUTSTANDING_POS)

#define VT1_ICS_ICSREQCREDITS2_OFFSET _ULL(0x2)

#define VT1_ICS_ICSREQCREDITS2_POS 0
#define VT1_ICS_ICSREQCREDITS2_WID 16
#define VT1_ICS_ICSREQCREDITS2_MSK (((_ULL(1) << VT1_ICS_ICSREQCREDITS2_WID) - _ULL(1)) << VT1_ICS_ICSREQCREDITS2_POS)

#define VT1_ICS_ICSREQCREDITS2_MAXCREDITS_POS 0
#define VT1_ICS_ICSREQCREDITS2_MAXCREDITS_WID 8
#define VT1_ICS_ICSREQCREDITS2_MAXCREDITS_MSK (((_ULL(1) << VT1_ICS_ICSREQCREDITS2_MAXCREDITS_WID) - _ULL(1)) << VT1_ICS_ICSREQCREDITS2_MAXCREDITS_POS)
#define VT1_ICS_ICSREQCREDITS2_OUTSTANDING_POS 8
#define VT1_ICS_ICSREQCREDITS2_OUTSTANDING_WID 8
#define VT1_ICS_ICSREQCREDITS2_OUTSTANDING_MSK (((_ULL(1) << VT1_ICS_ICSREQCREDITS2_OUTSTANDING_WID) - _ULL(1)) << VT1_ICS_ICSREQCREDITS2_OUTSTANDING_POS)

#define VT1_ICS_ICSREQCREDITS3_OFFSET _ULL(0x3)

#define VT1_ICS_ICSREQCREDITS3_POS 0
#define VT1_ICS_ICSREQCREDITS3_WID 16
#define VT1_ICS_ICSREQCREDITS3_MSK (((_ULL(1) << VT1_ICS_ICSREQCREDITS3_WID) - _ULL(1)) << VT1_ICS_ICSREQCREDITS3_POS)

#define VT1_ICS_ICSREQCREDITS3_MAXCREDITS_POS 0
#define VT1_ICS_ICSREQCREDITS3_MAXCREDITS_WID 8
#define VT1_ICS_ICSREQCREDITS3_MAXCREDITS_MSK (((_ULL(1) << VT1_ICS_ICSREQCREDITS3_MAXCREDITS_WID) - _ULL(1)) << VT1_ICS_ICSREQCREDITS3_MAXCREDITS_POS)
#define VT1_ICS_ICSREQCREDITS3_OUTSTANDING_POS 8
#define VT1_ICS_ICSREQCREDITS3_OUTSTANDING_WID 8
#define VT1_ICS_ICSREQCREDITS3_OUTSTANDING_MSK (((_ULL(1) << VT1_ICS_ICSREQCREDITS3_OUTSTANDING_WID) - _ULL(1)) << VT1_ICS_ICSREQCREDITS3_OUTSTANDING_POS)

#define VT1_ICS_SBRREQCREDITS_OFFSET _ULL(0x8)

#define VT1_ICS_SBRREQCREDITS_POS 0
#define VT1_ICS_SBRREQCREDITS_WID 16
#define VT1_ICS_SBRREQCREDITS_MSK (((_ULL(1) << VT1_ICS_SBRREQCREDITS_WID) - _ULL(1)) << VT1_ICS_SBRREQCREDITS_POS)

#define VT1_ICS_SBRREQCREDITS_MAXCREDITS_POS 0
#define VT1_ICS_SBRREQCREDITS_MAXCREDITS_WID 8
#define VT1_ICS_SBRREQCREDITS_MAXCREDITS_MSK (((_ULL(1) << VT1_ICS_SBRREQCREDITS_MAXCREDITS_WID) - _ULL(1)) << VT1_ICS_SBRREQCREDITS_MAXCREDITS_POS)
#define VT1_ICS_SBRREQCREDITS_OUTSTANDING_POS 8
#define VT1_ICS_SBRREQCREDITS_OUTSTANDING_WID 8
#define VT1_ICS_SBRREQCREDITS_OUTSTANDING_MSK (((_ULL(1) << VT1_ICS_SBRREQCREDITS_OUTSTANDING_WID) - _ULL(1)) << VT1_ICS_SBRREQCREDITS_OUTSTANDING_POS)

#define VT1_ICS_SNPCREDITS0_OFFSET _ULL(0x10)

#define VT1_ICS_SNPCREDITS0_POS 0
#define VT1_ICS_SNPCREDITS0_WID 16
#define VT1_ICS_SNPCREDITS0_MSK (((_ULL(1) << VT1_ICS_SNPCREDITS0_WID) - _ULL(1)) << VT1_ICS_SNPCREDITS0_POS)

#define VT1_ICS_SNPCREDITS0_MAXCREDITS_POS 0
#define VT1_ICS_SNPCREDITS0_MAXCREDITS_WID 8
#define VT1_ICS_SNPCREDITS0_MAXCREDITS_MSK (((_ULL(1) << VT1_ICS_SNPCREDITS0_MAXCREDITS_WID) - _ULL(1)) << VT1_ICS_SNPCREDITS0_MAXCREDITS_POS)
#define VT1_ICS_SNPCREDITS0_OUTSTANDING_POS 8
#define VT1_ICS_SNPCREDITS0_OUTSTANDING_WID 8
#define VT1_ICS_SNPCREDITS0_OUTSTANDING_MSK (((_ULL(1) << VT1_ICS_SNPCREDITS0_OUTSTANDING_WID) - _ULL(1)) << VT1_ICS_SNPCREDITS0_OUTSTANDING_POS)

#define VT1_ICS_SNPCREDITS1_OFFSET _ULL(0x11)

#define VT1_ICS_SNPCREDITS1_POS 0
#define VT1_ICS_SNPCREDITS1_WID 16
#define VT1_ICS_SNPCREDITS1_MSK (((_ULL(1) << VT1_ICS_SNPCREDITS1_WID) - _ULL(1)) << VT1_ICS_SNPCREDITS1_POS)

#define VT1_ICS_SNPCREDITS1_MAXCREDITS_POS 0
#define VT1_ICS_SNPCREDITS1_MAXCREDITS_WID 8
#define VT1_ICS_SNPCREDITS1_MAXCREDITS_MSK (((_ULL(1) << VT1_ICS_SNPCREDITS1_MAXCREDITS_WID) - _ULL(1)) << VT1_ICS_SNPCREDITS1_MAXCREDITS_POS)
#define VT1_ICS_SNPCREDITS1_OUTSTANDING_POS 8
#define VT1_ICS_SNPCREDITS1_OUTSTANDING_WID 8
#define VT1_ICS_SNPCREDITS1_OUTSTANDING_MSK (((_ULL(1) << VT1_ICS_SNPCREDITS1_OUTSTANDING_WID) - _ULL(1)) << VT1_ICS_SNPCREDITS1_OUTSTANDING_POS)

#define VT1_ICS_SNPCREDITS2_OFFSET _ULL(0x12)

#define VT1_ICS_SNPCREDITS2_POS 0
#define VT1_ICS_SNPCREDITS2_WID 16
#define VT1_ICS_SNPCREDITS2_MSK (((_ULL(1) << VT1_ICS_SNPCREDITS2_WID) - _ULL(1)) << VT1_ICS_SNPCREDITS2_POS)

#define VT1_ICS_SNPCREDITS2_MAXCREDITS_POS 0
#define VT1_ICS_SNPCREDITS2_MAXCREDITS_WID 8
#define VT1_ICS_SNPCREDITS2_MAXCREDITS_MSK (((_ULL(1) << VT1_ICS_SNPCREDITS2_MAXCREDITS_WID) - _ULL(1)) << VT1_ICS_SNPCREDITS2_MAXCREDITS_POS)
#define VT1_ICS_SNPCREDITS2_OUTSTANDING_POS 8
#define VT1_ICS_SNPCREDITS2_OUTSTANDING_WID 8
#define VT1_ICS_SNPCREDITS2_OUTSTANDING_MSK (((_ULL(1) << VT1_ICS_SNPCREDITS2_OUTSTANDING_WID) - _ULL(1)) << VT1_ICS_SNPCREDITS2_OUTSTANDING_POS)

#define VT1_ICS_SNPCREDITS3_OFFSET _ULL(0x13)

#define VT1_ICS_SNPCREDITS3_POS 0
#define VT1_ICS_SNPCREDITS3_WID 16
#define VT1_ICS_SNPCREDITS3_MSK (((_ULL(1) << VT1_ICS_SNPCREDITS3_WID) - _ULL(1)) << VT1_ICS_SNPCREDITS3_POS)

#define VT1_ICS_SNPCREDITS3_MAXCREDITS_POS 0
#define VT1_ICS_SNPCREDITS3_MAXCREDITS_WID 8
#define VT1_ICS_SNPCREDITS3_MAXCREDITS_MSK (((_ULL(1) << VT1_ICS_SNPCREDITS3_MAXCREDITS_WID) - _ULL(1)) << VT1_ICS_SNPCREDITS3_MAXCREDITS_POS)
#define VT1_ICS_SNPCREDITS3_OUTSTANDING_POS 8
#define VT1_ICS_SNPCREDITS3_OUTSTANDING_WID 8
#define VT1_ICS_SNPCREDITS3_OUTSTANDING_MSK (((_ULL(1) << VT1_ICS_SNPCREDITS3_OUTSTANDING_WID) - _ULL(1)) << VT1_ICS_SNPCREDITS3_OUTSTANDING_POS)

#define VT1_ICS_DATCREDITS0_OFFSET _ULL(0x20)

#define VT1_ICS_DATCREDITS0_POS 0
#define VT1_ICS_DATCREDITS0_WID 16
#define VT1_ICS_DATCREDITS0_MSK (((_ULL(1) << VT1_ICS_DATCREDITS0_WID) - _ULL(1)) << VT1_ICS_DATCREDITS0_POS)

#define VT1_ICS_DATCREDITS0_MAXCREDITS_POS 0
#define VT1_ICS_DATCREDITS0_MAXCREDITS_WID 8
#define VT1_ICS_DATCREDITS0_MAXCREDITS_MSK (((_ULL(1) << VT1_ICS_DATCREDITS0_MAXCREDITS_WID) - _ULL(1)) << VT1_ICS_DATCREDITS0_MAXCREDITS_POS)
#define VT1_ICS_DATCREDITS0_OUTSTANDING_POS 8
#define VT1_ICS_DATCREDITS0_OUTSTANDING_WID 8
#define VT1_ICS_DATCREDITS0_OUTSTANDING_MSK (((_ULL(1) << VT1_ICS_DATCREDITS0_OUTSTANDING_WID) - _ULL(1)) << VT1_ICS_DATCREDITS0_OUTSTANDING_POS)

#define VT1_ICS_DATCREDITS1_OFFSET _ULL(0x21)

#define VT1_ICS_DATCREDITS1_POS 0
#define VT1_ICS_DATCREDITS1_WID 16
#define VT1_ICS_DATCREDITS1_MSK (((_ULL(1) << VT1_ICS_DATCREDITS1_WID) - _ULL(1)) << VT1_ICS_DATCREDITS1_POS)

#define VT1_ICS_DATCREDITS1_MAXCREDITS_POS 0
#define VT1_ICS_DATCREDITS1_MAXCREDITS_WID 8
#define VT1_ICS_DATCREDITS1_MAXCREDITS_MSK (((_ULL(1) << VT1_ICS_DATCREDITS1_MAXCREDITS_WID) - _ULL(1)) << VT1_ICS_DATCREDITS1_MAXCREDITS_POS)
#define VT1_ICS_DATCREDITS1_OUTSTANDING_POS 8
#define VT1_ICS_DATCREDITS1_OUTSTANDING_WID 8
#define VT1_ICS_DATCREDITS1_OUTSTANDING_MSK (((_ULL(1) << VT1_ICS_DATCREDITS1_OUTSTANDING_WID) - _ULL(1)) << VT1_ICS_DATCREDITS1_OUTSTANDING_POS)

#define VT1_ICS_DATCREDITS2_OFFSET _ULL(0x22)

#define VT1_ICS_DATCREDITS2_POS 0
#define VT1_ICS_DATCREDITS2_WID 16
#define VT1_ICS_DATCREDITS2_MSK (((_ULL(1) << VT1_ICS_DATCREDITS2_WID) - _ULL(1)) << VT1_ICS_DATCREDITS2_POS)

#define VT1_ICS_DATCREDITS2_MAXCREDITS_POS 0
#define VT1_ICS_DATCREDITS2_MAXCREDITS_WID 8
#define VT1_ICS_DATCREDITS2_MAXCREDITS_MSK (((_ULL(1) << VT1_ICS_DATCREDITS2_MAXCREDITS_WID) - _ULL(1)) << VT1_ICS_DATCREDITS2_MAXCREDITS_POS)
#define VT1_ICS_DATCREDITS2_OUTSTANDING_POS 8
#define VT1_ICS_DATCREDITS2_OUTSTANDING_WID 8
#define VT1_ICS_DATCREDITS2_OUTSTANDING_MSK (((_ULL(1) << VT1_ICS_DATCREDITS2_OUTSTANDING_WID) - _ULL(1)) << VT1_ICS_DATCREDITS2_OUTSTANDING_POS)

#define VT1_ICS_DATCREDITS3_OFFSET _ULL(0x23)

#define VT1_ICS_DATCREDITS3_POS 0
#define VT1_ICS_DATCREDITS3_WID 16
#define VT1_ICS_DATCREDITS3_MSK (((_ULL(1) << VT1_ICS_DATCREDITS3_WID) - _ULL(1)) << VT1_ICS_DATCREDITS3_POS)

#define VT1_ICS_DATCREDITS3_MAXCREDITS_POS 0
#define VT1_ICS_DATCREDITS3_MAXCREDITS_WID 8
#define VT1_ICS_DATCREDITS3_MAXCREDITS_MSK (((_ULL(1) << VT1_ICS_DATCREDITS3_MAXCREDITS_WID) - _ULL(1)) << VT1_ICS_DATCREDITS3_MAXCREDITS_POS)
#define VT1_ICS_DATCREDITS3_OUTSTANDING_POS 8
#define VT1_ICS_DATCREDITS3_OUTSTANDING_WID 8
#define VT1_ICS_DATCREDITS3_OUTSTANDING_MSK (((_ULL(1) << VT1_ICS_DATCREDITS3_OUTSTANDING_WID) - _ULL(1)) << VT1_ICS_DATCREDITS3_OUTSTANDING_POS)

#define VT1_ICS_DATCREDITS4_OFFSET _ULL(0x24)

#define VT1_ICS_DATCREDITS4_POS 0
#define VT1_ICS_DATCREDITS4_WID 16
#define VT1_ICS_DATCREDITS4_MSK (((_ULL(1) << VT1_ICS_DATCREDITS4_WID) - _ULL(1)) << VT1_ICS_DATCREDITS4_POS)

#define VT1_ICS_DATCREDITS4_MAXCREDITS_POS 0
#define VT1_ICS_DATCREDITS4_MAXCREDITS_WID 8
#define VT1_ICS_DATCREDITS4_MAXCREDITS_MSK (((_ULL(1) << VT1_ICS_DATCREDITS4_MAXCREDITS_WID) - _ULL(1)) << VT1_ICS_DATCREDITS4_MAXCREDITS_POS)
#define VT1_ICS_DATCREDITS4_OUTSTANDING_POS 8
#define VT1_ICS_DATCREDITS4_OUTSTANDING_WID 8
#define VT1_ICS_DATCREDITS4_OUTSTANDING_MSK (((_ULL(1) << VT1_ICS_DATCREDITS4_OUTSTANDING_WID) - _ULL(1)) << VT1_ICS_DATCREDITS4_OUTSTANDING_POS)

#define VT1_ICS_RSPCREDITS0_OFFSET _ULL(0x30)

#define VT1_ICS_RSPCREDITS0_POS 0
#define VT1_ICS_RSPCREDITS0_WID 16
#define VT1_ICS_RSPCREDITS0_MSK (((_ULL(1) << VT1_ICS_RSPCREDITS0_WID) - _ULL(1)) << VT1_ICS_RSPCREDITS0_POS)

#define VT1_ICS_RSPCREDITS0_MAXCREDITS_POS 0
#define VT1_ICS_RSPCREDITS0_MAXCREDITS_WID 8
#define VT1_ICS_RSPCREDITS0_MAXCREDITS_MSK (((_ULL(1) << VT1_ICS_RSPCREDITS0_MAXCREDITS_WID) - _ULL(1)) << VT1_ICS_RSPCREDITS0_MAXCREDITS_POS)
#define VT1_ICS_RSPCREDITS0_OUTSTANDING_POS 8
#define VT1_ICS_RSPCREDITS0_OUTSTANDING_WID 8
#define VT1_ICS_RSPCREDITS0_OUTSTANDING_MSK (((_ULL(1) << VT1_ICS_RSPCREDITS0_OUTSTANDING_WID) - _ULL(1)) << VT1_ICS_RSPCREDITS0_OUTSTANDING_POS)

#define VT1_ICS_RSPCREDITS1_OFFSET _ULL(0x31)

#define VT1_ICS_RSPCREDITS1_POS 0
#define VT1_ICS_RSPCREDITS1_WID 16
#define VT1_ICS_RSPCREDITS1_MSK (((_ULL(1) << VT1_ICS_RSPCREDITS1_WID) - _ULL(1)) << VT1_ICS_RSPCREDITS1_POS)

#define VT1_ICS_RSPCREDITS1_MAXCREDITS_POS 0
#define VT1_ICS_RSPCREDITS1_MAXCREDITS_WID 8
#define VT1_ICS_RSPCREDITS1_MAXCREDITS_MSK (((_ULL(1) << VT1_ICS_RSPCREDITS1_MAXCREDITS_WID) - _ULL(1)) << VT1_ICS_RSPCREDITS1_MAXCREDITS_POS)
#define VT1_ICS_RSPCREDITS1_OUTSTANDING_POS 8
#define VT1_ICS_RSPCREDITS1_OUTSTANDING_WID 8
#define VT1_ICS_RSPCREDITS1_OUTSTANDING_MSK (((_ULL(1) << VT1_ICS_RSPCREDITS1_OUTSTANDING_WID) - _ULL(1)) << VT1_ICS_RSPCREDITS1_OUTSTANDING_POS)

#define VT1_ICS_RSPCREDITS2_OFFSET _ULL(0x32)

#define VT1_ICS_RSPCREDITS2_POS 0
#define VT1_ICS_RSPCREDITS2_WID 16
#define VT1_ICS_RSPCREDITS2_MSK (((_ULL(1) << VT1_ICS_RSPCREDITS2_WID) - _ULL(1)) << VT1_ICS_RSPCREDITS2_POS)

#define VT1_ICS_RSPCREDITS2_MAXCREDITS_POS 0
#define VT1_ICS_RSPCREDITS2_MAXCREDITS_WID 8
#define VT1_ICS_RSPCREDITS2_MAXCREDITS_MSK (((_ULL(1) << VT1_ICS_RSPCREDITS2_MAXCREDITS_WID) - _ULL(1)) << VT1_ICS_RSPCREDITS2_MAXCREDITS_POS)
#define VT1_ICS_RSPCREDITS2_OUTSTANDING_POS 8
#define VT1_ICS_RSPCREDITS2_OUTSTANDING_WID 8
#define VT1_ICS_RSPCREDITS2_OUTSTANDING_MSK (((_ULL(1) << VT1_ICS_RSPCREDITS2_OUTSTANDING_WID) - _ULL(1)) << VT1_ICS_RSPCREDITS2_OUTSTANDING_POS)

#define VT1_ICS_RSPCREDITS3_OFFSET _ULL(0x33)

#define VT1_ICS_RSPCREDITS3_POS 0
#define VT1_ICS_RSPCREDITS3_WID 16
#define VT1_ICS_RSPCREDITS3_MSK (((_ULL(1) << VT1_ICS_RSPCREDITS3_WID) - _ULL(1)) << VT1_ICS_RSPCREDITS3_POS)

#define VT1_ICS_RSPCREDITS3_MAXCREDITS_POS 0
#define VT1_ICS_RSPCREDITS3_MAXCREDITS_WID 8
#define VT1_ICS_RSPCREDITS3_MAXCREDITS_MSK (((_ULL(1) << VT1_ICS_RSPCREDITS3_MAXCREDITS_WID) - _ULL(1)) << VT1_ICS_RSPCREDITS3_MAXCREDITS_POS)
#define VT1_ICS_RSPCREDITS3_OUTSTANDING_POS 8
#define VT1_ICS_RSPCREDITS3_OUTSTANDING_WID 8
#define VT1_ICS_RSPCREDITS3_OUTSTANDING_MSK (((_ULL(1) << VT1_ICS_RSPCREDITS3_OUTSTANDING_WID) - _ULL(1)) << VT1_ICS_RSPCREDITS3_OUTSTANDING_POS)

#define VT1_ICS_RSPCREDITS4_OFFSET _ULL(0x34)

#define VT1_ICS_RSPCREDITS4_POS 0
#define VT1_ICS_RSPCREDITS4_WID 16
#define VT1_ICS_RSPCREDITS4_MSK (((_ULL(1) << VT1_ICS_RSPCREDITS4_WID) - _ULL(1)) << VT1_ICS_RSPCREDITS4_POS)

#define VT1_ICS_RSPCREDITS4_MAXCREDITS_POS 0
#define VT1_ICS_RSPCREDITS4_MAXCREDITS_WID 8
#define VT1_ICS_RSPCREDITS4_MAXCREDITS_MSK (((_ULL(1) << VT1_ICS_RSPCREDITS4_MAXCREDITS_WID) - _ULL(1)) << VT1_ICS_RSPCREDITS4_MAXCREDITS_POS)
#define VT1_ICS_RSPCREDITS4_OUTSTANDING_POS 8
#define VT1_ICS_RSPCREDITS4_OUTSTANDING_WID 8
#define VT1_ICS_RSPCREDITS4_OUTSTANDING_MSK (((_ULL(1) << VT1_ICS_RSPCREDITS4_OUTSTANDING_WID) - _ULL(1)) << VT1_ICS_RSPCREDITS4_OUTSTANDING_POS)
#endif /* VT1_ICS_MMR_H */
