/* This file is auto-generated. Do not hand edit this file. */

#ifndef VT1_SBR_MMR_H
#define VT1_SBR_MMR_H

#ifndef _ULL

#ifdef __ASSEMBLER__
#define _AC(X,Y) X
#else
#define __AC(X,Y) (X##Y)
#define _AC(X,Y) __AC(X,Y)
#endif

#define _ULL(x)  (_AC(x, ULL))
#endif


#define VT1_SBR_LINKINTERFACE_OFFSET _ULL(0x0)

#define VT1_SBR_LINKINTERFACE_POS 0
#define VT1_SBR_LINKINTERFACE_WID 5
#define VT1_SBR_LINKINTERFACE_MSK (((_ULL(1) << VT1_SBR_LINKINTERFACE_WID) - _ULL(1)) << VT1_SBR_LINKINTERFACE_POS)

#define VT1_SBR_LINKINTERFACE_TXLINKACTIVATE_POS 0
#define VT1_SBR_LINKINTERFACE_TXLINKACTIVATE_WID 1
#define VT1_SBR_LINKINTERFACE_TXLINKACTIVATE_MSK (((_ULL(1) << VT1_SBR_LINKINTERFACE_TXLINKACTIVATE_WID) - _ULL(1)) << VT1_SBR_LINKINTERFACE_TXLINKACTIVATE_POS)
#define VT1_SBR_LINKINTERFACE_TXLINKREQ_POS 1
#define VT1_SBR_LINKINTERFACE_TXLINKREQ_WID 1
#define VT1_SBR_LINKINTERFACE_TXLINKREQ_MSK (((_ULL(1) << VT1_SBR_LINKINTERFACE_TXLINKREQ_WID) - _ULL(1)) << VT1_SBR_LINKINTERFACE_TXLINKREQ_POS)
#define VT1_SBR_LINKINTERFACE_TXLINKACK_POS 2
#define VT1_SBR_LINKINTERFACE_TXLINKACK_WID 1
#define VT1_SBR_LINKINTERFACE_TXLINKACK_MSK (((_ULL(1) << VT1_SBR_LINKINTERFACE_TXLINKACK_WID) - _ULL(1)) << VT1_SBR_LINKINTERFACE_TXLINKACK_POS)
#define VT1_SBR_LINKINTERFACE_RXLINKREQ_POS 3
#define VT1_SBR_LINKINTERFACE_RXLINKREQ_WID 1
#define VT1_SBR_LINKINTERFACE_RXLINKREQ_MSK (((_ULL(1) << VT1_SBR_LINKINTERFACE_RXLINKREQ_WID) - _ULL(1)) << VT1_SBR_LINKINTERFACE_RXLINKREQ_POS)
#define VT1_SBR_LINKINTERFACE_RXLINKACK_POS 4
#define VT1_SBR_LINKINTERFACE_RXLINKACK_WID 1
#define VT1_SBR_LINKINTERFACE_RXLINKACK_MSK (((_ULL(1) << VT1_SBR_LINKINTERFACE_RXLINKACK_WID) - _ULL(1)) << VT1_SBR_LINKINTERFACE_RXLINKACK_POS)

#define VT1_SBR_PROTACTIVITY_OFFSET _ULL(0x1)

#define VT1_SBR_PROTACTIVITY_POS 0
#define VT1_SBR_PROTACTIVITY_WID 2
#define VT1_SBR_PROTACTIVITY_MSK (((_ULL(1) << VT1_SBR_PROTACTIVITY_WID) - _ULL(1)) << VT1_SBR_PROTACTIVITY_POS)

#define VT1_SBR_PROTACTIVITY_TXSACTIVE_POS 0
#define VT1_SBR_PROTACTIVITY_TXSACTIVE_WID 1
#define VT1_SBR_PROTACTIVITY_TXSACTIVE_MSK (((_ULL(1) << VT1_SBR_PROTACTIVITY_TXSACTIVE_WID) - _ULL(1)) << VT1_SBR_PROTACTIVITY_TXSACTIVE_POS)
#define VT1_SBR_PROTACTIVITY_RXSACTIVE_POS 1
#define VT1_SBR_PROTACTIVITY_RXSACTIVE_WID 1
#define VT1_SBR_PROTACTIVITY_RXSACTIVE_MSK (((_ULL(1) << VT1_SBR_PROTACTIVITY_RXSACTIVE_WID) - _ULL(1)) << VT1_SBR_PROTACTIVITY_RXSACTIVE_POS)

#define VT1_SBR_SYSTEMCOHERENCY_OFFSET _ULL(0x2)

#define VT1_SBR_SYSTEMCOHERENCY_POS 0
#define VT1_SBR_SYSTEMCOHERENCY_WID 2
#define VT1_SBR_SYSTEMCOHERENCY_MSK (((_ULL(1) << VT1_SBR_SYSTEMCOHERENCY_WID) - _ULL(1)) << VT1_SBR_SYSTEMCOHERENCY_POS)

#define VT1_SBR_SYSTEMCOHERENCY_SYSCOREQ_POS 0
#define VT1_SBR_SYSTEMCOHERENCY_SYSCOREQ_WID 1
#define VT1_SBR_SYSTEMCOHERENCY_SYSCOREQ_MSK (((_ULL(1) << VT1_SBR_SYSTEMCOHERENCY_SYSCOREQ_WID) - _ULL(1)) << VT1_SBR_SYSTEMCOHERENCY_SYSCOREQ_POS)
#define VT1_SBR_SYSTEMCOHERENCY_SYSCOACK_POS 1
#define VT1_SBR_SYSTEMCOHERENCY_SYSCOACK_WID 1
#define VT1_SBR_SYSTEMCOHERENCY_SYSCOACK_MSK (((_ULL(1) << VT1_SBR_SYSTEMCOHERENCY_SYSCOACK_WID) - _ULL(1)) << VT1_SBR_SYSTEMCOHERENCY_SYSCOACK_POS)

#define VT1_SBR_SBRCONFIG_OFFSET _ULL(0x3)

#define VT1_SBR_SBRCONFIG_POS 0
#define VT1_SBR_SBRCONFIG_WID 2
#define VT1_SBR_SBRCONFIG_MSK (((_ULL(1) << VT1_SBR_SBRCONFIG_WID) - _ULL(1)) << VT1_SBR_SBRCONFIG_POS)

#define VT1_SBR_SBRCONFIG_L2SETIDXHASHDIS_POS 0
#define VT1_SBR_SBRCONFIG_L2SETIDXHASHDIS_WID 1
#define VT1_SBR_SBRCONFIG_L2SETIDXHASHDIS_MSK (((_ULL(1) << VT1_SBR_SBRCONFIG_L2SETIDXHASHDIS_WID) - _ULL(1)) << VT1_SBR_SBRCONFIG_L2SETIDXHASHDIS_POS)
#define VT1_SBR_SBRCONFIG_L3SLICEHASHDIS_POS 1
#define VT1_SBR_SBRCONFIG_L3SLICEHASHDIS_WID 1
#define VT1_SBR_SBRCONFIG_L3SLICEHASHDIS_MSK (((_ULL(1) << VT1_SBR_SBRCONFIG_L3SLICEHASHDIS_WID) - _ULL(1)) << VT1_SBR_SBRCONFIG_L3SLICEHASHDIS_POS)

#define VT1_SBR_NMIDISTMASK_OFFSET _ULL(0x4)

#define VT1_SBR_NMIDISTMASK_POS 0
#define VT1_SBR_NMIDISTMASK_WID 17
#define VT1_SBR_NMIDISTMASK_MSK (((_ULL(1) << VT1_SBR_NMIDISTMASK_WID) - _ULL(1)) << VT1_SBR_NMIDISTMASK_POS)

#define VT1_SBR_NMIDISTMASK_CPUDIST_POS 0
#define VT1_SBR_NMIDISTMASK_CPUDIST_WID 16
#define VT1_SBR_NMIDISTMASK_CPUDIST_MSK (((_ULL(1) << VT1_SBR_NMIDISTMASK_CPUDIST_WID) - _ULL(1)) << VT1_SBR_NMIDISTMASK_CPUDIST_POS)
#define VT1_SBR_NMIDISTMASK_CLUSTERDIST_POS 16
#define VT1_SBR_NMIDISTMASK_CLUSTERDIST_WID 1
#define VT1_SBR_NMIDISTMASK_CLUSTERDIST_MSK (((_ULL(1) << VT1_SBR_NMIDISTMASK_CLUSTERDIST_WID) - _ULL(1)) << VT1_SBR_NMIDISTMASK_CLUSTERDIST_POS)

#define VT1_SBR_ERRSTATUS0_OFFSET _ULL(0x8)

#define VT1_SBR_ERRSTATUS0_POS 0
#define VT1_SBR_ERRSTATUS0_WID 16
#define VT1_SBR_ERRSTATUS0_MSK (((_ULL(1) << VT1_SBR_ERRSTATUS0_WID) - _ULL(1)) << VT1_SBR_ERRSTATUS0_POS)

#define VT1_SBR_ERRSTATUS0_ERRSTATUS_POS 0
#define VT1_SBR_ERRSTATUS0_ERRSTATUS_WID 16
#define VT1_SBR_ERRSTATUS0_ERRSTATUS_MSK (((_ULL(1) << VT1_SBR_ERRSTATUS0_ERRSTATUS_WID) - _ULL(1)) << VT1_SBR_ERRSTATUS0_ERRSTATUS_POS)

#define VT1_SBR_ERRSTATUS1_OFFSET _ULL(0x9)

#define VT1_SBR_ERRSTATUS1_POS 0
#define VT1_SBR_ERRSTATUS1_WID 16
#define VT1_SBR_ERRSTATUS1_MSK (((_ULL(1) << VT1_SBR_ERRSTATUS1_WID) - _ULL(1)) << VT1_SBR_ERRSTATUS1_POS)

#define VT1_SBR_ERRSTATUS1_ERRSTATUS_POS 0
#define VT1_SBR_ERRSTATUS1_ERRSTATUS_WID 16
#define VT1_SBR_ERRSTATUS1_ERRSTATUS_MSK (((_ULL(1) << VT1_SBR_ERRSTATUS1_ERRSTATUS_WID) - _ULL(1)) << VT1_SBR_ERRSTATUS1_ERRSTATUS_POS)

#define VT1_SBR_ERRSTATUS2_OFFSET _ULL(0xa)

#define VT1_SBR_ERRSTATUS2_POS 0
#define VT1_SBR_ERRSTATUS2_WID 16
#define VT1_SBR_ERRSTATUS2_MSK (((_ULL(1) << VT1_SBR_ERRSTATUS2_WID) - _ULL(1)) << VT1_SBR_ERRSTATUS2_POS)

#define VT1_SBR_ERRSTATUS2_ERRSTATUS_POS 0
#define VT1_SBR_ERRSTATUS2_ERRSTATUS_WID 16
#define VT1_SBR_ERRSTATUS2_ERRSTATUS_MSK (((_ULL(1) << VT1_SBR_ERRSTATUS2_ERRSTATUS_WID) - _ULL(1)) << VT1_SBR_ERRSTATUS2_ERRSTATUS_POS)

#define VT1_SBR_ERRSTATUS3_OFFSET _ULL(0xb)

#define VT1_SBR_ERRSTATUS3_POS 0
#define VT1_SBR_ERRSTATUS3_WID 16
#define VT1_SBR_ERRSTATUS3_MSK (((_ULL(1) << VT1_SBR_ERRSTATUS3_WID) - _ULL(1)) << VT1_SBR_ERRSTATUS3_POS)

#define VT1_SBR_ERRSTATUS3_ERRSTATUS_POS 0
#define VT1_SBR_ERRSTATUS3_ERRSTATUS_WID 16
#define VT1_SBR_ERRSTATUS3_ERRSTATUS_MSK (((_ULL(1) << VT1_SBR_ERRSTATUS3_ERRSTATUS_WID) - _ULL(1)) << VT1_SBR_ERRSTATUS3_ERRSTATUS_POS)

#define VT1_SBR_ERRSTATUS4_OFFSET _ULL(0xc)

#define VT1_SBR_ERRSTATUS4_POS 0
#define VT1_SBR_ERRSTATUS4_WID 16
#define VT1_SBR_ERRSTATUS4_MSK (((_ULL(1) << VT1_SBR_ERRSTATUS4_WID) - _ULL(1)) << VT1_SBR_ERRSTATUS4_POS)

#define VT1_SBR_ERRSTATUS4_ERRSTATUS_POS 0
#define VT1_SBR_ERRSTATUS4_ERRSTATUS_WID 16
#define VT1_SBR_ERRSTATUS4_ERRSTATUS_MSK (((_ULL(1) << VT1_SBR_ERRSTATUS4_ERRSTATUS_WID) - _ULL(1)) << VT1_SBR_ERRSTATUS4_ERRSTATUS_POS)

#define VT1_SBR_SNPCREDITS0_OFFSET _ULL(0x10)

#define VT1_SBR_SNPCREDITS0_POS 0
#define VT1_SBR_SNPCREDITS0_WID 16
#define VT1_SBR_SNPCREDITS0_MSK (((_ULL(1) << VT1_SBR_SNPCREDITS0_WID) - _ULL(1)) << VT1_SBR_SNPCREDITS0_POS)

#define VT1_SBR_SNPCREDITS0_MAXCREDITS_POS 0
#define VT1_SBR_SNPCREDITS0_MAXCREDITS_WID 8
#define VT1_SBR_SNPCREDITS0_MAXCREDITS_MSK (((_ULL(1) << VT1_SBR_SNPCREDITS0_MAXCREDITS_WID) - _ULL(1)) << VT1_SBR_SNPCREDITS0_MAXCREDITS_POS)
#define VT1_SBR_SNPCREDITS0_OUTSTANDING_POS 8
#define VT1_SBR_SNPCREDITS0_OUTSTANDING_WID 8
#define VT1_SBR_SNPCREDITS0_OUTSTANDING_MSK (((_ULL(1) << VT1_SBR_SNPCREDITS0_OUTSTANDING_WID) - _ULL(1)) << VT1_SBR_SNPCREDITS0_OUTSTANDING_POS)

#define VT1_SBR_SNPCREDITS1_OFFSET _ULL(0x11)

#define VT1_SBR_SNPCREDITS1_POS 0
#define VT1_SBR_SNPCREDITS1_WID 16
#define VT1_SBR_SNPCREDITS1_MSK (((_ULL(1) << VT1_SBR_SNPCREDITS1_WID) - _ULL(1)) << VT1_SBR_SNPCREDITS1_POS)

#define VT1_SBR_SNPCREDITS1_MAXCREDITS_POS 0
#define VT1_SBR_SNPCREDITS1_MAXCREDITS_WID 8
#define VT1_SBR_SNPCREDITS1_MAXCREDITS_MSK (((_ULL(1) << VT1_SBR_SNPCREDITS1_MAXCREDITS_WID) - _ULL(1)) << VT1_SBR_SNPCREDITS1_MAXCREDITS_POS)
#define VT1_SBR_SNPCREDITS1_OUTSTANDING_POS 8
#define VT1_SBR_SNPCREDITS1_OUTSTANDING_WID 8
#define VT1_SBR_SNPCREDITS1_OUTSTANDING_MSK (((_ULL(1) << VT1_SBR_SNPCREDITS1_OUTSTANDING_WID) - _ULL(1)) << VT1_SBR_SNPCREDITS1_OUTSTANDING_POS)

#define VT1_SBR_SNPCREDITS2_OFFSET _ULL(0x12)

#define VT1_SBR_SNPCREDITS2_POS 0
#define VT1_SBR_SNPCREDITS2_WID 16
#define VT1_SBR_SNPCREDITS2_MSK (((_ULL(1) << VT1_SBR_SNPCREDITS2_WID) - _ULL(1)) << VT1_SBR_SNPCREDITS2_POS)

#define VT1_SBR_SNPCREDITS2_MAXCREDITS_POS 0
#define VT1_SBR_SNPCREDITS2_MAXCREDITS_WID 8
#define VT1_SBR_SNPCREDITS2_MAXCREDITS_MSK (((_ULL(1) << VT1_SBR_SNPCREDITS2_MAXCREDITS_WID) - _ULL(1)) << VT1_SBR_SNPCREDITS2_MAXCREDITS_POS)
#define VT1_SBR_SNPCREDITS2_OUTSTANDING_POS 8
#define VT1_SBR_SNPCREDITS2_OUTSTANDING_WID 8
#define VT1_SBR_SNPCREDITS2_OUTSTANDING_MSK (((_ULL(1) << VT1_SBR_SNPCREDITS2_OUTSTANDING_WID) - _ULL(1)) << VT1_SBR_SNPCREDITS2_OUTSTANDING_POS)

#define VT1_SBR_SNPCREDITS3_OFFSET _ULL(0x13)

#define VT1_SBR_SNPCREDITS3_POS 0
#define VT1_SBR_SNPCREDITS3_WID 16
#define VT1_SBR_SNPCREDITS3_MSK (((_ULL(1) << VT1_SBR_SNPCREDITS3_WID) - _ULL(1)) << VT1_SBR_SNPCREDITS3_POS)

#define VT1_SBR_SNPCREDITS3_MAXCREDITS_POS 0
#define VT1_SBR_SNPCREDITS3_MAXCREDITS_WID 8
#define VT1_SBR_SNPCREDITS3_MAXCREDITS_MSK (((_ULL(1) << VT1_SBR_SNPCREDITS3_MAXCREDITS_WID) - _ULL(1)) << VT1_SBR_SNPCREDITS3_MAXCREDITS_POS)
#define VT1_SBR_SNPCREDITS3_OUTSTANDING_POS 8
#define VT1_SBR_SNPCREDITS3_OUTSTANDING_WID 8
#define VT1_SBR_SNPCREDITS3_OUTSTANDING_MSK (((_ULL(1) << VT1_SBR_SNPCREDITS3_OUTSTANDING_WID) - _ULL(1)) << VT1_SBR_SNPCREDITS3_OUTSTANDING_POS)

#define VT1_SBR_DATCREDITS0_OFFSET _ULL(0x20)

#define VT1_SBR_DATCREDITS0_POS 0
#define VT1_SBR_DATCREDITS0_WID 16
#define VT1_SBR_DATCREDITS0_MSK (((_ULL(1) << VT1_SBR_DATCREDITS0_WID) - _ULL(1)) << VT1_SBR_DATCREDITS0_POS)

#define VT1_SBR_DATCREDITS0_MAXCREDITS_POS 0
#define VT1_SBR_DATCREDITS0_MAXCREDITS_WID 8
#define VT1_SBR_DATCREDITS0_MAXCREDITS_MSK (((_ULL(1) << VT1_SBR_DATCREDITS0_MAXCREDITS_WID) - _ULL(1)) << VT1_SBR_DATCREDITS0_MAXCREDITS_POS)
#define VT1_SBR_DATCREDITS0_OUTSTANDING_POS 8
#define VT1_SBR_DATCREDITS0_OUTSTANDING_WID 8
#define VT1_SBR_DATCREDITS0_OUTSTANDING_MSK (((_ULL(1) << VT1_SBR_DATCREDITS0_OUTSTANDING_WID) - _ULL(1)) << VT1_SBR_DATCREDITS0_OUTSTANDING_POS)

#define VT1_SBR_DATCREDITS1_OFFSET _ULL(0x21)

#define VT1_SBR_DATCREDITS1_POS 0
#define VT1_SBR_DATCREDITS1_WID 16
#define VT1_SBR_DATCREDITS1_MSK (((_ULL(1) << VT1_SBR_DATCREDITS1_WID) - _ULL(1)) << VT1_SBR_DATCREDITS1_POS)

#define VT1_SBR_DATCREDITS1_MAXCREDITS_POS 0
#define VT1_SBR_DATCREDITS1_MAXCREDITS_WID 8
#define VT1_SBR_DATCREDITS1_MAXCREDITS_MSK (((_ULL(1) << VT1_SBR_DATCREDITS1_MAXCREDITS_WID) - _ULL(1)) << VT1_SBR_DATCREDITS1_MAXCREDITS_POS)
#define VT1_SBR_DATCREDITS1_OUTSTANDING_POS 8
#define VT1_SBR_DATCREDITS1_OUTSTANDING_WID 8
#define VT1_SBR_DATCREDITS1_OUTSTANDING_MSK (((_ULL(1) << VT1_SBR_DATCREDITS1_OUTSTANDING_WID) - _ULL(1)) << VT1_SBR_DATCREDITS1_OUTSTANDING_POS)

#define VT1_SBR_DATCREDITS2_OFFSET _ULL(0x22)

#define VT1_SBR_DATCREDITS2_POS 0
#define VT1_SBR_DATCREDITS2_WID 16
#define VT1_SBR_DATCREDITS2_MSK (((_ULL(1) << VT1_SBR_DATCREDITS2_WID) - _ULL(1)) << VT1_SBR_DATCREDITS2_POS)

#define VT1_SBR_DATCREDITS2_MAXCREDITS_POS 0
#define VT1_SBR_DATCREDITS2_MAXCREDITS_WID 8
#define VT1_SBR_DATCREDITS2_MAXCREDITS_MSK (((_ULL(1) << VT1_SBR_DATCREDITS2_MAXCREDITS_WID) - _ULL(1)) << VT1_SBR_DATCREDITS2_MAXCREDITS_POS)
#define VT1_SBR_DATCREDITS2_OUTSTANDING_POS 8
#define VT1_SBR_DATCREDITS2_OUTSTANDING_WID 8
#define VT1_SBR_DATCREDITS2_OUTSTANDING_MSK (((_ULL(1) << VT1_SBR_DATCREDITS2_OUTSTANDING_WID) - _ULL(1)) << VT1_SBR_DATCREDITS2_OUTSTANDING_POS)

#define VT1_SBR_DATCREDITS3_OFFSET _ULL(0x23)

#define VT1_SBR_DATCREDITS3_POS 0
#define VT1_SBR_DATCREDITS3_WID 16
#define VT1_SBR_DATCREDITS3_MSK (((_ULL(1) << VT1_SBR_DATCREDITS3_WID) - _ULL(1)) << VT1_SBR_DATCREDITS3_POS)

#define VT1_SBR_DATCREDITS3_MAXCREDITS_POS 0
#define VT1_SBR_DATCREDITS3_MAXCREDITS_WID 8
#define VT1_SBR_DATCREDITS3_MAXCREDITS_MSK (((_ULL(1) << VT1_SBR_DATCREDITS3_MAXCREDITS_WID) - _ULL(1)) << VT1_SBR_DATCREDITS3_MAXCREDITS_POS)
#define VT1_SBR_DATCREDITS3_OUTSTANDING_POS 8
#define VT1_SBR_DATCREDITS3_OUTSTANDING_WID 8
#define VT1_SBR_DATCREDITS3_OUTSTANDING_MSK (((_ULL(1) << VT1_SBR_DATCREDITS3_OUTSTANDING_WID) - _ULL(1)) << VT1_SBR_DATCREDITS3_OUTSTANDING_POS)

#define VT1_SBR_RSPCREDITS0_OFFSET _ULL(0x30)

#define VT1_SBR_RSPCREDITS0_POS 0
#define VT1_SBR_RSPCREDITS0_WID 16
#define VT1_SBR_RSPCREDITS0_MSK (((_ULL(1) << VT1_SBR_RSPCREDITS0_WID) - _ULL(1)) << VT1_SBR_RSPCREDITS0_POS)

#define VT1_SBR_RSPCREDITS0_MAXCREDITS_POS 0
#define VT1_SBR_RSPCREDITS0_MAXCREDITS_WID 8
#define VT1_SBR_RSPCREDITS0_MAXCREDITS_MSK (((_ULL(1) << VT1_SBR_RSPCREDITS0_MAXCREDITS_WID) - _ULL(1)) << VT1_SBR_RSPCREDITS0_MAXCREDITS_POS)
#define VT1_SBR_RSPCREDITS0_OUTSTANDING_POS 8
#define VT1_SBR_RSPCREDITS0_OUTSTANDING_WID 8
#define VT1_SBR_RSPCREDITS0_OUTSTANDING_MSK (((_ULL(1) << VT1_SBR_RSPCREDITS0_OUTSTANDING_WID) - _ULL(1)) << VT1_SBR_RSPCREDITS0_OUTSTANDING_POS)

#define VT1_SBR_RSPCREDITS1_OFFSET _ULL(0x31)

#define VT1_SBR_RSPCREDITS1_POS 0
#define VT1_SBR_RSPCREDITS1_WID 16
#define VT1_SBR_RSPCREDITS1_MSK (((_ULL(1) << VT1_SBR_RSPCREDITS1_WID) - _ULL(1)) << VT1_SBR_RSPCREDITS1_POS)

#define VT1_SBR_RSPCREDITS1_MAXCREDITS_POS 0
#define VT1_SBR_RSPCREDITS1_MAXCREDITS_WID 8
#define VT1_SBR_RSPCREDITS1_MAXCREDITS_MSK (((_ULL(1) << VT1_SBR_RSPCREDITS1_MAXCREDITS_WID) - _ULL(1)) << VT1_SBR_RSPCREDITS1_MAXCREDITS_POS)
#define VT1_SBR_RSPCREDITS1_OUTSTANDING_POS 8
#define VT1_SBR_RSPCREDITS1_OUTSTANDING_WID 8
#define VT1_SBR_RSPCREDITS1_OUTSTANDING_MSK (((_ULL(1) << VT1_SBR_RSPCREDITS1_OUTSTANDING_WID) - _ULL(1)) << VT1_SBR_RSPCREDITS1_OUTSTANDING_POS)

#define VT1_SBR_RSPCREDITS2_OFFSET _ULL(0x32)

#define VT1_SBR_RSPCREDITS2_POS 0
#define VT1_SBR_RSPCREDITS2_WID 16
#define VT1_SBR_RSPCREDITS2_MSK (((_ULL(1) << VT1_SBR_RSPCREDITS2_WID) - _ULL(1)) << VT1_SBR_RSPCREDITS2_POS)

#define VT1_SBR_RSPCREDITS2_MAXCREDITS_POS 0
#define VT1_SBR_RSPCREDITS2_MAXCREDITS_WID 8
#define VT1_SBR_RSPCREDITS2_MAXCREDITS_MSK (((_ULL(1) << VT1_SBR_RSPCREDITS2_MAXCREDITS_WID) - _ULL(1)) << VT1_SBR_RSPCREDITS2_MAXCREDITS_POS)
#define VT1_SBR_RSPCREDITS2_OUTSTANDING_POS 8
#define VT1_SBR_RSPCREDITS2_OUTSTANDING_WID 8
#define VT1_SBR_RSPCREDITS2_OUTSTANDING_MSK (((_ULL(1) << VT1_SBR_RSPCREDITS2_OUTSTANDING_WID) - _ULL(1)) << VT1_SBR_RSPCREDITS2_OUTSTANDING_POS)

#define VT1_SBR_RSPCREDITS3_OFFSET _ULL(0x33)

#define VT1_SBR_RSPCREDITS3_POS 0
#define VT1_SBR_RSPCREDITS3_WID 16
#define VT1_SBR_RSPCREDITS3_MSK (((_ULL(1) << VT1_SBR_RSPCREDITS3_WID) - _ULL(1)) << VT1_SBR_RSPCREDITS3_POS)

#define VT1_SBR_RSPCREDITS3_MAXCREDITS_POS 0
#define VT1_SBR_RSPCREDITS3_MAXCREDITS_WID 8
#define VT1_SBR_RSPCREDITS3_MAXCREDITS_MSK (((_ULL(1) << VT1_SBR_RSPCREDITS3_MAXCREDITS_WID) - _ULL(1)) << VT1_SBR_RSPCREDITS3_MAXCREDITS_POS)
#define VT1_SBR_RSPCREDITS3_OUTSTANDING_POS 8
#define VT1_SBR_RSPCREDITS3_OUTSTANDING_WID 8
#define VT1_SBR_RSPCREDITS3_OUTSTANDING_MSK (((_ULL(1) << VT1_SBR_RSPCREDITS3_OUTSTANDING_WID) - _ULL(1)) << VT1_SBR_RSPCREDITS3_OUTSTANDING_POS)

#define VT1_SBR_POWERESTIMATIONCOUNTER_OFFSET _ULL(0xc00)

#define VT1_SBR_POWERESTIMATIONCOUNTER_POS 0
#define VT1_SBR_POWERESTIMATIONCOUNTER_WID 32
#define VT1_SBR_POWERESTIMATIONCOUNTER_MSK (((_ULL(1) << VT1_SBR_POWERESTIMATIONCOUNTER_WID) - _ULL(1)) << VT1_SBR_POWERESTIMATIONCOUNTER_POS)

#define VT1_SBR_POWERESTIMATIONCOUNTER_UNDERFLOW_POS 0
#define VT1_SBR_POWERESTIMATIONCOUNTER_UNDERFLOW_WID 1
#define VT1_SBR_POWERESTIMATIONCOUNTER_UNDERFLOW_MSK (((_ULL(1) << VT1_SBR_POWERESTIMATIONCOUNTER_UNDERFLOW_WID) - _ULL(1)) << VT1_SBR_POWERESTIMATIONCOUNTER_UNDERFLOW_POS)
#define VT1_SBR_POWERESTIMATIONCOUNTER_SAMPLEID_POS 1
#define VT1_SBR_POWERESTIMATIONCOUNTER_SAMPLEID_WID 3
#define VT1_SBR_POWERESTIMATIONCOUNTER_SAMPLEID_MSK (((_ULL(1) << VT1_SBR_POWERESTIMATIONCOUNTER_SAMPLEID_WID) - _ULL(1)) << VT1_SBR_POWERESTIMATIONCOUNTER_SAMPLEID_POS)
#define VT1_SBR_POWERESTIMATIONCOUNTER_COUNTER_POS 4
#define VT1_SBR_POWERESTIMATIONCOUNTER_COUNTER_WID 28
#define VT1_SBR_POWERESTIMATIONCOUNTER_COUNTER_MSK (((_ULL(1) << VT1_SBR_POWERESTIMATIONCOUNTER_COUNTER_WID) - _ULL(1)) << VT1_SBR_POWERESTIMATIONCOUNTER_COUNTER_POS)

#define VT1_SBR_POWERESTIMATIONCONTROL_OFFSET _ULL(0xc01)

#define VT1_SBR_POWERESTIMATIONCONTROL_POS 0
#define VT1_SBR_POWERESTIMATIONCONTROL_WID 3
#define VT1_SBR_POWERESTIMATIONCONTROL_MSK (((_ULL(1) << VT1_SBR_POWERESTIMATIONCONTROL_WID) - _ULL(1)) << VT1_SBR_POWERESTIMATIONCONTROL_POS)

#define VT1_SBR_POWERESTIMATIONCONTROL_INTERVAL_POS 0
#define VT1_SBR_POWERESTIMATIONCONTROL_INTERVAL_WID 3
#define VT1_SBR_POWERESTIMATIONCONTROL_INTERVAL_MSK (((_ULL(1) << VT1_SBR_POWERESTIMATIONCONTROL_INTERVAL_WID) - _ULL(1)) << VT1_SBR_POWERESTIMATIONCONTROL_INTERVAL_POS)

#define VT1_SBR_POWERESTIMATIONSTATUS_OFFSET _ULL(0xc02)

#define VT1_SBR_POWERESTIMATIONSTATUS_POS 0
#define VT1_SBR_POWERESTIMATIONSTATUS_WID 1
#define VT1_SBR_POWERESTIMATIONSTATUS_MSK (((_ULL(1) << VT1_SBR_POWERESTIMATIONSTATUS_WID) - _ULL(1)) << VT1_SBR_POWERESTIMATIONSTATUS_POS)

#define VT1_SBR_POWERESTIMATIONSTATUS_OVERFLOW_POS 0
#define VT1_SBR_POWERESTIMATIONSTATUS_OVERFLOW_WID 1
#define VT1_SBR_POWERESTIMATIONSTATUS_OVERFLOW_MSK (((_ULL(1) << VT1_SBR_POWERESTIMATIONSTATUS_OVERFLOW_WID) - _ULL(1)) << VT1_SBR_POWERESTIMATIONSTATUS_OVERFLOW_POS)
#endif /* VT1_SBR_MMR_H */
