/* This file is auto-generated. Do not hand edit this file. */

#ifndef VT1_SMRC_MMR_H
#define VT1_SMRC_MMR_H

#ifndef _ULL

#ifdef __ASSEMBLER__
#define _AC(X,Y) X
#else
#define __AC(X,Y) (X##Y)
#define _AC(X,Y) __AC(X,Y)
#endif

#define _ULL(x)  (_AC(x, ULL))
#endif


#define VT1_SMRC_CLUSTERRESET_OFFSET _ULL(0x0)

#define VT1_SMRC_CLUSTERRESET_POS 0
#define VT1_SMRC_CLUSTERRESET_WID 3
#define VT1_SMRC_CLUSTERRESET_MSK (((_ULL(1) << VT1_SMRC_CLUSTERRESET_WID) - _ULL(1)) << VT1_SMRC_CLUSTERRESET_POS)

#define VT1_SMRC_CLUSTERRESET_NONCORERESET_POS 0
#define VT1_SMRC_CLUSTERRESET_NONCORERESET_WID 1
#define VT1_SMRC_CLUSTERRESET_NONCORERESET_MSK (((_ULL(1) << VT1_SMRC_CLUSTERRESET_NONCORERESET_WID) - _ULL(1)) << VT1_SMRC_CLUSTERRESET_NONCORERESET_POS)
#define VT1_SMRC_CLUSTERRESET_PCLREGBUSACTIVE_POS 1
#define VT1_SMRC_CLUSTERRESET_PCLREGBUSACTIVE_WID 1
#define VT1_SMRC_CLUSTERRESET_PCLREGBUSACTIVE_MSK (((_ULL(1) << VT1_SMRC_CLUSTERRESET_PCLREGBUSACTIVE_WID) - _ULL(1)) << VT1_SMRC_CLUSTERRESET_PCLREGBUSACTIVE_POS)
#define VT1_SMRC_CLUSTERRESET_PCLRSPBRIDGEENABLE_POS 2
#define VT1_SMRC_CLUSTERRESET_PCLRSPBRIDGEENABLE_WID 1
#define VT1_SMRC_CLUSTERRESET_PCLRSPBRIDGEENABLE_MSK (((_ULL(1) << VT1_SMRC_CLUSTERRESET_PCLRSPBRIDGEENABLE_WID) - _ULL(1)) << VT1_SMRC_CLUSTERRESET_PCLRSPBRIDGEENABLE_POS)

#define VT1_SMRC_CLUSTERCONFIG_OFFSET _ULL(0x1)

#define VT1_SMRC_CLUSTERCONFIG_POS 0
#define VT1_SMRC_CLUSTERCONFIG_WID 28
#define VT1_SMRC_CLUSTERCONFIG_MSK (((_ULL(1) << VT1_SMRC_CLUSTERCONFIG_WID) - _ULL(1)) << VT1_SMRC_CLUSTERCONFIG_POS)

#define VT1_SMRC_CLUSTERCONFIG_CLUSTERID_POS 0
#define VT1_SMRC_CLUSTERCONFIG_CLUSTERID_WID 4
#define VT1_SMRC_CLUSTERCONFIG_CLUSTERID_MSK (((_ULL(1) << VT1_SMRC_CLUSTERCONFIG_CLUSTERID_WID) - _ULL(1)) << VT1_SMRC_CLUSTERCONFIG_CLUSTERID_POS)
#define VT1_SMRC_CLUSTERCONFIG_CPUVECTOR_POS 4
#define VT1_SMRC_CLUSTERCONFIG_CPUVECTOR_WID 8
#define VT1_SMRC_CLUSTERCONFIG_CPUVECTOR_MSK (((_ULL(1) << VT1_SMRC_CLUSTERCONFIG_CPUVECTOR_WID) - _ULL(1)) << VT1_SMRC_CLUSTERCONFIG_CPUVECTOR_POS)
#define VT1_SMRC_CLUSTERCONFIG_NUMBERL3MSLICE_POS 20
#define VT1_SMRC_CLUSTERCONFIG_NUMBERL3MSLICE_WID 5
#define VT1_SMRC_CLUSTERCONFIG_NUMBERL3MSLICE_MSK (((_ULL(1) << VT1_SMRC_CLUSTERCONFIG_NUMBERL3MSLICE_WID) - _ULL(1)) << VT1_SMRC_CLUSTERCONFIG_NUMBERL3MSLICE_POS)
#define VT1_SMRC_CLUSTERCONFIG_L3MSLICECAP_POS 25
#define VT1_SMRC_CLUSTERCONFIG_L3MSLICECAP_WID 3
#define VT1_SMRC_CLUSTERCONFIG_L3MSLICECAP_MSK (((_ULL(1) << VT1_SMRC_CLUSTERCONFIG_L3MSLICECAP_WID) - _ULL(1)) << VT1_SMRC_CLUSTERCONFIG_L3MSLICECAP_POS)

#define VT1_SMRC_CLUSTERISOLATION_OFFSET _ULL(0x2)

#define VT1_SMRC_CLUSTERISOLATION_POS 0
#define VT1_SMRC_CLUSTERISOLATION_WID 1
#define VT1_SMRC_CLUSTERISOLATION_MSK (((_ULL(1) << VT1_SMRC_CLUSTERISOLATION_WID) - _ULL(1)) << VT1_SMRC_CLUSTERISOLATION_POS)

#define VT1_SMRC_CLUSTERISOLATION_ENABLE_POS 0
#define VT1_SMRC_CLUSTERISOLATION_ENABLE_WID 1
#define VT1_SMRC_CLUSTERISOLATION_ENABLE_MSK (((_ULL(1) << VT1_SMRC_CLUSTERISOLATION_ENABLE_WID) - _ULL(1)) << VT1_SMRC_CLUSTERISOLATION_ENABLE_POS)

#define VT1_SMRC_BISRSTATUS_OFFSET _ULL(0x3)

#define VT1_SMRC_BISRSTATUS_POS 0
#define VT1_SMRC_BISRSTATUS_WID 3
#define VT1_SMRC_BISRSTATUS_MSK (((_ULL(1) << VT1_SMRC_BISRSTATUS_WID) - _ULL(1)) << VT1_SMRC_BISRSTATUS_POS)

#define VT1_SMRC_BISRSTATUS_BISRGO_POS 0
#define VT1_SMRC_BISRSTATUS_BISRGO_WID 1
#define VT1_SMRC_BISRSTATUS_BISRGO_MSK (((_ULL(1) << VT1_SMRC_BISRSTATUS_BISRGO_WID) - _ULL(1)) << VT1_SMRC_BISRSTATUS_BISRGO_POS)
#define VT1_SMRC_BISRSTATUS_BISRDONE_POS 1
#define VT1_SMRC_BISRSTATUS_BISRDONE_WID 1
#define VT1_SMRC_BISRSTATUS_BISRDONE_MSK (((_ULL(1) << VT1_SMRC_BISRSTATUS_BISRDONE_WID) - _ULL(1)) << VT1_SMRC_BISRSTATUS_BISRDONE_POS)
#define VT1_SMRC_BISRSTATUS_BISRCLKFREQ_POS 2
#define VT1_SMRC_BISRSTATUS_BISRCLKFREQ_WID 1
#define VT1_SMRC_BISRSTATUS_BISRCLKFREQ_MSK (((_ULL(1) << VT1_SMRC_BISRSTATUS_BISRCLKFREQ_WID) - _ULL(1)) << VT1_SMRC_BISRSTATUS_BISRCLKFREQ_POS)

#define VT1_SMRC_SPXCONFIG_OFFSET _ULL(0x4)

#define VT1_SMRC_SPXCONFIG_POS 1
#define VT1_SMRC_SPXCONFIG_WID 2
#define VT1_SMRC_SPXCONFIG_MSK (((_ULL(1) << VT1_SMRC_SPXCONFIG_WID) - _ULL(1)) << VT1_SMRC_SPXCONFIG_POS)

#define VT1_SMRC_SPXCONFIG_DBMDAUTHENTICATED_POS 1
#define VT1_SMRC_SPXCONFIG_DBMDAUTHENTICATED_WID 1
#define VT1_SMRC_SPXCONFIG_DBMDAUTHENTICATED_MSK (((_ULL(1) << VT1_SMRC_SPXCONFIG_DBMDAUTHENTICATED_WID) - _ULL(1)) << VT1_SMRC_SPXCONFIG_DBMDAUTHENTICATED_POS)
#define VT1_SMRC_SPXCONFIG_DBMDEXTERNALENABLE_POS 2
#define VT1_SMRC_SPXCONFIG_DBMDEXTERNALENABLE_WID 1
#define VT1_SMRC_SPXCONFIG_DBMDEXTERNALENABLE_MSK (((_ULL(1) << VT1_SMRC_SPXCONFIG_DBMDEXTERNALENABLE_WID) - _ULL(1)) << VT1_SMRC_SPXCONFIG_DBMDEXTERNALENABLE_POS)

#define VT1_SMRC_DBIDDVECBASE_OFFSET _ULL(0x200)

#define VT1_SMRC_DBIDDVECBASE_POS 12
#define VT1_SMRC_DBIDDVECBASE_WID 51
#define VT1_SMRC_DBIDDVECBASE_MSK (((_ULL(1) << VT1_SMRC_DBIDDVECBASE_WID) - _ULL(1)) << VT1_SMRC_DBIDDVECBASE_POS)

#define VT1_SMRC_DBIDDVECBASE_BASE_POS 12
#define VT1_SMRC_DBIDDVECBASE_BASE_WID 40
#define VT1_SMRC_DBIDDVECBASE_BASE_MSK (((_ULL(1) << VT1_SMRC_DBIDDVECBASE_BASE_WID) - _ULL(1)) << VT1_SMRC_DBIDDVECBASE_BASE_POS)
#define VT1_SMRC_DBIDDVECBASE_ENABLE_POS 62
#define VT1_SMRC_DBIDDVECBASE_ENABLE_WID 1
#define VT1_SMRC_DBIDDVECBASE_ENABLE_MSK (((_ULL(1) << VT1_SMRC_DBIDDVECBASE_ENABLE_WID) - _ULL(1)) << VT1_SMRC_DBIDDVECBASE_ENABLE_POS)

#define VT1_SMRC_DBIDDREGBASE_OFFSET _ULL(0x201)

#define VT1_SMRC_DBIDDREGBASE_POS 12
#define VT1_SMRC_DBIDDREGBASE_WID 51
#define VT1_SMRC_DBIDDREGBASE_MSK (((_ULL(1) << VT1_SMRC_DBIDDREGBASE_WID) - _ULL(1)) << VT1_SMRC_DBIDDREGBASE_POS)

#define VT1_SMRC_DBIDDREGBASE_BASE_POS 12
#define VT1_SMRC_DBIDDREGBASE_BASE_WID 40
#define VT1_SMRC_DBIDDREGBASE_BASE_MSK (((_ULL(1) << VT1_SMRC_DBIDDREGBASE_BASE_WID) - _ULL(1)) << VT1_SMRC_DBIDDREGBASE_BASE_POS)
#define VT1_SMRC_DBIDDREGBASE_ENABLE_POS 62
#define VT1_SMRC_DBIDDREGBASE_ENABLE_WID 1
#define VT1_SMRC_DBIDDREGBASE_ENABLE_MSK (((_ULL(1) << VT1_SMRC_DBIDDREGBASE_ENABLE_WID) - _ULL(1)) << VT1_SMRC_DBIDDREGBASE_ENABLE_POS)

#define VT1_SMRC_DBIDPUCBASE_OFFSET _ULL(0x202)

#define VT1_SMRC_DBIDPUCBASE_POS 12
#define VT1_SMRC_DBIDPUCBASE_WID 51
#define VT1_SMRC_DBIDPUCBASE_MSK (((_ULL(1) << VT1_SMRC_DBIDPUCBASE_WID) - _ULL(1)) << VT1_SMRC_DBIDPUCBASE_POS)

#define VT1_SMRC_DBIDPUCBASE_BASE_POS 12
#define VT1_SMRC_DBIDPUCBASE_BASE_WID 40
#define VT1_SMRC_DBIDPUCBASE_BASE_MSK (((_ULL(1) << VT1_SMRC_DBIDPUCBASE_BASE_WID) - _ULL(1)) << VT1_SMRC_DBIDPUCBASE_BASE_POS)
#define VT1_SMRC_DBIDPUCBASE_ENABLE_POS 62
#define VT1_SMRC_DBIDPUCBASE_ENABLE_WID 1
#define VT1_SMRC_DBIDPUCBASE_ENABLE_MSK (((_ULL(1) << VT1_SMRC_DBIDPUCBASE_ENABLE_WID) - _ULL(1)) << VT1_SMRC_DBIDPUCBASE_ENABLE_POS)

#define VT1_SMRC_LWICMMODETIMERBASE_OFFSET _ULL(0x204)

#define VT1_SMRC_LWICMMODETIMERBASE_POS 14
#define VT1_SMRC_LWICMMODETIMERBASE_WID 49
#define VT1_SMRC_LWICMMODETIMERBASE_MSK (((_ULL(1) << VT1_SMRC_LWICMMODETIMERBASE_WID) - _ULL(1)) << VT1_SMRC_LWICMMODETIMERBASE_POS)

#define VT1_SMRC_LWICMMODETIMERBASE_BASE_POS 14
#define VT1_SMRC_LWICMMODETIMERBASE_BASE_WID 38
#define VT1_SMRC_LWICMMODETIMERBASE_BASE_MSK (((_ULL(1) << VT1_SMRC_LWICMMODETIMERBASE_BASE_WID) - _ULL(1)) << VT1_SMRC_LWICMMODETIMERBASE_BASE_POS)
#define VT1_SMRC_LWICMMODETIMERBASE_ENABLE_POS 62
#define VT1_SMRC_LWICMMODETIMERBASE_ENABLE_WID 1
#define VT1_SMRC_LWICMMODETIMERBASE_ENABLE_MSK (((_ULL(1) << VT1_SMRC_LWICMMODETIMERBASE_ENABLE_WID) - _ULL(1)) << VT1_SMRC_LWICMMODETIMERBASE_ENABLE_POS)

#define VT1_SMRC_SMRCBASE_OFFSET _ULL(0x208)

#define VT1_SMRC_SMRCBASE_POS 14
#define VT1_SMRC_SMRCBASE_WID 49
#define VT1_SMRC_SMRCBASE_MSK (((_ULL(1) << VT1_SMRC_SMRCBASE_WID) - _ULL(1)) << VT1_SMRC_SMRCBASE_POS)

#define VT1_SMRC_SMRCBASE_BASE_POS 14
#define VT1_SMRC_SMRCBASE_BASE_WID 38
#define VT1_SMRC_SMRCBASE_BASE_MSK (((_ULL(1) << VT1_SMRC_SMRCBASE_BASE_WID) - _ULL(1)) << VT1_SMRC_SMRCBASE_BASE_POS)
#define VT1_SMRC_SMRCBASE_ENABLE_POS 62
#define VT1_SMRC_SMRCBASE_ENABLE_WID 1
#define VT1_SMRC_SMRCBASE_ENABLE_MSK (((_ULL(1) << VT1_SMRC_SMRCBASE_ENABLE_WID) - _ULL(1)) << VT1_SMRC_SMRCBASE_ENABLE_POS)

#define VT1_SMRC_CHIBBASE_OFFSET _ULL(0x20c)

#define VT1_SMRC_CHIBBASE_POS 14
#define VT1_SMRC_CHIBBASE_WID 49
#define VT1_SMRC_CHIBBASE_MSK (((_ULL(1) << VT1_SMRC_CHIBBASE_WID) - _ULL(1)) << VT1_SMRC_CHIBBASE_POS)

#define VT1_SMRC_CHIBBASE_BASE_POS 14
#define VT1_SMRC_CHIBBASE_BASE_WID 38
#define VT1_SMRC_CHIBBASE_BASE_MSK (((_ULL(1) << VT1_SMRC_CHIBBASE_BASE_WID) - _ULL(1)) << VT1_SMRC_CHIBBASE_BASE_POS)
#define VT1_SMRC_CHIBBASE_ENABLE_POS 62
#define VT1_SMRC_CHIBBASE_ENABLE_WID 1
#define VT1_SMRC_CHIBBASE_ENABLE_MSK (((_ULL(1) << VT1_SMRC_CHIBBASE_ENABLE_WID) - _ULL(1)) << VT1_SMRC_CHIBBASE_ENABLE_POS)

#define VT1_SMRC_SDDIBASE_OFFSET _ULL(0x220)

#define VT1_SMRC_SDDIBASE_POS 16
#define VT1_SMRC_SDDIBASE_WID 47
#define VT1_SMRC_SDDIBASE_MSK (((_ULL(1) << VT1_SMRC_SDDIBASE_WID) - _ULL(1)) << VT1_SMRC_SDDIBASE_POS)

#define VT1_SMRC_SDDIBASE_BASE_POS 16
#define VT1_SMRC_SDDIBASE_BASE_WID 36
#define VT1_SMRC_SDDIBASE_BASE_MSK (((_ULL(1) << VT1_SMRC_SDDIBASE_BASE_WID) - _ULL(1)) << VT1_SMRC_SDDIBASE_BASE_POS)
#define VT1_SMRC_SDDIBASE_ENABLE_POS 62
#define VT1_SMRC_SDDIBASE_ENABLE_WID 1
#define VT1_SMRC_SDDIBASE_ENABLE_MSK (((_ULL(1) << VT1_SMRC_SDDIBASE_ENABLE_WID) - _ULL(1)) << VT1_SMRC_SDDIBASE_ENABLE_POS)

#define VT1_SMRC_CKGNBASE_OFFSET _ULL(0x230)

#define VT1_SMRC_CKGNBASE_POS 14
#define VT1_SMRC_CKGNBASE_WID 49
#define VT1_SMRC_CKGNBASE_MSK (((_ULL(1) << VT1_SMRC_CKGNBASE_WID) - _ULL(1)) << VT1_SMRC_CKGNBASE_POS)

#define VT1_SMRC_CKGNBASE_BASE_POS 14
#define VT1_SMRC_CKGNBASE_BASE_WID 38
#define VT1_SMRC_CKGNBASE_BASE_MSK (((_ULL(1) << VT1_SMRC_CKGNBASE_BASE_WID) - _ULL(1)) << VT1_SMRC_CKGNBASE_BASE_POS)
#define VT1_SMRC_CKGNBASE_ENABLE_POS 62
#define VT1_SMRC_CKGNBASE_ENABLE_WID 1
#define VT1_SMRC_CKGNBASE_ENABLE_MSK (((_ULL(1) << VT1_SMRC_CKGNBASE_ENABLE_WID) - _ULL(1)) << VT1_SMRC_CKGNBASE_ENABLE_POS)

#define VT1_SMRC_I3CBASE_OFFSET _ULL(0x23f)

#define VT1_SMRC_I3CBASE_POS 12
#define VT1_SMRC_I3CBASE_WID 51
#define VT1_SMRC_I3CBASE_MSK (((_ULL(1) << VT1_SMRC_I3CBASE_WID) - _ULL(1)) << VT1_SMRC_I3CBASE_POS)

#define VT1_SMRC_I3CBASE_BASE_POS 12
#define VT1_SMRC_I3CBASE_BASE_WID 40
#define VT1_SMRC_I3CBASE_BASE_MSK (((_ULL(1) << VT1_SMRC_I3CBASE_BASE_WID) - _ULL(1)) << VT1_SMRC_I3CBASE_BASE_POS)
#define VT1_SMRC_I3CBASE_ENABLE_POS 62
#define VT1_SMRC_I3CBASE_ENABLE_WID 1
#define VT1_SMRC_I3CBASE_ENABLE_MSK (((_ULL(1) << VT1_SMRC_I3CBASE_ENABLE_WID) - _ULL(1)) << VT1_SMRC_I3CBASE_ENABLE_POS)

#define VT1_SMRC_PCLBASE_OFFSET _ULL(0x2ff)

#define VT1_SMRC_PCLBASE_POS 23
#define VT1_SMRC_PCLBASE_WID 40
#define VT1_SMRC_PCLBASE_MSK (((_ULL(1) << VT1_SMRC_PCLBASE_WID) - _ULL(1)) << VT1_SMRC_PCLBASE_POS)

#define VT1_SMRC_PCLBASE_BASE_POS 23
#define VT1_SMRC_PCLBASE_BASE_WID 29
#define VT1_SMRC_PCLBASE_BASE_MSK (((_ULL(1) << VT1_SMRC_PCLBASE_BASE_WID) - _ULL(1)) << VT1_SMRC_PCLBASE_BASE_POS)
#define VT1_SMRC_PCLBASE_ENABLE_POS 62
#define VT1_SMRC_PCLBASE_ENABLE_WID 1
#define VT1_SMRC_PCLBASE_ENABLE_MSK (((_ULL(1) << VT1_SMRC_PCLBASE_ENABLE_WID) - _ULL(1)) << VT1_SMRC_PCLBASE_ENABLE_POS)

#define VT1_SMRC_DBIDDVECSTAGING_OFFSET _ULL(0x300)

#define VT1_SMRC_DBIDDVECSTAGING_POS 12
#define VT1_SMRC_DBIDDVECSTAGING_WID 52
#define VT1_SMRC_DBIDDVECSTAGING_MSK (((_ULL(1) << VT1_SMRC_DBIDDVECSTAGING_WID) - _ULL(1)) << VT1_SMRC_DBIDDVECSTAGING_POS)

#define VT1_SMRC_DBIDDVECSTAGING_BASE_POS 12
#define VT1_SMRC_DBIDDVECSTAGING_BASE_WID 40
#define VT1_SMRC_DBIDDVECSTAGING_BASE_MSK (((_ULL(1) << VT1_SMRC_DBIDDVECSTAGING_BASE_WID) - _ULL(1)) << VT1_SMRC_DBIDDVECSTAGING_BASE_POS)
#define VT1_SMRC_DBIDDVECSTAGING_ENABLE_POS 62
#define VT1_SMRC_DBIDDVECSTAGING_ENABLE_WID 1
#define VT1_SMRC_DBIDDVECSTAGING_ENABLE_MSK (((_ULL(1) << VT1_SMRC_DBIDDVECSTAGING_ENABLE_WID) - _ULL(1)) << VT1_SMRC_DBIDDVECSTAGING_ENABLE_POS)
#define VT1_SMRC_DBIDDVECSTAGING_LOAD_POS 63
#define VT1_SMRC_DBIDDVECSTAGING_LOAD_WID 1
#define VT1_SMRC_DBIDDVECSTAGING_LOAD_MSK (((_ULL(1) << VT1_SMRC_DBIDDVECSTAGING_LOAD_WID) - _ULL(1)) << VT1_SMRC_DBIDDVECSTAGING_LOAD_POS)

#define VT1_SMRC_DBIDDREGSTAGING_OFFSET _ULL(0x301)

#define VT1_SMRC_DBIDDREGSTAGING_POS 12
#define VT1_SMRC_DBIDDREGSTAGING_WID 52
#define VT1_SMRC_DBIDDREGSTAGING_MSK (((_ULL(1) << VT1_SMRC_DBIDDREGSTAGING_WID) - _ULL(1)) << VT1_SMRC_DBIDDREGSTAGING_POS)

#define VT1_SMRC_DBIDDREGSTAGING_BASE_POS 12
#define VT1_SMRC_DBIDDREGSTAGING_BASE_WID 40
#define VT1_SMRC_DBIDDREGSTAGING_BASE_MSK (((_ULL(1) << VT1_SMRC_DBIDDREGSTAGING_BASE_WID) - _ULL(1)) << VT1_SMRC_DBIDDREGSTAGING_BASE_POS)
#define VT1_SMRC_DBIDDREGSTAGING_ENABLE_POS 62
#define VT1_SMRC_DBIDDREGSTAGING_ENABLE_WID 1
#define VT1_SMRC_DBIDDREGSTAGING_ENABLE_MSK (((_ULL(1) << VT1_SMRC_DBIDDREGSTAGING_ENABLE_WID) - _ULL(1)) << VT1_SMRC_DBIDDREGSTAGING_ENABLE_POS)
#define VT1_SMRC_DBIDDREGSTAGING_LOAD_POS 63
#define VT1_SMRC_DBIDDREGSTAGING_LOAD_WID 1
#define VT1_SMRC_DBIDDREGSTAGING_LOAD_MSK (((_ULL(1) << VT1_SMRC_DBIDDREGSTAGING_LOAD_WID) - _ULL(1)) << VT1_SMRC_DBIDDREGSTAGING_LOAD_POS)

#define VT1_SMRC_DBIDPUCSTAGING_OFFSET _ULL(0x302)

#define VT1_SMRC_DBIDPUCSTAGING_POS 12
#define VT1_SMRC_DBIDPUCSTAGING_WID 52
#define VT1_SMRC_DBIDPUCSTAGING_MSK (((_ULL(1) << VT1_SMRC_DBIDPUCSTAGING_WID) - _ULL(1)) << VT1_SMRC_DBIDPUCSTAGING_POS)

#define VT1_SMRC_DBIDPUCSTAGING_BASE_POS 12
#define VT1_SMRC_DBIDPUCSTAGING_BASE_WID 40
#define VT1_SMRC_DBIDPUCSTAGING_BASE_MSK (((_ULL(1) << VT1_SMRC_DBIDPUCSTAGING_BASE_WID) - _ULL(1)) << VT1_SMRC_DBIDPUCSTAGING_BASE_POS)
#define VT1_SMRC_DBIDPUCSTAGING_ENABLE_POS 62
#define VT1_SMRC_DBIDPUCSTAGING_ENABLE_WID 1
#define VT1_SMRC_DBIDPUCSTAGING_ENABLE_MSK (((_ULL(1) << VT1_SMRC_DBIDPUCSTAGING_ENABLE_WID) - _ULL(1)) << VT1_SMRC_DBIDPUCSTAGING_ENABLE_POS)
#define VT1_SMRC_DBIDPUCSTAGING_LOAD_POS 63
#define VT1_SMRC_DBIDPUCSTAGING_LOAD_WID 1
#define VT1_SMRC_DBIDPUCSTAGING_LOAD_MSK (((_ULL(1) << VT1_SMRC_DBIDPUCSTAGING_LOAD_WID) - _ULL(1)) << VT1_SMRC_DBIDPUCSTAGING_LOAD_POS)

#define VT1_SMRC_LWICMMODETIMERSTAGING_OFFSET _ULL(0x304)

#define VT1_SMRC_LWICMMODETIMERSTAGING_POS 14
#define VT1_SMRC_LWICMMODETIMERSTAGING_WID 50
#define VT1_SMRC_LWICMMODETIMERSTAGING_MSK (((_ULL(1) << VT1_SMRC_LWICMMODETIMERSTAGING_WID) - _ULL(1)) << VT1_SMRC_LWICMMODETIMERSTAGING_POS)

#define VT1_SMRC_LWICMMODETIMERSTAGING_BASE_POS 14
#define VT1_SMRC_LWICMMODETIMERSTAGING_BASE_WID 38
#define VT1_SMRC_LWICMMODETIMERSTAGING_BASE_MSK (((_ULL(1) << VT1_SMRC_LWICMMODETIMERSTAGING_BASE_WID) - _ULL(1)) << VT1_SMRC_LWICMMODETIMERSTAGING_BASE_POS)
#define VT1_SMRC_LWICMMODETIMERSTAGING_ENABLE_POS 62
#define VT1_SMRC_LWICMMODETIMERSTAGING_ENABLE_WID 1
#define VT1_SMRC_LWICMMODETIMERSTAGING_ENABLE_MSK (((_ULL(1) << VT1_SMRC_LWICMMODETIMERSTAGING_ENABLE_WID) - _ULL(1)) << VT1_SMRC_LWICMMODETIMERSTAGING_ENABLE_POS)
#define VT1_SMRC_LWICMMODETIMERSTAGING_LOAD_POS 63
#define VT1_SMRC_LWICMMODETIMERSTAGING_LOAD_WID 1
#define VT1_SMRC_LWICMMODETIMERSTAGING_LOAD_MSK (((_ULL(1) << VT1_SMRC_LWICMMODETIMERSTAGING_LOAD_WID) - _ULL(1)) << VT1_SMRC_LWICMMODETIMERSTAGING_LOAD_POS)

#define VT1_SMRC_SMRCSTAGING_OFFSET _ULL(0x308)

#define VT1_SMRC_SMRCSTAGING_POS 14
#define VT1_SMRC_SMRCSTAGING_WID 50
#define VT1_SMRC_SMRCSTAGING_MSK (((_ULL(1) << VT1_SMRC_SMRCSTAGING_WID) - _ULL(1)) << VT1_SMRC_SMRCSTAGING_POS)

#define VT1_SMRC_SMRCSTAGING_BASE_POS 14
#define VT1_SMRC_SMRCSTAGING_BASE_WID 38
#define VT1_SMRC_SMRCSTAGING_BASE_MSK (((_ULL(1) << VT1_SMRC_SMRCSTAGING_BASE_WID) - _ULL(1)) << VT1_SMRC_SMRCSTAGING_BASE_POS)
#define VT1_SMRC_SMRCSTAGING_ENABLE_POS 62
#define VT1_SMRC_SMRCSTAGING_ENABLE_WID 1
#define VT1_SMRC_SMRCSTAGING_ENABLE_MSK (((_ULL(1) << VT1_SMRC_SMRCSTAGING_ENABLE_WID) - _ULL(1)) << VT1_SMRC_SMRCSTAGING_ENABLE_POS)
#define VT1_SMRC_SMRCSTAGING_LOAD_POS 63
#define VT1_SMRC_SMRCSTAGING_LOAD_WID 1
#define VT1_SMRC_SMRCSTAGING_LOAD_MSK (((_ULL(1) << VT1_SMRC_SMRCSTAGING_LOAD_WID) - _ULL(1)) << VT1_SMRC_SMRCSTAGING_LOAD_POS)

#define VT1_SMRC_CHIBSTAGING_OFFSET _ULL(0x30c)

#define VT1_SMRC_CHIBSTAGING_POS 14
#define VT1_SMRC_CHIBSTAGING_WID 50
#define VT1_SMRC_CHIBSTAGING_MSK (((_ULL(1) << VT1_SMRC_CHIBSTAGING_WID) - _ULL(1)) << VT1_SMRC_CHIBSTAGING_POS)

#define VT1_SMRC_CHIBSTAGING_BASE_POS 14
#define VT1_SMRC_CHIBSTAGING_BASE_WID 38
#define VT1_SMRC_CHIBSTAGING_BASE_MSK (((_ULL(1) << VT1_SMRC_CHIBSTAGING_BASE_WID) - _ULL(1)) << VT1_SMRC_CHIBSTAGING_BASE_POS)
#define VT1_SMRC_CHIBSTAGING_ENABLE_POS 62
#define VT1_SMRC_CHIBSTAGING_ENABLE_WID 1
#define VT1_SMRC_CHIBSTAGING_ENABLE_MSK (((_ULL(1) << VT1_SMRC_CHIBSTAGING_ENABLE_WID) - _ULL(1)) << VT1_SMRC_CHIBSTAGING_ENABLE_POS)
#define VT1_SMRC_CHIBSTAGING_LOAD_POS 63
#define VT1_SMRC_CHIBSTAGING_LOAD_WID 1
#define VT1_SMRC_CHIBSTAGING_LOAD_MSK (((_ULL(1) << VT1_SMRC_CHIBSTAGING_LOAD_WID) - _ULL(1)) << VT1_SMRC_CHIBSTAGING_LOAD_POS)

#define VT1_SMRC_SDDISTAGING_OFFSET _ULL(0x320)

#define VT1_SMRC_SDDISTAGING_POS 16
#define VT1_SMRC_SDDISTAGING_WID 48
#define VT1_SMRC_SDDISTAGING_MSK (((_ULL(1) << VT1_SMRC_SDDISTAGING_WID) - _ULL(1)) << VT1_SMRC_SDDISTAGING_POS)

#define VT1_SMRC_SDDISTAGING_BASE_POS 16
#define VT1_SMRC_SDDISTAGING_BASE_WID 36
#define VT1_SMRC_SDDISTAGING_BASE_MSK (((_ULL(1) << VT1_SMRC_SDDISTAGING_BASE_WID) - _ULL(1)) << VT1_SMRC_SDDISTAGING_BASE_POS)
#define VT1_SMRC_SDDISTAGING_ENABLE_POS 62
#define VT1_SMRC_SDDISTAGING_ENABLE_WID 1
#define VT1_SMRC_SDDISTAGING_ENABLE_MSK (((_ULL(1) << VT1_SMRC_SDDISTAGING_ENABLE_WID) - _ULL(1)) << VT1_SMRC_SDDISTAGING_ENABLE_POS)
#define VT1_SMRC_SDDISTAGING_LOAD_POS 63
#define VT1_SMRC_SDDISTAGING_LOAD_WID 1
#define VT1_SMRC_SDDISTAGING_LOAD_MSK (((_ULL(1) << VT1_SMRC_SDDISTAGING_LOAD_WID) - _ULL(1)) << VT1_SMRC_SDDISTAGING_LOAD_POS)

#define VT1_SMRC_CKGNSTAGING_OFFSET _ULL(0x330)

#define VT1_SMRC_CKGNSTAGING_POS 14
#define VT1_SMRC_CKGNSTAGING_WID 50
#define VT1_SMRC_CKGNSTAGING_MSK (((_ULL(1) << VT1_SMRC_CKGNSTAGING_WID) - _ULL(1)) << VT1_SMRC_CKGNSTAGING_POS)

#define VT1_SMRC_CKGNSTAGING_BASE_POS 14
#define VT1_SMRC_CKGNSTAGING_BASE_WID 38
#define VT1_SMRC_CKGNSTAGING_BASE_MSK (((_ULL(1) << VT1_SMRC_CKGNSTAGING_BASE_WID) - _ULL(1)) << VT1_SMRC_CKGNSTAGING_BASE_POS)
#define VT1_SMRC_CKGNSTAGING_ENABLE_POS 62
#define VT1_SMRC_CKGNSTAGING_ENABLE_WID 1
#define VT1_SMRC_CKGNSTAGING_ENABLE_MSK (((_ULL(1) << VT1_SMRC_CKGNSTAGING_ENABLE_WID) - _ULL(1)) << VT1_SMRC_CKGNSTAGING_ENABLE_POS)
#define VT1_SMRC_CKGNSTAGING_LOAD_POS 63
#define VT1_SMRC_CKGNSTAGING_LOAD_WID 1
#define VT1_SMRC_CKGNSTAGING_LOAD_MSK (((_ULL(1) << VT1_SMRC_CKGNSTAGING_LOAD_WID) - _ULL(1)) << VT1_SMRC_CKGNSTAGING_LOAD_POS)

#define VT1_SMRC_I3CSTAGING_OFFSET _ULL(0x33f)

#define VT1_SMRC_I3CSTAGING_POS 12
#define VT1_SMRC_I3CSTAGING_WID 52
#define VT1_SMRC_I3CSTAGING_MSK (((_ULL(1) << VT1_SMRC_I3CSTAGING_WID) - _ULL(1)) << VT1_SMRC_I3CSTAGING_POS)

#define VT1_SMRC_I3CSTAGING_BASE_POS 12
#define VT1_SMRC_I3CSTAGING_BASE_WID 40
#define VT1_SMRC_I3CSTAGING_BASE_MSK (((_ULL(1) << VT1_SMRC_I3CSTAGING_BASE_WID) - _ULL(1)) << VT1_SMRC_I3CSTAGING_BASE_POS)
#define VT1_SMRC_I3CSTAGING_ENABLE_POS 62
#define VT1_SMRC_I3CSTAGING_ENABLE_WID 1
#define VT1_SMRC_I3CSTAGING_ENABLE_MSK (((_ULL(1) << VT1_SMRC_I3CSTAGING_ENABLE_WID) - _ULL(1)) << VT1_SMRC_I3CSTAGING_ENABLE_POS)
#define VT1_SMRC_I3CSTAGING_LOAD_POS 63
#define VT1_SMRC_I3CSTAGING_LOAD_WID 1
#define VT1_SMRC_I3CSTAGING_LOAD_MSK (((_ULL(1) << VT1_SMRC_I3CSTAGING_LOAD_WID) - _ULL(1)) << VT1_SMRC_I3CSTAGING_LOAD_POS)

#define VT1_SMRC_PCLSTAGING_OFFSET _ULL(0x3ff)

#define VT1_SMRC_PCLSTAGING_POS 23
#define VT1_SMRC_PCLSTAGING_WID 41
#define VT1_SMRC_PCLSTAGING_MSK (((_ULL(1) << VT1_SMRC_PCLSTAGING_WID) - _ULL(1)) << VT1_SMRC_PCLSTAGING_POS)

#define VT1_SMRC_PCLSTAGING_BASE_POS 23
#define VT1_SMRC_PCLSTAGING_BASE_WID 29
#define VT1_SMRC_PCLSTAGING_BASE_MSK (((_ULL(1) << VT1_SMRC_PCLSTAGING_BASE_WID) - _ULL(1)) << VT1_SMRC_PCLSTAGING_BASE_POS)
#define VT1_SMRC_PCLSTAGING_ENABLE_POS 62
#define VT1_SMRC_PCLSTAGING_ENABLE_WID 1
#define VT1_SMRC_PCLSTAGING_ENABLE_MSK (((_ULL(1) << VT1_SMRC_PCLSTAGING_ENABLE_WID) - _ULL(1)) << VT1_SMRC_PCLSTAGING_ENABLE_POS)
#define VT1_SMRC_PCLSTAGING_LOAD_POS 63
#define VT1_SMRC_PCLSTAGING_LOAD_WID 1
#define VT1_SMRC_PCLSTAGING_LOAD_MSK (((_ULL(1) << VT1_SMRC_PCLSTAGING_LOAD_WID) - _ULL(1)) << VT1_SMRC_PCLSTAGING_LOAD_POS)
#endif /* VT1_SMRC_MMR_H */
