/* This file is auto-generated. Do not hand edit this file. */

#ifndef VT2_DBMD_MMR_H
#define VT2_DBMD_MMR_H

#ifndef _ULL

#ifdef __ASSEMBLER__
#define _AC(X,Y) X
#else
#define __AC(X,Y) (X##Y)
#define _AC(X,Y) __AC(X,Y)
#endif

#define _ULL(x)  (_AC(x, ULL))
#endif


#define VT2_DBMD_ABSTRACTDATA0_OFFSET _ULL(0x404)

#define VT2_DBMD_ABSTRACTDATA0_POS 0
#define VT2_DBMD_ABSTRACTDATA0_WID 32
#define VT2_DBMD_ABSTRACTDATA0_MSK (((_ULL(1) << VT2_DBMD_ABSTRACTDATA0_WID) - _ULL(1)) << VT2_DBMD_ABSTRACTDATA0_POS)

#define VT2_DBMD_ABSTRACTDATA0_ABSTRACTDATA_POS 0
#define VT2_DBMD_ABSTRACTDATA0_ABSTRACTDATA_WID 32
#define VT2_DBMD_ABSTRACTDATA0_ABSTRACTDATA_MSK (((_ULL(1) << VT2_DBMD_ABSTRACTDATA0_ABSTRACTDATA_WID) - _ULL(1)) << VT2_DBMD_ABSTRACTDATA0_ABSTRACTDATA_POS)

#define VT2_DBMD_ABSTRACTDATA1_OFFSET _ULL(0x405)

#define VT2_DBMD_ABSTRACTDATA1_POS 0
#define VT2_DBMD_ABSTRACTDATA1_WID 32
#define VT2_DBMD_ABSTRACTDATA1_MSK (((_ULL(1) << VT2_DBMD_ABSTRACTDATA1_WID) - _ULL(1)) << VT2_DBMD_ABSTRACTDATA1_POS)

#define VT2_DBMD_ABSTRACTDATA1_ABSTRACTDATA_POS 0
#define VT2_DBMD_ABSTRACTDATA1_ABSTRACTDATA_WID 32
#define VT2_DBMD_ABSTRACTDATA1_ABSTRACTDATA_MSK (((_ULL(1) << VT2_DBMD_ABSTRACTDATA1_ABSTRACTDATA_WID) - _ULL(1)) << VT2_DBMD_ABSTRACTDATA1_ABSTRACTDATA_POS)

#define VT2_DBMD_DMCONTROL_OFFSET _ULL(0x410)

#define VT2_DBMD_DMCONTROL_POS 0
#define VT2_DBMD_DMCONTROL_WID 32
#define VT2_DBMD_DMCONTROL_MSK (((_ULL(1) << VT2_DBMD_DMCONTROL_WID) - _ULL(1)) << VT2_DBMD_DMCONTROL_POS)

#define VT2_DBMD_DMCONTROL_DMACTIVE_POS 0
#define VT2_DBMD_DMCONTROL_DMACTIVE_WID 1
#define VT2_DBMD_DMCONTROL_DMACTIVE_MSK (((_ULL(1) << VT2_DBMD_DMCONTROL_DMACTIVE_WID) - _ULL(1)) << VT2_DBMD_DMCONTROL_DMACTIVE_POS)
#define VT2_DBMD_DMCONTROL_NDMRESET_POS 1
#define VT2_DBMD_DMCONTROL_NDMRESET_WID 1
#define VT2_DBMD_DMCONTROL_NDMRESET_MSK (((_ULL(1) << VT2_DBMD_DMCONTROL_NDMRESET_WID) - _ULL(1)) << VT2_DBMD_DMCONTROL_NDMRESET_POS)
#define VT2_DBMD_DMCONTROL_CLRRESETHALTREQ_POS 2
#define VT2_DBMD_DMCONTROL_CLRRESETHALTREQ_WID 1
#define VT2_DBMD_DMCONTROL_CLRRESETHALTREQ_MSK (((_ULL(1) << VT2_DBMD_DMCONTROL_CLRRESETHALTREQ_WID) - _ULL(1)) << VT2_DBMD_DMCONTROL_CLRRESETHALTREQ_POS)
#define VT2_DBMD_DMCONTROL_SETRESETHALTREQ_POS 3
#define VT2_DBMD_DMCONTROL_SETRESETHALTREQ_WID 1
#define VT2_DBMD_DMCONTROL_SETRESETHALTREQ_MSK (((_ULL(1) << VT2_DBMD_DMCONTROL_SETRESETHALTREQ_WID) - _ULL(1)) << VT2_DBMD_DMCONTROL_SETRESETHALTREQ_POS)
#define VT2_DBMD_DMCONTROL_HARTSELLO_POS 16
#define VT2_DBMD_DMCONTROL_HARTSELLO_WID 10
#define VT2_DBMD_DMCONTROL_HARTSELLO_MSK (((_ULL(1) << VT2_DBMD_DMCONTROL_HARTSELLO_WID) - _ULL(1)) << VT2_DBMD_DMCONTROL_HARTSELLO_POS)
#define VT2_DBMD_DMCONTROL_HASEL_POS 26
#define VT2_DBMD_DMCONTROL_HASEL_WID 1
#define VT2_DBMD_DMCONTROL_HASEL_MSK (((_ULL(1) << VT2_DBMD_DMCONTROL_HASEL_WID) - _ULL(1)) << VT2_DBMD_DMCONTROL_HASEL_POS)
#define VT2_DBMD_DMCONTROL_ACKUNAVAIL_POS 27
#define VT2_DBMD_DMCONTROL_ACKUNAVAIL_WID 1
#define VT2_DBMD_DMCONTROL_ACKUNAVAIL_MSK (((_ULL(1) << VT2_DBMD_DMCONTROL_ACKUNAVAIL_WID) - _ULL(1)) << VT2_DBMD_DMCONTROL_ACKUNAVAIL_POS)
#define VT2_DBMD_DMCONTROL_ACKHAVERESET_POS 28
#define VT2_DBMD_DMCONTROL_ACKHAVERESET_WID 1
#define VT2_DBMD_DMCONTROL_ACKHAVERESET_MSK (((_ULL(1) << VT2_DBMD_DMCONTROL_ACKHAVERESET_WID) - _ULL(1)) << VT2_DBMD_DMCONTROL_ACKHAVERESET_POS)
#define VT2_DBMD_DMCONTROL_HARTRESET_POS 29
#define VT2_DBMD_DMCONTROL_HARTRESET_WID 1
#define VT2_DBMD_DMCONTROL_HARTRESET_MSK (((_ULL(1) << VT2_DBMD_DMCONTROL_HARTRESET_WID) - _ULL(1)) << VT2_DBMD_DMCONTROL_HARTRESET_POS)
#define VT2_DBMD_DMCONTROL_RESUMEREQ_POS 30
#define VT2_DBMD_DMCONTROL_RESUMEREQ_WID 1
#define VT2_DBMD_DMCONTROL_RESUMEREQ_MSK (((_ULL(1) << VT2_DBMD_DMCONTROL_RESUMEREQ_WID) - _ULL(1)) << VT2_DBMD_DMCONTROL_RESUMEREQ_POS)
#define VT2_DBMD_DMCONTROL_HALTREQ_POS 31
#define VT2_DBMD_DMCONTROL_HALTREQ_WID 1
#define VT2_DBMD_DMCONTROL_HALTREQ_MSK (((_ULL(1) << VT2_DBMD_DMCONTROL_HALTREQ_WID) - _ULL(1)) << VT2_DBMD_DMCONTROL_HALTREQ_POS)

#define VT2_DBMD_DMSTATUS_OFFSET _ULL(0x411)

#define VT2_DBMD_DMSTATUS_POS 0
#define VT2_DBMD_DMSTATUS_WID 25
#define VT2_DBMD_DMSTATUS_MSK (((_ULL(1) << VT2_DBMD_DMSTATUS_WID) - _ULL(1)) << VT2_DBMD_DMSTATUS_POS)

#define VT2_DBMD_DMSTATUS_VERSION_POS 0
#define VT2_DBMD_DMSTATUS_VERSION_WID 4
#define VT2_DBMD_DMSTATUS_VERSION_MSK (((_ULL(1) << VT2_DBMD_DMSTATUS_VERSION_WID) - _ULL(1)) << VT2_DBMD_DMSTATUS_VERSION_POS)
#define VT2_DBMD_DMSTATUS_CONFSTRPTRVALID_POS 4
#define VT2_DBMD_DMSTATUS_CONFSTRPTRVALID_WID 1
#define VT2_DBMD_DMSTATUS_CONFSTRPTRVALID_MSK (((_ULL(1) << VT2_DBMD_DMSTATUS_CONFSTRPTRVALID_WID) - _ULL(1)) << VT2_DBMD_DMSTATUS_CONFSTRPTRVALID_POS)
#define VT2_DBMD_DMSTATUS_HASRESETHALTREQ_POS 5
#define VT2_DBMD_DMSTATUS_HASRESETHALTREQ_WID 1
#define VT2_DBMD_DMSTATUS_HASRESETHALTREQ_MSK (((_ULL(1) << VT2_DBMD_DMSTATUS_HASRESETHALTREQ_WID) - _ULL(1)) << VT2_DBMD_DMSTATUS_HASRESETHALTREQ_POS)
#define VT2_DBMD_DMSTATUS_AUTHBUSY_POS 6
#define VT2_DBMD_DMSTATUS_AUTHBUSY_WID 1
#define VT2_DBMD_DMSTATUS_AUTHBUSY_MSK (((_ULL(1) << VT2_DBMD_DMSTATUS_AUTHBUSY_WID) - _ULL(1)) << VT2_DBMD_DMSTATUS_AUTHBUSY_POS)
#define VT2_DBMD_DMSTATUS_AUTHENTICATED_POS 7
#define VT2_DBMD_DMSTATUS_AUTHENTICATED_WID 1
#define VT2_DBMD_DMSTATUS_AUTHENTICATED_MSK (((_ULL(1) << VT2_DBMD_DMSTATUS_AUTHENTICATED_WID) - _ULL(1)) << VT2_DBMD_DMSTATUS_AUTHENTICATED_POS)
#define VT2_DBMD_DMSTATUS_ANYHALTED_POS 8
#define VT2_DBMD_DMSTATUS_ANYHALTED_WID 1
#define VT2_DBMD_DMSTATUS_ANYHALTED_MSK (((_ULL(1) << VT2_DBMD_DMSTATUS_ANYHALTED_WID) - _ULL(1)) << VT2_DBMD_DMSTATUS_ANYHALTED_POS)
#define VT2_DBMD_DMSTATUS_ALLHALTED_POS 9
#define VT2_DBMD_DMSTATUS_ALLHALTED_WID 1
#define VT2_DBMD_DMSTATUS_ALLHALTED_MSK (((_ULL(1) << VT2_DBMD_DMSTATUS_ALLHALTED_WID) - _ULL(1)) << VT2_DBMD_DMSTATUS_ALLHALTED_POS)
#define VT2_DBMD_DMSTATUS_ANYRUNNING_POS 10
#define VT2_DBMD_DMSTATUS_ANYRUNNING_WID 1
#define VT2_DBMD_DMSTATUS_ANYRUNNING_MSK (((_ULL(1) << VT2_DBMD_DMSTATUS_ANYRUNNING_WID) - _ULL(1)) << VT2_DBMD_DMSTATUS_ANYRUNNING_POS)
#define VT2_DBMD_DMSTATUS_ALLRUNNING_POS 11
#define VT2_DBMD_DMSTATUS_ALLRUNNING_WID 1
#define VT2_DBMD_DMSTATUS_ALLRUNNING_MSK (((_ULL(1) << VT2_DBMD_DMSTATUS_ALLRUNNING_WID) - _ULL(1)) << VT2_DBMD_DMSTATUS_ALLRUNNING_POS)
#define VT2_DBMD_DMSTATUS_ANYUNAVAIL_POS 12
#define VT2_DBMD_DMSTATUS_ANYUNAVAIL_WID 1
#define VT2_DBMD_DMSTATUS_ANYUNAVAIL_MSK (((_ULL(1) << VT2_DBMD_DMSTATUS_ANYUNAVAIL_WID) - _ULL(1)) << VT2_DBMD_DMSTATUS_ANYUNAVAIL_POS)
#define VT2_DBMD_DMSTATUS_ALLUNAVAIL_POS 13
#define VT2_DBMD_DMSTATUS_ALLUNAVAIL_WID 1
#define VT2_DBMD_DMSTATUS_ALLUNAVAIL_MSK (((_ULL(1) << VT2_DBMD_DMSTATUS_ALLUNAVAIL_WID) - _ULL(1)) << VT2_DBMD_DMSTATUS_ALLUNAVAIL_POS)
#define VT2_DBMD_DMSTATUS_ANYNONEXISTENT_POS 14
#define VT2_DBMD_DMSTATUS_ANYNONEXISTENT_WID 1
#define VT2_DBMD_DMSTATUS_ANYNONEXISTENT_MSK (((_ULL(1) << VT2_DBMD_DMSTATUS_ANYNONEXISTENT_WID) - _ULL(1)) << VT2_DBMD_DMSTATUS_ANYNONEXISTENT_POS)
#define VT2_DBMD_DMSTATUS_ALLNONEXISTENT_POS 15
#define VT2_DBMD_DMSTATUS_ALLNONEXISTENT_WID 1
#define VT2_DBMD_DMSTATUS_ALLNONEXISTENT_MSK (((_ULL(1) << VT2_DBMD_DMSTATUS_ALLNONEXISTENT_WID) - _ULL(1)) << VT2_DBMD_DMSTATUS_ALLNONEXISTENT_POS)
#define VT2_DBMD_DMSTATUS_ANYRESUMEACK_POS 16
#define VT2_DBMD_DMSTATUS_ANYRESUMEACK_WID 1
#define VT2_DBMD_DMSTATUS_ANYRESUMEACK_MSK (((_ULL(1) << VT2_DBMD_DMSTATUS_ANYRESUMEACK_WID) - _ULL(1)) << VT2_DBMD_DMSTATUS_ANYRESUMEACK_POS)
#define VT2_DBMD_DMSTATUS_ALLRESUMEACK_POS 17
#define VT2_DBMD_DMSTATUS_ALLRESUMEACK_WID 1
#define VT2_DBMD_DMSTATUS_ALLRESUMEACK_MSK (((_ULL(1) << VT2_DBMD_DMSTATUS_ALLRESUMEACK_WID) - _ULL(1)) << VT2_DBMD_DMSTATUS_ALLRESUMEACK_POS)
#define VT2_DBMD_DMSTATUS_ANYHAVERESET_POS 18
#define VT2_DBMD_DMSTATUS_ANYHAVERESET_WID 1
#define VT2_DBMD_DMSTATUS_ANYHAVERESET_MSK (((_ULL(1) << VT2_DBMD_DMSTATUS_ANYHAVERESET_WID) - _ULL(1)) << VT2_DBMD_DMSTATUS_ANYHAVERESET_POS)
#define VT2_DBMD_DMSTATUS_ALLHAVERESET_POS 19
#define VT2_DBMD_DMSTATUS_ALLHAVERESET_WID 1
#define VT2_DBMD_DMSTATUS_ALLHAVERESET_MSK (((_ULL(1) << VT2_DBMD_DMSTATUS_ALLHAVERESET_WID) - _ULL(1)) << VT2_DBMD_DMSTATUS_ALLHAVERESET_POS)
#define VT2_DBMD_DMSTATUS_IMPEBREAK_POS 22
#define VT2_DBMD_DMSTATUS_IMPEBREAK_WID 1
#define VT2_DBMD_DMSTATUS_IMPEBREAK_MSK (((_ULL(1) << VT2_DBMD_DMSTATUS_IMPEBREAK_WID) - _ULL(1)) << VT2_DBMD_DMSTATUS_IMPEBREAK_POS)
#define VT2_DBMD_DMSTATUS_STICKYUNAVAIL_POS 23
#define VT2_DBMD_DMSTATUS_STICKYUNAVAIL_WID 1
#define VT2_DBMD_DMSTATUS_STICKYUNAVAIL_MSK (((_ULL(1) << VT2_DBMD_DMSTATUS_STICKYUNAVAIL_WID) - _ULL(1)) << VT2_DBMD_DMSTATUS_STICKYUNAVAIL_POS)
#define VT2_DBMD_DMSTATUS_NDMRESETPENDING_POS 24
#define VT2_DBMD_DMSTATUS_NDMRESETPENDING_WID 1
#define VT2_DBMD_DMSTATUS_NDMRESETPENDING_MSK (((_ULL(1) << VT2_DBMD_DMSTATUS_NDMRESETPENDING_WID) - _ULL(1)) << VT2_DBMD_DMSTATUS_NDMRESETPENDING_POS)

#define VT2_DBMD_HAWINDOWSELECT_OFFSET _ULL(0x414)

#define VT2_DBMD_HAWINDOWSELECT_POS 0
#define VT2_DBMD_HAWINDOWSELECT_WID 32
#define VT2_DBMD_HAWINDOWSELECT_MSK (((_ULL(1) << VT2_DBMD_HAWINDOWSELECT_WID) - _ULL(1)) << VT2_DBMD_HAWINDOWSELECT_POS)

#define VT2_DBMD_HAWINDOWSELECT_HAWINDOWSELECT_POS 0
#define VT2_DBMD_HAWINDOWSELECT_HAWINDOWSELECT_WID 32
#define VT2_DBMD_HAWINDOWSELECT_HAWINDOWSELECT_MSK (((_ULL(1) << VT2_DBMD_HAWINDOWSELECT_HAWINDOWSELECT_WID) - _ULL(1)) << VT2_DBMD_HAWINDOWSELECT_HAWINDOWSELECT_POS)

#define VT2_DBMD_HAWINDOW_OFFSET _ULL(0x415)

#define VT2_DBMD_HAWINDOW_POS 0
#define VT2_DBMD_HAWINDOW_WID 32
#define VT2_DBMD_HAWINDOW_MSK (((_ULL(1) << VT2_DBMD_HAWINDOW_WID) - _ULL(1)) << VT2_DBMD_HAWINDOW_POS)

#define VT2_DBMD_HAWINDOW_HAWINDOW_POS 0
#define VT2_DBMD_HAWINDOW_HAWINDOW_WID 32
#define VT2_DBMD_HAWINDOW_HAWINDOW_MSK (((_ULL(1) << VT2_DBMD_HAWINDOW_HAWINDOW_WID) - _ULL(1)) << VT2_DBMD_HAWINDOW_HAWINDOW_POS)

#define VT2_DBMD_ABSTRACTCS_OFFSET _ULL(0x416)

#define VT2_DBMD_ABSTRACTCS_POS 0
#define VT2_DBMD_ABSTRACTCS_WID 29
#define VT2_DBMD_ABSTRACTCS_MSK (((_ULL(1) << VT2_DBMD_ABSTRACTCS_WID) - _ULL(1)) << VT2_DBMD_ABSTRACTCS_POS)

#define VT2_DBMD_ABSTRACTCS_DATACOUNT_POS 0
#define VT2_DBMD_ABSTRACTCS_DATACOUNT_WID 4
#define VT2_DBMD_ABSTRACTCS_DATACOUNT_MSK (((_ULL(1) << VT2_DBMD_ABSTRACTCS_DATACOUNT_WID) - _ULL(1)) << VT2_DBMD_ABSTRACTCS_DATACOUNT_POS)
#define VT2_DBMD_ABSTRACTCS_CMDERR_POS 8
#define VT2_DBMD_ABSTRACTCS_CMDERR_WID 3
#define VT2_DBMD_ABSTRACTCS_CMDERR_MSK (((_ULL(1) << VT2_DBMD_ABSTRACTCS_CMDERR_WID) - _ULL(1)) << VT2_DBMD_ABSTRACTCS_CMDERR_POS)
#define VT2_DBMD_ABSTRACTCS_RELAXEDPRIV_POS 11
#define VT2_DBMD_ABSTRACTCS_RELAXEDPRIV_WID 1
#define VT2_DBMD_ABSTRACTCS_RELAXEDPRIV_MSK (((_ULL(1) << VT2_DBMD_ABSTRACTCS_RELAXEDPRIV_WID) - _ULL(1)) << VT2_DBMD_ABSTRACTCS_RELAXEDPRIV_POS)
#define VT2_DBMD_ABSTRACTCS_BUSY_POS 12
#define VT2_DBMD_ABSTRACTCS_BUSY_WID 1
#define VT2_DBMD_ABSTRACTCS_BUSY_MSK (((_ULL(1) << VT2_DBMD_ABSTRACTCS_BUSY_WID) - _ULL(1)) << VT2_DBMD_ABSTRACTCS_BUSY_POS)
#define VT2_DBMD_ABSTRACTCS_PROGBUFSIZE_POS 24
#define VT2_DBMD_ABSTRACTCS_PROGBUFSIZE_WID 5
#define VT2_DBMD_ABSTRACTCS_PROGBUFSIZE_MSK (((_ULL(1) << VT2_DBMD_ABSTRACTCS_PROGBUFSIZE_WID) - _ULL(1)) << VT2_DBMD_ABSTRACTCS_PROGBUFSIZE_POS)

#define VT2_DBMD_COMMAND_OFFSET _ULL(0x417)

#define VT2_DBMD_COMMAND_POS 0
#define VT2_DBMD_COMMAND_WID 23
#define VT2_DBMD_COMMAND_MSK (((_ULL(1) << VT2_DBMD_COMMAND_WID) - _ULL(1)) << VT2_DBMD_COMMAND_POS)

#define VT2_DBMD_COMMAND_REGNO_POS 0
#define VT2_DBMD_COMMAND_REGNO_WID 16
#define VT2_DBMD_COMMAND_REGNO_MSK (((_ULL(1) << VT2_DBMD_COMMAND_REGNO_WID) - _ULL(1)) << VT2_DBMD_COMMAND_REGNO_POS)
#define VT2_DBMD_COMMAND_WRITE_POS 16
#define VT2_DBMD_COMMAND_WRITE_WID 1
#define VT2_DBMD_COMMAND_WRITE_MSK (((_ULL(1) << VT2_DBMD_COMMAND_WRITE_WID) - _ULL(1)) << VT2_DBMD_COMMAND_WRITE_POS)
#define VT2_DBMD_COMMAND_TRANSFER_POS 17
#define VT2_DBMD_COMMAND_TRANSFER_WID 1
#define VT2_DBMD_COMMAND_TRANSFER_MSK (((_ULL(1) << VT2_DBMD_COMMAND_TRANSFER_WID) - _ULL(1)) << VT2_DBMD_COMMAND_TRANSFER_POS)
#define VT2_DBMD_COMMAND_POSTEXEC_POS 18
#define VT2_DBMD_COMMAND_POSTEXEC_WID 1
#define VT2_DBMD_COMMAND_POSTEXEC_MSK (((_ULL(1) << VT2_DBMD_COMMAND_POSTEXEC_WID) - _ULL(1)) << VT2_DBMD_COMMAND_POSTEXEC_POS)
#define VT2_DBMD_COMMAND_AARPOSTINCREMENT_POS 19
#define VT2_DBMD_COMMAND_AARPOSTINCREMENT_WID 1
#define VT2_DBMD_COMMAND_AARPOSTINCREMENT_MSK (((_ULL(1) << VT2_DBMD_COMMAND_AARPOSTINCREMENT_WID) - _ULL(1)) << VT2_DBMD_COMMAND_AARPOSTINCREMENT_POS)
#define VT2_DBMD_COMMAND_AARSIZE_POS 20
#define VT2_DBMD_COMMAND_AARSIZE_WID 3
#define VT2_DBMD_COMMAND_AARSIZE_MSK (((_ULL(1) << VT2_DBMD_COMMAND_AARSIZE_WID) - _ULL(1)) << VT2_DBMD_COMMAND_AARSIZE_POS)

#define VT2_DBMD_AUTOEXEC_OFFSET _ULL(0x418)

#define VT2_DBMD_AUTOEXEC_POS 0
#define VT2_DBMD_AUTOEXEC_WID 20
#define VT2_DBMD_AUTOEXEC_MSK (((_ULL(1) << VT2_DBMD_AUTOEXEC_WID) - _ULL(1)) << VT2_DBMD_AUTOEXEC_POS)

#define VT2_DBMD_AUTOEXEC_AUTOEXECDATA_POS 0
#define VT2_DBMD_AUTOEXEC_AUTOEXECDATA_WID 2
#define VT2_DBMD_AUTOEXEC_AUTOEXECDATA_MSK (((_ULL(1) << VT2_DBMD_AUTOEXEC_AUTOEXECDATA_WID) - _ULL(1)) << VT2_DBMD_AUTOEXEC_AUTOEXECDATA_POS)
#define VT2_DBMD_AUTOEXEC_AUTOEXECPROGBUF_POS 16
#define VT2_DBMD_AUTOEXEC_AUTOEXECPROGBUF_WID 4
#define VT2_DBMD_AUTOEXEC_AUTOEXECPROGBUF_MSK (((_ULL(1) << VT2_DBMD_AUTOEXEC_AUTOEXECPROGBUF_WID) - _ULL(1)) << VT2_DBMD_AUTOEXEC_AUTOEXECPROGBUF_POS)

#define VT2_DBMD_CONFSTRPTR0_OFFSET _ULL(0x419)

#define VT2_DBMD_CONFSTRPTR0_POS 0
#define VT2_DBMD_CONFSTRPTR0_WID 32
#define VT2_DBMD_CONFSTRPTR0_MSK (((_ULL(1) << VT2_DBMD_CONFSTRPTR0_WID) - _ULL(1)) << VT2_DBMD_CONFSTRPTR0_POS)

#define VT2_DBMD_CONFSTRPTR0_CONFSTRPTR_POS 0
#define VT2_DBMD_CONFSTRPTR0_CONFSTRPTR_WID 32
#define VT2_DBMD_CONFSTRPTR0_CONFSTRPTR_MSK (((_ULL(1) << VT2_DBMD_CONFSTRPTR0_CONFSTRPTR_WID) - _ULL(1)) << VT2_DBMD_CONFSTRPTR0_CONFSTRPTR_POS)

#define VT2_DBMD_CONFSTRPTR1_OFFSET _ULL(0x41a)

#define VT2_DBMD_CONFSTRPTR1_POS 0
#define VT2_DBMD_CONFSTRPTR1_WID 32
#define VT2_DBMD_CONFSTRPTR1_MSK (((_ULL(1) << VT2_DBMD_CONFSTRPTR1_WID) - _ULL(1)) << VT2_DBMD_CONFSTRPTR1_POS)

#define VT2_DBMD_CONFSTRPTR1_CONFSTRPTR_POS 0
#define VT2_DBMD_CONFSTRPTR1_CONFSTRPTR_WID 32
#define VT2_DBMD_CONFSTRPTR1_CONFSTRPTR_MSK (((_ULL(1) << VT2_DBMD_CONFSTRPTR1_CONFSTRPTR_WID) - _ULL(1)) << VT2_DBMD_CONFSTRPTR1_CONFSTRPTR_POS)

#define VT2_DBMD_NEXTDM_OFFSET _ULL(0x41d)

#define VT2_DBMD_NEXTDM_POS 0
#define VT2_DBMD_NEXTDM_WID 32
#define VT2_DBMD_NEXTDM_MSK (((_ULL(1) << VT2_DBMD_NEXTDM_WID) - _ULL(1)) << VT2_DBMD_NEXTDM_POS)

#define VT2_DBMD_NEXTDM_NEXTDM_POS 0
#define VT2_DBMD_NEXTDM_NEXTDM_WID 32
#define VT2_DBMD_NEXTDM_NEXTDM_MSK (((_ULL(1) << VT2_DBMD_NEXTDM_NEXTDM_WID) - _ULL(1)) << VT2_DBMD_NEXTDM_NEXTDM_POS)

#define VT2_DBMD_PROGBUF0_OFFSET _ULL(0x420)

#define VT2_DBMD_PROGBUF0_POS 0
#define VT2_DBMD_PROGBUF0_WID 32
#define VT2_DBMD_PROGBUF0_MSK (((_ULL(1) << VT2_DBMD_PROGBUF0_WID) - _ULL(1)) << VT2_DBMD_PROGBUF0_POS)

#define VT2_DBMD_PROGBUF0_PROGBUF_POS 0
#define VT2_DBMD_PROGBUF0_PROGBUF_WID 32
#define VT2_DBMD_PROGBUF0_PROGBUF_MSK (((_ULL(1) << VT2_DBMD_PROGBUF0_PROGBUF_WID) - _ULL(1)) << VT2_DBMD_PROGBUF0_PROGBUF_POS)

#define VT2_DBMD_PROGBUF1_OFFSET _ULL(0x421)

#define VT2_DBMD_PROGBUF1_POS 0
#define VT2_DBMD_PROGBUF1_WID 32
#define VT2_DBMD_PROGBUF1_MSK (((_ULL(1) << VT2_DBMD_PROGBUF1_WID) - _ULL(1)) << VT2_DBMD_PROGBUF1_POS)

#define VT2_DBMD_PROGBUF1_PROGBUF_POS 0
#define VT2_DBMD_PROGBUF1_PROGBUF_WID 32
#define VT2_DBMD_PROGBUF1_PROGBUF_MSK (((_ULL(1) << VT2_DBMD_PROGBUF1_PROGBUF_WID) - _ULL(1)) << VT2_DBMD_PROGBUF1_PROGBUF_POS)

#define VT2_DBMD_PROGBUF2_OFFSET _ULL(0x422)

#define VT2_DBMD_PROGBUF2_POS 0
#define VT2_DBMD_PROGBUF2_WID 32
#define VT2_DBMD_PROGBUF2_MSK (((_ULL(1) << VT2_DBMD_PROGBUF2_WID) - _ULL(1)) << VT2_DBMD_PROGBUF2_POS)

#define VT2_DBMD_PROGBUF2_PROGBUF_POS 0
#define VT2_DBMD_PROGBUF2_PROGBUF_WID 32
#define VT2_DBMD_PROGBUF2_PROGBUF_MSK (((_ULL(1) << VT2_DBMD_PROGBUF2_PROGBUF_WID) - _ULL(1)) << VT2_DBMD_PROGBUF2_PROGBUF_POS)

#define VT2_DBMD_PROGBUF3_OFFSET _ULL(0x423)

#define VT2_DBMD_PROGBUF3_POS 0
#define VT2_DBMD_PROGBUF3_WID 32
#define VT2_DBMD_PROGBUF3_MSK (((_ULL(1) << VT2_DBMD_PROGBUF3_WID) - _ULL(1)) << VT2_DBMD_PROGBUF3_POS)

#define VT2_DBMD_PROGBUF3_PROGBUF_POS 0
#define VT2_DBMD_PROGBUF3_PROGBUF_WID 32
#define VT2_DBMD_PROGBUF3_PROGBUF_MSK (((_ULL(1) << VT2_DBMD_PROGBUF3_PROGBUF_WID) - _ULL(1)) << VT2_DBMD_PROGBUF3_PROGBUF_POS)

#define VT2_DBMD_DMCS2_OFFSET _ULL(0x432)

#define VT2_DBMD_DMCS2_POS 0
#define VT2_DBMD_DMCS2_WID 12
#define VT2_DBMD_DMCS2_MSK (((_ULL(1) << VT2_DBMD_DMCS2_WID) - _ULL(1)) << VT2_DBMD_DMCS2_POS)

#define VT2_DBMD_DMCS2_HGSELECT_POS 0
#define VT2_DBMD_DMCS2_HGSELECT_WID 1
#define VT2_DBMD_DMCS2_HGSELECT_MSK (((_ULL(1) << VT2_DBMD_DMCS2_HGSELECT_WID) - _ULL(1)) << VT2_DBMD_DMCS2_HGSELECT_POS)
#define VT2_DBMD_DMCS2_HGWRITE_POS 1
#define VT2_DBMD_DMCS2_HGWRITE_WID 1
#define VT2_DBMD_DMCS2_HGWRITE_MSK (((_ULL(1) << VT2_DBMD_DMCS2_HGWRITE_WID) - _ULL(1)) << VT2_DBMD_DMCS2_HGWRITE_POS)
#define VT2_DBMD_DMCS2_GROUP_POS 2
#define VT2_DBMD_DMCS2_GROUP_WID 5
#define VT2_DBMD_DMCS2_GROUP_MSK (((_ULL(1) << VT2_DBMD_DMCS2_GROUP_WID) - _ULL(1)) << VT2_DBMD_DMCS2_GROUP_POS)
#define VT2_DBMD_DMCS2_DMEXTTRIGGER_POS 7
#define VT2_DBMD_DMCS2_DMEXTTRIGGER_WID 4
#define VT2_DBMD_DMCS2_DMEXTTRIGGER_MSK (((_ULL(1) << VT2_DBMD_DMCS2_DMEXTTRIGGER_WID) - _ULL(1)) << VT2_DBMD_DMCS2_DMEXTTRIGGER_POS)
#define VT2_DBMD_DMCS2_GROUPTYPE_POS 11
#define VT2_DBMD_DMCS2_GROUPTYPE_WID 1
#define VT2_DBMD_DMCS2_GROUPTYPE_MSK (((_ULL(1) << VT2_DBMD_DMCS2_GROUPTYPE_WID) - _ULL(1)) << VT2_DBMD_DMCS2_GROUPTYPE_POS)

#define VT2_DBMD_HALTSUM0_OFFSET _ULL(0x440)

#define VT2_DBMD_HALTSUM0_POS 0
#define VT2_DBMD_HALTSUM0_WID 32
#define VT2_DBMD_HALTSUM0_MSK (((_ULL(1) << VT2_DBMD_HALTSUM0_WID) - _ULL(1)) << VT2_DBMD_HALTSUM0_POS)

#define VT2_DBMD_HALTSUM0_HALTSUM_POS 0
#define VT2_DBMD_HALTSUM0_HALTSUM_WID 32
#define VT2_DBMD_HALTSUM0_HALTSUM_MSK (((_ULL(1) << VT2_DBMD_HALTSUM0_HALTSUM_WID) - _ULL(1)) << VT2_DBMD_HALTSUM0_HALTSUM_POS)

#define VT2_DBMD_EXTERNALEXCLUSIVEACCESS_OFFSET _ULL(0x470)

#define VT2_DBMD_EXTERNALEXCLUSIVEACCESS_POS 0
#define VT2_DBMD_EXTERNALEXCLUSIVEACCESS_WID 5
#define VT2_DBMD_EXTERNALEXCLUSIVEACCESS_MSK (((_ULL(1) << VT2_DBMD_EXTERNALEXCLUSIVEACCESS_WID) - _ULL(1)) << VT2_DBMD_EXTERNALEXCLUSIVEACCESS_POS)

#define VT2_DBMD_EXTERNALEXCLUSIVEACCESS_DISABLEINTERNALDREG_POS 0
#define VT2_DBMD_EXTERNALEXCLUSIVEACCESS_DISABLEINTERNALDREG_WID 1
#define VT2_DBMD_EXTERNALEXCLUSIVEACCESS_DISABLEINTERNALDREG_MSK (((_ULL(1) << VT2_DBMD_EXTERNALEXCLUSIVEACCESS_DISABLEINTERNALDREG_WID) - _ULL(1)) << VT2_DBMD_EXTERNALEXCLUSIVEACCESS_DISABLEINTERNALDREG_POS)
#define VT2_DBMD_EXTERNALEXCLUSIVEACCESS_DISABLEINTERNALDREGWRITEENABLE_POS 1
#define VT2_DBMD_EXTERNALEXCLUSIVEACCESS_DISABLEINTERNALDREGWRITEENABLE_WID 1
#define VT2_DBMD_EXTERNALEXCLUSIVEACCESS_DISABLEINTERNALDREGWRITEENABLE_MSK (((_ULL(1) << VT2_DBMD_EXTERNALEXCLUSIVEACCESS_DISABLEINTERNALDREGWRITEENABLE_WID) - _ULL(1)) << VT2_DBMD_EXTERNALEXCLUSIVEACCESS_DISABLEINTERNALDREGWRITEENABLE_POS)
#define VT2_DBMD_EXTERNALEXCLUSIVEACCESS_DMACTIVEOVERRIDE_POS 2
#define VT2_DBMD_EXTERNALEXCLUSIVEACCESS_DMACTIVEOVERRIDE_WID 2
#define VT2_DBMD_EXTERNALEXCLUSIVEACCESS_DMACTIVEOVERRIDE_MSK (((_ULL(1) << VT2_DBMD_EXTERNALEXCLUSIVEACCESS_DMACTIVEOVERRIDE_WID) - _ULL(1)) << VT2_DBMD_EXTERNALEXCLUSIVEACCESS_DMACTIVEOVERRIDE_POS)
#define VT2_DBMD_EXTERNALEXCLUSIVEACCESS_DMACTIVEOVERRIDEWRITEENABLE_POS 4
#define VT2_DBMD_EXTERNALEXCLUSIVEACCESS_DMACTIVEOVERRIDEWRITEENABLE_WID 1
#define VT2_DBMD_EXTERNALEXCLUSIVEACCESS_DMACTIVEOVERRIDEWRITEENABLE_MSK (((_ULL(1) << VT2_DBMD_EXTERNALEXCLUSIVEACCESS_DMACTIVEOVERRIDEWRITEENABLE_WID) - _ULL(1)) << VT2_DBMD_EXTERNALEXCLUSIVEACCESS_DMACTIVEOVERRIDEWRITEENABLE_POS)

#define VT2_DBMD_DMACTIVECONTROLSTATUS_OFFSET _ULL(0x800)

#define VT2_DBMD_DMACTIVECONTROLSTATUS_POS 0
#define VT2_DBMD_DMACTIVECONTROLSTATUS_WID 2
#define VT2_DBMD_DMACTIVECONTROLSTATUS_MSK (((_ULL(1) << VT2_DBMD_DMACTIVECONTROLSTATUS_WID) - _ULL(1)) << VT2_DBMD_DMACTIVECONTROLSTATUS_POS)

#define VT2_DBMD_DMACTIVECONTROLSTATUS_DMACTIVECURRENTSTATE_POS 0
#define VT2_DBMD_DMACTIVECONTROLSTATUS_DMACTIVECURRENTSTATE_WID 1
#define VT2_DBMD_DMACTIVECONTROLSTATUS_DMACTIVECURRENTSTATE_MSK (((_ULL(1) << VT2_DBMD_DMACTIVECONTROLSTATUS_DMACTIVECURRENTSTATE_WID) - _ULL(1)) << VT2_DBMD_DMACTIVECONTROLSTATUS_DMACTIVECURRENTSTATE_POS)
#define VT2_DBMD_DMACTIVECONTROLSTATUS_DMACTIVEREQUESTEDSTATE_POS 1
#define VT2_DBMD_DMACTIVECONTROLSTATUS_DMACTIVEREQUESTEDSTATE_WID 1
#define VT2_DBMD_DMACTIVECONTROLSTATUS_DMACTIVEREQUESTEDSTATE_MSK (((_ULL(1) << VT2_DBMD_DMACTIVECONTROLSTATUS_DMACTIVEREQUESTEDSTATE_WID) - _ULL(1)) << VT2_DBMD_DMACTIVECONTROLSTATUS_DMACTIVEREQUESTEDSTATE_POS)

#define VT2_DBMD_DMRESETCONTROLSTATUS_OFFSET _ULL(0x801)

#define VT2_DBMD_DMRESETCONTROLSTATUS_POS 0
#define VT2_DBMD_DMRESETCONTROLSTATUS_WID 32
#define VT2_DBMD_DMRESETCONTROLSTATUS_MSK (((_ULL(1) << VT2_DBMD_DMRESETCONTROLSTATUS_WID) - _ULL(1)) << VT2_DBMD_DMRESETCONTROLSTATUS_POS)

#define VT2_DBMD_DMRESETCONTROLSTATUS_NDMRESETREQ_POS 0
#define VT2_DBMD_DMRESETCONTROLSTATUS_NDMRESETREQ_WID 1
#define VT2_DBMD_DMRESETCONTROLSTATUS_NDMRESETREQ_MSK (((_ULL(1) << VT2_DBMD_DMRESETCONTROLSTATUS_NDMRESETREQ_WID) - _ULL(1)) << VT2_DBMD_DMRESETCONTROLSTATUS_NDMRESETREQ_POS)
#define VT2_DBMD_DMRESETCONTROLSTATUS_HARTRESETREQ_POS 31
#define VT2_DBMD_DMRESETCONTROLSTATUS_HARTRESETREQ_WID 1
#define VT2_DBMD_DMRESETCONTROLSTATUS_HARTRESETREQ_MSK (((_ULL(1) << VT2_DBMD_DMRESETCONTROLSTATUS_HARTRESETREQ_WID) - _ULL(1)) << VT2_DBMD_DMRESETCONTROLSTATUS_HARTRESETREQ_POS)

#define VT2_DBMD_PUCINTERRUPTENABLE_OFFSET _ULL(0x802)

#define VT2_DBMD_PUCINTERRUPTENABLE_POS 0
#define VT2_DBMD_PUCINTERRUPTENABLE_WID 3
#define VT2_DBMD_PUCINTERRUPTENABLE_MSK (((_ULL(1) << VT2_DBMD_PUCINTERRUPTENABLE_WID) - _ULL(1)) << VT2_DBMD_PUCINTERRUPTENABLE_POS)

#define VT2_DBMD_PUCINTERRUPTENABLE_HARTRESETENABLE_POS 0
#define VT2_DBMD_PUCINTERRUPTENABLE_HARTRESETENABLE_WID 1
#define VT2_DBMD_PUCINTERRUPTENABLE_HARTRESETENABLE_MSK (((_ULL(1) << VT2_DBMD_PUCINTERRUPTENABLE_HARTRESETENABLE_WID) - _ULL(1)) << VT2_DBMD_PUCINTERRUPTENABLE_HARTRESETENABLE_POS)
#define VT2_DBMD_PUCINTERRUPTENABLE_NDMRESETENABLE_POS 1
#define VT2_DBMD_PUCINTERRUPTENABLE_NDMRESETENABLE_WID 1
#define VT2_DBMD_PUCINTERRUPTENABLE_NDMRESETENABLE_MSK (((_ULL(1) << VT2_DBMD_PUCINTERRUPTENABLE_NDMRESETENABLE_WID) - _ULL(1)) << VT2_DBMD_PUCINTERRUPTENABLE_NDMRESETENABLE_POS)
#define VT2_DBMD_PUCINTERRUPTENABLE_DMACTIVEENABLE_POS 2
#define VT2_DBMD_PUCINTERRUPTENABLE_DMACTIVEENABLE_WID 1
#define VT2_DBMD_PUCINTERRUPTENABLE_DMACTIVEENABLE_MSK (((_ULL(1) << VT2_DBMD_PUCINTERRUPTENABLE_DMACTIVEENABLE_WID) - _ULL(1)) << VT2_DBMD_PUCINTERRUPTENABLE_DMACTIVEENABLE_POS)

#define VT2_DBMD_HARTSELECT_OFFSET _ULL(0x804)

#define VT2_DBMD_HARTSELECT_POS 0
#define VT2_DBMD_HARTSELECT_WID 5
#define VT2_DBMD_HARTSELECT_MSK (((_ULL(1) << VT2_DBMD_HARTSELECT_WID) - _ULL(1)) << VT2_DBMD_HARTSELECT_POS)

#define VT2_DBMD_HARTSELECT_HARTSELECT_POS 0
#define VT2_DBMD_HARTSELECT_HARTSELECT_WID 5
#define VT2_DBMD_HARTSELECT_HARTSELECT_MSK (((_ULL(1) << VT2_DBMD_HARTSELECT_HARTSELECT_WID) - _ULL(1)) << VT2_DBMD_HARTSELECT_HARTSELECT_POS)

#define VT2_DBMD_HARTAVAILABLESTATUS_OFFSET _ULL(0x805)

#define VT2_DBMD_HARTAVAILABLESTATUS_POS 0
#define VT2_DBMD_HARTAVAILABLESTATUS_WID 1
#define VT2_DBMD_HARTAVAILABLESTATUS_MSK (((_ULL(1) << VT2_DBMD_HARTAVAILABLESTATUS_WID) - _ULL(1)) << VT2_DBMD_HARTAVAILABLESTATUS_POS)

#define VT2_DBMD_HARTAVAILABLESTATUS_HARTAVAILABLE_POS 0
#define VT2_DBMD_HARTAVAILABLESTATUS_HARTAVAILABLE_WID 1
#define VT2_DBMD_HARTAVAILABLESTATUS_HARTAVAILABLE_MSK (((_ULL(1) << VT2_DBMD_HARTAVAILABLESTATUS_HARTAVAILABLE_WID) - _ULL(1)) << VT2_DBMD_HARTAVAILABLESTATUS_HARTAVAILABLE_POS)

#define VT2_DBMD_HARTRESETSTATUS_OFFSET _ULL(0x806)

#define VT2_DBMD_HARTRESETSTATUS_POS 31
#define VT2_DBMD_HARTRESETSTATUS_WID 1
#define VT2_DBMD_HARTRESETSTATUS_MSK (((_ULL(1) << VT2_DBMD_HARTRESETSTATUS_WID) - _ULL(1)) << VT2_DBMD_HARTRESETSTATUS_POS)

#define VT2_DBMD_HARTRESETSTATUS_RESETPENDING_POS 31
#define VT2_DBMD_HARTRESETSTATUS_RESETPENDING_WID 1
#define VT2_DBMD_HARTRESETSTATUS_RESETPENDING_MSK (((_ULL(1) << VT2_DBMD_HARTRESETSTATUS_RESETPENDING_WID) - _ULL(1)) << VT2_DBMD_HARTRESETSTATUS_RESETPENDING_POS)

#define VT2_DBMD_DREGALIASCONFSTRPTR0_OFFSET _ULL(0x80c)

#define VT2_DBMD_DREGALIASCONFSTRPTR0_POS 0
#define VT2_DBMD_DREGALIASCONFSTRPTR0_WID 32
#define VT2_DBMD_DREGALIASCONFSTRPTR0_MSK (((_ULL(1) << VT2_DBMD_DREGALIASCONFSTRPTR0_WID) - _ULL(1)) << VT2_DBMD_DREGALIASCONFSTRPTR0_POS)

#define VT2_DBMD_DREGALIASCONFSTRPTR0_CONFSTRPTR_POS 0
#define VT2_DBMD_DREGALIASCONFSTRPTR0_CONFSTRPTR_WID 32
#define VT2_DBMD_DREGALIASCONFSTRPTR0_CONFSTRPTR_MSK (((_ULL(1) << VT2_DBMD_DREGALIASCONFSTRPTR0_CONFSTRPTR_WID) - _ULL(1)) << VT2_DBMD_DREGALIASCONFSTRPTR0_CONFSTRPTR_POS)

#define VT2_DBMD_DREGALIASCONFSTRPTR1_OFFSET _ULL(0x80d)

#define VT2_DBMD_DREGALIASCONFSTRPTR1_POS 0
#define VT2_DBMD_DREGALIASCONFSTRPTR1_WID 32
#define VT2_DBMD_DREGALIASCONFSTRPTR1_MSK (((_ULL(1) << VT2_DBMD_DREGALIASCONFSTRPTR1_WID) - _ULL(1)) << VT2_DBMD_DREGALIASCONFSTRPTR1_POS)

#define VT2_DBMD_DREGALIASCONFSTRPTR1_CONFSTRPTR_POS 0
#define VT2_DBMD_DREGALIASCONFSTRPTR1_CONFSTRPTR_WID 32
#define VT2_DBMD_DREGALIASCONFSTRPTR1_CONFSTRPTR_MSK (((_ULL(1) << VT2_DBMD_DREGALIASCONFSTRPTR1_CONFSTRPTR_WID) - _ULL(1)) << VT2_DBMD_DREGALIASCONFSTRPTR1_CONFSTRPTR_POS)

#define VT2_DBMD_DREGALIASCONFSTRPTRVALID_OFFSET _ULL(0x810)

#define VT2_DBMD_DREGALIASCONFSTRPTRVALID_POS 0
#define VT2_DBMD_DREGALIASCONFSTRPTRVALID_WID 1
#define VT2_DBMD_DREGALIASCONFSTRPTRVALID_MSK (((_ULL(1) << VT2_DBMD_DREGALIASCONFSTRPTRVALID_WID) - _ULL(1)) << VT2_DBMD_DREGALIASCONFSTRPTRVALID_POS)

#define VT2_DBMD_DREGALIASCONFSTRPTRVALID_CONFSTRPTRVALID_POS 0
#define VT2_DBMD_DREGALIASCONFSTRPTRVALID_CONFSTRPTRVALID_WID 1
#define VT2_DBMD_DREGALIASCONFSTRPTRVALID_CONFSTRPTRVALID_MSK (((_ULL(1) << VT2_DBMD_DREGALIASCONFSTRPTRVALID_CONFSTRPTRVALID_WID) - _ULL(1)) << VT2_DBMD_DREGALIASCONFSTRPTRVALID_CONFSTRPTRVALID_POS)

#define VT2_DBMD_DREGALIASNEXTDM_OFFSET _ULL(0x814)

#define VT2_DBMD_DREGALIASNEXTDM_POS 0
#define VT2_DBMD_DREGALIASNEXTDM_WID 32
#define VT2_DBMD_DREGALIASNEXTDM_MSK (((_ULL(1) << VT2_DBMD_DREGALIASNEXTDM_WID) - _ULL(1)) << VT2_DBMD_DREGALIASNEXTDM_POS)

#define VT2_DBMD_DREGALIASNEXTDM_NEXTDM_POS 0
#define VT2_DBMD_DREGALIASNEXTDM_NEXTDM_WID 32
#define VT2_DBMD_DREGALIASNEXTDM_NEXTDM_MSK (((_ULL(1) << VT2_DBMD_DREGALIASNEXTDM_NEXTDM_WID) - _ULL(1)) << VT2_DBMD_DREGALIASNEXTDM_NEXTDM_POS)
#endif /* VT2_DBMD_MMR_H */
