/* This file is auto-generated. Do not hand edit this file. */

#ifndef VT2_CPU_CSR_H
#define VT2_CPU_CSR_H

#ifndef _ULL

#ifdef __ASSEMBLER__
#define _AC(X,Y) X
#else
#define __AC(X,Y) (X##Y)
#define _AC(X,Y) __AC(X,Y)
#endif

#define _ULL(x)  (_AC(x, ULL))
#endif


#define VT2_CPU_CPURSTCTL_OFFSET _ULL(0x70000)

#define VT2_CPU_CPURSTCTL_POS 0
#define VT2_CPU_CPURSTCTL_WID 8
#define VT2_CPU_CPURSTCTL_MSK (((_ULL(1) << VT2_CPU_CPURSTCTL_WID) - _ULL(1)) << VT2_CPU_CPURSTCTL_POS)

#define VT2_CPU_CPURSTCTL_HARDRESET_POS 0
#define VT2_CPU_CPURSTCTL_HARDRESET_WID 1
#define VT2_CPU_CPURSTCTL_HARDRESET_MSK (((_ULL(1) << VT2_CPU_CPURSTCTL_HARDRESET_WID) - _ULL(1)) << VT2_CPU_CPURSTCTL_HARDRESET_POS)
#define VT2_CPU_CPURSTCTL_HARDRESETDONE_POS 1
#define VT2_CPU_CPURSTCTL_HARDRESETDONE_WID 1
#define VT2_CPU_CPURSTCTL_HARDRESETDONE_MSK (((_ULL(1) << VT2_CPU_CPURSTCTL_HARDRESETDONE_WID) - _ULL(1)) << VT2_CPU_CPURSTCTL_HARDRESETDONE_POS)
#define VT2_CPU_CPURSTCTL_SOFTRESETREQUEST_POS 2
#define VT2_CPU_CPURSTCTL_SOFTRESETREQUEST_WID 1
#define VT2_CPU_CPURSTCTL_SOFTRESETREQUEST_MSK (((_ULL(1) << VT2_CPU_CPURSTCTL_SOFTRESETREQUEST_WID) - _ULL(1)) << VT2_CPU_CPURSTCTL_SOFTRESETREQUEST_POS)
#define VT2_CPU_CPURSTCTL_SOFTRESETDONE_POS 3
#define VT2_CPU_CPURSTCTL_SOFTRESETDONE_WID 1
#define VT2_CPU_CPURSTCTL_SOFTRESETDONE_MSK (((_ULL(1) << VT2_CPU_CPURSTCTL_SOFTRESETDONE_WID) - _ULL(1)) << VT2_CPU_CPURSTCTL_SOFTRESETDONE_POS)
#define VT2_CPU_CPURSTCTL_STARTRAMINIT_POS 4
#define VT2_CPU_CPURSTCTL_STARTRAMINIT_WID 1
#define VT2_CPU_CPURSTCTL_STARTRAMINIT_MSK (((_ULL(1) << VT2_CPU_CPURSTCTL_STARTRAMINIT_WID) - _ULL(1)) << VT2_CPU_CPURSTCTL_STARTRAMINIT_POS)
#define VT2_CPU_CPURSTCTL_RAMINTDONE_POS 5
#define VT2_CPU_CPURSTCTL_RAMINTDONE_WID 1
#define VT2_CPU_CPURSTCTL_RAMINTDONE_MSK (((_ULL(1) << VT2_CPU_CPURSTCTL_RAMINTDONE_WID) - _ULL(1)) << VT2_CPU_CPURSTCTL_RAMINTDONE_POS)
#define VT2_CPU_CPURSTCTL_START_POS 6
#define VT2_CPU_CPURSTCTL_START_WID 1
#define VT2_CPU_CPURSTCTL_START_MSK (((_ULL(1) << VT2_CPU_CPURSTCTL_START_WID) - _ULL(1)) << VT2_CPU_CPURSTCTL_START_POS)
#define VT2_CPU_CPURSTCTL_REGBUSENABLE_POS 7
#define VT2_CPU_CPURSTCTL_REGBUSENABLE_WID 1
#define VT2_CPU_CPURSTCTL_REGBUSENABLE_MSK (((_ULL(1) << VT2_CPU_CPURSTCTL_REGBUSENABLE_WID) - _ULL(1)) << VT2_CPU_CPURSTCTL_REGBUSENABLE_POS)

#define VT2_CPU_CPUCLKCTL_OFFSET _ULL(0x70001)

#define VT2_CPU_CPUCLKCTL_POS 0
#define VT2_CPU_CPUCLKCTL_WID 15
#define VT2_CPU_CPUCLKCTL_MSK (((_ULL(1) << VT2_CPU_CPUCLKCTL_WID) - _ULL(1)) << VT2_CPU_CPUCLKCTL_POS)

#define VT2_CPU_CPUCLKCTL_CLKGATEREN_POS 0
#define VT2_CPU_CPUCLKCTL_CLKGATEREN_WID 1
#define VT2_CPU_CPUCLKCTL_CLKGATEREN_MSK (((_ULL(1) << VT2_CPU_CPUCLKCTL_CLKGATEREN_WID) - _ULL(1)) << VT2_CPU_CPUCLKCTL_CLKGATEREN_POS)
#define VT2_CPU_CPUCLKCTL_CLKGATEROVRD_POS 1
#define VT2_CPU_CPUCLKCTL_CLKGATEROVRD_WID 1
#define VT2_CPU_CPUCLKCTL_CLKGATEROVRD_MSK (((_ULL(1) << VT2_CPU_CPUCLKCTL_CLKGATEROVRD_WID) - _ULL(1)) << VT2_CPU_CPUCLKCTL_CLKGATEROVRD_POS)
#define VT2_CPU_CPUCLKCTL_CLKFREQDIV_POS 2
#define VT2_CPU_CPUCLKCTL_CLKFREQDIV_WID 5
#define VT2_CPU_CPUCLKCTL_CLKFREQDIV_MSK (((_ULL(1) << VT2_CPU_CPUCLKCTL_CLKFREQDIV_WID) - _ULL(1)) << VT2_CPU_CPUCLKCTL_CLKFREQDIV_POS)
#define VT2_CPU_CPUCLKCTL_CLKFREQRAMPUPSTEPDLY_POS 7
#define VT2_CPU_CPUCLKCTL_CLKFREQRAMPUPSTEPDLY_WID 4
#define VT2_CPU_CPUCLKCTL_CLKFREQRAMPUPSTEPDLY_MSK (((_ULL(1) << VT2_CPU_CPUCLKCTL_CLKFREQRAMPUPSTEPDLY_WID) - _ULL(1)) << VT2_CPU_CPUCLKCTL_CLKFREQRAMPUPSTEPDLY_POS)
#define VT2_CPU_CPUCLKCTL_CLKFREQRAMPDNSTEPDLY_POS 11
#define VT2_CPU_CPUCLKCTL_CLKFREQRAMPDNSTEPDLY_WID 4
#define VT2_CPU_CPUCLKCTL_CLKFREQRAMPDNSTEPDLY_MSK (((_ULL(1) << VT2_CPU_CPUCLKCTL_CLKFREQRAMPDNSTEPDLY_WID) - _ULL(1)) << VT2_CPU_CPUCLKCTL_CLKFREQRAMPDNSTEPDLY_POS)

#define VT2_CPU_CPUCLKSTAT_OFFSET _ULL(0x70002)

#define VT2_CPU_CPUCLKSTAT_POS 0
#define VT2_CPU_CPUCLKSTAT_WID 5
#define VT2_CPU_CPUCLKSTAT_MSK (((_ULL(1) << VT2_CPU_CPUCLKSTAT_WID) - _ULL(1)) << VT2_CPU_CPUCLKSTAT_POS)

#define VT2_CPU_CPUCLKSTAT_CPUQUIESCED_POS 0
#define VT2_CPU_CPUCLKSTAT_CPUQUIESCED_WID 1
#define VT2_CPU_CPUCLKSTAT_CPUQUIESCED_MSK (((_ULL(1) << VT2_CPU_CPUCLKSTAT_CPUQUIESCED_WID) - _ULL(1)) << VT2_CPU_CPUCLKSTAT_CPUQUIESCED_POS)
#define VT2_CPU_CPUCLKSTAT_ICRQUIESCED_POS 1
#define VT2_CPU_CPUCLKSTAT_ICRQUIESCED_WID 1
#define VT2_CPU_CPUCLKSTAT_ICRQUIESCED_MSK (((_ULL(1) << VT2_CPU_CPUCLKSTAT_ICRQUIESCED_WID) - _ULL(1)) << VT2_CPU_CPUCLKSTAT_ICRQUIESCED_POS)
#define VT2_CPU_CPUCLKSTAT_WAKEEVENT_POS 2
#define VT2_CPU_CPUCLKSTAT_WAKEEVENT_WID 1
#define VT2_CPU_CPUCLKSTAT_WAKEEVENT_MSK (((_ULL(1) << VT2_CPU_CPUCLKSTAT_WAKEEVENT_WID) - _ULL(1)) << VT2_CPU_CPUCLKSTAT_WAKEEVENT_POS)
#define VT2_CPU_CPUCLKSTAT_RUNEVENT_POS 3
#define VT2_CPU_CPUCLKSTAT_RUNEVENT_WID 1
#define VT2_CPU_CPUCLKSTAT_RUNEVENT_MSK (((_ULL(1) << VT2_CPU_CPUCLKSTAT_RUNEVENT_WID) - _ULL(1)) << VT2_CPU_CPUCLKSTAT_RUNEVENT_POS)
#define VT2_CPU_CPUCLKSTAT_CPUCLKSTATECGE_POS 4
#define VT2_CPU_CPUCLKSTAT_CPUCLKSTATECGE_WID 1
#define VT2_CPU_CPUCLKSTAT_CPUCLKSTATECGE_MSK (((_ULL(1) << VT2_CPU_CPUCLKSTAT_CPUCLKSTATECGE_WID) - _ULL(1)) << VT2_CPU_CPUCLKSTAT_CPUCLKSTATECGE_POS)

#define VT2_CPU_CPUPWRCFG_OFFSET _ULL(0x70003)

#define VT2_CPU_CPUPWRCFG_POS 0
#define VT2_CPU_CPUPWRCFG_WID 1
#define VT2_CPU_CPUPWRCFG_MSK (((_ULL(1) << VT2_CPU_CPUPWRCFG_WID) - _ULL(1)) << VT2_CPU_CPUPWRCFG_POS)

#define VT2_CPU_CPUPWRCFG_LSDIS_POS 0
#define VT2_CPU_CPUPWRCFG_LSDIS_WID 1
#define VT2_CPU_CPUPWRCFG_LSDIS_MSK (((_ULL(1) << VT2_CPU_CPUPWRCFG_LSDIS_WID) - _ULL(1)) << VT2_CPU_CPUPWRCFG_LSDIS_POS)

#define VT2_CPU_CPURSTCTL_OFFSET _ULL(0x70400)

#define VT2_CPU_CPURSTCTL_POS 0
#define VT2_CPU_CPURSTCTL_WID 8
#define VT2_CPU_CPURSTCTL_MSK (((_ULL(1) << VT2_CPU_CPURSTCTL_WID) - _ULL(1)) << VT2_CPU_CPURSTCTL_POS)

#define VT2_CPU_CPURSTCTL_HARDRESET_POS 0
#define VT2_CPU_CPURSTCTL_HARDRESET_WID 1
#define VT2_CPU_CPURSTCTL_HARDRESET_MSK (((_ULL(1) << VT2_CPU_CPURSTCTL_HARDRESET_WID) - _ULL(1)) << VT2_CPU_CPURSTCTL_HARDRESET_POS)
#define VT2_CPU_CPURSTCTL_HARDRESETDONE_POS 1
#define VT2_CPU_CPURSTCTL_HARDRESETDONE_WID 1
#define VT2_CPU_CPURSTCTL_HARDRESETDONE_MSK (((_ULL(1) << VT2_CPU_CPURSTCTL_HARDRESETDONE_WID) - _ULL(1)) << VT2_CPU_CPURSTCTL_HARDRESETDONE_POS)
#define VT2_CPU_CPURSTCTL_SOFTRESETREQUEST_POS 2
#define VT2_CPU_CPURSTCTL_SOFTRESETREQUEST_WID 1
#define VT2_CPU_CPURSTCTL_SOFTRESETREQUEST_MSK (((_ULL(1) << VT2_CPU_CPURSTCTL_SOFTRESETREQUEST_WID) - _ULL(1)) << VT2_CPU_CPURSTCTL_SOFTRESETREQUEST_POS)
#define VT2_CPU_CPURSTCTL_SOFTRESETDONE_POS 3
#define VT2_CPU_CPURSTCTL_SOFTRESETDONE_WID 1
#define VT2_CPU_CPURSTCTL_SOFTRESETDONE_MSK (((_ULL(1) << VT2_CPU_CPURSTCTL_SOFTRESETDONE_WID) - _ULL(1)) << VT2_CPU_CPURSTCTL_SOFTRESETDONE_POS)
#define VT2_CPU_CPURSTCTL_STARTRAMINIT_POS 4
#define VT2_CPU_CPURSTCTL_STARTRAMINIT_WID 1
#define VT2_CPU_CPURSTCTL_STARTRAMINIT_MSK (((_ULL(1) << VT2_CPU_CPURSTCTL_STARTRAMINIT_WID) - _ULL(1)) << VT2_CPU_CPURSTCTL_STARTRAMINIT_POS)
#define VT2_CPU_CPURSTCTL_RAMINTDONE_POS 5
#define VT2_CPU_CPURSTCTL_RAMINTDONE_WID 1
#define VT2_CPU_CPURSTCTL_RAMINTDONE_MSK (((_ULL(1) << VT2_CPU_CPURSTCTL_RAMINTDONE_WID) - _ULL(1)) << VT2_CPU_CPURSTCTL_RAMINTDONE_POS)
#define VT2_CPU_CPURSTCTL_START_POS 6
#define VT2_CPU_CPURSTCTL_START_WID 1
#define VT2_CPU_CPURSTCTL_START_MSK (((_ULL(1) << VT2_CPU_CPURSTCTL_START_WID) - _ULL(1)) << VT2_CPU_CPURSTCTL_START_POS)
#define VT2_CPU_CPURSTCTL_REGBUSENABLE_POS 7
#define VT2_CPU_CPURSTCTL_REGBUSENABLE_WID 1
#define VT2_CPU_CPURSTCTL_REGBUSENABLE_MSK (((_ULL(1) << VT2_CPU_CPURSTCTL_REGBUSENABLE_WID) - _ULL(1)) << VT2_CPU_CPURSTCTL_REGBUSENABLE_POS)

#define VT2_CPU_CPUCLKCTL_OFFSET _ULL(0x70401)

#define VT2_CPU_CPUCLKCTL_POS 0
#define VT2_CPU_CPUCLKCTL_WID 15
#define VT2_CPU_CPUCLKCTL_MSK (((_ULL(1) << VT2_CPU_CPUCLKCTL_WID) - _ULL(1)) << VT2_CPU_CPUCLKCTL_POS)

#define VT2_CPU_CPUCLKCTL_CLKGATEREN_POS 0
#define VT2_CPU_CPUCLKCTL_CLKGATEREN_WID 1
#define VT2_CPU_CPUCLKCTL_CLKGATEREN_MSK (((_ULL(1) << VT2_CPU_CPUCLKCTL_CLKGATEREN_WID) - _ULL(1)) << VT2_CPU_CPUCLKCTL_CLKGATEREN_POS)
#define VT2_CPU_CPUCLKCTL_CLKGATEROVRD_POS 1
#define VT2_CPU_CPUCLKCTL_CLKGATEROVRD_WID 1
#define VT2_CPU_CPUCLKCTL_CLKGATEROVRD_MSK (((_ULL(1) << VT2_CPU_CPUCLKCTL_CLKGATEROVRD_WID) - _ULL(1)) << VT2_CPU_CPUCLKCTL_CLKGATEROVRD_POS)
#define VT2_CPU_CPUCLKCTL_CLKFREQDIV_POS 2
#define VT2_CPU_CPUCLKCTL_CLKFREQDIV_WID 5
#define VT2_CPU_CPUCLKCTL_CLKFREQDIV_MSK (((_ULL(1) << VT2_CPU_CPUCLKCTL_CLKFREQDIV_WID) - _ULL(1)) << VT2_CPU_CPUCLKCTL_CLKFREQDIV_POS)
#define VT2_CPU_CPUCLKCTL_CLKFREQRAMPUPSTEPDLY_POS 7
#define VT2_CPU_CPUCLKCTL_CLKFREQRAMPUPSTEPDLY_WID 4
#define VT2_CPU_CPUCLKCTL_CLKFREQRAMPUPSTEPDLY_MSK (((_ULL(1) << VT2_CPU_CPUCLKCTL_CLKFREQRAMPUPSTEPDLY_WID) - _ULL(1)) << VT2_CPU_CPUCLKCTL_CLKFREQRAMPUPSTEPDLY_POS)
#define VT2_CPU_CPUCLKCTL_CLKFREQRAMPDNSTEPDLY_POS 11
#define VT2_CPU_CPUCLKCTL_CLKFREQRAMPDNSTEPDLY_WID 4
#define VT2_CPU_CPUCLKCTL_CLKFREQRAMPDNSTEPDLY_MSK (((_ULL(1) << VT2_CPU_CPUCLKCTL_CLKFREQRAMPDNSTEPDLY_WID) - _ULL(1)) << VT2_CPU_CPUCLKCTL_CLKFREQRAMPDNSTEPDLY_POS)

#define VT2_CPU_CPUCLKSTAT_OFFSET _ULL(0x70402)

#define VT2_CPU_CPUCLKSTAT_POS 0
#define VT2_CPU_CPUCLKSTAT_WID 5
#define VT2_CPU_CPUCLKSTAT_MSK (((_ULL(1) << VT2_CPU_CPUCLKSTAT_WID) - _ULL(1)) << VT2_CPU_CPUCLKSTAT_POS)

#define VT2_CPU_CPUCLKSTAT_CPUQUIESCED_POS 0
#define VT2_CPU_CPUCLKSTAT_CPUQUIESCED_WID 1
#define VT2_CPU_CPUCLKSTAT_CPUQUIESCED_MSK (((_ULL(1) << VT2_CPU_CPUCLKSTAT_CPUQUIESCED_WID) - _ULL(1)) << VT2_CPU_CPUCLKSTAT_CPUQUIESCED_POS)
#define VT2_CPU_CPUCLKSTAT_ICRQUIESCED_POS 1
#define VT2_CPU_CPUCLKSTAT_ICRQUIESCED_WID 1
#define VT2_CPU_CPUCLKSTAT_ICRQUIESCED_MSK (((_ULL(1) << VT2_CPU_CPUCLKSTAT_ICRQUIESCED_WID) - _ULL(1)) << VT2_CPU_CPUCLKSTAT_ICRQUIESCED_POS)
#define VT2_CPU_CPUCLKSTAT_WAKEEVENT_POS 2
#define VT2_CPU_CPUCLKSTAT_WAKEEVENT_WID 1
#define VT2_CPU_CPUCLKSTAT_WAKEEVENT_MSK (((_ULL(1) << VT2_CPU_CPUCLKSTAT_WAKEEVENT_WID) - _ULL(1)) << VT2_CPU_CPUCLKSTAT_WAKEEVENT_POS)
#define VT2_CPU_CPUCLKSTAT_RUNEVENT_POS 3
#define VT2_CPU_CPUCLKSTAT_RUNEVENT_WID 1
#define VT2_CPU_CPUCLKSTAT_RUNEVENT_MSK (((_ULL(1) << VT2_CPU_CPUCLKSTAT_RUNEVENT_WID) - _ULL(1)) << VT2_CPU_CPUCLKSTAT_RUNEVENT_POS)
#define VT2_CPU_CPUCLKSTAT_CPUCLKSTATECGE_POS 4
#define VT2_CPU_CPUCLKSTAT_CPUCLKSTATECGE_WID 1
#define VT2_CPU_CPUCLKSTAT_CPUCLKSTATECGE_MSK (((_ULL(1) << VT2_CPU_CPUCLKSTAT_CPUCLKSTATECGE_WID) - _ULL(1)) << VT2_CPU_CPUCLKSTAT_CPUCLKSTATECGE_POS)

#define VT2_CPU_CPUPWRCFG_OFFSET _ULL(0x70403)

#define VT2_CPU_CPUPWRCFG_POS 0
#define VT2_CPU_CPUPWRCFG_WID 1
#define VT2_CPU_CPUPWRCFG_MSK (((_ULL(1) << VT2_CPU_CPUPWRCFG_WID) - _ULL(1)) << VT2_CPU_CPUPWRCFG_POS)

#define VT2_CPU_CPUPWRCFG_LSDIS_POS 0
#define VT2_CPU_CPUPWRCFG_LSDIS_WID 1
#define VT2_CPU_CPUPWRCFG_LSDIS_MSK (((_ULL(1) << VT2_CPU_CPUPWRCFG_LSDIS_WID) - _ULL(1)) << VT2_CPU_CPUPWRCFG_LSDIS_POS)

#define VT2_CPU_CPURSTCTL_OFFSET _ULL(0x70800)

#define VT2_CPU_CPURSTCTL_POS 0
#define VT2_CPU_CPURSTCTL_WID 8
#define VT2_CPU_CPURSTCTL_MSK (((_ULL(1) << VT2_CPU_CPURSTCTL_WID) - _ULL(1)) << VT2_CPU_CPURSTCTL_POS)

#define VT2_CPU_CPURSTCTL_HARDRESET_POS 0
#define VT2_CPU_CPURSTCTL_HARDRESET_WID 1
#define VT2_CPU_CPURSTCTL_HARDRESET_MSK (((_ULL(1) << VT2_CPU_CPURSTCTL_HARDRESET_WID) - _ULL(1)) << VT2_CPU_CPURSTCTL_HARDRESET_POS)
#define VT2_CPU_CPURSTCTL_HARDRESETDONE_POS 1
#define VT2_CPU_CPURSTCTL_HARDRESETDONE_WID 1
#define VT2_CPU_CPURSTCTL_HARDRESETDONE_MSK (((_ULL(1) << VT2_CPU_CPURSTCTL_HARDRESETDONE_WID) - _ULL(1)) << VT2_CPU_CPURSTCTL_HARDRESETDONE_POS)
#define VT2_CPU_CPURSTCTL_SOFTRESETREQUEST_POS 2
#define VT2_CPU_CPURSTCTL_SOFTRESETREQUEST_WID 1
#define VT2_CPU_CPURSTCTL_SOFTRESETREQUEST_MSK (((_ULL(1) << VT2_CPU_CPURSTCTL_SOFTRESETREQUEST_WID) - _ULL(1)) << VT2_CPU_CPURSTCTL_SOFTRESETREQUEST_POS)
#define VT2_CPU_CPURSTCTL_SOFTRESETDONE_POS 3
#define VT2_CPU_CPURSTCTL_SOFTRESETDONE_WID 1
#define VT2_CPU_CPURSTCTL_SOFTRESETDONE_MSK (((_ULL(1) << VT2_CPU_CPURSTCTL_SOFTRESETDONE_WID) - _ULL(1)) << VT2_CPU_CPURSTCTL_SOFTRESETDONE_POS)
#define VT2_CPU_CPURSTCTL_STARTRAMINIT_POS 4
#define VT2_CPU_CPURSTCTL_STARTRAMINIT_WID 1
#define VT2_CPU_CPURSTCTL_STARTRAMINIT_MSK (((_ULL(1) << VT2_CPU_CPURSTCTL_STARTRAMINIT_WID) - _ULL(1)) << VT2_CPU_CPURSTCTL_STARTRAMINIT_POS)
#define VT2_CPU_CPURSTCTL_RAMINTDONE_POS 5
#define VT2_CPU_CPURSTCTL_RAMINTDONE_WID 1
#define VT2_CPU_CPURSTCTL_RAMINTDONE_MSK (((_ULL(1) << VT2_CPU_CPURSTCTL_RAMINTDONE_WID) - _ULL(1)) << VT2_CPU_CPURSTCTL_RAMINTDONE_POS)
#define VT2_CPU_CPURSTCTL_START_POS 6
#define VT2_CPU_CPURSTCTL_START_WID 1
#define VT2_CPU_CPURSTCTL_START_MSK (((_ULL(1) << VT2_CPU_CPURSTCTL_START_WID) - _ULL(1)) << VT2_CPU_CPURSTCTL_START_POS)
#define VT2_CPU_CPURSTCTL_REGBUSENABLE_POS 7
#define VT2_CPU_CPURSTCTL_REGBUSENABLE_WID 1
#define VT2_CPU_CPURSTCTL_REGBUSENABLE_MSK (((_ULL(1) << VT2_CPU_CPURSTCTL_REGBUSENABLE_WID) - _ULL(1)) << VT2_CPU_CPURSTCTL_REGBUSENABLE_POS)

#define VT2_CPU_CPUCLKCTL_OFFSET _ULL(0x70801)

#define VT2_CPU_CPUCLKCTL_POS 0
#define VT2_CPU_CPUCLKCTL_WID 15
#define VT2_CPU_CPUCLKCTL_MSK (((_ULL(1) << VT2_CPU_CPUCLKCTL_WID) - _ULL(1)) << VT2_CPU_CPUCLKCTL_POS)

#define VT2_CPU_CPUCLKCTL_CLKGATEREN_POS 0
#define VT2_CPU_CPUCLKCTL_CLKGATEREN_WID 1
#define VT2_CPU_CPUCLKCTL_CLKGATEREN_MSK (((_ULL(1) << VT2_CPU_CPUCLKCTL_CLKGATEREN_WID) - _ULL(1)) << VT2_CPU_CPUCLKCTL_CLKGATEREN_POS)
#define VT2_CPU_CPUCLKCTL_CLKGATEROVRD_POS 1
#define VT2_CPU_CPUCLKCTL_CLKGATEROVRD_WID 1
#define VT2_CPU_CPUCLKCTL_CLKGATEROVRD_MSK (((_ULL(1) << VT2_CPU_CPUCLKCTL_CLKGATEROVRD_WID) - _ULL(1)) << VT2_CPU_CPUCLKCTL_CLKGATEROVRD_POS)
#define VT2_CPU_CPUCLKCTL_CLKFREQDIV_POS 2
#define VT2_CPU_CPUCLKCTL_CLKFREQDIV_WID 5
#define VT2_CPU_CPUCLKCTL_CLKFREQDIV_MSK (((_ULL(1) << VT2_CPU_CPUCLKCTL_CLKFREQDIV_WID) - _ULL(1)) << VT2_CPU_CPUCLKCTL_CLKFREQDIV_POS)
#define VT2_CPU_CPUCLKCTL_CLKFREQRAMPUPSTEPDLY_POS 7
#define VT2_CPU_CPUCLKCTL_CLKFREQRAMPUPSTEPDLY_WID 4
#define VT2_CPU_CPUCLKCTL_CLKFREQRAMPUPSTEPDLY_MSK (((_ULL(1) << VT2_CPU_CPUCLKCTL_CLKFREQRAMPUPSTEPDLY_WID) - _ULL(1)) << VT2_CPU_CPUCLKCTL_CLKFREQRAMPUPSTEPDLY_POS)
#define VT2_CPU_CPUCLKCTL_CLKFREQRAMPDNSTEPDLY_POS 11
#define VT2_CPU_CPUCLKCTL_CLKFREQRAMPDNSTEPDLY_WID 4
#define VT2_CPU_CPUCLKCTL_CLKFREQRAMPDNSTEPDLY_MSK (((_ULL(1) << VT2_CPU_CPUCLKCTL_CLKFREQRAMPDNSTEPDLY_WID) - _ULL(1)) << VT2_CPU_CPUCLKCTL_CLKFREQRAMPDNSTEPDLY_POS)

#define VT2_CPU_CPUCLKSTAT_OFFSET _ULL(0x70802)

#define VT2_CPU_CPUCLKSTAT_POS 0
#define VT2_CPU_CPUCLKSTAT_WID 5
#define VT2_CPU_CPUCLKSTAT_MSK (((_ULL(1) << VT2_CPU_CPUCLKSTAT_WID) - _ULL(1)) << VT2_CPU_CPUCLKSTAT_POS)

#define VT2_CPU_CPUCLKSTAT_CPUQUIESCED_POS 0
#define VT2_CPU_CPUCLKSTAT_CPUQUIESCED_WID 1
#define VT2_CPU_CPUCLKSTAT_CPUQUIESCED_MSK (((_ULL(1) << VT2_CPU_CPUCLKSTAT_CPUQUIESCED_WID) - _ULL(1)) << VT2_CPU_CPUCLKSTAT_CPUQUIESCED_POS)
#define VT2_CPU_CPUCLKSTAT_ICRQUIESCED_POS 1
#define VT2_CPU_CPUCLKSTAT_ICRQUIESCED_WID 1
#define VT2_CPU_CPUCLKSTAT_ICRQUIESCED_MSK (((_ULL(1) << VT2_CPU_CPUCLKSTAT_ICRQUIESCED_WID) - _ULL(1)) << VT2_CPU_CPUCLKSTAT_ICRQUIESCED_POS)
#define VT2_CPU_CPUCLKSTAT_WAKEEVENT_POS 2
#define VT2_CPU_CPUCLKSTAT_WAKEEVENT_WID 1
#define VT2_CPU_CPUCLKSTAT_WAKEEVENT_MSK (((_ULL(1) << VT2_CPU_CPUCLKSTAT_WAKEEVENT_WID) - _ULL(1)) << VT2_CPU_CPUCLKSTAT_WAKEEVENT_POS)
#define VT2_CPU_CPUCLKSTAT_RUNEVENT_POS 3
#define VT2_CPU_CPUCLKSTAT_RUNEVENT_WID 1
#define VT2_CPU_CPUCLKSTAT_RUNEVENT_MSK (((_ULL(1) << VT2_CPU_CPUCLKSTAT_RUNEVENT_WID) - _ULL(1)) << VT2_CPU_CPUCLKSTAT_RUNEVENT_POS)
#define VT2_CPU_CPUCLKSTAT_CPUCLKSTATECGE_POS 4
#define VT2_CPU_CPUCLKSTAT_CPUCLKSTATECGE_WID 1
#define VT2_CPU_CPUCLKSTAT_CPUCLKSTATECGE_MSK (((_ULL(1) << VT2_CPU_CPUCLKSTAT_CPUCLKSTATECGE_WID) - _ULL(1)) << VT2_CPU_CPUCLKSTAT_CPUCLKSTATECGE_POS)

#define VT2_CPU_CPUPWRCFG_OFFSET _ULL(0x70803)

#define VT2_CPU_CPUPWRCFG_POS 0
#define VT2_CPU_CPUPWRCFG_WID 1
#define VT2_CPU_CPUPWRCFG_MSK (((_ULL(1) << VT2_CPU_CPUPWRCFG_WID) - _ULL(1)) << VT2_CPU_CPUPWRCFG_POS)

#define VT2_CPU_CPUPWRCFG_LSDIS_POS 0
#define VT2_CPU_CPUPWRCFG_LSDIS_WID 1
#define VT2_CPU_CPUPWRCFG_LSDIS_MSK (((_ULL(1) << VT2_CPU_CPUPWRCFG_LSDIS_WID) - _ULL(1)) << VT2_CPU_CPUPWRCFG_LSDIS_POS)

#define VT2_CPU_CPURSTCTL_OFFSET _ULL(0x70c00)

#define VT2_CPU_CPURSTCTL_POS 0
#define VT2_CPU_CPURSTCTL_WID 8
#define VT2_CPU_CPURSTCTL_MSK (((_ULL(1) << VT2_CPU_CPURSTCTL_WID) - _ULL(1)) << VT2_CPU_CPURSTCTL_POS)

#define VT2_CPU_CPURSTCTL_HARDRESET_POS 0
#define VT2_CPU_CPURSTCTL_HARDRESET_WID 1
#define VT2_CPU_CPURSTCTL_HARDRESET_MSK (((_ULL(1) << VT2_CPU_CPURSTCTL_HARDRESET_WID) - _ULL(1)) << VT2_CPU_CPURSTCTL_HARDRESET_POS)
#define VT2_CPU_CPURSTCTL_HARDRESETDONE_POS 1
#define VT2_CPU_CPURSTCTL_HARDRESETDONE_WID 1
#define VT2_CPU_CPURSTCTL_HARDRESETDONE_MSK (((_ULL(1) << VT2_CPU_CPURSTCTL_HARDRESETDONE_WID) - _ULL(1)) << VT2_CPU_CPURSTCTL_HARDRESETDONE_POS)
#define VT2_CPU_CPURSTCTL_SOFTRESETREQUEST_POS 2
#define VT2_CPU_CPURSTCTL_SOFTRESETREQUEST_WID 1
#define VT2_CPU_CPURSTCTL_SOFTRESETREQUEST_MSK (((_ULL(1) << VT2_CPU_CPURSTCTL_SOFTRESETREQUEST_WID) - _ULL(1)) << VT2_CPU_CPURSTCTL_SOFTRESETREQUEST_POS)
#define VT2_CPU_CPURSTCTL_SOFTRESETDONE_POS 3
#define VT2_CPU_CPURSTCTL_SOFTRESETDONE_WID 1
#define VT2_CPU_CPURSTCTL_SOFTRESETDONE_MSK (((_ULL(1) << VT2_CPU_CPURSTCTL_SOFTRESETDONE_WID) - _ULL(1)) << VT2_CPU_CPURSTCTL_SOFTRESETDONE_POS)
#define VT2_CPU_CPURSTCTL_STARTRAMINIT_POS 4
#define VT2_CPU_CPURSTCTL_STARTRAMINIT_WID 1
#define VT2_CPU_CPURSTCTL_STARTRAMINIT_MSK (((_ULL(1) << VT2_CPU_CPURSTCTL_STARTRAMINIT_WID) - _ULL(1)) << VT2_CPU_CPURSTCTL_STARTRAMINIT_POS)
#define VT2_CPU_CPURSTCTL_RAMINTDONE_POS 5
#define VT2_CPU_CPURSTCTL_RAMINTDONE_WID 1
#define VT2_CPU_CPURSTCTL_RAMINTDONE_MSK (((_ULL(1) << VT2_CPU_CPURSTCTL_RAMINTDONE_WID) - _ULL(1)) << VT2_CPU_CPURSTCTL_RAMINTDONE_POS)
#define VT2_CPU_CPURSTCTL_START_POS 6
#define VT2_CPU_CPURSTCTL_START_WID 1
#define VT2_CPU_CPURSTCTL_START_MSK (((_ULL(1) << VT2_CPU_CPURSTCTL_START_WID) - _ULL(1)) << VT2_CPU_CPURSTCTL_START_POS)
#define VT2_CPU_CPURSTCTL_REGBUSENABLE_POS 7
#define VT2_CPU_CPURSTCTL_REGBUSENABLE_WID 1
#define VT2_CPU_CPURSTCTL_REGBUSENABLE_MSK (((_ULL(1) << VT2_CPU_CPURSTCTL_REGBUSENABLE_WID) - _ULL(1)) << VT2_CPU_CPURSTCTL_REGBUSENABLE_POS)

#define VT2_CPU_CPUCLKCTL_OFFSET _ULL(0x70c01)

#define VT2_CPU_CPUCLKCTL_POS 0
#define VT2_CPU_CPUCLKCTL_WID 15
#define VT2_CPU_CPUCLKCTL_MSK (((_ULL(1) << VT2_CPU_CPUCLKCTL_WID) - _ULL(1)) << VT2_CPU_CPUCLKCTL_POS)

#define VT2_CPU_CPUCLKCTL_CLKGATEREN_POS 0
#define VT2_CPU_CPUCLKCTL_CLKGATEREN_WID 1
#define VT2_CPU_CPUCLKCTL_CLKGATEREN_MSK (((_ULL(1) << VT2_CPU_CPUCLKCTL_CLKGATEREN_WID) - _ULL(1)) << VT2_CPU_CPUCLKCTL_CLKGATEREN_POS)
#define VT2_CPU_CPUCLKCTL_CLKGATEROVRD_POS 1
#define VT2_CPU_CPUCLKCTL_CLKGATEROVRD_WID 1
#define VT2_CPU_CPUCLKCTL_CLKGATEROVRD_MSK (((_ULL(1) << VT2_CPU_CPUCLKCTL_CLKGATEROVRD_WID) - _ULL(1)) << VT2_CPU_CPUCLKCTL_CLKGATEROVRD_POS)
#define VT2_CPU_CPUCLKCTL_CLKFREQDIV_POS 2
#define VT2_CPU_CPUCLKCTL_CLKFREQDIV_WID 5
#define VT2_CPU_CPUCLKCTL_CLKFREQDIV_MSK (((_ULL(1) << VT2_CPU_CPUCLKCTL_CLKFREQDIV_WID) - _ULL(1)) << VT2_CPU_CPUCLKCTL_CLKFREQDIV_POS)
#define VT2_CPU_CPUCLKCTL_CLKFREQRAMPUPSTEPDLY_POS 7
#define VT2_CPU_CPUCLKCTL_CLKFREQRAMPUPSTEPDLY_WID 4
#define VT2_CPU_CPUCLKCTL_CLKFREQRAMPUPSTEPDLY_MSK (((_ULL(1) << VT2_CPU_CPUCLKCTL_CLKFREQRAMPUPSTEPDLY_WID) - _ULL(1)) << VT2_CPU_CPUCLKCTL_CLKFREQRAMPUPSTEPDLY_POS)
#define VT2_CPU_CPUCLKCTL_CLKFREQRAMPDNSTEPDLY_POS 11
#define VT2_CPU_CPUCLKCTL_CLKFREQRAMPDNSTEPDLY_WID 4
#define VT2_CPU_CPUCLKCTL_CLKFREQRAMPDNSTEPDLY_MSK (((_ULL(1) << VT2_CPU_CPUCLKCTL_CLKFREQRAMPDNSTEPDLY_WID) - _ULL(1)) << VT2_CPU_CPUCLKCTL_CLKFREQRAMPDNSTEPDLY_POS)

#define VT2_CPU_CPUCLKSTAT_OFFSET _ULL(0x70c02)

#define VT2_CPU_CPUCLKSTAT_POS 0
#define VT2_CPU_CPUCLKSTAT_WID 5
#define VT2_CPU_CPUCLKSTAT_MSK (((_ULL(1) << VT2_CPU_CPUCLKSTAT_WID) - _ULL(1)) << VT2_CPU_CPUCLKSTAT_POS)

#define VT2_CPU_CPUCLKSTAT_CPUQUIESCED_POS 0
#define VT2_CPU_CPUCLKSTAT_CPUQUIESCED_WID 1
#define VT2_CPU_CPUCLKSTAT_CPUQUIESCED_MSK (((_ULL(1) << VT2_CPU_CPUCLKSTAT_CPUQUIESCED_WID) - _ULL(1)) << VT2_CPU_CPUCLKSTAT_CPUQUIESCED_POS)
#define VT2_CPU_CPUCLKSTAT_ICRQUIESCED_POS 1
#define VT2_CPU_CPUCLKSTAT_ICRQUIESCED_WID 1
#define VT2_CPU_CPUCLKSTAT_ICRQUIESCED_MSK (((_ULL(1) << VT2_CPU_CPUCLKSTAT_ICRQUIESCED_WID) - _ULL(1)) << VT2_CPU_CPUCLKSTAT_ICRQUIESCED_POS)
#define VT2_CPU_CPUCLKSTAT_WAKEEVENT_POS 2
#define VT2_CPU_CPUCLKSTAT_WAKEEVENT_WID 1
#define VT2_CPU_CPUCLKSTAT_WAKEEVENT_MSK (((_ULL(1) << VT2_CPU_CPUCLKSTAT_WAKEEVENT_WID) - _ULL(1)) << VT2_CPU_CPUCLKSTAT_WAKEEVENT_POS)
#define VT2_CPU_CPUCLKSTAT_RUNEVENT_POS 3
#define VT2_CPU_CPUCLKSTAT_RUNEVENT_WID 1
#define VT2_CPU_CPUCLKSTAT_RUNEVENT_MSK (((_ULL(1) << VT2_CPU_CPUCLKSTAT_RUNEVENT_WID) - _ULL(1)) << VT2_CPU_CPUCLKSTAT_RUNEVENT_POS)
#define VT2_CPU_CPUCLKSTAT_CPUCLKSTATECGE_POS 4
#define VT2_CPU_CPUCLKSTAT_CPUCLKSTATECGE_WID 1
#define VT2_CPU_CPUCLKSTAT_CPUCLKSTATECGE_MSK (((_ULL(1) << VT2_CPU_CPUCLKSTAT_CPUCLKSTATECGE_WID) - _ULL(1)) << VT2_CPU_CPUCLKSTAT_CPUCLKSTATECGE_POS)

#define VT2_CPU_CPUPWRCFG_OFFSET _ULL(0x70c03)

#define VT2_CPU_CPUPWRCFG_POS 0
#define VT2_CPU_CPUPWRCFG_WID 1
#define VT2_CPU_CPUPWRCFG_MSK (((_ULL(1) << VT2_CPU_CPUPWRCFG_WID) - _ULL(1)) << VT2_CPU_CPUPWRCFG_POS)

#define VT2_CPU_CPUPWRCFG_LSDIS_POS 0
#define VT2_CPU_CPUPWRCFG_LSDIS_WID 1
#define VT2_CPU_CPUPWRCFG_LSDIS_MSK (((_ULL(1) << VT2_CPU_CPUPWRCFG_LSDIS_WID) - _ULL(1)) << VT2_CPU_CPUPWRCFG_LSDIS_POS)
#endif /* VT2_CPU_CSR_H */
