/* This file is auto-generated. Do not hand edit this file. */

#ifndef VT2_EFUSE_MMR_H
#define VT2_EFUSE_MMR_H

#ifndef _ULL

#ifdef __ASSEMBLER__
#define _AC(X,Y) X
#else
#define __AC(X,Y) (X##Y)
#define _AC(X,Y) __AC(X,Y)
#endif

#define _ULL(x)  (_AC(x, ULL))
#endif

#define VT2_CKGN_EFUSECTL_OFFSET _ULL(0x800)

#define VT2_CKGN_EFUSECTL_POS 0
#define VT2_CKGN_EFUSECTL_WID 6
#define VT2_CKGN_EFUSECTL_MSK (((_ULL(1) << VT2_CKGN_EFUSECTL_WID) - _ULL(1)) << VT2_CKGN_EFUSECTL_POS)

#define VT2_CKGN_EFUSECTL_RDWRCTL_POS 0
#define VT2_CKGN_EFUSECTL_RDWRCTL_WID 3
#define VT2_CKGN_EFUSECTL_RDWRCTL_MSK (((_ULL(1) << VT2_CKGN_EFUSECTL_RDWRCTL_WID) - _ULL(1)) << VT2_CKGN_EFUSECTL_RDWRCTL_POS)
#define VT2_CKGN_EFUSECTL_PROGTIME_POS 3
#define VT2_CKGN_EFUSECTL_PROGTIME_WID 2
#define VT2_CKGN_EFUSECTL_PROGTIME_MSK (((_ULL(1) << VT2_CKGN_EFUSECTL_PROGTIME_WID) - _ULL(1)) << VT2_CKGN_EFUSECTL_PROGTIME_POS)
#define VT2_CKGN_EFUSECTL_RSPAFTERARRRDDONE_POS 5
#define VT2_CKGN_EFUSECTL_RSPAFTERARRRDDONE_WID 1
#define VT2_CKGN_EFUSECTL_RSPAFTERARRRDDONE_MSK (((_ULL(1) << VT2_CKGN_EFUSECTL_RSPAFTERARRRDDONE_WID) - _ULL(1)) << VT2_CKGN_EFUSECTL_RSPAFTERARRRDDONE_POS)

#define VT2_CKGN_EFUSESTATUS_OFFSET _ULL(0x801)

#define VT2_CKGN_EFUSESTATUS_POS 0
#define VT2_CKGN_EFUSESTATUS_WID 1
#define VT2_CKGN_EFUSESTATUS_MSK (((_ULL(1) << VT2_CKGN_EFUSESTATUS_WID) - _ULL(1)) << VT2_CKGN_EFUSESTATUS_POS)

#define VT2_CKGN_EFUSESTATUS_PROGNOTDONE_POS 0
#define VT2_CKGN_EFUSESTATUS_PROGNOTDONE_WID 1
#define VT2_CKGN_EFUSESTATUS_PROGNOTDONE_MSK (((_ULL(1) << VT2_CKGN_EFUSESTATUS_PROGNOTDONE_WID) - _ULL(1)) << VT2_CKGN_EFUSESTATUS_PROGNOTDONE_POS)

#define VT2_CKGN_EFUSEATADDR0_OFFSET _ULL(0x810)

#define VT2_CKGN_EFUSEATADDR0_POS 0
#define VT2_CKGN_EFUSEATADDR0_WID 16
#define VT2_CKGN_EFUSEATADDR0_MSK (((_ULL(1) << VT2_CKGN_EFUSEATADDR0_WID) - _ULL(1)) << VT2_CKGN_EFUSEATADDR0_POS)

#define VT2_CKGN_EFUSEATADDR0_VALUE_POS 0
#define VT2_CKGN_EFUSEATADDR0_VALUE_WID 16
#define VT2_CKGN_EFUSEATADDR0_VALUE_MSK (((_ULL(1) << VT2_CKGN_EFUSEATADDR0_VALUE_WID) - _ULL(1)) << VT2_CKGN_EFUSEATADDR0_VALUE_POS)

#define VT2_CKGN_EFUSEATADDR1_OFFSET _ULL(0x811)

#define VT2_CKGN_EFUSEATADDR1_POS 0
#define VT2_CKGN_EFUSEATADDR1_WID 16
#define VT2_CKGN_EFUSEATADDR1_MSK (((_ULL(1) << VT2_CKGN_EFUSEATADDR1_WID) - _ULL(1)) << VT2_CKGN_EFUSEATADDR1_POS)

#define VT2_CKGN_EFUSEATADDR1_VALUE_POS 0
#define VT2_CKGN_EFUSEATADDR1_VALUE_WID 16
#define VT2_CKGN_EFUSEATADDR1_VALUE_MSK (((_ULL(1) << VT2_CKGN_EFUSEATADDR1_VALUE_WID) - _ULL(1)) << VT2_CKGN_EFUSEATADDR1_VALUE_POS)

#define VT2_CKGN_EFUSEATADDR2_OFFSET _ULL(0x812)

#define VT2_CKGN_EFUSEATADDR2_POS 0
#define VT2_CKGN_EFUSEATADDR2_WID 16
#define VT2_CKGN_EFUSEATADDR2_MSK (((_ULL(1) << VT2_CKGN_EFUSEATADDR2_WID) - _ULL(1)) << VT2_CKGN_EFUSEATADDR2_POS)

#define VT2_CKGN_EFUSEATADDR2_VALUE_POS 0
#define VT2_CKGN_EFUSEATADDR2_VALUE_WID 16
#define VT2_CKGN_EFUSEATADDR2_VALUE_MSK (((_ULL(1) << VT2_CKGN_EFUSEATADDR2_VALUE_WID) - _ULL(1)) << VT2_CKGN_EFUSEATADDR2_VALUE_POS)

#define VT2_CKGN_EFUSEATADDR3_OFFSET _ULL(0x813)

#define VT2_CKGN_EFUSEATADDR3_POS 0
#define VT2_CKGN_EFUSEATADDR3_WID 16
#define VT2_CKGN_EFUSEATADDR3_MSK (((_ULL(1) << VT2_CKGN_EFUSEATADDR3_WID) - _ULL(1)) << VT2_CKGN_EFUSEATADDR3_POS)

#define VT2_CKGN_EFUSEATADDR3_VALUE_POS 0
#define VT2_CKGN_EFUSEATADDR3_VALUE_WID 16
#define VT2_CKGN_EFUSEATADDR3_VALUE_MSK (((_ULL(1) << VT2_CKGN_EFUSEATADDR3_VALUE_WID) - _ULL(1)) << VT2_CKGN_EFUSEATADDR3_VALUE_POS)

#define VT2_CKGN_EFUSEATADDR4_OFFSET _ULL(0x814)

#define VT2_CKGN_EFUSEATADDR4_POS 0
#define VT2_CKGN_EFUSEATADDR4_WID 16
#define VT2_CKGN_EFUSEATADDR4_MSK (((_ULL(1) << VT2_CKGN_EFUSEATADDR4_WID) - _ULL(1)) << VT2_CKGN_EFUSEATADDR4_POS)

#define VT2_CKGN_EFUSEATADDR4_VALUE_POS 0
#define VT2_CKGN_EFUSEATADDR4_VALUE_WID 16
#define VT2_CKGN_EFUSEATADDR4_VALUE_MSK (((_ULL(1) << VT2_CKGN_EFUSEATADDR4_VALUE_WID) - _ULL(1)) << VT2_CKGN_EFUSEATADDR4_VALUE_POS)

#define VT2_CKGN_EFUSEATADDR5_OFFSET _ULL(0x815)

#define VT2_CKGN_EFUSEATADDR5_POS 0
#define VT2_CKGN_EFUSEATADDR5_WID 16
#define VT2_CKGN_EFUSEATADDR5_MSK (((_ULL(1) << VT2_CKGN_EFUSEATADDR5_WID) - _ULL(1)) << VT2_CKGN_EFUSEATADDR5_POS)

#define VT2_CKGN_EFUSEATADDR5_VALUE_POS 0
#define VT2_CKGN_EFUSEATADDR5_VALUE_WID 16
#define VT2_CKGN_EFUSEATADDR5_VALUE_MSK (((_ULL(1) << VT2_CKGN_EFUSEATADDR5_VALUE_WID) - _ULL(1)) << VT2_CKGN_EFUSEATADDR5_VALUE_POS)

#define VT2_CKGN_EFUSEATADDR6_OFFSET _ULL(0x816)

#define VT2_CKGN_EFUSEATADDR6_POS 0
#define VT2_CKGN_EFUSEATADDR6_WID 16
#define VT2_CKGN_EFUSEATADDR6_MSK (((_ULL(1) << VT2_CKGN_EFUSEATADDR6_WID) - _ULL(1)) << VT2_CKGN_EFUSEATADDR6_POS)

#define VT2_CKGN_EFUSEATADDR6_VALUE_POS 0
#define VT2_CKGN_EFUSEATADDR6_VALUE_WID 16
#define VT2_CKGN_EFUSEATADDR6_VALUE_MSK (((_ULL(1) << VT2_CKGN_EFUSEATADDR6_VALUE_WID) - _ULL(1)) << VT2_CKGN_EFUSEATADDR6_VALUE_POS)

#define VT2_CKGN_EFUSEATADDR7_OFFSET _ULL(0x817)

#define VT2_CKGN_EFUSEATADDR7_POS 0
#define VT2_CKGN_EFUSEATADDR7_WID 16
#define VT2_CKGN_EFUSEATADDR7_MSK (((_ULL(1) << VT2_CKGN_EFUSEATADDR7_WID) - _ULL(1)) << VT2_CKGN_EFUSEATADDR7_POS)

#define VT2_CKGN_EFUSEATADDR7_VALUE_POS 0
#define VT2_CKGN_EFUSEATADDR7_VALUE_WID 16
#define VT2_CKGN_EFUSEATADDR7_VALUE_MSK (((_ULL(1) << VT2_CKGN_EFUSEATADDR7_VALUE_WID) - _ULL(1)) << VT2_CKGN_EFUSEATADDR7_VALUE_POS)

#define VT2_CKGN_EFUSEATADDR8_OFFSET _ULL(0x818)

#define VT2_CKGN_EFUSEATADDR8_POS 0
#define VT2_CKGN_EFUSEATADDR8_WID 16
#define VT2_CKGN_EFUSEATADDR8_MSK (((_ULL(1) << VT2_CKGN_EFUSEATADDR8_WID) - _ULL(1)) << VT2_CKGN_EFUSEATADDR8_POS)

#define VT2_CKGN_EFUSEATADDR8_VALUE_POS 0
#define VT2_CKGN_EFUSEATADDR8_VALUE_WID 16
#define VT2_CKGN_EFUSEATADDR8_VALUE_MSK (((_ULL(1) << VT2_CKGN_EFUSEATADDR8_VALUE_WID) - _ULL(1)) << VT2_CKGN_EFUSEATADDR8_VALUE_POS)

#define VT2_CKGN_EFUSEATADDR9_OFFSET _ULL(0x819)

#define VT2_CKGN_EFUSEATADDR9_POS 0
#define VT2_CKGN_EFUSEATADDR9_WID 16
#define VT2_CKGN_EFUSEATADDR9_MSK (((_ULL(1) << VT2_CKGN_EFUSEATADDR9_WID) - _ULL(1)) << VT2_CKGN_EFUSEATADDR9_POS)

#define VT2_CKGN_EFUSEATADDR9_VALUE_POS 0
#define VT2_CKGN_EFUSEATADDR9_VALUE_WID 16
#define VT2_CKGN_EFUSEATADDR9_VALUE_MSK (((_ULL(1) << VT2_CKGN_EFUSEATADDR9_VALUE_WID) - _ULL(1)) << VT2_CKGN_EFUSEATADDR9_VALUE_POS)

#define VT2_CKGN_EFUSEATADDR10_OFFSET _ULL(0x81a)

#define VT2_CKGN_EFUSEATADDR10_POS 0
#define VT2_CKGN_EFUSEATADDR10_WID 16
#define VT2_CKGN_EFUSEATADDR10_MSK (((_ULL(1) << VT2_CKGN_EFUSEATADDR10_WID) - _ULL(1)) << VT2_CKGN_EFUSEATADDR10_POS)

#define VT2_CKGN_EFUSEATADDR10_VALUE_POS 0
#define VT2_CKGN_EFUSEATADDR10_VALUE_WID 16
#define VT2_CKGN_EFUSEATADDR10_VALUE_MSK (((_ULL(1) << VT2_CKGN_EFUSEATADDR10_VALUE_WID) - _ULL(1)) << VT2_CKGN_EFUSEATADDR10_VALUE_POS)

#define VT2_CKGN_EFUSEATADDR11_OFFSET _ULL(0x81b)

#define VT2_CKGN_EFUSEATADDR11_POS 0
#define VT2_CKGN_EFUSEATADDR11_WID 16
#define VT2_CKGN_EFUSEATADDR11_MSK (((_ULL(1) << VT2_CKGN_EFUSEATADDR11_WID) - _ULL(1)) << VT2_CKGN_EFUSEATADDR11_POS)

#define VT2_CKGN_EFUSEATADDR11_VALUE_POS 0
#define VT2_CKGN_EFUSEATADDR11_VALUE_WID 16
#define VT2_CKGN_EFUSEATADDR11_VALUE_MSK (((_ULL(1) << VT2_CKGN_EFUSEATADDR11_VALUE_WID) - _ULL(1)) << VT2_CKGN_EFUSEATADDR11_VALUE_POS)

#define VT2_CKGN_EFUSEATADDR12_OFFSET _ULL(0x81c)

#define VT2_CKGN_EFUSEATADDR12_POS 0
#define VT2_CKGN_EFUSEATADDR12_WID 16
#define VT2_CKGN_EFUSEATADDR12_MSK (((_ULL(1) << VT2_CKGN_EFUSEATADDR12_WID) - _ULL(1)) << VT2_CKGN_EFUSEATADDR12_POS)

#define VT2_CKGN_EFUSEATADDR12_VALUE_POS 0
#define VT2_CKGN_EFUSEATADDR12_VALUE_WID 16
#define VT2_CKGN_EFUSEATADDR12_VALUE_MSK (((_ULL(1) << VT2_CKGN_EFUSEATADDR12_VALUE_WID) - _ULL(1)) << VT2_CKGN_EFUSEATADDR12_VALUE_POS)

#define VT2_CKGN_EFUSEATADDR13_OFFSET _ULL(0x81d)

#define VT2_CKGN_EFUSEATADDR13_POS 0
#define VT2_CKGN_EFUSEATADDR13_WID 16
#define VT2_CKGN_EFUSEATADDR13_MSK (((_ULL(1) << VT2_CKGN_EFUSEATADDR13_WID) - _ULL(1)) << VT2_CKGN_EFUSEATADDR13_POS)

#define VT2_CKGN_EFUSEATADDR13_VALUE_POS 0
#define VT2_CKGN_EFUSEATADDR13_VALUE_WID 16
#define VT2_CKGN_EFUSEATADDR13_VALUE_MSK (((_ULL(1) << VT2_CKGN_EFUSEATADDR13_VALUE_WID) - _ULL(1)) << VT2_CKGN_EFUSEATADDR13_VALUE_POS)

#define VT2_CKGN_EFUSEATADDR14_OFFSET _ULL(0x81e)

#define VT2_CKGN_EFUSEATADDR14_POS 0
#define VT2_CKGN_EFUSEATADDR14_WID 16
#define VT2_CKGN_EFUSEATADDR14_MSK (((_ULL(1) << VT2_CKGN_EFUSEATADDR14_WID) - _ULL(1)) << VT2_CKGN_EFUSEATADDR14_POS)

#define VT2_CKGN_EFUSEATADDR14_VALUE_POS 0
#define VT2_CKGN_EFUSEATADDR14_VALUE_WID 16
#define VT2_CKGN_EFUSEATADDR14_VALUE_MSK (((_ULL(1) << VT2_CKGN_EFUSEATADDR14_VALUE_WID) - _ULL(1)) << VT2_CKGN_EFUSEATADDR14_VALUE_POS)

#define VT2_CKGN_EFUSEATADDR15_OFFSET _ULL(0x81f)

#define VT2_CKGN_EFUSEATADDR15_POS 0
#define VT2_CKGN_EFUSEATADDR15_WID 16
#define VT2_CKGN_EFUSEATADDR15_MSK (((_ULL(1) << VT2_CKGN_EFUSEATADDR15_WID) - _ULL(1)) << VT2_CKGN_EFUSEATADDR15_POS)

#define VT2_CKGN_EFUSEATADDR15_VALUE_POS 0
#define VT2_CKGN_EFUSEATADDR15_VALUE_WID 16
#define VT2_CKGN_EFUSEATADDR15_VALUE_MSK (((_ULL(1) << VT2_CKGN_EFUSEATADDR15_VALUE_WID) - _ULL(1)) << VT2_CKGN_EFUSEATADDR15_VALUE_POS)

#define VT2_CKGN_EFUSEATADDR16_OFFSET _ULL(0x820)

#define VT2_CKGN_EFUSEATADDR16_POS 0
#define VT2_CKGN_EFUSEATADDR16_WID 16
#define VT2_CKGN_EFUSEATADDR16_MSK (((_ULL(1) << VT2_CKGN_EFUSEATADDR16_WID) - _ULL(1)) << VT2_CKGN_EFUSEATADDR16_POS)

#define VT2_CKGN_EFUSEATADDR16_VALUE_POS 0
#define VT2_CKGN_EFUSEATADDR16_VALUE_WID 16
#define VT2_CKGN_EFUSEATADDR16_VALUE_MSK (((_ULL(1) << VT2_CKGN_EFUSEATADDR16_VALUE_WID) - _ULL(1)) << VT2_CKGN_EFUSEATADDR16_VALUE_POS)

#define VT2_CKGN_EFUSEATADDR17_OFFSET _ULL(0x821)

#define VT2_CKGN_EFUSEATADDR17_POS 0
#define VT2_CKGN_EFUSEATADDR17_WID 16
#define VT2_CKGN_EFUSEATADDR17_MSK (((_ULL(1) << VT2_CKGN_EFUSEATADDR17_WID) - _ULL(1)) << VT2_CKGN_EFUSEATADDR17_POS)

#define VT2_CKGN_EFUSEATADDR17_VALUE_POS 0
#define VT2_CKGN_EFUSEATADDR17_VALUE_WID 16
#define VT2_CKGN_EFUSEATADDR17_VALUE_MSK (((_ULL(1) << VT2_CKGN_EFUSEATADDR17_VALUE_WID) - _ULL(1)) << VT2_CKGN_EFUSEATADDR17_VALUE_POS)

#define VT2_CKGN_EFUSEATADDR18_OFFSET _ULL(0x822)

#define VT2_CKGN_EFUSEATADDR18_POS 0
#define VT2_CKGN_EFUSEATADDR18_WID 16
#define VT2_CKGN_EFUSEATADDR18_MSK (((_ULL(1) << VT2_CKGN_EFUSEATADDR18_WID) - _ULL(1)) << VT2_CKGN_EFUSEATADDR18_POS)

#define VT2_CKGN_EFUSEATADDR18_VALUE_POS 0
#define VT2_CKGN_EFUSEATADDR18_VALUE_WID 16
#define VT2_CKGN_EFUSEATADDR18_VALUE_MSK (((_ULL(1) << VT2_CKGN_EFUSEATADDR18_VALUE_WID) - _ULL(1)) << VT2_CKGN_EFUSEATADDR18_VALUE_POS)

#define VT2_CKGN_EFUSEATADDR19_OFFSET _ULL(0x823)

#define VT2_CKGN_EFUSEATADDR19_POS 0
#define VT2_CKGN_EFUSEATADDR19_WID 16
#define VT2_CKGN_EFUSEATADDR19_MSK (((_ULL(1) << VT2_CKGN_EFUSEATADDR19_WID) - _ULL(1)) << VT2_CKGN_EFUSEATADDR19_POS)

#define VT2_CKGN_EFUSEATADDR19_VALUE_POS 0
#define VT2_CKGN_EFUSEATADDR19_VALUE_WID 16
#define VT2_CKGN_EFUSEATADDR19_VALUE_MSK (((_ULL(1) << VT2_CKGN_EFUSEATADDR19_VALUE_WID) - _ULL(1)) << VT2_CKGN_EFUSEATADDR19_VALUE_POS)

#define VT2_CKGN_EFUSEATADDR20_OFFSET _ULL(0x824)

#define VT2_CKGN_EFUSEATADDR20_POS 0
#define VT2_CKGN_EFUSEATADDR20_WID 16
#define VT2_CKGN_EFUSEATADDR20_MSK (((_ULL(1) << VT2_CKGN_EFUSEATADDR20_WID) - _ULL(1)) << VT2_CKGN_EFUSEATADDR20_POS)

#define VT2_CKGN_EFUSEATADDR20_VALUE_POS 0
#define VT2_CKGN_EFUSEATADDR20_VALUE_WID 16
#define VT2_CKGN_EFUSEATADDR20_VALUE_MSK (((_ULL(1) << VT2_CKGN_EFUSEATADDR20_VALUE_WID) - _ULL(1)) << VT2_CKGN_EFUSEATADDR20_VALUE_POS)

#define VT2_CKGN_EFUSEATADDR21_OFFSET _ULL(0x825)

#define VT2_CKGN_EFUSEATADDR21_POS 0
#define VT2_CKGN_EFUSEATADDR21_WID 16
#define VT2_CKGN_EFUSEATADDR21_MSK (((_ULL(1) << VT2_CKGN_EFUSEATADDR21_WID) - _ULL(1)) << VT2_CKGN_EFUSEATADDR21_POS)

#define VT2_CKGN_EFUSEATADDR21_VALUE_POS 0
#define VT2_CKGN_EFUSEATADDR21_VALUE_WID 16
#define VT2_CKGN_EFUSEATADDR21_VALUE_MSK (((_ULL(1) << VT2_CKGN_EFUSEATADDR21_VALUE_WID) - _ULL(1)) << VT2_CKGN_EFUSEATADDR21_VALUE_POS)

#define VT2_CKGN_EFUSEATADDR22_OFFSET _ULL(0x826)

#define VT2_CKGN_EFUSEATADDR22_POS 0
#define VT2_CKGN_EFUSEATADDR22_WID 16
#define VT2_CKGN_EFUSEATADDR22_MSK (((_ULL(1) << VT2_CKGN_EFUSEATADDR22_WID) - _ULL(1)) << VT2_CKGN_EFUSEATADDR22_POS)

#define VT2_CKGN_EFUSEATADDR22_VALUE_POS 0
#define VT2_CKGN_EFUSEATADDR22_VALUE_WID 16
#define VT2_CKGN_EFUSEATADDR22_VALUE_MSK (((_ULL(1) << VT2_CKGN_EFUSEATADDR22_VALUE_WID) - _ULL(1)) << VT2_CKGN_EFUSEATADDR22_VALUE_POS)

#define VT2_CKGN_EFUSEATADDR23_OFFSET _ULL(0x827)

#define VT2_CKGN_EFUSEATADDR23_POS 0
#define VT2_CKGN_EFUSEATADDR23_WID 16
#define VT2_CKGN_EFUSEATADDR23_MSK (((_ULL(1) << VT2_CKGN_EFUSEATADDR23_WID) - _ULL(1)) << VT2_CKGN_EFUSEATADDR23_POS)

#define VT2_CKGN_EFUSEATADDR23_VALUE_POS 0
#define VT2_CKGN_EFUSEATADDR23_VALUE_WID 16
#define VT2_CKGN_EFUSEATADDR23_VALUE_MSK (((_ULL(1) << VT2_CKGN_EFUSEATADDR23_VALUE_WID) - _ULL(1)) << VT2_CKGN_EFUSEATADDR23_VALUE_POS)

#define VT2_CKGN_EFUSEATADDR24_OFFSET _ULL(0x828)

#define VT2_CKGN_EFUSEATADDR24_POS 0
#define VT2_CKGN_EFUSEATADDR24_WID 16
#define VT2_CKGN_EFUSEATADDR24_MSK (((_ULL(1) << VT2_CKGN_EFUSEATADDR24_WID) - _ULL(1)) << VT2_CKGN_EFUSEATADDR24_POS)

#define VT2_CKGN_EFUSEATADDR24_VALUE_POS 0
#define VT2_CKGN_EFUSEATADDR24_VALUE_WID 16
#define VT2_CKGN_EFUSEATADDR24_VALUE_MSK (((_ULL(1) << VT2_CKGN_EFUSEATADDR24_VALUE_WID) - _ULL(1)) << VT2_CKGN_EFUSEATADDR24_VALUE_POS)

#define VT2_CKGN_EFUSEATADDR25_OFFSET _ULL(0x829)

#define VT2_CKGN_EFUSEATADDR25_POS 0
#define VT2_CKGN_EFUSEATADDR25_WID 16
#define VT2_CKGN_EFUSEATADDR25_MSK (((_ULL(1) << VT2_CKGN_EFUSEATADDR25_WID) - _ULL(1)) << VT2_CKGN_EFUSEATADDR25_POS)

#define VT2_CKGN_EFUSEATADDR25_VALUE_POS 0
#define VT2_CKGN_EFUSEATADDR25_VALUE_WID 16
#define VT2_CKGN_EFUSEATADDR25_VALUE_MSK (((_ULL(1) << VT2_CKGN_EFUSEATADDR25_VALUE_WID) - _ULL(1)) << VT2_CKGN_EFUSEATADDR25_VALUE_POS)

#define VT2_CKGN_EFUSEATADDR26_OFFSET _ULL(0x82a)

#define VT2_CKGN_EFUSEATADDR26_POS 0
#define VT2_CKGN_EFUSEATADDR26_WID 16
#define VT2_CKGN_EFUSEATADDR26_MSK (((_ULL(1) << VT2_CKGN_EFUSEATADDR26_WID) - _ULL(1)) << VT2_CKGN_EFUSEATADDR26_POS)

#define VT2_CKGN_EFUSEATADDR26_VALUE_POS 0
#define VT2_CKGN_EFUSEATADDR26_VALUE_WID 16
#define VT2_CKGN_EFUSEATADDR26_VALUE_MSK (((_ULL(1) << VT2_CKGN_EFUSEATADDR26_VALUE_WID) - _ULL(1)) << VT2_CKGN_EFUSEATADDR26_VALUE_POS)

#define VT2_CKGN_EFUSEATADDR27_OFFSET _ULL(0x82b)

#define VT2_CKGN_EFUSEATADDR27_POS 0
#define VT2_CKGN_EFUSEATADDR27_WID 16
#define VT2_CKGN_EFUSEATADDR27_MSK (((_ULL(1) << VT2_CKGN_EFUSEATADDR27_WID) - _ULL(1)) << VT2_CKGN_EFUSEATADDR27_POS)

#define VT2_CKGN_EFUSEATADDR27_VALUE_POS 0
#define VT2_CKGN_EFUSEATADDR27_VALUE_WID 16
#define VT2_CKGN_EFUSEATADDR27_VALUE_MSK (((_ULL(1) << VT2_CKGN_EFUSEATADDR27_VALUE_WID) - _ULL(1)) << VT2_CKGN_EFUSEATADDR27_VALUE_POS)

#define VT2_CKGN_EFUSEATADDR28_OFFSET _ULL(0x82c)

#define VT2_CKGN_EFUSEATADDR28_POS 0
#define VT2_CKGN_EFUSEATADDR28_WID 16
#define VT2_CKGN_EFUSEATADDR28_MSK (((_ULL(1) << VT2_CKGN_EFUSEATADDR28_WID) - _ULL(1)) << VT2_CKGN_EFUSEATADDR28_POS)

#define VT2_CKGN_EFUSEATADDR28_VALUE_POS 0
#define VT2_CKGN_EFUSEATADDR28_VALUE_WID 16
#define VT2_CKGN_EFUSEATADDR28_VALUE_MSK (((_ULL(1) << VT2_CKGN_EFUSEATADDR28_VALUE_WID) - _ULL(1)) << VT2_CKGN_EFUSEATADDR28_VALUE_POS)

#define VT2_CKGN_EFUSEATADDR29_OFFSET _ULL(0x82d)

#define VT2_CKGN_EFUSEATADDR29_POS 0
#define VT2_CKGN_EFUSEATADDR29_WID 16
#define VT2_CKGN_EFUSEATADDR29_MSK (((_ULL(1) << VT2_CKGN_EFUSEATADDR29_WID) - _ULL(1)) << VT2_CKGN_EFUSEATADDR29_POS)

#define VT2_CKGN_EFUSEATADDR29_VALUE_POS 0
#define VT2_CKGN_EFUSEATADDR29_VALUE_WID 16
#define VT2_CKGN_EFUSEATADDR29_VALUE_MSK (((_ULL(1) << VT2_CKGN_EFUSEATADDR29_VALUE_WID) - _ULL(1)) << VT2_CKGN_EFUSEATADDR29_VALUE_POS)

#define VT2_CKGN_EFUSEATADDR30_OFFSET _ULL(0x82e)

#define VT2_CKGN_EFUSEATADDR30_POS 0
#define VT2_CKGN_EFUSEATADDR30_WID 16
#define VT2_CKGN_EFUSEATADDR30_MSK (((_ULL(1) << VT2_CKGN_EFUSEATADDR30_WID) - _ULL(1)) << VT2_CKGN_EFUSEATADDR30_POS)

#define VT2_CKGN_EFUSEATADDR30_VALUE_POS 0
#define VT2_CKGN_EFUSEATADDR30_VALUE_WID 16
#define VT2_CKGN_EFUSEATADDR30_VALUE_MSK (((_ULL(1) << VT2_CKGN_EFUSEATADDR30_VALUE_WID) - _ULL(1)) << VT2_CKGN_EFUSEATADDR30_VALUE_POS)

#define VT2_CKGN_EFUSEATADDR31_OFFSET _ULL(0x82f)

#define VT2_CKGN_EFUSEATADDR31_POS 0
#define VT2_CKGN_EFUSEATADDR31_WID 16
#define VT2_CKGN_EFUSEATADDR31_MSK (((_ULL(1) << VT2_CKGN_EFUSEATADDR31_WID) - _ULL(1)) << VT2_CKGN_EFUSEATADDR31_POS)

#define VT2_CKGN_EFUSEATADDR31_VALUE_POS 0
#define VT2_CKGN_EFUSEATADDR31_VALUE_WID 16
#define VT2_CKGN_EFUSEATADDR31_VALUE_MSK (((_ULL(1) << VT2_CKGN_EFUSEATADDR31_VALUE_WID) - _ULL(1)) << VT2_CKGN_EFUSEATADDR31_VALUE_POS)

#endif /* VT2_EFUSE_MMR_H */
