/* This file is auto-generated. Do not hand edit this file. */

#ifndef VT2_ICP_MMR_H
#define VT2_ICP_MMR_H

#ifndef _ULL

#ifdef __ASSEMBLER__
#define _AC(X,Y) X
#else
#define __AC(X,Y) (X##Y)
#define _AC(X,Y) __AC(X,Y)
#endif

#define _ULL(x)  (_AC(x, ULL))
#endif


#define VT2_ICP_LINKINTERFACE_OFFSET _ULL(0x0)

#define VT2_ICP_LINKINTERFACE_POS 0
#define VT2_ICP_LINKINTERFACE_WID 5
#define VT2_ICP_LINKINTERFACE_MSK (((_ULL(1) << VT2_ICP_LINKINTERFACE_WID) - _ULL(1)) << VT2_ICP_LINKINTERFACE_POS)

#define VT2_ICP_LINKINTERFACE_TXLINKACTIVATE_POS 0
#define VT2_ICP_LINKINTERFACE_TXLINKACTIVATE_WID 1
#define VT2_ICP_LINKINTERFACE_TXLINKACTIVATE_MSK (((_ULL(1) << VT2_ICP_LINKINTERFACE_TXLINKACTIVATE_WID) - _ULL(1)) << VT2_ICP_LINKINTERFACE_TXLINKACTIVATE_POS)
#define VT2_ICP_LINKINTERFACE_TXLINKREQ_POS 1
#define VT2_ICP_LINKINTERFACE_TXLINKREQ_WID 1
#define VT2_ICP_LINKINTERFACE_TXLINKREQ_MSK (((_ULL(1) << VT2_ICP_LINKINTERFACE_TXLINKREQ_WID) - _ULL(1)) << VT2_ICP_LINKINTERFACE_TXLINKREQ_POS)
#define VT2_ICP_LINKINTERFACE_TXLINKACK_POS 2
#define VT2_ICP_LINKINTERFACE_TXLINKACK_WID 1
#define VT2_ICP_LINKINTERFACE_TXLINKACK_MSK (((_ULL(1) << VT2_ICP_LINKINTERFACE_TXLINKACK_WID) - _ULL(1)) << VT2_ICP_LINKINTERFACE_TXLINKACK_POS)
#define VT2_ICP_LINKINTERFACE_RXLINKREQ_POS 3
#define VT2_ICP_LINKINTERFACE_RXLINKREQ_WID 1
#define VT2_ICP_LINKINTERFACE_RXLINKREQ_MSK (((_ULL(1) << VT2_ICP_LINKINTERFACE_RXLINKREQ_WID) - _ULL(1)) << VT2_ICP_LINKINTERFACE_RXLINKREQ_POS)
#define VT2_ICP_LINKINTERFACE_RXLINKACK_POS 4
#define VT2_ICP_LINKINTERFACE_RXLINKACK_WID 1
#define VT2_ICP_LINKINTERFACE_RXLINKACK_MSK (((_ULL(1) << VT2_ICP_LINKINTERFACE_RXLINKACK_WID) - _ULL(1)) << VT2_ICP_LINKINTERFACE_RXLINKACK_POS)

#define VT2_ICP_PROTACTIVITY_OFFSET _ULL(0x1)

#define VT2_ICP_PROTACTIVITY_POS 0
#define VT2_ICP_PROTACTIVITY_WID 2
#define VT2_ICP_PROTACTIVITY_MSK (((_ULL(1) << VT2_ICP_PROTACTIVITY_WID) - _ULL(1)) << VT2_ICP_PROTACTIVITY_POS)

#define VT2_ICP_PROTACTIVITY_TXSACTIVE_POS 0
#define VT2_ICP_PROTACTIVITY_TXSACTIVE_WID 1
#define VT2_ICP_PROTACTIVITY_TXSACTIVE_MSK (((_ULL(1) << VT2_ICP_PROTACTIVITY_TXSACTIVE_WID) - _ULL(1)) << VT2_ICP_PROTACTIVITY_TXSACTIVE_POS)
#define VT2_ICP_PROTACTIVITY_RXSACTIVE_POS 1
#define VT2_ICP_PROTACTIVITY_RXSACTIVE_WID 1
#define VT2_ICP_PROTACTIVITY_RXSACTIVE_MSK (((_ULL(1) << VT2_ICP_PROTACTIVITY_RXSACTIVE_WID) - _ULL(1)) << VT2_ICP_PROTACTIVITY_RXSACTIVE_POS)

#define VT2_ICP_SYSTEMCOHERENCY_OFFSET _ULL(0x2)

#define VT2_ICP_SYSTEMCOHERENCY_POS 0
#define VT2_ICP_SYSTEMCOHERENCY_WID 2
#define VT2_ICP_SYSTEMCOHERENCY_MSK (((_ULL(1) << VT2_ICP_SYSTEMCOHERENCY_WID) - _ULL(1)) << VT2_ICP_SYSTEMCOHERENCY_POS)

#define VT2_ICP_SYSTEMCOHERENCY_SYSCOREQ_POS 0
#define VT2_ICP_SYSTEMCOHERENCY_SYSCOREQ_WID 1
#define VT2_ICP_SYSTEMCOHERENCY_SYSCOREQ_MSK (((_ULL(1) << VT2_ICP_SYSTEMCOHERENCY_SYSCOREQ_WID) - _ULL(1)) << VT2_ICP_SYSTEMCOHERENCY_SYSCOREQ_POS)
#define VT2_ICP_SYSTEMCOHERENCY_SYSCOACK_POS 1
#define VT2_ICP_SYSTEMCOHERENCY_SYSCOACK_WID 1
#define VT2_ICP_SYSTEMCOHERENCY_SYSCOACK_MSK (((_ULL(1) << VT2_ICP_SYSTEMCOHERENCY_SYSCOACK_WID) - _ULL(1)) << VT2_ICP_SYSTEMCOHERENCY_SYSCOACK_POS)

#define VT2_ICP_ICPCONFIG_OFFSET _ULL(0x3)

#define VT2_ICP_ICPCONFIG_POS 0
#define VT2_ICP_ICPCONFIG_WID 32
#define VT2_ICP_ICPCONFIG_MSK (((_ULL(1) << VT2_ICP_ICPCONFIG_WID) - _ULL(1)) << VT2_ICP_ICPCONFIG_POS)

#define VT2_ICP_ICPCONFIG_L2SETIDXHASHDIS_POS 0
#define VT2_ICP_ICPCONFIG_L2SETIDXHASHDIS_WID 1
#define VT2_ICP_ICPCONFIG_L2SETIDXHASHDIS_MSK (((_ULL(1) << VT2_ICP_ICPCONFIG_L2SETIDXHASHDIS_WID) - _ULL(1)) << VT2_ICP_ICPCONFIG_L2SETIDXHASHDIS_POS)
#define VT2_ICP_ICPCONFIG_L3SLICEHASHDIS_POS 1
#define VT2_ICP_ICPCONFIG_L3SLICEHASHDIS_WID 1
#define VT2_ICP_ICPCONFIG_L3SLICEHASHDIS_MSK (((_ULL(1) << VT2_ICP_ICPCONFIG_L3SLICEHASHDIS_WID) - _ULL(1)) << VT2_ICP_ICPCONFIG_L3SLICEHASHDIS_POS)
#define VT2_ICP_ICPCONFIG_CLUSTERVERID_POS 16
#define VT2_ICP_ICPCONFIG_CLUSTERVERID_WID 4
#define VT2_ICP_ICPCONFIG_CLUSTERVERID_MSK (((_ULL(1) << VT2_ICP_ICPCONFIG_CLUSTERVERID_WID) - _ULL(1)) << VT2_ICP_ICPCONFIG_CLUSTERVERID_POS)
#define VT2_ICP_ICPCONFIG_CLUSTERIMPID_POS 20
#define VT2_ICP_ICPCONFIG_CLUSTERIMPID_WID 12
#define VT2_ICP_ICPCONFIG_CLUSTERIMPID_MSK (((_ULL(1) << VT2_ICP_ICPCONFIG_CLUSTERIMPID_WID) - _ULL(1)) << VT2_ICP_ICPCONFIG_CLUSTERIMPID_POS)

#define VT2_ICP_ERRSTATUS0_OFFSET _ULL(0x800)

#define VT2_ICP_ERRSTATUS0_POS 0
#define VT2_ICP_ERRSTATUS0_WID 32
#define VT2_ICP_ERRSTATUS0_MSK (((_ULL(1) << VT2_ICP_ERRSTATUS0_WID) - _ULL(1)) << VT2_ICP_ERRSTATUS0_POS)

#define VT2_ICP_ERRSTATUS0_ERRSTATUS_POS 0
#define VT2_ICP_ERRSTATUS0_ERRSTATUS_WID 32
#define VT2_ICP_ERRSTATUS0_ERRSTATUS_MSK (((_ULL(1) << VT2_ICP_ERRSTATUS0_ERRSTATUS_WID) - _ULL(1)) << VT2_ICP_ERRSTATUS0_ERRSTATUS_POS)

#define VT2_ICP_ERRSTATUS1_OFFSET _ULL(0x801)

#define VT2_ICP_ERRSTATUS1_POS 0
#define VT2_ICP_ERRSTATUS1_WID 32
#define VT2_ICP_ERRSTATUS1_MSK (((_ULL(1) << VT2_ICP_ERRSTATUS1_WID) - _ULL(1)) << VT2_ICP_ERRSTATUS1_POS)

#define VT2_ICP_ERRSTATUS1_ERRSTATUS_POS 0
#define VT2_ICP_ERRSTATUS1_ERRSTATUS_WID 32
#define VT2_ICP_ERRSTATUS1_ERRSTATUS_MSK (((_ULL(1) << VT2_ICP_ERRSTATUS1_ERRSTATUS_WID) - _ULL(1)) << VT2_ICP_ERRSTATUS1_ERRSTATUS_POS)

#define VT2_ICP_ERRSTATUS2_OFFSET _ULL(0x802)

#define VT2_ICP_ERRSTATUS2_POS 0
#define VT2_ICP_ERRSTATUS2_WID 32
#define VT2_ICP_ERRSTATUS2_MSK (((_ULL(1) << VT2_ICP_ERRSTATUS2_WID) - _ULL(1)) << VT2_ICP_ERRSTATUS2_POS)

#define VT2_ICP_ERRSTATUS2_ERRSTATUS_POS 0
#define VT2_ICP_ERRSTATUS2_ERRSTATUS_WID 32
#define VT2_ICP_ERRSTATUS2_ERRSTATUS_MSK (((_ULL(1) << VT2_ICP_ERRSTATUS2_ERRSTATUS_WID) - _ULL(1)) << VT2_ICP_ERRSTATUS2_ERRSTATUS_POS)

#define VT2_ICP_ERRSTATUS3_OFFSET _ULL(0x803)

#define VT2_ICP_ERRSTATUS3_POS 0
#define VT2_ICP_ERRSTATUS3_WID 32
#define VT2_ICP_ERRSTATUS3_MSK (((_ULL(1) << VT2_ICP_ERRSTATUS3_WID) - _ULL(1)) << VT2_ICP_ERRSTATUS3_POS)

#define VT2_ICP_ERRSTATUS3_ERRSTATUS_POS 0
#define VT2_ICP_ERRSTATUS3_ERRSTATUS_WID 32
#define VT2_ICP_ERRSTATUS3_ERRSTATUS_MSK (((_ULL(1) << VT2_ICP_ERRSTATUS3_ERRSTATUS_WID) - _ULL(1)) << VT2_ICP_ERRSTATUS3_ERRSTATUS_POS)

#define VT2_ICP_ERRSTATUS4_OFFSET _ULL(0x804)

#define VT2_ICP_ERRSTATUS4_POS 0
#define VT2_ICP_ERRSTATUS4_WID 32
#define VT2_ICP_ERRSTATUS4_MSK (((_ULL(1) << VT2_ICP_ERRSTATUS4_WID) - _ULL(1)) << VT2_ICP_ERRSTATUS4_POS)

#define VT2_ICP_ERRSTATUS4_ERRSTATUS_POS 0
#define VT2_ICP_ERRSTATUS4_ERRSTATUS_WID 32
#define VT2_ICP_ERRSTATUS4_ERRSTATUS_MSK (((_ULL(1) << VT2_ICP_ERRSTATUS4_ERRSTATUS_WID) - _ULL(1)) << VT2_ICP_ERRSTATUS4_ERRSTATUS_POS)

#define VT2_ICP_POWERESTIMATIONCOUNTER_OFFSET _ULL(0xc00)

#define VT2_ICP_POWERESTIMATIONCOUNTER_POS 0
#define VT2_ICP_POWERESTIMATIONCOUNTER_WID 32
#define VT2_ICP_POWERESTIMATIONCOUNTER_MSK (((_ULL(1) << VT2_ICP_POWERESTIMATIONCOUNTER_WID) - _ULL(1)) << VT2_ICP_POWERESTIMATIONCOUNTER_POS)

#define VT2_ICP_POWERESTIMATIONCOUNTER_UNDERFLOW_POS 0
#define VT2_ICP_POWERESTIMATIONCOUNTER_UNDERFLOW_WID 1
#define VT2_ICP_POWERESTIMATIONCOUNTER_UNDERFLOW_MSK (((_ULL(1) << VT2_ICP_POWERESTIMATIONCOUNTER_UNDERFLOW_WID) - _ULL(1)) << VT2_ICP_POWERESTIMATIONCOUNTER_UNDERFLOW_POS)
#define VT2_ICP_POWERESTIMATIONCOUNTER_SAMPLEID_POS 1
#define VT2_ICP_POWERESTIMATIONCOUNTER_SAMPLEID_WID 3
#define VT2_ICP_POWERESTIMATIONCOUNTER_SAMPLEID_MSK (((_ULL(1) << VT2_ICP_POWERESTIMATIONCOUNTER_SAMPLEID_WID) - _ULL(1)) << VT2_ICP_POWERESTIMATIONCOUNTER_SAMPLEID_POS)
#define VT2_ICP_POWERESTIMATIONCOUNTER_COUNTER_POS 4
#define VT2_ICP_POWERESTIMATIONCOUNTER_COUNTER_WID 28
#define VT2_ICP_POWERESTIMATIONCOUNTER_COUNTER_MSK (((_ULL(1) << VT2_ICP_POWERESTIMATIONCOUNTER_COUNTER_WID) - _ULL(1)) << VT2_ICP_POWERESTIMATIONCOUNTER_COUNTER_POS)

#define VT2_ICP_POWERESTIMATIONCONTROL_OFFSET _ULL(0xc01)

#define VT2_ICP_POWERESTIMATIONCONTROL_POS 0
#define VT2_ICP_POWERESTIMATIONCONTROL_WID 3
#define VT2_ICP_POWERESTIMATIONCONTROL_MSK (((_ULL(1) << VT2_ICP_POWERESTIMATIONCONTROL_WID) - _ULL(1)) << VT2_ICP_POWERESTIMATIONCONTROL_POS)

#define VT2_ICP_POWERESTIMATIONCONTROL_INTERVAL_POS 0
#define VT2_ICP_POWERESTIMATIONCONTROL_INTERVAL_WID 3
#define VT2_ICP_POWERESTIMATIONCONTROL_INTERVAL_MSK (((_ULL(1) << VT2_ICP_POWERESTIMATIONCONTROL_INTERVAL_WID) - _ULL(1)) << VT2_ICP_POWERESTIMATIONCONTROL_INTERVAL_POS)

#define VT2_ICP_POWERESTIMATIONSTATUS_OFFSET _ULL(0xc02)

#define VT2_ICP_POWERESTIMATIONSTATUS_POS 0
#define VT2_ICP_POWERESTIMATIONSTATUS_WID 1
#define VT2_ICP_POWERESTIMATIONSTATUS_MSK (((_ULL(1) << VT2_ICP_POWERESTIMATIONSTATUS_WID) - _ULL(1)) << VT2_ICP_POWERESTIMATIONSTATUS_POS)

#define VT2_ICP_POWERESTIMATIONSTATUS_OVERFLOW_POS 0
#define VT2_ICP_POWERESTIMATIONSTATUS_OVERFLOW_WID 1
#define VT2_ICP_POWERESTIMATIONSTATUS_OVERFLOW_MSK (((_ULL(1) << VT2_ICP_POWERESTIMATIONSTATUS_OVERFLOW_WID) - _ULL(1)) << VT2_ICP_POWERESTIMATIONSTATUS_OVERFLOW_POS)
#endif /* VT2_ICP_MMR_H */
