/* This file is auto-generated. Do not hand edit this file. */

#ifndef VT2_CPU_CSR_H
#define VT2_CPU_CSR_H

#ifndef _ULL

#ifdef __ASSEMBLER__
#define _AC(X,Y) X
#else
#define __AC(X,Y) (X##Y)
#define _AC(X,Y) __AC(X,Y)
#endif

#define _ULL(x)  (_AC(x, ULL))
#endif


#define VT2_CPU_LINKINTERFACE_OFFSET _ULL(0x18000)

#define VT2_CPU_LINKINTERFACE_POS 0
#define VT2_CPU_LINKINTERFACE_WID 5
#define VT2_CPU_LINKINTERFACE_MSK (((_ULL(1) << VT2_CPU_LINKINTERFACE_WID) - _ULL(1)) << VT2_CPU_LINKINTERFACE_POS)

#define VT2_CPU_LINKINTERFACE_TXLINKACTIVATE_POS 0
#define VT2_CPU_LINKINTERFACE_TXLINKACTIVATE_WID 1
#define VT2_CPU_LINKINTERFACE_TXLINKACTIVATE_MSK (((_ULL(1) << VT2_CPU_LINKINTERFACE_TXLINKACTIVATE_WID) - _ULL(1)) << VT2_CPU_LINKINTERFACE_TXLINKACTIVATE_POS)
#define VT2_CPU_LINKINTERFACE_TXLINKREQ_POS 1
#define VT2_CPU_LINKINTERFACE_TXLINKREQ_WID 1
#define VT2_CPU_LINKINTERFACE_TXLINKREQ_MSK (((_ULL(1) << VT2_CPU_LINKINTERFACE_TXLINKREQ_WID) - _ULL(1)) << VT2_CPU_LINKINTERFACE_TXLINKREQ_POS)
#define VT2_CPU_LINKINTERFACE_TXLINKACK_POS 2
#define VT2_CPU_LINKINTERFACE_TXLINKACK_WID 1
#define VT2_CPU_LINKINTERFACE_TXLINKACK_MSK (((_ULL(1) << VT2_CPU_LINKINTERFACE_TXLINKACK_WID) - _ULL(1)) << VT2_CPU_LINKINTERFACE_TXLINKACK_POS)
#define VT2_CPU_LINKINTERFACE_RXLINKREQ_POS 3
#define VT2_CPU_LINKINTERFACE_RXLINKREQ_WID 1
#define VT2_CPU_LINKINTERFACE_RXLINKREQ_MSK (((_ULL(1) << VT2_CPU_LINKINTERFACE_RXLINKREQ_WID) - _ULL(1)) << VT2_CPU_LINKINTERFACE_RXLINKREQ_POS)
#define VT2_CPU_LINKINTERFACE_RXLINKACK_POS 4
#define VT2_CPU_LINKINTERFACE_RXLINKACK_WID 1
#define VT2_CPU_LINKINTERFACE_RXLINKACK_MSK (((_ULL(1) << VT2_CPU_LINKINTERFACE_RXLINKACK_WID) - _ULL(1)) << VT2_CPU_LINKINTERFACE_RXLINKACK_POS)

#define VT2_CPU_PROTACTIVITY_OFFSET _ULL(0x18001)

#define VT2_CPU_PROTACTIVITY_POS 0
#define VT2_CPU_PROTACTIVITY_WID 2
#define VT2_CPU_PROTACTIVITY_MSK (((_ULL(1) << VT2_CPU_PROTACTIVITY_WID) - _ULL(1)) << VT2_CPU_PROTACTIVITY_POS)

#define VT2_CPU_PROTACTIVITY_TXSACTIVE_POS 0
#define VT2_CPU_PROTACTIVITY_TXSACTIVE_WID 1
#define VT2_CPU_PROTACTIVITY_TXSACTIVE_MSK (((_ULL(1) << VT2_CPU_PROTACTIVITY_TXSACTIVE_WID) - _ULL(1)) << VT2_CPU_PROTACTIVITY_TXSACTIVE_POS)
#define VT2_CPU_PROTACTIVITY_RXSACTIVE_POS 1
#define VT2_CPU_PROTACTIVITY_RXSACTIVE_WID 1
#define VT2_CPU_PROTACTIVITY_RXSACTIVE_MSK (((_ULL(1) << VT2_CPU_PROTACTIVITY_RXSACTIVE_WID) - _ULL(1)) << VT2_CPU_PROTACTIVITY_RXSACTIVE_POS)

#define VT2_CPU_SYSTEMCOHERENCY_OFFSET _ULL(0x18002)

#define VT2_CPU_SYSTEMCOHERENCY_POS 0
#define VT2_CPU_SYSTEMCOHERENCY_WID 2
#define VT2_CPU_SYSTEMCOHERENCY_MSK (((_ULL(1) << VT2_CPU_SYSTEMCOHERENCY_WID) - _ULL(1)) << VT2_CPU_SYSTEMCOHERENCY_POS)

#define VT2_CPU_SYSTEMCOHERENCY_SYSCOREQ_POS 0
#define VT2_CPU_SYSTEMCOHERENCY_SYSCOREQ_WID 1
#define VT2_CPU_SYSTEMCOHERENCY_SYSCOREQ_MSK (((_ULL(1) << VT2_CPU_SYSTEMCOHERENCY_SYSCOREQ_WID) - _ULL(1)) << VT2_CPU_SYSTEMCOHERENCY_SYSCOREQ_POS)
#define VT2_CPU_SYSTEMCOHERENCY_SYSCOACK_POS 1
#define VT2_CPU_SYSTEMCOHERENCY_SYSCOACK_WID 1
#define VT2_CPU_SYSTEMCOHERENCY_SYSCOACK_MSK (((_ULL(1) << VT2_CPU_SYSTEMCOHERENCY_SYSCOACK_WID) - _ULL(1)) << VT2_CPU_SYSTEMCOHERENCY_SYSCOACK_POS)

#define VT2_CPU_ICPCONFIG_OFFSET _ULL(0x18003)

#define VT2_CPU_ICPCONFIG_POS 0
#define VT2_CPU_ICPCONFIG_WID 4
#define VT2_CPU_ICPCONFIG_MSK (((_ULL(1) << VT2_CPU_ICPCONFIG_WID) - _ULL(1)) << VT2_CPU_ICPCONFIG_POS)

#define VT2_CPU_ICPCONFIG_L2SETIDXHASHDIS_POS 0
#define VT2_CPU_ICPCONFIG_L2SETIDXHASHDIS_WID 1
#define VT2_CPU_ICPCONFIG_L2SETIDXHASHDIS_MSK (((_ULL(1) << VT2_CPU_ICPCONFIG_L2SETIDXHASHDIS_WID) - _ULL(1)) << VT2_CPU_ICPCONFIG_L2SETIDXHASHDIS_POS)
#define VT2_CPU_ICPCONFIG_L3SLICEHASHDIS_POS 1
#define VT2_CPU_ICPCONFIG_L3SLICEHASHDIS_WID 1
#define VT2_CPU_ICPCONFIG_L3SLICEHASHDIS_MSK (((_ULL(1) << VT2_CPU_ICPCONFIG_L3SLICEHASHDIS_WID) - _ULL(1)) << VT2_CPU_ICPCONFIG_L3SLICEHASHDIS_POS)
#define VT2_CPU_ICPCONFIG_RNFSELECT_POS 2
#define VT2_CPU_ICPCONFIG_RNFSELECT_WID 2
#define VT2_CPU_ICPCONFIG_RNFSELECT_MSK (((_ULL(1) << VT2_CPU_ICPCONFIG_RNFSELECT_WID) - _ULL(1)) << VT2_CPU_ICPCONFIG_RNFSELECT_POS)

#define VT2_CPU_ERRSTATUS0_OFFSET _ULL(0x18800)

#define VT2_CPU_ERRSTATUS0_POS 0
#define VT2_CPU_ERRSTATUS0_WID 32
#define VT2_CPU_ERRSTATUS0_MSK (((_ULL(1) << VT2_CPU_ERRSTATUS0_WID) - _ULL(1)) << VT2_CPU_ERRSTATUS0_POS)

#define VT2_CPU_ERRSTATUS0_ERRSTATUS_POS 0
#define VT2_CPU_ERRSTATUS0_ERRSTATUS_WID 32
#define VT2_CPU_ERRSTATUS0_ERRSTATUS_MSK (((_ULL(1) << VT2_CPU_ERRSTATUS0_ERRSTATUS_WID) - _ULL(1)) << VT2_CPU_ERRSTATUS0_ERRSTATUS_POS)

#define VT2_CPU_ERRSTATUS1_OFFSET _ULL(0x18801)

#define VT2_CPU_ERRSTATUS1_POS 0
#define VT2_CPU_ERRSTATUS1_WID 32
#define VT2_CPU_ERRSTATUS1_MSK (((_ULL(1) << VT2_CPU_ERRSTATUS1_WID) - _ULL(1)) << VT2_CPU_ERRSTATUS1_POS)

#define VT2_CPU_ERRSTATUS1_ERRSTATUS_POS 0
#define VT2_CPU_ERRSTATUS1_ERRSTATUS_WID 32
#define VT2_CPU_ERRSTATUS1_ERRSTATUS_MSK (((_ULL(1) << VT2_CPU_ERRSTATUS1_ERRSTATUS_WID) - _ULL(1)) << VT2_CPU_ERRSTATUS1_ERRSTATUS_POS)

#define VT2_CPU_ERRSTATUS2_OFFSET _ULL(0x18802)

#define VT2_CPU_ERRSTATUS2_POS 0
#define VT2_CPU_ERRSTATUS2_WID 32
#define VT2_CPU_ERRSTATUS2_MSK (((_ULL(1) << VT2_CPU_ERRSTATUS2_WID) - _ULL(1)) << VT2_CPU_ERRSTATUS2_POS)

#define VT2_CPU_ERRSTATUS2_ERRSTATUS_POS 0
#define VT2_CPU_ERRSTATUS2_ERRSTATUS_WID 32
#define VT2_CPU_ERRSTATUS2_ERRSTATUS_MSK (((_ULL(1) << VT2_CPU_ERRSTATUS2_ERRSTATUS_WID) - _ULL(1)) << VT2_CPU_ERRSTATUS2_ERRSTATUS_POS)

#define VT2_CPU_ERRSTATUS3_OFFSET _ULL(0x18803)

#define VT2_CPU_ERRSTATUS3_POS 0
#define VT2_CPU_ERRSTATUS3_WID 32
#define VT2_CPU_ERRSTATUS3_MSK (((_ULL(1) << VT2_CPU_ERRSTATUS3_WID) - _ULL(1)) << VT2_CPU_ERRSTATUS3_POS)

#define VT2_CPU_ERRSTATUS3_ERRSTATUS_POS 0
#define VT2_CPU_ERRSTATUS3_ERRSTATUS_WID 32
#define VT2_CPU_ERRSTATUS3_ERRSTATUS_MSK (((_ULL(1) << VT2_CPU_ERRSTATUS3_ERRSTATUS_WID) - _ULL(1)) << VT2_CPU_ERRSTATUS3_ERRSTATUS_POS)

#define VT2_CPU_ERRSTATUS4_OFFSET _ULL(0x18804)

#define VT2_CPU_ERRSTATUS4_POS 0
#define VT2_CPU_ERRSTATUS4_WID 32
#define VT2_CPU_ERRSTATUS4_MSK (((_ULL(1) << VT2_CPU_ERRSTATUS4_WID) - _ULL(1)) << VT2_CPU_ERRSTATUS4_POS)

#define VT2_CPU_ERRSTATUS4_ERRSTATUS_POS 0
#define VT2_CPU_ERRSTATUS4_ERRSTATUS_WID 32
#define VT2_CPU_ERRSTATUS4_ERRSTATUS_MSK (((_ULL(1) << VT2_CPU_ERRSTATUS4_ERRSTATUS_WID) - _ULL(1)) << VT2_CPU_ERRSTATUS4_ERRSTATUS_POS)

#define VT2_CPU_POWERESTIMATIONCOUNTER_OFFSET _ULL(0x18c00)

#define VT2_CPU_POWERESTIMATIONCOUNTER_POS 0
#define VT2_CPU_POWERESTIMATIONCOUNTER_WID 32
#define VT2_CPU_POWERESTIMATIONCOUNTER_MSK (((_ULL(1) << VT2_CPU_POWERESTIMATIONCOUNTER_WID) - _ULL(1)) << VT2_CPU_POWERESTIMATIONCOUNTER_POS)

#define VT2_CPU_POWERESTIMATIONCOUNTER_UNDERFLOW_POS 0
#define VT2_CPU_POWERESTIMATIONCOUNTER_UNDERFLOW_WID 1
#define VT2_CPU_POWERESTIMATIONCOUNTER_UNDERFLOW_MSK (((_ULL(1) << VT2_CPU_POWERESTIMATIONCOUNTER_UNDERFLOW_WID) - _ULL(1)) << VT2_CPU_POWERESTIMATIONCOUNTER_UNDERFLOW_POS)
#define VT2_CPU_POWERESTIMATIONCOUNTER_SAMPLEID_POS 1
#define VT2_CPU_POWERESTIMATIONCOUNTER_SAMPLEID_WID 3
#define VT2_CPU_POWERESTIMATIONCOUNTER_SAMPLEID_MSK (((_ULL(1) << VT2_CPU_POWERESTIMATIONCOUNTER_SAMPLEID_WID) - _ULL(1)) << VT2_CPU_POWERESTIMATIONCOUNTER_SAMPLEID_POS)
#define VT2_CPU_POWERESTIMATIONCOUNTER_COUNTER_POS 4
#define VT2_CPU_POWERESTIMATIONCOUNTER_COUNTER_WID 28
#define VT2_CPU_POWERESTIMATIONCOUNTER_COUNTER_MSK (((_ULL(1) << VT2_CPU_POWERESTIMATIONCOUNTER_COUNTER_WID) - _ULL(1)) << VT2_CPU_POWERESTIMATIONCOUNTER_COUNTER_POS)

#define VT2_CPU_POWERESTIMATIONCONTROL_OFFSET _ULL(0x18c01)

#define VT2_CPU_POWERESTIMATIONCONTROL_POS 0
#define VT2_CPU_POWERESTIMATIONCONTROL_WID 3
#define VT2_CPU_POWERESTIMATIONCONTROL_MSK (((_ULL(1) << VT2_CPU_POWERESTIMATIONCONTROL_WID) - _ULL(1)) << VT2_CPU_POWERESTIMATIONCONTROL_POS)

#define VT2_CPU_POWERESTIMATIONCONTROL_INTERVAL_POS 0
#define VT2_CPU_POWERESTIMATIONCONTROL_INTERVAL_WID 3
#define VT2_CPU_POWERESTIMATIONCONTROL_INTERVAL_MSK (((_ULL(1) << VT2_CPU_POWERESTIMATIONCONTROL_INTERVAL_WID) - _ULL(1)) << VT2_CPU_POWERESTIMATIONCONTROL_INTERVAL_POS)

#define VT2_CPU_POWERESTIMATIONSTATUS_OFFSET _ULL(0x18c02)

#define VT2_CPU_POWERESTIMATIONSTATUS_POS 0
#define VT2_CPU_POWERESTIMATIONSTATUS_WID 1
#define VT2_CPU_POWERESTIMATIONSTATUS_MSK (((_ULL(1) << VT2_CPU_POWERESTIMATIONSTATUS_WID) - _ULL(1)) << VT2_CPU_POWERESTIMATIONSTATUS_POS)

#define VT2_CPU_POWERESTIMATIONSTATUS_OVERFLOW_POS 0
#define VT2_CPU_POWERESTIMATIONSTATUS_OVERFLOW_WID 1
#define VT2_CPU_POWERESTIMATIONSTATUS_OVERFLOW_MSK (((_ULL(1) << VT2_CPU_POWERESTIMATIONSTATUS_OVERFLOW_WID) - _ULL(1)) << VT2_CPU_POWERESTIMATIONSTATUS_OVERFLOW_POS)

#define VT2_CPU_CPURSTCTL_OFFSET _ULL(0x71000)

#define VT2_CPU_CPURSTCTL_POS 0
#define VT2_CPU_CPURSTCTL_WID 8
#define VT2_CPU_CPURSTCTL_MSK (((_ULL(1) << VT2_CPU_CPURSTCTL_WID) - _ULL(1)) << VT2_CPU_CPURSTCTL_POS)

#define VT2_CPU_CPURSTCTL_HARDRESET_POS 0
#define VT2_CPU_CPURSTCTL_HARDRESET_WID 1
#define VT2_CPU_CPURSTCTL_HARDRESET_MSK (((_ULL(1) << VT2_CPU_CPURSTCTL_HARDRESET_WID) - _ULL(1)) << VT2_CPU_CPURSTCTL_HARDRESET_POS)
#define VT2_CPU_CPURSTCTL_HARDRESETDONE_POS 1
#define VT2_CPU_CPURSTCTL_HARDRESETDONE_WID 1
#define VT2_CPU_CPURSTCTL_HARDRESETDONE_MSK (((_ULL(1) << VT2_CPU_CPURSTCTL_HARDRESETDONE_WID) - _ULL(1)) << VT2_CPU_CPURSTCTL_HARDRESETDONE_POS)
#define VT2_CPU_CPURSTCTL_SOFTRESETREQUEST_POS 2
#define VT2_CPU_CPURSTCTL_SOFTRESETREQUEST_WID 1
#define VT2_CPU_CPURSTCTL_SOFTRESETREQUEST_MSK (((_ULL(1) << VT2_CPU_CPURSTCTL_SOFTRESETREQUEST_WID) - _ULL(1)) << VT2_CPU_CPURSTCTL_SOFTRESETREQUEST_POS)
#define VT2_CPU_CPURSTCTL_SOFTRESETDONE_POS 3
#define VT2_CPU_CPURSTCTL_SOFTRESETDONE_WID 1
#define VT2_CPU_CPURSTCTL_SOFTRESETDONE_MSK (((_ULL(1) << VT2_CPU_CPURSTCTL_SOFTRESETDONE_WID) - _ULL(1)) << VT2_CPU_CPURSTCTL_SOFTRESETDONE_POS)
#define VT2_CPU_CPURSTCTL_STARTRAMINIT_POS 4
#define VT2_CPU_CPURSTCTL_STARTRAMINIT_WID 1
#define VT2_CPU_CPURSTCTL_STARTRAMINIT_MSK (((_ULL(1) << VT2_CPU_CPURSTCTL_STARTRAMINIT_WID) - _ULL(1)) << VT2_CPU_CPURSTCTL_STARTRAMINIT_POS)
#define VT2_CPU_CPURSTCTL_RAMINTDONE_POS 5
#define VT2_CPU_CPURSTCTL_RAMINTDONE_WID 1
#define VT2_CPU_CPURSTCTL_RAMINTDONE_MSK (((_ULL(1) << VT2_CPU_CPURSTCTL_RAMINTDONE_WID) - _ULL(1)) << VT2_CPU_CPURSTCTL_RAMINTDONE_POS)
#define VT2_CPU_CPURSTCTL_START_POS 6
#define VT2_CPU_CPURSTCTL_START_WID 1
#define VT2_CPU_CPURSTCTL_START_MSK (((_ULL(1) << VT2_CPU_CPURSTCTL_START_WID) - _ULL(1)) << VT2_CPU_CPURSTCTL_START_POS)
#define VT2_CPU_CPURSTCTL_REGBUSENABLE_POS 7
#define VT2_CPU_CPURSTCTL_REGBUSENABLE_WID 1
#define VT2_CPU_CPURSTCTL_REGBUSENABLE_MSK (((_ULL(1) << VT2_CPU_CPURSTCTL_REGBUSENABLE_WID) - _ULL(1)) << VT2_CPU_CPURSTCTL_REGBUSENABLE_POS)

#define VT2_CPU_CPUCLKCTL_OFFSET _ULL(0x71001)

#define VT2_CPU_CPUCLKCTL_POS 0
#define VT2_CPU_CPUCLKCTL_WID 15
#define VT2_CPU_CPUCLKCTL_MSK (((_ULL(1) << VT2_CPU_CPUCLKCTL_WID) - _ULL(1)) << VT2_CPU_CPUCLKCTL_POS)

#define VT2_CPU_CPUCLKCTL_CLKGATEREN_POS 0
#define VT2_CPU_CPUCLKCTL_CLKGATEREN_WID 1
#define VT2_CPU_CPUCLKCTL_CLKGATEREN_MSK (((_ULL(1) << VT2_CPU_CPUCLKCTL_CLKGATEREN_WID) - _ULL(1)) << VT2_CPU_CPUCLKCTL_CLKGATEREN_POS)
#define VT2_CPU_CPUCLKCTL_CLKGATEROVRD_POS 1
#define VT2_CPU_CPUCLKCTL_CLKGATEROVRD_WID 1
#define VT2_CPU_CPUCLKCTL_CLKGATEROVRD_MSK (((_ULL(1) << VT2_CPU_CPUCLKCTL_CLKGATEROVRD_WID) - _ULL(1)) << VT2_CPU_CPUCLKCTL_CLKGATEROVRD_POS)
#define VT2_CPU_CPUCLKCTL_CLKFREQDIV_POS 2
#define VT2_CPU_CPUCLKCTL_CLKFREQDIV_WID 5
#define VT2_CPU_CPUCLKCTL_CLKFREQDIV_MSK (((_ULL(1) << VT2_CPU_CPUCLKCTL_CLKFREQDIV_WID) - _ULL(1)) << VT2_CPU_CPUCLKCTL_CLKFREQDIV_POS)
#define VT2_CPU_CPUCLKCTL_CLKFREQRAMPUPSTEPDLY_POS 7
#define VT2_CPU_CPUCLKCTL_CLKFREQRAMPUPSTEPDLY_WID 4
#define VT2_CPU_CPUCLKCTL_CLKFREQRAMPUPSTEPDLY_MSK (((_ULL(1) << VT2_CPU_CPUCLKCTL_CLKFREQRAMPUPSTEPDLY_WID) - _ULL(1)) << VT2_CPU_CPUCLKCTL_CLKFREQRAMPUPSTEPDLY_POS)
#define VT2_CPU_CPUCLKCTL_CLKFREQRAMPDNSTEPDLY_POS 11
#define VT2_CPU_CPUCLKCTL_CLKFREQRAMPDNSTEPDLY_WID 4
#define VT2_CPU_CPUCLKCTL_CLKFREQRAMPDNSTEPDLY_MSK (((_ULL(1) << VT2_CPU_CPUCLKCTL_CLKFREQRAMPDNSTEPDLY_WID) - _ULL(1)) << VT2_CPU_CPUCLKCTL_CLKFREQRAMPDNSTEPDLY_POS)

#define VT2_CPU_CPUCLKSTAT_OFFSET _ULL(0x71002)

#define VT2_CPU_CPUCLKSTAT_POS 0
#define VT2_CPU_CPUCLKSTAT_WID 5
#define VT2_CPU_CPUCLKSTAT_MSK (((_ULL(1) << VT2_CPU_CPUCLKSTAT_WID) - _ULL(1)) << VT2_CPU_CPUCLKSTAT_POS)

#define VT2_CPU_CPUCLKSTAT_CPUQUIESCED_POS 0
#define VT2_CPU_CPUCLKSTAT_CPUQUIESCED_WID 1
#define VT2_CPU_CPUCLKSTAT_CPUQUIESCED_MSK (((_ULL(1) << VT2_CPU_CPUCLKSTAT_CPUQUIESCED_WID) - _ULL(1)) << VT2_CPU_CPUCLKSTAT_CPUQUIESCED_POS)
#define VT2_CPU_CPUCLKSTAT_ICRQUIESCED_POS 1
#define VT2_CPU_CPUCLKSTAT_ICRQUIESCED_WID 1
#define VT2_CPU_CPUCLKSTAT_ICRQUIESCED_MSK (((_ULL(1) << VT2_CPU_CPUCLKSTAT_ICRQUIESCED_WID) - _ULL(1)) << VT2_CPU_CPUCLKSTAT_ICRQUIESCED_POS)
#define VT2_CPU_CPUCLKSTAT_WAKEEVENT_POS 2
#define VT2_CPU_CPUCLKSTAT_WAKEEVENT_WID 1
#define VT2_CPU_CPUCLKSTAT_WAKEEVENT_MSK (((_ULL(1) << VT2_CPU_CPUCLKSTAT_WAKEEVENT_WID) - _ULL(1)) << VT2_CPU_CPUCLKSTAT_WAKEEVENT_POS)
#define VT2_CPU_CPUCLKSTAT_RUNEVENT_POS 3
#define VT2_CPU_CPUCLKSTAT_RUNEVENT_WID 1
#define VT2_CPU_CPUCLKSTAT_RUNEVENT_MSK (((_ULL(1) << VT2_CPU_CPUCLKSTAT_RUNEVENT_WID) - _ULL(1)) << VT2_CPU_CPUCLKSTAT_RUNEVENT_POS)
#define VT2_CPU_CPUCLKSTAT_CPUCLKSTATECGE_POS 4
#define VT2_CPU_CPUCLKSTAT_CPUCLKSTATECGE_WID 1
#define VT2_CPU_CPUCLKSTAT_CPUCLKSTATECGE_MSK (((_ULL(1) << VT2_CPU_CPUCLKSTAT_CPUCLKSTATECGE_WID) - _ULL(1)) << VT2_CPU_CPUCLKSTAT_CPUCLKSTATECGE_POS)

#define VT2_CPU_CPUPWRCFG_OFFSET _ULL(0x71003)

#define VT2_CPU_CPUPWRCFG_POS 0
#define VT2_CPU_CPUPWRCFG_WID 1
#define VT2_CPU_CPUPWRCFG_MSK (((_ULL(1) << VT2_CPU_CPUPWRCFG_WID) - _ULL(1)) << VT2_CPU_CPUPWRCFG_POS)

#define VT2_CPU_CPUPWRCFG_LSDIS_POS 0
#define VT2_CPU_CPUPWRCFG_LSDIS_WID 1
#define VT2_CPU_CPUPWRCFG_LSDIS_MSK (((_ULL(1) << VT2_CPU_CPUPWRCFG_LSDIS_WID) - _ULL(1)) << VT2_CPU_CPUPWRCFG_LSDIS_POS)

/*
#define VT2_CPU_CPURSTCTL_OFFSET _ULL(0x71400)

#define VT2_CPU_CPURSTCTL_POS 0
#define VT2_CPU_CPURSTCTL_WID 8
#define VT2_CPU_CPURSTCTL_MSK (((_ULL(1) << VT2_CPU_CPURSTCTL_WID) - _ULL(1)) << VT2_CPU_CPURSTCTL_POS)

#define VT2_CPU_CPURSTCTL_HARDRESET_POS 0
#define VT2_CPU_CPURSTCTL_HARDRESET_WID 1
#define VT2_CPU_CPURSTCTL_HARDRESET_MSK (((_ULL(1) << VT2_CPU_CPURSTCTL_HARDRESET_WID) - _ULL(1)) << VT2_CPU_CPURSTCTL_HARDRESET_POS)
#define VT2_CPU_CPURSTCTL_HARDRESETDONE_POS 1
#define VT2_CPU_CPURSTCTL_HARDRESETDONE_WID 1
#define VT2_CPU_CPURSTCTL_HARDRESETDONE_MSK (((_ULL(1) << VT2_CPU_CPURSTCTL_HARDRESETDONE_WID) - _ULL(1)) << VT2_CPU_CPURSTCTL_HARDRESETDONE_POS)
#define VT2_CPU_CPURSTCTL_SOFTRESETREQUEST_POS 2
#define VT2_CPU_CPURSTCTL_SOFTRESETREQUEST_WID 1
#define VT2_CPU_CPURSTCTL_SOFTRESETREQUEST_MSK (((_ULL(1) << VT2_CPU_CPURSTCTL_SOFTRESETREQUEST_WID) - _ULL(1)) << VT2_CPU_CPURSTCTL_SOFTRESETREQUEST_POS)
#define VT2_CPU_CPURSTCTL_SOFTRESETDONE_POS 3
#define VT2_CPU_CPURSTCTL_SOFTRESETDONE_WID 1
#define VT2_CPU_CPURSTCTL_SOFTRESETDONE_MSK (((_ULL(1) << VT2_CPU_CPURSTCTL_SOFTRESETDONE_WID) - _ULL(1)) << VT2_CPU_CPURSTCTL_SOFTRESETDONE_POS)
#define VT2_CPU_CPURSTCTL_STARTRAMINIT_POS 4
#define VT2_CPU_CPURSTCTL_STARTRAMINIT_WID 1
#define VT2_CPU_CPURSTCTL_STARTRAMINIT_MSK (((_ULL(1) << VT2_CPU_CPURSTCTL_STARTRAMINIT_WID) - _ULL(1)) << VT2_CPU_CPURSTCTL_STARTRAMINIT_POS)
#define VT2_CPU_CPURSTCTL_RAMINTDONE_POS 5
#define VT2_CPU_CPURSTCTL_RAMINTDONE_WID 1
#define VT2_CPU_CPURSTCTL_RAMINTDONE_MSK (((_ULL(1) << VT2_CPU_CPURSTCTL_RAMINTDONE_WID) - _ULL(1)) << VT2_CPU_CPURSTCTL_RAMINTDONE_POS)
#define VT2_CPU_CPURSTCTL_START_POS 6
#define VT2_CPU_CPURSTCTL_START_WID 1
#define VT2_CPU_CPURSTCTL_START_MSK (((_ULL(1) << VT2_CPU_CPURSTCTL_START_WID) - _ULL(1)) << VT2_CPU_CPURSTCTL_START_POS)
#define VT2_CPU_CPURSTCTL_REGBUSENABLE_POS 7
#define VT2_CPU_CPURSTCTL_REGBUSENABLE_WID 1
#define VT2_CPU_CPURSTCTL_REGBUSENABLE_MSK (((_ULL(1) << VT2_CPU_CPURSTCTL_REGBUSENABLE_WID) - _ULL(1)) << VT2_CPU_CPURSTCTL_REGBUSENABLE_POS)

#define VT2_CPU_CPUCLKCTL_OFFSET _ULL(0x71401)

#define VT2_CPU_CPUCLKCTL_POS 0
#define VT2_CPU_CPUCLKCTL_WID 15
#define VT2_CPU_CPUCLKCTL_MSK (((_ULL(1) << VT2_CPU_CPUCLKCTL_WID) - _ULL(1)) << VT2_CPU_CPUCLKCTL_POS)

#define VT2_CPU_CPUCLKCTL_CLKGATEREN_POS 0
#define VT2_CPU_CPUCLKCTL_CLKGATEREN_WID 1
#define VT2_CPU_CPUCLKCTL_CLKGATEREN_MSK (((_ULL(1) << VT2_CPU_CPUCLKCTL_CLKGATEREN_WID) - _ULL(1)) << VT2_CPU_CPUCLKCTL_CLKGATEREN_POS)
#define VT2_CPU_CPUCLKCTL_CLKGATEROVRD_POS 1
#define VT2_CPU_CPUCLKCTL_CLKGATEROVRD_WID 1
#define VT2_CPU_CPUCLKCTL_CLKGATEROVRD_MSK (((_ULL(1) << VT2_CPU_CPUCLKCTL_CLKGATEROVRD_WID) - _ULL(1)) << VT2_CPU_CPUCLKCTL_CLKGATEROVRD_POS)
#define VT2_CPU_CPUCLKCTL_CLKFREQDIV_POS 2
#define VT2_CPU_CPUCLKCTL_CLKFREQDIV_WID 5
#define VT2_CPU_CPUCLKCTL_CLKFREQDIV_MSK (((_ULL(1) << VT2_CPU_CPUCLKCTL_CLKFREQDIV_WID) - _ULL(1)) << VT2_CPU_CPUCLKCTL_CLKFREQDIV_POS)
#define VT2_CPU_CPUCLKCTL_CLKFREQRAMPUPSTEPDLY_POS 7
#define VT2_CPU_CPUCLKCTL_CLKFREQRAMPUPSTEPDLY_WID 4
#define VT2_CPU_CPUCLKCTL_CLKFREQRAMPUPSTEPDLY_MSK (((_ULL(1) << VT2_CPU_CPUCLKCTL_CLKFREQRAMPUPSTEPDLY_WID) - _ULL(1)) << VT2_CPU_CPUCLKCTL_CLKFREQRAMPUPSTEPDLY_POS)
#define VT2_CPU_CPUCLKCTL_CLKFREQRAMPDNSTEPDLY_POS 11
#define VT2_CPU_CPUCLKCTL_CLKFREQRAMPDNSTEPDLY_WID 4
#define VT2_CPU_CPUCLKCTL_CLKFREQRAMPDNSTEPDLY_MSK (((_ULL(1) << VT2_CPU_CPUCLKCTL_CLKFREQRAMPDNSTEPDLY_WID) - _ULL(1)) << VT2_CPU_CPUCLKCTL_CLKFREQRAMPDNSTEPDLY_POS)

#define VT2_CPU_CPUCLKSTAT_OFFSET _ULL(0x71402)

#define VT2_CPU_CPUCLKSTAT_POS 0
#define VT2_CPU_CPUCLKSTAT_WID 5
#define VT2_CPU_CPUCLKSTAT_MSK (((_ULL(1) << VT2_CPU_CPUCLKSTAT_WID) - _ULL(1)) << VT2_CPU_CPUCLKSTAT_POS)

#define VT2_CPU_CPUCLKSTAT_CPUQUIESCED_POS 0
#define VT2_CPU_CPUCLKSTAT_CPUQUIESCED_WID 1
#define VT2_CPU_CPUCLKSTAT_CPUQUIESCED_MSK (((_ULL(1) << VT2_CPU_CPUCLKSTAT_CPUQUIESCED_WID) - _ULL(1)) << VT2_CPU_CPUCLKSTAT_CPUQUIESCED_POS)
#define VT2_CPU_CPUCLKSTAT_ICRQUIESCED_POS 1
#define VT2_CPU_CPUCLKSTAT_ICRQUIESCED_WID 1
#define VT2_CPU_CPUCLKSTAT_ICRQUIESCED_MSK (((_ULL(1) << VT2_CPU_CPUCLKSTAT_ICRQUIESCED_WID) - _ULL(1)) << VT2_CPU_CPUCLKSTAT_ICRQUIESCED_POS)
#define VT2_CPU_CPUCLKSTAT_WAKEEVENT_POS 2
#define VT2_CPU_CPUCLKSTAT_WAKEEVENT_WID 1
#define VT2_CPU_CPUCLKSTAT_WAKEEVENT_MSK (((_ULL(1) << VT2_CPU_CPUCLKSTAT_WAKEEVENT_WID) - _ULL(1)) << VT2_CPU_CPUCLKSTAT_WAKEEVENT_POS)
#define VT2_CPU_CPUCLKSTAT_RUNEVENT_POS 3
#define VT2_CPU_CPUCLKSTAT_RUNEVENT_WID 1
#define VT2_CPU_CPUCLKSTAT_RUNEVENT_MSK (((_ULL(1) << VT2_CPU_CPUCLKSTAT_RUNEVENT_WID) - _ULL(1)) << VT2_CPU_CPUCLKSTAT_RUNEVENT_POS)
#define VT2_CPU_CPUCLKSTAT_CPUCLKSTATECGE_POS 4
#define VT2_CPU_CPUCLKSTAT_CPUCLKSTATECGE_WID 1
#define VT2_CPU_CPUCLKSTAT_CPUCLKSTATECGE_MSK (((_ULL(1) << VT2_CPU_CPUCLKSTAT_CPUCLKSTATECGE_WID) - _ULL(1)) << VT2_CPU_CPUCLKSTAT_CPUCLKSTATECGE_POS)

#define VT2_CPU_CPUPWRCFG_OFFSET _ULL(0x71403)

#define VT2_CPU_CPUPWRCFG_POS 0
#define VT2_CPU_CPUPWRCFG_WID 1
#define VT2_CPU_CPUPWRCFG_MSK (((_ULL(1) << VT2_CPU_CPUPWRCFG_WID) - _ULL(1)) << VT2_CPU_CPUPWRCFG_POS)

#define VT2_CPU_CPUPWRCFG_LSDIS_POS 0
#define VT2_CPU_CPUPWRCFG_LSDIS_WID 1
#define VT2_CPU_CPUPWRCFG_LSDIS_MSK (((_ULL(1) << VT2_CPU_CPUPWRCFG_LSDIS_WID) - _ULL(1)) << VT2_CPU_CPUPWRCFG_LSDIS_POS)

#define VT2_CPU_CPURSTCTL_OFFSET _ULL(0x71800)

#define VT2_CPU_CPURSTCTL_POS 0
#define VT2_CPU_CPURSTCTL_WID 8
#define VT2_CPU_CPURSTCTL_MSK (((_ULL(1) << VT2_CPU_CPURSTCTL_WID) - _ULL(1)) << VT2_CPU_CPURSTCTL_POS)

#define VT2_CPU_CPURSTCTL_HARDRESET_POS 0
#define VT2_CPU_CPURSTCTL_HARDRESET_WID 1
#define VT2_CPU_CPURSTCTL_HARDRESET_MSK (((_ULL(1) << VT2_CPU_CPURSTCTL_HARDRESET_WID) - _ULL(1)) << VT2_CPU_CPURSTCTL_HARDRESET_POS)
#define VT2_CPU_CPURSTCTL_HARDRESETDONE_POS 1
#define VT2_CPU_CPURSTCTL_HARDRESETDONE_WID 1
#define VT2_CPU_CPURSTCTL_HARDRESETDONE_MSK (((_ULL(1) << VT2_CPU_CPURSTCTL_HARDRESETDONE_WID) - _ULL(1)) << VT2_CPU_CPURSTCTL_HARDRESETDONE_POS)
#define VT2_CPU_CPURSTCTL_SOFTRESETREQUEST_POS 2
#define VT2_CPU_CPURSTCTL_SOFTRESETREQUEST_WID 1
#define VT2_CPU_CPURSTCTL_SOFTRESETREQUEST_MSK (((_ULL(1) << VT2_CPU_CPURSTCTL_SOFTRESETREQUEST_WID) - _ULL(1)) << VT2_CPU_CPURSTCTL_SOFTRESETREQUEST_POS)
#define VT2_CPU_CPURSTCTL_SOFTRESETDONE_POS 3
#define VT2_CPU_CPURSTCTL_SOFTRESETDONE_WID 1
#define VT2_CPU_CPURSTCTL_SOFTRESETDONE_MSK (((_ULL(1) << VT2_CPU_CPURSTCTL_SOFTRESETDONE_WID) - _ULL(1)) << VT2_CPU_CPURSTCTL_SOFTRESETDONE_POS)
#define VT2_CPU_CPURSTCTL_STARTRAMINIT_POS 4
#define VT2_CPU_CPURSTCTL_STARTRAMINIT_WID 1
#define VT2_CPU_CPURSTCTL_STARTRAMINIT_MSK (((_ULL(1) << VT2_CPU_CPURSTCTL_STARTRAMINIT_WID) - _ULL(1)) << VT2_CPU_CPURSTCTL_STARTRAMINIT_POS)
#define VT2_CPU_CPURSTCTL_RAMINTDONE_POS 5
#define VT2_CPU_CPURSTCTL_RAMINTDONE_WID 1
#define VT2_CPU_CPURSTCTL_RAMINTDONE_MSK (((_ULL(1) << VT2_CPU_CPURSTCTL_RAMINTDONE_WID) - _ULL(1)) << VT2_CPU_CPURSTCTL_RAMINTDONE_POS)
#define VT2_CPU_CPURSTCTL_START_POS 6
#define VT2_CPU_CPURSTCTL_START_WID 1
#define VT2_CPU_CPURSTCTL_START_MSK (((_ULL(1) << VT2_CPU_CPURSTCTL_START_WID) - _ULL(1)) << VT2_CPU_CPURSTCTL_START_POS)
#define VT2_CPU_CPURSTCTL_REGBUSENABLE_POS 7
#define VT2_CPU_CPURSTCTL_REGBUSENABLE_WID 1
#define VT2_CPU_CPURSTCTL_REGBUSENABLE_MSK (((_ULL(1) << VT2_CPU_CPURSTCTL_REGBUSENABLE_WID) - _ULL(1)) << VT2_CPU_CPURSTCTL_REGBUSENABLE_POS)

#define VT2_CPU_CPUCLKCTL_OFFSET _ULL(0x71801)

#define VT2_CPU_CPUCLKCTL_POS 0
#define VT2_CPU_CPUCLKCTL_WID 15
#define VT2_CPU_CPUCLKCTL_MSK (((_ULL(1) << VT2_CPU_CPUCLKCTL_WID) - _ULL(1)) << VT2_CPU_CPUCLKCTL_POS)

#define VT2_CPU_CPUCLKCTL_CLKGATEREN_POS 0
#define VT2_CPU_CPUCLKCTL_CLKGATEREN_WID 1
#define VT2_CPU_CPUCLKCTL_CLKGATEREN_MSK (((_ULL(1) << VT2_CPU_CPUCLKCTL_CLKGATEREN_WID) - _ULL(1)) << VT2_CPU_CPUCLKCTL_CLKGATEREN_POS)
#define VT2_CPU_CPUCLKCTL_CLKGATEROVRD_POS 1
#define VT2_CPU_CPUCLKCTL_CLKGATEROVRD_WID 1
#define VT2_CPU_CPUCLKCTL_CLKGATEROVRD_MSK (((_ULL(1) << VT2_CPU_CPUCLKCTL_CLKGATEROVRD_WID) - _ULL(1)) << VT2_CPU_CPUCLKCTL_CLKGATEROVRD_POS)
#define VT2_CPU_CPUCLKCTL_CLKFREQDIV_POS 2
#define VT2_CPU_CPUCLKCTL_CLKFREQDIV_WID 5
#define VT2_CPU_CPUCLKCTL_CLKFREQDIV_MSK (((_ULL(1) << VT2_CPU_CPUCLKCTL_CLKFREQDIV_WID) - _ULL(1)) << VT2_CPU_CPUCLKCTL_CLKFREQDIV_POS)
#define VT2_CPU_CPUCLKCTL_CLKFREQRAMPUPSTEPDLY_POS 7
#define VT2_CPU_CPUCLKCTL_CLKFREQRAMPUPSTEPDLY_WID 4
#define VT2_CPU_CPUCLKCTL_CLKFREQRAMPUPSTEPDLY_MSK (((_ULL(1) << VT2_CPU_CPUCLKCTL_CLKFREQRAMPUPSTEPDLY_WID) - _ULL(1)) << VT2_CPU_CPUCLKCTL_CLKFREQRAMPUPSTEPDLY_POS)
#define VT2_CPU_CPUCLKCTL_CLKFREQRAMPDNSTEPDLY_POS 11
#define VT2_CPU_CPUCLKCTL_CLKFREQRAMPDNSTEPDLY_WID 4
#define VT2_CPU_CPUCLKCTL_CLKFREQRAMPDNSTEPDLY_MSK (((_ULL(1) << VT2_CPU_CPUCLKCTL_CLKFREQRAMPDNSTEPDLY_WID) - _ULL(1)) << VT2_CPU_CPUCLKCTL_CLKFREQRAMPDNSTEPDLY_POS)

#define VT2_CPU_CPUCLKSTAT_OFFSET _ULL(0x71802)

#define VT2_CPU_CPUCLKSTAT_POS 0
#define VT2_CPU_CPUCLKSTAT_WID 5
#define VT2_CPU_CPUCLKSTAT_MSK (((_ULL(1) << VT2_CPU_CPUCLKSTAT_WID) - _ULL(1)) << VT2_CPU_CPUCLKSTAT_POS)

#define VT2_CPU_CPUCLKSTAT_CPUQUIESCED_POS 0
#define VT2_CPU_CPUCLKSTAT_CPUQUIESCED_WID 1
#define VT2_CPU_CPUCLKSTAT_CPUQUIESCED_MSK (((_ULL(1) << VT2_CPU_CPUCLKSTAT_CPUQUIESCED_WID) - _ULL(1)) << VT2_CPU_CPUCLKSTAT_CPUQUIESCED_POS)
#define VT2_CPU_CPUCLKSTAT_ICRQUIESCED_POS 1
#define VT2_CPU_CPUCLKSTAT_ICRQUIESCED_WID 1
#define VT2_CPU_CPUCLKSTAT_ICRQUIESCED_MSK (((_ULL(1) << VT2_CPU_CPUCLKSTAT_ICRQUIESCED_WID) - _ULL(1)) << VT2_CPU_CPUCLKSTAT_ICRQUIESCED_POS)
#define VT2_CPU_CPUCLKSTAT_WAKEEVENT_POS 2
#define VT2_CPU_CPUCLKSTAT_WAKEEVENT_WID 1
#define VT2_CPU_CPUCLKSTAT_WAKEEVENT_MSK (((_ULL(1) << VT2_CPU_CPUCLKSTAT_WAKEEVENT_WID) - _ULL(1)) << VT2_CPU_CPUCLKSTAT_WAKEEVENT_POS)
#define VT2_CPU_CPUCLKSTAT_RUNEVENT_POS 3
#define VT2_CPU_CPUCLKSTAT_RUNEVENT_WID 1
#define VT2_CPU_CPUCLKSTAT_RUNEVENT_MSK (((_ULL(1) << VT2_CPU_CPUCLKSTAT_RUNEVENT_WID) - _ULL(1)) << VT2_CPU_CPUCLKSTAT_RUNEVENT_POS)
#define VT2_CPU_CPUCLKSTAT_CPUCLKSTATECGE_POS 4
#define VT2_CPU_CPUCLKSTAT_CPUCLKSTATECGE_WID 1
#define VT2_CPU_CPUCLKSTAT_CPUCLKSTATECGE_MSK (((_ULL(1) << VT2_CPU_CPUCLKSTAT_CPUCLKSTATECGE_WID) - _ULL(1)) << VT2_CPU_CPUCLKSTAT_CPUCLKSTATECGE_POS)

#define VT2_CPU_CPUPWRCFG_OFFSET _ULL(0x71803)

#define VT2_CPU_CPUPWRCFG_POS 0
#define VT2_CPU_CPUPWRCFG_WID 1
#define VT2_CPU_CPUPWRCFG_MSK (((_ULL(1) << VT2_CPU_CPUPWRCFG_WID) - _ULL(1)) << VT2_CPU_CPUPWRCFG_POS)

#define VT2_CPU_CPUPWRCFG_LSDIS_POS 0
#define VT2_CPU_CPUPWRCFG_LSDIS_WID 1
#define VT2_CPU_CPUPWRCFG_LSDIS_MSK (((_ULL(1) << VT2_CPU_CPUPWRCFG_LSDIS_WID) - _ULL(1)) << VT2_CPU_CPUPWRCFG_LSDIS_POS)

#define VT2_CPU_CPURSTCTL_OFFSET _ULL(0x71c00)

#define VT2_CPU_CPURSTCTL_POS 0
#define VT2_CPU_CPURSTCTL_WID 8
#define VT2_CPU_CPURSTCTL_MSK (((_ULL(1) << VT2_CPU_CPURSTCTL_WID) - _ULL(1)) << VT2_CPU_CPURSTCTL_POS)

#define VT2_CPU_CPURSTCTL_HARDRESET_POS 0
#define VT2_CPU_CPURSTCTL_HARDRESET_WID 1
#define VT2_CPU_CPURSTCTL_HARDRESET_MSK (((_ULL(1) << VT2_CPU_CPURSTCTL_HARDRESET_WID) - _ULL(1)) << VT2_CPU_CPURSTCTL_HARDRESET_POS)
#define VT2_CPU_CPURSTCTL_HARDRESETDONE_POS 1
#define VT2_CPU_CPURSTCTL_HARDRESETDONE_WID 1
#define VT2_CPU_CPURSTCTL_HARDRESETDONE_MSK (((_ULL(1) << VT2_CPU_CPURSTCTL_HARDRESETDONE_WID) - _ULL(1)) << VT2_CPU_CPURSTCTL_HARDRESETDONE_POS)
#define VT2_CPU_CPURSTCTL_SOFTRESETREQUEST_POS 2
#define VT2_CPU_CPURSTCTL_SOFTRESETREQUEST_WID 1
#define VT2_CPU_CPURSTCTL_SOFTRESETREQUEST_MSK (((_ULL(1) << VT2_CPU_CPURSTCTL_SOFTRESETREQUEST_WID) - _ULL(1)) << VT2_CPU_CPURSTCTL_SOFTRESETREQUEST_POS)
#define VT2_CPU_CPURSTCTL_SOFTRESETDONE_POS 3
#define VT2_CPU_CPURSTCTL_SOFTRESETDONE_WID 1
#define VT2_CPU_CPURSTCTL_SOFTRESETDONE_MSK (((_ULL(1) << VT2_CPU_CPURSTCTL_SOFTRESETDONE_WID) - _ULL(1)) << VT2_CPU_CPURSTCTL_SOFTRESETDONE_POS)
#define VT2_CPU_CPURSTCTL_STARTRAMINIT_POS 4
#define VT2_CPU_CPURSTCTL_STARTRAMINIT_WID 1
#define VT2_CPU_CPURSTCTL_STARTRAMINIT_MSK (((_ULL(1) << VT2_CPU_CPURSTCTL_STARTRAMINIT_WID) - _ULL(1)) << VT2_CPU_CPURSTCTL_STARTRAMINIT_POS)
#define VT2_CPU_CPURSTCTL_RAMINTDONE_POS 5
#define VT2_CPU_CPURSTCTL_RAMINTDONE_WID 1
#define VT2_CPU_CPURSTCTL_RAMINTDONE_MSK (((_ULL(1) << VT2_CPU_CPURSTCTL_RAMINTDONE_WID) - _ULL(1)) << VT2_CPU_CPURSTCTL_RAMINTDONE_POS)
#define VT2_CPU_CPURSTCTL_START_POS 6
#define VT2_CPU_CPURSTCTL_START_WID 1
#define VT2_CPU_CPURSTCTL_START_MSK (((_ULL(1) << VT2_CPU_CPURSTCTL_START_WID) - _ULL(1)) << VT2_CPU_CPURSTCTL_START_POS)
#define VT2_CPU_CPURSTCTL_REGBUSENABLE_POS 7
#define VT2_CPU_CPURSTCTL_REGBUSENABLE_WID 1
#define VT2_CPU_CPURSTCTL_REGBUSENABLE_MSK (((_ULL(1) << VT2_CPU_CPURSTCTL_REGBUSENABLE_WID) - _ULL(1)) << VT2_CPU_CPURSTCTL_REGBUSENABLE_POS)

#define VT2_CPU_CPUCLKCTL_OFFSET _ULL(0x71c01)

#define VT2_CPU_CPUCLKCTL_POS 0
#define VT2_CPU_CPUCLKCTL_WID 15
#define VT2_CPU_CPUCLKCTL_MSK (((_ULL(1) << VT2_CPU_CPUCLKCTL_WID) - _ULL(1)) << VT2_CPU_CPUCLKCTL_POS)

#define VT2_CPU_CPUCLKCTL_CLKGATEREN_POS 0
#define VT2_CPU_CPUCLKCTL_CLKGATEREN_WID 1
#define VT2_CPU_CPUCLKCTL_CLKGATEREN_MSK (((_ULL(1) << VT2_CPU_CPUCLKCTL_CLKGATEREN_WID) - _ULL(1)) << VT2_CPU_CPUCLKCTL_CLKGATEREN_POS)
#define VT2_CPU_CPUCLKCTL_CLKGATEROVRD_POS 1
#define VT2_CPU_CPUCLKCTL_CLKGATEROVRD_WID 1
#define VT2_CPU_CPUCLKCTL_CLKGATEROVRD_MSK (((_ULL(1) << VT2_CPU_CPUCLKCTL_CLKGATEROVRD_WID) - _ULL(1)) << VT2_CPU_CPUCLKCTL_CLKGATEROVRD_POS)
#define VT2_CPU_CPUCLKCTL_CLKFREQDIV_POS 2
#define VT2_CPU_CPUCLKCTL_CLKFREQDIV_WID 5
#define VT2_CPU_CPUCLKCTL_CLKFREQDIV_MSK (((_ULL(1) << VT2_CPU_CPUCLKCTL_CLKFREQDIV_WID) - _ULL(1)) << VT2_CPU_CPUCLKCTL_CLKFREQDIV_POS)
#define VT2_CPU_CPUCLKCTL_CLKFREQRAMPUPSTEPDLY_POS 7
#define VT2_CPU_CPUCLKCTL_CLKFREQRAMPUPSTEPDLY_WID 4
#define VT2_CPU_CPUCLKCTL_CLKFREQRAMPUPSTEPDLY_MSK (((_ULL(1) << VT2_CPU_CPUCLKCTL_CLKFREQRAMPUPSTEPDLY_WID) - _ULL(1)) << VT2_CPU_CPUCLKCTL_CLKFREQRAMPUPSTEPDLY_POS)
#define VT2_CPU_CPUCLKCTL_CLKFREQRAMPDNSTEPDLY_POS 11
#define VT2_CPU_CPUCLKCTL_CLKFREQRAMPDNSTEPDLY_WID 4
#define VT2_CPU_CPUCLKCTL_CLKFREQRAMPDNSTEPDLY_MSK (((_ULL(1) << VT2_CPU_CPUCLKCTL_CLKFREQRAMPDNSTEPDLY_WID) - _ULL(1)) << VT2_CPU_CPUCLKCTL_CLKFREQRAMPDNSTEPDLY_POS)

#define VT2_CPU_CPUCLKSTAT_OFFSET _ULL(0x71c02)

#define VT2_CPU_CPUCLKSTAT_POS 0
#define VT2_CPU_CPUCLKSTAT_WID 5
#define VT2_CPU_CPUCLKSTAT_MSK (((_ULL(1) << VT2_CPU_CPUCLKSTAT_WID) - _ULL(1)) << VT2_CPU_CPUCLKSTAT_POS)

#define VT2_CPU_CPUCLKSTAT_CPUQUIESCED_POS 0
#define VT2_CPU_CPUCLKSTAT_CPUQUIESCED_WID 1
#define VT2_CPU_CPUCLKSTAT_CPUQUIESCED_MSK (((_ULL(1) << VT2_CPU_CPUCLKSTAT_CPUQUIESCED_WID) - _ULL(1)) << VT2_CPU_CPUCLKSTAT_CPUQUIESCED_POS)
#define VT2_CPU_CPUCLKSTAT_ICRQUIESCED_POS 1
#define VT2_CPU_CPUCLKSTAT_ICRQUIESCED_WID 1
#define VT2_CPU_CPUCLKSTAT_ICRQUIESCED_MSK (((_ULL(1) << VT2_CPU_CPUCLKSTAT_ICRQUIESCED_WID) - _ULL(1)) << VT2_CPU_CPUCLKSTAT_ICRQUIESCED_POS)
#define VT2_CPU_CPUCLKSTAT_WAKEEVENT_POS 2
#define VT2_CPU_CPUCLKSTAT_WAKEEVENT_WID 1
#define VT2_CPU_CPUCLKSTAT_WAKEEVENT_MSK (((_ULL(1) << VT2_CPU_CPUCLKSTAT_WAKEEVENT_WID) - _ULL(1)) << VT2_CPU_CPUCLKSTAT_WAKEEVENT_POS)
#define VT2_CPU_CPUCLKSTAT_RUNEVENT_POS 3
#define VT2_CPU_CPUCLKSTAT_RUNEVENT_WID 1
#define VT2_CPU_CPUCLKSTAT_RUNEVENT_MSK (((_ULL(1) << VT2_CPU_CPUCLKSTAT_RUNEVENT_WID) - _ULL(1)) << VT2_CPU_CPUCLKSTAT_RUNEVENT_POS)
#define VT2_CPU_CPUCLKSTAT_CPUCLKSTATECGE_POS 4
#define VT2_CPU_CPUCLKSTAT_CPUCLKSTATECGE_WID 1
#define VT2_CPU_CPUCLKSTAT_CPUCLKSTATECGE_MSK (((_ULL(1) << VT2_CPU_CPUCLKSTAT_CPUCLKSTATECGE_WID) - _ULL(1)) << VT2_CPU_CPUCLKSTAT_CPUCLKSTATECGE_POS)

#define VT2_CPU_CPUPWRCFG_OFFSET _ULL(0x71c03)

#define VT2_CPU_CPUPWRCFG_POS 0
#define VT2_CPU_CPUPWRCFG_WID 1
#define VT2_CPU_CPUPWRCFG_MSK (((_ULL(1) << VT2_CPU_CPUPWRCFG_WID) - _ULL(1)) << VT2_CPU_CPUPWRCFG_POS)

#define VT2_CPU_CPUPWRCFG_LSDIS_POS 0
#define VT2_CPU_CPUPWRCFG_LSDIS_WID 1
#define VT2_CPU_CPUPWRCFG_LSDIS_MSK (((_ULL(1) << VT2_CPU_CPUPWRCFG_LSDIS_WID) - _ULL(1)) << VT2_CPU_CPUPWRCFG_LSDIS_POS)
*/
#endif /* VT2_CPU_CSR_H */
