/* This file is auto-generated. Do not hand edit this file. */

#ifndef VT2_CKGN_MMR_H
#define VT2_CKGN_MMR_H

#ifndef _ULL

#ifdef __ASSEMBLER__
#define _AC(X,Y) X
#else
#define __AC(X,Y) (X##Y)
#define _AC(X,Y) __AC(X,Y)
#endif

#define _ULL(x)  (_AC(x, ULL))
#endif


#define VT2_CKGN_PCLKPLLCTL_OFFSET _ULL(0x0)

#define VT2_CKGN_PCLKPLLCTL_POS 0
#define VT2_CKGN_PCLKPLLCTL_WID 25
#define VT2_CKGN_PCLKPLLCTL_MSK (((_ULL(1) << VT2_CKGN_PCLKPLLCTL_WID) - _ULL(1)) << VT2_CKGN_PCLKPLLCTL_POS)

#define VT2_CKGN_PCLKPLLCTL_FBDIV_POS 0
#define VT2_CKGN_PCLKPLLCTL_FBDIV_WID 12
#define VT2_CKGN_PCLKPLLCTL_FBDIV_MSK (((_ULL(1) << VT2_CKGN_PCLKPLLCTL_FBDIV_WID) - _ULL(1)) << VT2_CKGN_PCLKPLLCTL_FBDIV_POS)
#define VT2_CKGN_PCLKPLLCTL_CLOCKGATE_POS 12
#define VT2_CKGN_PCLKPLLCTL_CLOCKGATE_WID 1
#define VT2_CKGN_PCLKPLLCTL_CLOCKGATE_MSK (((_ULL(1) << VT2_CKGN_PCLKPLLCTL_CLOCKGATE_WID) - _ULL(1)) << VT2_CKGN_PCLKPLLCTL_CLOCKGATE_POS)
#define VT2_CKGN_PCLKPLLCTL_AUXILIARY_POS 13
#define VT2_CKGN_PCLKPLLCTL_AUXILIARY_WID 1
#define VT2_CKGN_PCLKPLLCTL_AUXILIARY_MSK (((_ULL(1) << VT2_CKGN_PCLKPLLCTL_AUXILIARY_WID) - _ULL(1)) << VT2_CKGN_PCLKPLLCTL_AUXILIARY_POS)
#define VT2_CKGN_PCLKPLLCTL_BYPASS_POS 14
#define VT2_CKGN_PCLKPLLCTL_BYPASS_WID 1
#define VT2_CKGN_PCLKPLLCTL_BYPASS_MSK (((_ULL(1) << VT2_CKGN_PCLKPLLCTL_BYPASS_WID) - _ULL(1)) << VT2_CKGN_PCLKPLLCTL_BYPASS_POS)
#define VT2_CKGN_PCLKPLLCTL_PLLEN_POS 15
#define VT2_CKGN_PCLKPLLCTL_PLLEN_WID 1
#define VT2_CKGN_PCLKPLLCTL_PLLEN_MSK (((_ULL(1) << VT2_CKGN_PCLKPLLCTL_PLLEN_WID) - _ULL(1)) << VT2_CKGN_PCLKPLLCTL_PLLEN_POS)
#define VT2_CKGN_PCLKPLLCTL_REFDIV_POS 16
#define VT2_CKGN_PCLKPLLCTL_REFDIV_WID 6
#define VT2_CKGN_PCLKPLLCTL_REFDIV_MSK (((_ULL(1) << VT2_CKGN_PCLKPLLCTL_REFDIV_WID) - _ULL(1)) << VT2_CKGN_PCLKPLLCTL_REFDIV_POS)
#define VT2_CKGN_PCLKPLLCTL_FOUT4PHASEEN_POS 22
#define VT2_CKGN_PCLKPLLCTL_FOUT4PHASEEN_WID 1
#define VT2_CKGN_PCLKPLLCTL_FOUT4PHASEEN_MSK (((_ULL(1) << VT2_CKGN_PCLKPLLCTL_FOUT4PHASEEN_WID) - _ULL(1)) << VT2_CKGN_PCLKPLLCTL_FOUT4PHASEEN_POS)
#define VT2_CKGN_PCLKPLLCTL_FOUTPOSTDIVEN_POS 23
#define VT2_CKGN_PCLKPLLCTL_FOUTPOSTDIVEN_WID 1
#define VT2_CKGN_PCLKPLLCTL_FOUTPOSTDIVEN_MSK (((_ULL(1) << VT2_CKGN_PCLKPLLCTL_FOUTPOSTDIVEN_WID) - _ULL(1)) << VT2_CKGN_PCLKPLLCTL_FOUTPOSTDIVEN_POS)
#define VT2_CKGN_PCLKPLLCTL_FOUTVCOEN_POS 24
#define VT2_CKGN_PCLKPLLCTL_FOUTVCOEN_WID 1
#define VT2_CKGN_PCLKPLLCTL_FOUTVCOEN_MSK (((_ULL(1) << VT2_CKGN_PCLKPLLCTL_FOUTVCOEN_WID) - _ULL(1)) << VT2_CKGN_PCLKPLLCTL_FOUTVCOEN_POS)

#define VT2_CKGN_PCLKPLLCTL2_OFFSET _ULL(0x1)

#define VT2_CKGN_PCLKPLLCTL2_POS 0
#define VT2_CKGN_PCLKPLLCTL2_WID 6
#define VT2_CKGN_PCLKPLLCTL2_MSK (((_ULL(1) << VT2_CKGN_PCLKPLLCTL2_WID) - _ULL(1)) << VT2_CKGN_PCLKPLLCTL2_POS)

#define VT2_CKGN_PCLKPLLCTL2_POSTDIV2_POS 0
#define VT2_CKGN_PCLKPLLCTL2_POSTDIV2_WID 3
#define VT2_CKGN_PCLKPLLCTL2_POSTDIV2_MSK (((_ULL(1) << VT2_CKGN_PCLKPLLCTL2_POSTDIV2_WID) - _ULL(1)) << VT2_CKGN_PCLKPLLCTL2_POSTDIV2_POS)
#define VT2_CKGN_PCLKPLLCTL2_POSTDIV1_POS 3
#define VT2_CKGN_PCLKPLLCTL2_POSTDIV1_WID 3
#define VT2_CKGN_PCLKPLLCTL2_POSTDIV1_MSK (((_ULL(1) << VT2_CKGN_PCLKPLLCTL2_POSTDIV1_WID) - _ULL(1)) << VT2_CKGN_PCLKPLLCTL2_POSTDIV1_POS)

#define VT2_CKGN_PCLKPLLSTATUS_OFFSET _ULL(0x4)

#define VT2_CKGN_PCLKPLLSTATUS_POS 0
#define VT2_CKGN_PCLKPLLSTATUS_WID 5
#define VT2_CKGN_PCLKPLLSTATUS_MSK (((_ULL(1) << VT2_CKGN_PCLKPLLSTATUS_WID) - _ULL(1)) << VT2_CKGN_PCLKPLLSTATUS_POS)

#define VT2_CKGN_PCLKPLLSTATUS_DONE_POS 0
#define VT2_CKGN_PCLKPLLSTATUS_DONE_WID 1
#define VT2_CKGN_PCLKPLLSTATUS_DONE_MSK (((_ULL(1) << VT2_CKGN_PCLKPLLSTATUS_DONE_WID) - _ULL(1)) << VT2_CKGN_PCLKPLLSTATUS_DONE_POS)
#define VT2_CKGN_PCLKPLLSTATUS_LOCKP_POS 1
#define VT2_CKGN_PCLKPLLSTATUS_LOCKP_WID 1
#define VT2_CKGN_PCLKPLLSTATUS_LOCKP_MSK (((_ULL(1) << VT2_CKGN_PCLKPLLSTATUS_LOCKP_WID) - _ULL(1)) << VT2_CKGN_PCLKPLLSTATUS_LOCKP_POS)
#define VT2_CKGN_PCLKPLLSTATUS_LOCKF_POS 2
#define VT2_CKGN_PCLKPLLSTATUS_LOCKF_WID 1
#define VT2_CKGN_PCLKPLLSTATUS_LOCKF_MSK (((_ULL(1) << VT2_CKGN_PCLKPLLSTATUS_LOCKF_WID) - _ULL(1)) << VT2_CKGN_PCLKPLLSTATUS_LOCKF_POS)
#define VT2_CKGN_PCLKPLLSTATUS_CLOCKGATE_POS 3
#define VT2_CKGN_PCLKPLLSTATUS_CLOCKGATE_WID 1
#define VT2_CKGN_PCLKPLLSTATUS_CLOCKGATE_MSK (((_ULL(1) << VT2_CKGN_PCLKPLLSTATUS_CLOCKGATE_WID) - _ULL(1)) << VT2_CKGN_PCLKPLLSTATUS_CLOCKGATE_POS)
#define VT2_CKGN_PCLKPLLSTATUS_AUXILIARY_POS 4
#define VT2_CKGN_PCLKPLLSTATUS_AUXILIARY_WID 1
#define VT2_CKGN_PCLKPLLSTATUS_AUXILIARY_MSK (((_ULL(1) << VT2_CKGN_PCLKPLLSTATUS_AUXILIARY_WID) - _ULL(1)) << VT2_CKGN_PCLKPLLSTATUS_AUXILIARY_POS)

#define VT2_CKGN_NCLKPLLCTL_OFFSET _ULL(0x8)

#define VT2_CKGN_NCLKPLLCTL_POS 0
#define VT2_CKGN_NCLKPLLCTL_WID 25
#define VT2_CKGN_NCLKPLLCTL_MSK (((_ULL(1) << VT2_CKGN_NCLKPLLCTL_WID) - _ULL(1)) << VT2_CKGN_NCLKPLLCTL_POS)

#define VT2_CKGN_NCLKPLLCTL_FBDIV_POS 0
#define VT2_CKGN_NCLKPLLCTL_FBDIV_WID 12
#define VT2_CKGN_NCLKPLLCTL_FBDIV_MSK (((_ULL(1) << VT2_CKGN_NCLKPLLCTL_FBDIV_WID) - _ULL(1)) << VT2_CKGN_NCLKPLLCTL_FBDIV_POS)
#define VT2_CKGN_NCLKPLLCTL_CLOCKGATE_POS 12
#define VT2_CKGN_NCLKPLLCTL_CLOCKGATE_WID 1
#define VT2_CKGN_NCLKPLLCTL_CLOCKGATE_MSK (((_ULL(1) << VT2_CKGN_NCLKPLLCTL_CLOCKGATE_WID) - _ULL(1)) << VT2_CKGN_NCLKPLLCTL_CLOCKGATE_POS)
#define VT2_CKGN_NCLKPLLCTL_AUXILIARY_POS 13
#define VT2_CKGN_NCLKPLLCTL_AUXILIARY_WID 1
#define VT2_CKGN_NCLKPLLCTL_AUXILIARY_MSK (((_ULL(1) << VT2_CKGN_NCLKPLLCTL_AUXILIARY_WID) - _ULL(1)) << VT2_CKGN_NCLKPLLCTL_AUXILIARY_POS)
#define VT2_CKGN_NCLKPLLCTL_BYPASS_POS 14
#define VT2_CKGN_NCLKPLLCTL_BYPASS_WID 1
#define VT2_CKGN_NCLKPLLCTL_BYPASS_MSK (((_ULL(1) << VT2_CKGN_NCLKPLLCTL_BYPASS_WID) - _ULL(1)) << VT2_CKGN_NCLKPLLCTL_BYPASS_POS)
#define VT2_CKGN_NCLKPLLCTL_PLLEN_POS 15
#define VT2_CKGN_NCLKPLLCTL_PLLEN_WID 1
#define VT2_CKGN_NCLKPLLCTL_PLLEN_MSK (((_ULL(1) << VT2_CKGN_NCLKPLLCTL_PLLEN_WID) - _ULL(1)) << VT2_CKGN_NCLKPLLCTL_PLLEN_POS)
#define VT2_CKGN_NCLKPLLCTL_REFDIV_POS 16
#define VT2_CKGN_NCLKPLLCTL_REFDIV_WID 6
#define VT2_CKGN_NCLKPLLCTL_REFDIV_MSK (((_ULL(1) << VT2_CKGN_NCLKPLLCTL_REFDIV_WID) - _ULL(1)) << VT2_CKGN_NCLKPLLCTL_REFDIV_POS)
#define VT2_CKGN_NCLKPLLCTL_FOUT4PHASEEN_POS 22
#define VT2_CKGN_NCLKPLLCTL_FOUT4PHASEEN_WID 1
#define VT2_CKGN_NCLKPLLCTL_FOUT4PHASEEN_MSK (((_ULL(1) << VT2_CKGN_NCLKPLLCTL_FOUT4PHASEEN_WID) - _ULL(1)) << VT2_CKGN_NCLKPLLCTL_FOUT4PHASEEN_POS)
#define VT2_CKGN_NCLKPLLCTL_FOUTPOSTDIVEN_POS 23
#define VT2_CKGN_NCLKPLLCTL_FOUTPOSTDIVEN_WID 1
#define VT2_CKGN_NCLKPLLCTL_FOUTPOSTDIVEN_MSK (((_ULL(1) << VT2_CKGN_NCLKPLLCTL_FOUTPOSTDIVEN_WID) - _ULL(1)) << VT2_CKGN_NCLKPLLCTL_FOUTPOSTDIVEN_POS)
#define VT2_CKGN_NCLKPLLCTL_FOUTVCOEN_POS 24
#define VT2_CKGN_NCLKPLLCTL_FOUTVCOEN_WID 1
#define VT2_CKGN_NCLKPLLCTL_FOUTVCOEN_MSK (((_ULL(1) << VT2_CKGN_NCLKPLLCTL_FOUTVCOEN_WID) - _ULL(1)) << VT2_CKGN_NCLKPLLCTL_FOUTVCOEN_POS)

#define VT2_CKGN_NCLKPLLCTL2_OFFSET _ULL(0x9)

#define VT2_CKGN_NCLKPLLCTL2_POS 0
#define VT2_CKGN_NCLKPLLCTL2_WID 6
#define VT2_CKGN_NCLKPLLCTL2_MSK (((_ULL(1) << VT2_CKGN_NCLKPLLCTL2_WID) - _ULL(1)) << VT2_CKGN_NCLKPLLCTL2_POS)

#define VT2_CKGN_NCLKPLLCTL2_POSTDIV2_POS 0
#define VT2_CKGN_NCLKPLLCTL2_POSTDIV2_WID 3
#define VT2_CKGN_NCLKPLLCTL2_POSTDIV2_MSK (((_ULL(1) << VT2_CKGN_NCLKPLLCTL2_POSTDIV2_WID) - _ULL(1)) << VT2_CKGN_NCLKPLLCTL2_POSTDIV2_POS)
#define VT2_CKGN_NCLKPLLCTL2_POSTDIV1_POS 3
#define VT2_CKGN_NCLKPLLCTL2_POSTDIV1_WID 3
#define VT2_CKGN_NCLKPLLCTL2_POSTDIV1_MSK (((_ULL(1) << VT2_CKGN_NCLKPLLCTL2_POSTDIV1_WID) - _ULL(1)) << VT2_CKGN_NCLKPLLCTL2_POSTDIV1_POS)

#define VT2_CKGN_NCLKPLLSTATUS_OFFSET _ULL(0xc)

#define VT2_CKGN_NCLKPLLSTATUS_POS 0
#define VT2_CKGN_NCLKPLLSTATUS_WID 5
#define VT2_CKGN_NCLKPLLSTATUS_MSK (((_ULL(1) << VT2_CKGN_NCLKPLLSTATUS_WID) - _ULL(1)) << VT2_CKGN_NCLKPLLSTATUS_POS)

#define VT2_CKGN_NCLKPLLSTATUS_DONE_POS 0
#define VT2_CKGN_NCLKPLLSTATUS_DONE_WID 1
#define VT2_CKGN_NCLKPLLSTATUS_DONE_MSK (((_ULL(1) << VT2_CKGN_NCLKPLLSTATUS_DONE_WID) - _ULL(1)) << VT2_CKGN_NCLKPLLSTATUS_DONE_POS)
#define VT2_CKGN_NCLKPLLSTATUS_LOCKP_POS 1
#define VT2_CKGN_NCLKPLLSTATUS_LOCKP_WID 1
#define VT2_CKGN_NCLKPLLSTATUS_LOCKP_MSK (((_ULL(1) << VT2_CKGN_NCLKPLLSTATUS_LOCKP_WID) - _ULL(1)) << VT2_CKGN_NCLKPLLSTATUS_LOCKP_POS)
#define VT2_CKGN_NCLKPLLSTATUS_LOCKF_POS 2
#define VT2_CKGN_NCLKPLLSTATUS_LOCKF_WID 1
#define VT2_CKGN_NCLKPLLSTATUS_LOCKF_MSK (((_ULL(1) << VT2_CKGN_NCLKPLLSTATUS_LOCKF_WID) - _ULL(1)) << VT2_CKGN_NCLKPLLSTATUS_LOCKF_POS)
#define VT2_CKGN_NCLKPLLSTATUS_CLOCKGATE_POS 3
#define VT2_CKGN_NCLKPLLSTATUS_CLOCKGATE_WID 1
#define VT2_CKGN_NCLKPLLSTATUS_CLOCKGATE_MSK (((_ULL(1) << VT2_CKGN_NCLKPLLSTATUS_CLOCKGATE_WID) - _ULL(1)) << VT2_CKGN_NCLKPLLSTATUS_CLOCKGATE_POS)
#define VT2_CKGN_NCLKPLLSTATUS_AUXILIARY_POS 4
#define VT2_CKGN_NCLKPLLSTATUS_AUXILIARY_WID 1
#define VT2_CKGN_NCLKPLLSTATUS_AUXILIARY_MSK (((_ULL(1) << VT2_CKGN_NCLKPLLSTATUS_AUXILIARY_WID) - _ULL(1)) << VT2_CKGN_NCLKPLLSTATUS_AUXILIARY_POS)

#define VT2_CKGN_CCLKPLLCTL_OFFSET _ULL(0x10)

#define VT2_CKGN_CCLKPLLCTL_POS 0
#define VT2_CKGN_CCLKPLLCTL_WID 25
#define VT2_CKGN_CCLKPLLCTL_MSK (((_ULL(1) << VT2_CKGN_CCLKPLLCTL_WID) - _ULL(1)) << VT2_CKGN_CCLKPLLCTL_POS)

#define VT2_CKGN_CCLKPLLCTL_FBDIV_POS 0
#define VT2_CKGN_CCLKPLLCTL_FBDIV_WID 12
#define VT2_CKGN_CCLKPLLCTL_FBDIV_MSK (((_ULL(1) << VT2_CKGN_CCLKPLLCTL_FBDIV_WID) - _ULL(1)) << VT2_CKGN_CCLKPLLCTL_FBDIV_POS)
#define VT2_CKGN_CCLKPLLCTL_CLOCKGATE_POS 12
#define VT2_CKGN_CCLKPLLCTL_CLOCKGATE_WID 1
#define VT2_CKGN_CCLKPLLCTL_CLOCKGATE_MSK (((_ULL(1) << VT2_CKGN_CCLKPLLCTL_CLOCKGATE_WID) - _ULL(1)) << VT2_CKGN_CCLKPLLCTL_CLOCKGATE_POS)
#define VT2_CKGN_CCLKPLLCTL_AUXILIARY_POS 13
#define VT2_CKGN_CCLKPLLCTL_AUXILIARY_WID 1
#define VT2_CKGN_CCLKPLLCTL_AUXILIARY_MSK (((_ULL(1) << VT2_CKGN_CCLKPLLCTL_AUXILIARY_WID) - _ULL(1)) << VT2_CKGN_CCLKPLLCTL_AUXILIARY_POS)
#define VT2_CKGN_CCLKPLLCTL_BYPASS_POS 14
#define VT2_CKGN_CCLKPLLCTL_BYPASS_WID 1
#define VT2_CKGN_CCLKPLLCTL_BYPASS_MSK (((_ULL(1) << VT2_CKGN_CCLKPLLCTL_BYPASS_WID) - _ULL(1)) << VT2_CKGN_CCLKPLLCTL_BYPASS_POS)
#define VT2_CKGN_CCLKPLLCTL_PLLEN_POS 15
#define VT2_CKGN_CCLKPLLCTL_PLLEN_WID 1
#define VT2_CKGN_CCLKPLLCTL_PLLEN_MSK (((_ULL(1) << VT2_CKGN_CCLKPLLCTL_PLLEN_WID) - _ULL(1)) << VT2_CKGN_CCLKPLLCTL_PLLEN_POS)
#define VT2_CKGN_CCLKPLLCTL_REFDIV_POS 16
#define VT2_CKGN_CCLKPLLCTL_REFDIV_WID 6
#define VT2_CKGN_CCLKPLLCTL_REFDIV_MSK (((_ULL(1) << VT2_CKGN_CCLKPLLCTL_REFDIV_WID) - _ULL(1)) << VT2_CKGN_CCLKPLLCTL_REFDIV_POS)
#define VT2_CKGN_CCLKPLLCTL_FOUT4PHASEEN_POS 22
#define VT2_CKGN_CCLKPLLCTL_FOUT4PHASEEN_WID 1
#define VT2_CKGN_CCLKPLLCTL_FOUT4PHASEEN_MSK (((_ULL(1) << VT2_CKGN_CCLKPLLCTL_FOUT4PHASEEN_WID) - _ULL(1)) << VT2_CKGN_CCLKPLLCTL_FOUT4PHASEEN_POS)
#define VT2_CKGN_CCLKPLLCTL_FOUTPOSTDIVEN_POS 23
#define VT2_CKGN_CCLKPLLCTL_FOUTPOSTDIVEN_WID 1
#define VT2_CKGN_CCLKPLLCTL_FOUTPOSTDIVEN_MSK (((_ULL(1) << VT2_CKGN_CCLKPLLCTL_FOUTPOSTDIVEN_WID) - _ULL(1)) << VT2_CKGN_CCLKPLLCTL_FOUTPOSTDIVEN_POS)
#define VT2_CKGN_CCLKPLLCTL_FOUTVCOEN_POS 24
#define VT2_CKGN_CCLKPLLCTL_FOUTVCOEN_WID 1
#define VT2_CKGN_CCLKPLLCTL_FOUTVCOEN_MSK (((_ULL(1) << VT2_CKGN_CCLKPLLCTL_FOUTVCOEN_WID) - _ULL(1)) << VT2_CKGN_CCLKPLLCTL_FOUTVCOEN_POS)

#define VT2_CKGN_CCLKPLLCTL2_OFFSET _ULL(0x11)

#define VT2_CKGN_CCLKPLLCTL2_POS 0
#define VT2_CKGN_CCLKPLLCTL2_WID 6
#define VT2_CKGN_CCLKPLLCTL2_MSK (((_ULL(1) << VT2_CKGN_CCLKPLLCTL2_WID) - _ULL(1)) << VT2_CKGN_CCLKPLLCTL2_POS)

#define VT2_CKGN_CCLKPLLCTL2_POSTDIV2_POS 0
#define VT2_CKGN_CCLKPLLCTL2_POSTDIV2_WID 3
#define VT2_CKGN_CCLKPLLCTL2_POSTDIV2_MSK (((_ULL(1) << VT2_CKGN_CCLKPLLCTL2_POSTDIV2_WID) - _ULL(1)) << VT2_CKGN_CCLKPLLCTL2_POSTDIV2_POS)
#define VT2_CKGN_CCLKPLLCTL2_POSTDIV1_POS 3
#define VT2_CKGN_CCLKPLLCTL2_POSTDIV1_WID 3
#define VT2_CKGN_CCLKPLLCTL2_POSTDIV1_MSK (((_ULL(1) << VT2_CKGN_CCLKPLLCTL2_POSTDIV1_WID) - _ULL(1)) << VT2_CKGN_CCLKPLLCTL2_POSTDIV1_POS)

#define VT2_CKGN_CCLKPLLSTATUS_OFFSET _ULL(0x14)

#define VT2_CKGN_CCLKPLLSTATUS_POS 0
#define VT2_CKGN_CCLKPLLSTATUS_WID 5
#define VT2_CKGN_CCLKPLLSTATUS_MSK (((_ULL(1) << VT2_CKGN_CCLKPLLSTATUS_WID) - _ULL(1)) << VT2_CKGN_CCLKPLLSTATUS_POS)

#define VT2_CKGN_CCLKPLLSTATUS_DONE_POS 0
#define VT2_CKGN_CCLKPLLSTATUS_DONE_WID 1
#define VT2_CKGN_CCLKPLLSTATUS_DONE_MSK (((_ULL(1) << VT2_CKGN_CCLKPLLSTATUS_DONE_WID) - _ULL(1)) << VT2_CKGN_CCLKPLLSTATUS_DONE_POS)
#define VT2_CKGN_CCLKPLLSTATUS_LOCKP_POS 1
#define VT2_CKGN_CCLKPLLSTATUS_LOCKP_WID 1
#define VT2_CKGN_CCLKPLLSTATUS_LOCKP_MSK (((_ULL(1) << VT2_CKGN_CCLKPLLSTATUS_LOCKP_WID) - _ULL(1)) << VT2_CKGN_CCLKPLLSTATUS_LOCKP_POS)
#define VT2_CKGN_CCLKPLLSTATUS_LOCKF_POS 2
#define VT2_CKGN_CCLKPLLSTATUS_LOCKF_WID 1
#define VT2_CKGN_CCLKPLLSTATUS_LOCKF_MSK (((_ULL(1) << VT2_CKGN_CCLKPLLSTATUS_LOCKF_WID) - _ULL(1)) << VT2_CKGN_CCLKPLLSTATUS_LOCKF_POS)
#define VT2_CKGN_CCLKPLLSTATUS_CLOCKGATE_POS 3
#define VT2_CKGN_CCLKPLLSTATUS_CLOCKGATE_WID 1
#define VT2_CKGN_CCLKPLLSTATUS_CLOCKGATE_MSK (((_ULL(1) << VT2_CKGN_CCLKPLLSTATUS_CLOCKGATE_WID) - _ULL(1)) << VT2_CKGN_CCLKPLLSTATUS_CLOCKGATE_POS)
#define VT2_CKGN_CCLKPLLSTATUS_AUXILIARY_POS 4
#define VT2_CKGN_CCLKPLLSTATUS_AUXILIARY_WID 1
#define VT2_CKGN_CCLKPLLSTATUS_AUXILIARY_MSK (((_ULL(1) << VT2_CKGN_CCLKPLLSTATUS_AUXILIARY_WID) - _ULL(1)) << VT2_CKGN_CCLKPLLSTATUS_AUXILIARY_POS)

#define VT2_CKGN_PADCTLNMI_OFFSET _ULL(0x400)

#define VT2_CKGN_PADCTLNMI_POS 0
#define VT2_CKGN_PADCTLNMI_WID 4
#define VT2_CKGN_PADCTLNMI_MSK (((_ULL(1) << VT2_CKGN_PADCTLNMI_WID) - _ULL(1)) << VT2_CKGN_PADCTLNMI_POS)

#define VT2_CKGN_PADCTLNMI_DS_POS 0
#define VT2_CKGN_PADCTLNMI_DS_WID 3
#define VT2_CKGN_PADCTLNMI_DS_MSK (((_ULL(1) << VT2_CKGN_PADCTLNMI_DS_WID) - _ULL(1)) << VT2_CKGN_PADCTLNMI_DS_POS)
#define VT2_CKGN_PADCTLNMI_SL_POS 3
#define VT2_CKGN_PADCTLNMI_SL_WID 1
#define VT2_CKGN_PADCTLNMI_SL_MSK (((_ULL(1) << VT2_CKGN_PADCTLNMI_SL_WID) - _ULL(1)) << VT2_CKGN_PADCTLNMI_SL_POS)

#define VT2_CKGN_PADCTLHIGHTEMP_OFFSET _ULL(0x401)

#define VT2_CKGN_PADCTLHIGHTEMP_POS 0
#define VT2_CKGN_PADCTLHIGHTEMP_WID 4
#define VT2_CKGN_PADCTLHIGHTEMP_MSK (((_ULL(1) << VT2_CKGN_PADCTLHIGHTEMP_WID) - _ULL(1)) << VT2_CKGN_PADCTLHIGHTEMP_POS)

#define VT2_CKGN_PADCTLHIGHTEMP_DS_POS 0
#define VT2_CKGN_PADCTLHIGHTEMP_DS_WID 3
#define VT2_CKGN_PADCTLHIGHTEMP_DS_MSK (((_ULL(1) << VT2_CKGN_PADCTLHIGHTEMP_DS_WID) - _ULL(1)) << VT2_CKGN_PADCTLHIGHTEMP_DS_POS)
#define VT2_CKGN_PADCTLHIGHTEMP_SL_POS 3
#define VT2_CKGN_PADCTLHIGHTEMP_SL_WID 1
#define VT2_CKGN_PADCTLHIGHTEMP_SL_MSK (((_ULL(1) << VT2_CKGN_PADCTLHIGHTEMP_SL_WID) - _ULL(1)) << VT2_CKGN_PADCTLHIGHTEMP_SL_POS)

#define VT2_CKGN_PADCTLSCL_OFFSET _ULL(0x402)

#define VT2_CKGN_PADCTLSCL_POS 0
#define VT2_CKGN_PADCTLSCL_WID 4
#define VT2_CKGN_PADCTLSCL_MSK (((_ULL(1) << VT2_CKGN_PADCTLSCL_WID) - _ULL(1)) << VT2_CKGN_PADCTLSCL_POS)

#define VT2_CKGN_PADCTLSCL_DS_POS 0
#define VT2_CKGN_PADCTLSCL_DS_WID 3
#define VT2_CKGN_PADCTLSCL_DS_MSK (((_ULL(1) << VT2_CKGN_PADCTLSCL_DS_WID) - _ULL(1)) << VT2_CKGN_PADCTLSCL_DS_POS)
#define VT2_CKGN_PADCTLSCL_SL_POS 3
#define VT2_CKGN_PADCTLSCL_SL_WID 1
#define VT2_CKGN_PADCTLSCL_SL_MSK (((_ULL(1) << VT2_CKGN_PADCTLSCL_SL_WID) - _ULL(1)) << VT2_CKGN_PADCTLSCL_SL_POS)

#define VT2_CKGN_PADCTLSDA_OFFSET _ULL(0x403)

#define VT2_CKGN_PADCTLSDA_POS 0
#define VT2_CKGN_PADCTLSDA_WID 4
#define VT2_CKGN_PADCTLSDA_MSK (((_ULL(1) << VT2_CKGN_PADCTLSDA_WID) - _ULL(1)) << VT2_CKGN_PADCTLSDA_POS)

#define VT2_CKGN_PADCTLSDA_DS_POS 0
#define VT2_CKGN_PADCTLSDA_DS_WID 3
#define VT2_CKGN_PADCTLSDA_DS_MSK (((_ULL(1) << VT2_CKGN_PADCTLSDA_DS_WID) - _ULL(1)) << VT2_CKGN_PADCTLSDA_DS_POS)
#define VT2_CKGN_PADCTLSDA_SL_POS 3
#define VT2_CKGN_PADCTLSDA_SL_WID 1
#define VT2_CKGN_PADCTLSDA_SL_MSK (((_ULL(1) << VT2_CKGN_PADCTLSDA_SL_WID) - _ULL(1)) << VT2_CKGN_PADCTLSDA_SL_POS)

#define VT2_CKGN_PADCTLTSTTDO_OFFSET _ULL(0x404)

#define VT2_CKGN_PADCTLTSTTDO_POS 0
#define VT2_CKGN_PADCTLTSTTDO_WID 4
#define VT2_CKGN_PADCTLTSTTDO_MSK (((_ULL(1) << VT2_CKGN_PADCTLTSTTDO_WID) - _ULL(1)) << VT2_CKGN_PADCTLTSTTDO_POS)

#define VT2_CKGN_PADCTLTSTTDO_DS_POS 0
#define VT2_CKGN_PADCTLTSTTDO_DS_WID 3
#define VT2_CKGN_PADCTLTSTTDO_DS_MSK (((_ULL(1) << VT2_CKGN_PADCTLTSTTDO_DS_WID) - _ULL(1)) << VT2_CKGN_PADCTLTSTTDO_DS_POS)
#define VT2_CKGN_PADCTLTSTTDO_SL_POS 3
#define VT2_CKGN_PADCTLTSTTDO_SL_WID 1
#define VT2_CKGN_PADCTLTSTTDO_SL_MSK (((_ULL(1) << VT2_CKGN_PADCTLTSTTDO_SL_WID) - _ULL(1)) << VT2_CKGN_PADCTLTSTTDO_SL_POS)

#define VT2_CKGN_PADCTLDBGTDO_OFFSET _ULL(0x405)

#define VT2_CKGN_PADCTLDBGTDO_POS 0
#define VT2_CKGN_PADCTLDBGTDO_WID 4
#define VT2_CKGN_PADCTLDBGTDO_MSK (((_ULL(1) << VT2_CKGN_PADCTLDBGTDO_WID) - _ULL(1)) << VT2_CKGN_PADCTLDBGTDO_POS)

#define VT2_CKGN_PADCTLDBGTDO_DS_POS 0
#define VT2_CKGN_PADCTLDBGTDO_DS_WID 3
#define VT2_CKGN_PADCTLDBGTDO_DS_MSK (((_ULL(1) << VT2_CKGN_PADCTLDBGTDO_DS_WID) - _ULL(1)) << VT2_CKGN_PADCTLDBGTDO_DS_POS)
#define VT2_CKGN_PADCTLDBGTDO_SL_POS 3
#define VT2_CKGN_PADCTLDBGTDO_SL_WID 1
#define VT2_CKGN_PADCTLDBGTDO_SL_MSK (((_ULL(1) << VT2_CKGN_PADCTLDBGTDO_SL_WID) - _ULL(1)) << VT2_CKGN_PADCTLDBGTDO_SL_POS)

#define VT2_CKGN_PADCTLGPOUT0_OFFSET _ULL(0x406)

#define VT2_CKGN_PADCTLGPOUT0_POS 0
#define VT2_CKGN_PADCTLGPOUT0_WID 4
#define VT2_CKGN_PADCTLGPOUT0_MSK (((_ULL(1) << VT2_CKGN_PADCTLGPOUT0_WID) - _ULL(1)) << VT2_CKGN_PADCTLGPOUT0_POS)

#define VT2_CKGN_PADCTLGPOUT0_DS_POS 0
#define VT2_CKGN_PADCTLGPOUT0_DS_WID 3
#define VT2_CKGN_PADCTLGPOUT0_DS_MSK (((_ULL(1) << VT2_CKGN_PADCTLGPOUT0_DS_WID) - _ULL(1)) << VT2_CKGN_PADCTLGPOUT0_DS_POS)
#define VT2_CKGN_PADCTLGPOUT0_SL_POS 3
#define VT2_CKGN_PADCTLGPOUT0_SL_WID 1
#define VT2_CKGN_PADCTLGPOUT0_SL_MSK (((_ULL(1) << VT2_CKGN_PADCTLGPOUT0_SL_WID) - _ULL(1)) << VT2_CKGN_PADCTLGPOUT0_SL_POS)

#define VT2_CKGN_PADCTLGPOUT1_OFFSET _ULL(0x407)

#define VT2_CKGN_PADCTLGPOUT1_POS 0
#define VT2_CKGN_PADCTLGPOUT1_WID 4
#define VT2_CKGN_PADCTLGPOUT1_MSK (((_ULL(1) << VT2_CKGN_PADCTLGPOUT1_WID) - _ULL(1)) << VT2_CKGN_PADCTLGPOUT1_POS)

#define VT2_CKGN_PADCTLGPOUT1_DS_POS 0
#define VT2_CKGN_PADCTLGPOUT1_DS_WID 3
#define VT2_CKGN_PADCTLGPOUT1_DS_MSK (((_ULL(1) << VT2_CKGN_PADCTLGPOUT1_DS_WID) - _ULL(1)) << VT2_CKGN_PADCTLGPOUT1_DS_POS)
#define VT2_CKGN_PADCTLGPOUT1_SL_POS 3
#define VT2_CKGN_PADCTLGPOUT1_SL_WID 1
#define VT2_CKGN_PADCTLGPOUT1_SL_MSK (((_ULL(1) << VT2_CKGN_PADCTLGPOUT1_SL_WID) - _ULL(1)) << VT2_CKGN_PADCTLGPOUT1_SL_POS)

#define VT2_CKGN_EFUSECTL_OFFSET _ULL(0x800)

#define VT2_CKGN_EFUSECTL_POS 0
#define VT2_CKGN_EFUSECTL_WID 6
#define VT2_CKGN_EFUSECTL_MSK (((_ULL(1) << VT2_CKGN_EFUSECTL_WID) - _ULL(1)) << VT2_CKGN_EFUSECTL_POS)

#define VT2_CKGN_EFUSECTL_RDWRCTL_POS 0
#define VT2_CKGN_EFUSECTL_RDWRCTL_WID 3
#define VT2_CKGN_EFUSECTL_RDWRCTL_MSK (((_ULL(1) << VT2_CKGN_EFUSECTL_RDWRCTL_WID) - _ULL(1)) << VT2_CKGN_EFUSECTL_RDWRCTL_POS)
#define VT2_CKGN_EFUSECTL_PROGTIME_POS 3
#define VT2_CKGN_EFUSECTL_PROGTIME_WID 2
#define VT2_CKGN_EFUSECTL_PROGTIME_MSK (((_ULL(1) << VT2_CKGN_EFUSECTL_PROGTIME_WID) - _ULL(1)) << VT2_CKGN_EFUSECTL_PROGTIME_POS)
#define VT2_CKGN_EFUSECTL_RSPAFTERARRRDDONE_POS 5
#define VT2_CKGN_EFUSECTL_RSPAFTERARRRDDONE_WID 1
#define VT2_CKGN_EFUSECTL_RSPAFTERARRRDDONE_MSK (((_ULL(1) << VT2_CKGN_EFUSECTL_RSPAFTERARRRDDONE_WID) - _ULL(1)) << VT2_CKGN_EFUSECTL_RSPAFTERARRRDDONE_POS)

#define VT2_CKGN_EFUSESTATUS_OFFSET _ULL(0x801)

#define VT2_CKGN_EFUSESTATUS_POS 0
#define VT2_CKGN_EFUSESTATUS_WID 1
#define VT2_CKGN_EFUSESTATUS_MSK (((_ULL(1) << VT2_CKGN_EFUSESTATUS_WID) - _ULL(1)) << VT2_CKGN_EFUSESTATUS_POS)

#define VT2_CKGN_EFUSESTATUS_PROGNOTDONE_POS 0
#define VT2_CKGN_EFUSESTATUS_PROGNOTDONE_WID 1
#define VT2_CKGN_EFUSESTATUS_PROGNOTDONE_MSK (((_ULL(1) << VT2_CKGN_EFUSESTATUS_PROGNOTDONE_WID) - _ULL(1)) << VT2_CKGN_EFUSESTATUS_PROGNOTDONE_POS)

#define VT2_CKGN_EFUSEATADDR0_OFFSET _ULL(0x810)

#define VT2_CKGN_EFUSEATADDR0_POS 0
#define VT2_CKGN_EFUSEATADDR0_WID 16
#define VT2_CKGN_EFUSEATADDR0_MSK (((_ULL(1) << VT2_CKGN_EFUSEATADDR0_WID) - _ULL(1)) << VT2_CKGN_EFUSEATADDR0_POS)

#define VT2_CKGN_EFUSEATADDR0_VALUE_POS 0
#define VT2_CKGN_EFUSEATADDR0_VALUE_WID 16
#define VT2_CKGN_EFUSEATADDR0_VALUE_MSK (((_ULL(1) << VT2_CKGN_EFUSEATADDR0_VALUE_WID) - _ULL(1)) << VT2_CKGN_EFUSEATADDR0_VALUE_POS)

#define VT2_CKGN_EFUSEATADDR1_OFFSET _ULL(0x811)

#define VT2_CKGN_EFUSEATADDR1_POS 0
#define VT2_CKGN_EFUSEATADDR1_WID 16
#define VT2_CKGN_EFUSEATADDR1_MSK (((_ULL(1) << VT2_CKGN_EFUSEATADDR1_WID) - _ULL(1)) << VT2_CKGN_EFUSEATADDR1_POS)

#define VT2_CKGN_EFUSEATADDR1_VALUE_POS 0
#define VT2_CKGN_EFUSEATADDR1_VALUE_WID 16
#define VT2_CKGN_EFUSEATADDR1_VALUE_MSK (((_ULL(1) << VT2_CKGN_EFUSEATADDR1_VALUE_WID) - _ULL(1)) << VT2_CKGN_EFUSEATADDR1_VALUE_POS)

#define VT2_CKGN_EFUSEATADDR2_OFFSET _ULL(0x812)

#define VT2_CKGN_EFUSEATADDR2_POS 0
#define VT2_CKGN_EFUSEATADDR2_WID 16
#define VT2_CKGN_EFUSEATADDR2_MSK (((_ULL(1) << VT2_CKGN_EFUSEATADDR2_WID) - _ULL(1)) << VT2_CKGN_EFUSEATADDR2_POS)

#define VT2_CKGN_EFUSEATADDR2_VALUE_POS 0
#define VT2_CKGN_EFUSEATADDR2_VALUE_WID 16
#define VT2_CKGN_EFUSEATADDR2_VALUE_MSK (((_ULL(1) << VT2_CKGN_EFUSEATADDR2_VALUE_WID) - _ULL(1)) << VT2_CKGN_EFUSEATADDR2_VALUE_POS)

#define VT2_CKGN_EFUSEATADDR3_OFFSET _ULL(0x813)

#define VT2_CKGN_EFUSEATADDR3_POS 0
#define VT2_CKGN_EFUSEATADDR3_WID 16
#define VT2_CKGN_EFUSEATADDR3_MSK (((_ULL(1) << VT2_CKGN_EFUSEATADDR3_WID) - _ULL(1)) << VT2_CKGN_EFUSEATADDR3_POS)

#define VT2_CKGN_EFUSEATADDR3_VALUE_POS 0
#define VT2_CKGN_EFUSEATADDR3_VALUE_WID 16
#define VT2_CKGN_EFUSEATADDR3_VALUE_MSK (((_ULL(1) << VT2_CKGN_EFUSEATADDR3_VALUE_WID) - _ULL(1)) << VT2_CKGN_EFUSEATADDR3_VALUE_POS)

#define VT2_CKGN_EFUSEATADDR4_OFFSET _ULL(0x814)

#define VT2_CKGN_EFUSEATADDR4_POS 0
#define VT2_CKGN_EFUSEATADDR4_WID 16
#define VT2_CKGN_EFUSEATADDR4_MSK (((_ULL(1) << VT2_CKGN_EFUSEATADDR4_WID) - _ULL(1)) << VT2_CKGN_EFUSEATADDR4_POS)

#define VT2_CKGN_EFUSEATADDR4_VALUE_POS 0
#define VT2_CKGN_EFUSEATADDR4_VALUE_WID 16
#define VT2_CKGN_EFUSEATADDR4_VALUE_MSK (((_ULL(1) << VT2_CKGN_EFUSEATADDR4_VALUE_WID) - _ULL(1)) << VT2_CKGN_EFUSEATADDR4_VALUE_POS)

#define VT2_CKGN_EFUSEATADDR5_OFFSET _ULL(0x815)

#define VT2_CKGN_EFUSEATADDR5_POS 0
#define VT2_CKGN_EFUSEATADDR5_WID 16
#define VT2_CKGN_EFUSEATADDR5_MSK (((_ULL(1) << VT2_CKGN_EFUSEATADDR5_WID) - _ULL(1)) << VT2_CKGN_EFUSEATADDR5_POS)

#define VT2_CKGN_EFUSEATADDR5_VALUE_POS 0
#define VT2_CKGN_EFUSEATADDR5_VALUE_WID 16
#define VT2_CKGN_EFUSEATADDR5_VALUE_MSK (((_ULL(1) << VT2_CKGN_EFUSEATADDR5_VALUE_WID) - _ULL(1)) << VT2_CKGN_EFUSEATADDR5_VALUE_POS)

#define VT2_CKGN_EFUSEATADDR6_OFFSET _ULL(0x816)

#define VT2_CKGN_EFUSEATADDR6_POS 0
#define VT2_CKGN_EFUSEATADDR6_WID 16
#define VT2_CKGN_EFUSEATADDR6_MSK (((_ULL(1) << VT2_CKGN_EFUSEATADDR6_WID) - _ULL(1)) << VT2_CKGN_EFUSEATADDR6_POS)

#define VT2_CKGN_EFUSEATADDR6_VALUE_POS 0
#define VT2_CKGN_EFUSEATADDR6_VALUE_WID 16
#define VT2_CKGN_EFUSEATADDR6_VALUE_MSK (((_ULL(1) << VT2_CKGN_EFUSEATADDR6_VALUE_WID) - _ULL(1)) << VT2_CKGN_EFUSEATADDR6_VALUE_POS)

#define VT2_CKGN_EFUSEATADDR7_OFFSET _ULL(0x817)

#define VT2_CKGN_EFUSEATADDR7_POS 0
#define VT2_CKGN_EFUSEATADDR7_WID 16
#define VT2_CKGN_EFUSEATADDR7_MSK (((_ULL(1) << VT2_CKGN_EFUSEATADDR7_WID) - _ULL(1)) << VT2_CKGN_EFUSEATADDR7_POS)

#define VT2_CKGN_EFUSEATADDR7_VALUE_POS 0
#define VT2_CKGN_EFUSEATADDR7_VALUE_WID 16
#define VT2_CKGN_EFUSEATADDR7_VALUE_MSK (((_ULL(1) << VT2_CKGN_EFUSEATADDR7_VALUE_WID) - _ULL(1)) << VT2_CKGN_EFUSEATADDR7_VALUE_POS)

#define VT2_CKGN_EFUSEATADDR8_OFFSET _ULL(0x818)

#define VT2_CKGN_EFUSEATADDR8_POS 0
#define VT2_CKGN_EFUSEATADDR8_WID 16
#define VT2_CKGN_EFUSEATADDR8_MSK (((_ULL(1) << VT2_CKGN_EFUSEATADDR8_WID) - _ULL(1)) << VT2_CKGN_EFUSEATADDR8_POS)

#define VT2_CKGN_EFUSEATADDR8_VALUE_POS 0
#define VT2_CKGN_EFUSEATADDR8_VALUE_WID 16
#define VT2_CKGN_EFUSEATADDR8_VALUE_MSK (((_ULL(1) << VT2_CKGN_EFUSEATADDR8_VALUE_WID) - _ULL(1)) << VT2_CKGN_EFUSEATADDR8_VALUE_POS)

#define VT2_CKGN_EFUSEATADDR9_OFFSET _ULL(0x819)

#define VT2_CKGN_EFUSEATADDR9_POS 0
#define VT2_CKGN_EFUSEATADDR9_WID 16
#define VT2_CKGN_EFUSEATADDR9_MSK (((_ULL(1) << VT2_CKGN_EFUSEATADDR9_WID) - _ULL(1)) << VT2_CKGN_EFUSEATADDR9_POS)

#define VT2_CKGN_EFUSEATADDR9_VALUE_POS 0
#define VT2_CKGN_EFUSEATADDR9_VALUE_WID 16
#define VT2_CKGN_EFUSEATADDR9_VALUE_MSK (((_ULL(1) << VT2_CKGN_EFUSEATADDR9_VALUE_WID) - _ULL(1)) << VT2_CKGN_EFUSEATADDR9_VALUE_POS)

#define VT2_CKGN_EFUSEATADDR10_OFFSET _ULL(0x81a)

#define VT2_CKGN_EFUSEATADDR10_POS 0
#define VT2_CKGN_EFUSEATADDR10_WID 16
#define VT2_CKGN_EFUSEATADDR10_MSK (((_ULL(1) << VT2_CKGN_EFUSEATADDR10_WID) - _ULL(1)) << VT2_CKGN_EFUSEATADDR10_POS)

#define VT2_CKGN_EFUSEATADDR10_VALUE_POS 0
#define VT2_CKGN_EFUSEATADDR10_VALUE_WID 16
#define VT2_CKGN_EFUSEATADDR10_VALUE_MSK (((_ULL(1) << VT2_CKGN_EFUSEATADDR10_VALUE_WID) - _ULL(1)) << VT2_CKGN_EFUSEATADDR10_VALUE_POS)

#define VT2_CKGN_EFUSEATADDR11_OFFSET _ULL(0x81b)

#define VT2_CKGN_EFUSEATADDR11_POS 0
#define VT2_CKGN_EFUSEATADDR11_WID 16
#define VT2_CKGN_EFUSEATADDR11_MSK (((_ULL(1) << VT2_CKGN_EFUSEATADDR11_WID) - _ULL(1)) << VT2_CKGN_EFUSEATADDR11_POS)

#define VT2_CKGN_EFUSEATADDR11_VALUE_POS 0
#define VT2_CKGN_EFUSEATADDR11_VALUE_WID 16
#define VT2_CKGN_EFUSEATADDR11_VALUE_MSK (((_ULL(1) << VT2_CKGN_EFUSEATADDR11_VALUE_WID) - _ULL(1)) << VT2_CKGN_EFUSEATADDR11_VALUE_POS)

#define VT2_CKGN_EFUSEATADDR12_OFFSET _ULL(0x81c)

#define VT2_CKGN_EFUSEATADDR12_POS 0
#define VT2_CKGN_EFUSEATADDR12_WID 16
#define VT2_CKGN_EFUSEATADDR12_MSK (((_ULL(1) << VT2_CKGN_EFUSEATADDR12_WID) - _ULL(1)) << VT2_CKGN_EFUSEATADDR12_POS)

#define VT2_CKGN_EFUSEATADDR12_VALUE_POS 0
#define VT2_CKGN_EFUSEATADDR12_VALUE_WID 16
#define VT2_CKGN_EFUSEATADDR12_VALUE_MSK (((_ULL(1) << VT2_CKGN_EFUSEATADDR12_VALUE_WID) - _ULL(1)) << VT2_CKGN_EFUSEATADDR12_VALUE_POS)

#define VT2_CKGN_EFUSEATADDR13_OFFSET _ULL(0x81d)

#define VT2_CKGN_EFUSEATADDR13_POS 0
#define VT2_CKGN_EFUSEATADDR13_WID 16
#define VT2_CKGN_EFUSEATADDR13_MSK (((_ULL(1) << VT2_CKGN_EFUSEATADDR13_WID) - _ULL(1)) << VT2_CKGN_EFUSEATADDR13_POS)

#define VT2_CKGN_EFUSEATADDR13_VALUE_POS 0
#define VT2_CKGN_EFUSEATADDR13_VALUE_WID 16
#define VT2_CKGN_EFUSEATADDR13_VALUE_MSK (((_ULL(1) << VT2_CKGN_EFUSEATADDR13_VALUE_WID) - _ULL(1)) << VT2_CKGN_EFUSEATADDR13_VALUE_POS)

#define VT2_CKGN_EFUSEATADDR14_OFFSET _ULL(0x81e)

#define VT2_CKGN_EFUSEATADDR14_POS 0
#define VT2_CKGN_EFUSEATADDR14_WID 16
#define VT2_CKGN_EFUSEATADDR14_MSK (((_ULL(1) << VT2_CKGN_EFUSEATADDR14_WID) - _ULL(1)) << VT2_CKGN_EFUSEATADDR14_POS)

#define VT2_CKGN_EFUSEATADDR14_VALUE_POS 0
#define VT2_CKGN_EFUSEATADDR14_VALUE_WID 16
#define VT2_CKGN_EFUSEATADDR14_VALUE_MSK (((_ULL(1) << VT2_CKGN_EFUSEATADDR14_VALUE_WID) - _ULL(1)) << VT2_CKGN_EFUSEATADDR14_VALUE_POS)

#define VT2_CKGN_EFUSEATADDR15_OFFSET _ULL(0x81f)

#define VT2_CKGN_EFUSEATADDR15_POS 0
#define VT2_CKGN_EFUSEATADDR15_WID 16
#define VT2_CKGN_EFUSEATADDR15_MSK (((_ULL(1) << VT2_CKGN_EFUSEATADDR15_WID) - _ULL(1)) << VT2_CKGN_EFUSEATADDR15_POS)

#define VT2_CKGN_EFUSEATADDR15_VALUE_POS 0
#define VT2_CKGN_EFUSEATADDR15_VALUE_WID 16
#define VT2_CKGN_EFUSEATADDR15_VALUE_MSK (((_ULL(1) << VT2_CKGN_EFUSEATADDR15_VALUE_WID) - _ULL(1)) << VT2_CKGN_EFUSEATADDR15_VALUE_POS)

#define VT2_CKGN_EFUSEATADDR16_OFFSET _ULL(0x820)

#define VT2_CKGN_EFUSEATADDR16_POS 0
#define VT2_CKGN_EFUSEATADDR16_WID 16
#define VT2_CKGN_EFUSEATADDR16_MSK (((_ULL(1) << VT2_CKGN_EFUSEATADDR16_WID) - _ULL(1)) << VT2_CKGN_EFUSEATADDR16_POS)

#define VT2_CKGN_EFUSEATADDR16_VALUE_POS 0
#define VT2_CKGN_EFUSEATADDR16_VALUE_WID 16
#define VT2_CKGN_EFUSEATADDR16_VALUE_MSK (((_ULL(1) << VT2_CKGN_EFUSEATADDR16_VALUE_WID) - _ULL(1)) << VT2_CKGN_EFUSEATADDR16_VALUE_POS)

#define VT2_CKGN_EFUSEATADDR17_OFFSET _ULL(0x821)

#define VT2_CKGN_EFUSEATADDR17_POS 0
#define VT2_CKGN_EFUSEATADDR17_WID 16
#define VT2_CKGN_EFUSEATADDR17_MSK (((_ULL(1) << VT2_CKGN_EFUSEATADDR17_WID) - _ULL(1)) << VT2_CKGN_EFUSEATADDR17_POS)

#define VT2_CKGN_EFUSEATADDR17_VALUE_POS 0
#define VT2_CKGN_EFUSEATADDR17_VALUE_WID 16
#define VT2_CKGN_EFUSEATADDR17_VALUE_MSK (((_ULL(1) << VT2_CKGN_EFUSEATADDR17_VALUE_WID) - _ULL(1)) << VT2_CKGN_EFUSEATADDR17_VALUE_POS)

#define VT2_CKGN_EFUSEATADDR18_OFFSET _ULL(0x822)

#define VT2_CKGN_EFUSEATADDR18_POS 0
#define VT2_CKGN_EFUSEATADDR18_WID 16
#define VT2_CKGN_EFUSEATADDR18_MSK (((_ULL(1) << VT2_CKGN_EFUSEATADDR18_WID) - _ULL(1)) << VT2_CKGN_EFUSEATADDR18_POS)

#define VT2_CKGN_EFUSEATADDR18_VALUE_POS 0
#define VT2_CKGN_EFUSEATADDR18_VALUE_WID 16
#define VT2_CKGN_EFUSEATADDR18_VALUE_MSK (((_ULL(1) << VT2_CKGN_EFUSEATADDR18_VALUE_WID) - _ULL(1)) << VT2_CKGN_EFUSEATADDR18_VALUE_POS)

#define VT2_CKGN_EFUSEATADDR19_OFFSET _ULL(0x823)

#define VT2_CKGN_EFUSEATADDR19_POS 0
#define VT2_CKGN_EFUSEATADDR19_WID 16
#define VT2_CKGN_EFUSEATADDR19_MSK (((_ULL(1) << VT2_CKGN_EFUSEATADDR19_WID) - _ULL(1)) << VT2_CKGN_EFUSEATADDR19_POS)

#define VT2_CKGN_EFUSEATADDR19_VALUE_POS 0
#define VT2_CKGN_EFUSEATADDR19_VALUE_WID 16
#define VT2_CKGN_EFUSEATADDR19_VALUE_MSK (((_ULL(1) << VT2_CKGN_EFUSEATADDR19_VALUE_WID) - _ULL(1)) << VT2_CKGN_EFUSEATADDR19_VALUE_POS)

#define VT2_CKGN_EFUSEATADDR20_OFFSET _ULL(0x824)

#define VT2_CKGN_EFUSEATADDR20_POS 0
#define VT2_CKGN_EFUSEATADDR20_WID 16
#define VT2_CKGN_EFUSEATADDR20_MSK (((_ULL(1) << VT2_CKGN_EFUSEATADDR20_WID) - _ULL(1)) << VT2_CKGN_EFUSEATADDR20_POS)

#define VT2_CKGN_EFUSEATADDR20_VALUE_POS 0
#define VT2_CKGN_EFUSEATADDR20_VALUE_WID 16
#define VT2_CKGN_EFUSEATADDR20_VALUE_MSK (((_ULL(1) << VT2_CKGN_EFUSEATADDR20_VALUE_WID) - _ULL(1)) << VT2_CKGN_EFUSEATADDR20_VALUE_POS)

#define VT2_CKGN_EFUSEATADDR21_OFFSET _ULL(0x825)

#define VT2_CKGN_EFUSEATADDR21_POS 0
#define VT2_CKGN_EFUSEATADDR21_WID 16
#define VT2_CKGN_EFUSEATADDR21_MSK (((_ULL(1) << VT2_CKGN_EFUSEATADDR21_WID) - _ULL(1)) << VT2_CKGN_EFUSEATADDR21_POS)

#define VT2_CKGN_EFUSEATADDR21_VALUE_POS 0
#define VT2_CKGN_EFUSEATADDR21_VALUE_WID 16
#define VT2_CKGN_EFUSEATADDR21_VALUE_MSK (((_ULL(1) << VT2_CKGN_EFUSEATADDR21_VALUE_WID) - _ULL(1)) << VT2_CKGN_EFUSEATADDR21_VALUE_POS)

#define VT2_CKGN_EFUSEATADDR22_OFFSET _ULL(0x826)

#define VT2_CKGN_EFUSEATADDR22_POS 0
#define VT2_CKGN_EFUSEATADDR22_WID 16
#define VT2_CKGN_EFUSEATADDR22_MSK (((_ULL(1) << VT2_CKGN_EFUSEATADDR22_WID) - _ULL(1)) << VT2_CKGN_EFUSEATADDR22_POS)

#define VT2_CKGN_EFUSEATADDR22_VALUE_POS 0
#define VT2_CKGN_EFUSEATADDR22_VALUE_WID 16
#define VT2_CKGN_EFUSEATADDR22_VALUE_MSK (((_ULL(1) << VT2_CKGN_EFUSEATADDR22_VALUE_WID) - _ULL(1)) << VT2_CKGN_EFUSEATADDR22_VALUE_POS)

#define VT2_CKGN_EFUSEATADDR23_OFFSET _ULL(0x827)

#define VT2_CKGN_EFUSEATADDR23_POS 0
#define VT2_CKGN_EFUSEATADDR23_WID 16
#define VT2_CKGN_EFUSEATADDR23_MSK (((_ULL(1) << VT2_CKGN_EFUSEATADDR23_WID) - _ULL(1)) << VT2_CKGN_EFUSEATADDR23_POS)

#define VT2_CKGN_EFUSEATADDR23_VALUE_POS 0
#define VT2_CKGN_EFUSEATADDR23_VALUE_WID 16
#define VT2_CKGN_EFUSEATADDR23_VALUE_MSK (((_ULL(1) << VT2_CKGN_EFUSEATADDR23_VALUE_WID) - _ULL(1)) << VT2_CKGN_EFUSEATADDR23_VALUE_POS)

#define VT2_CKGN_EFUSEATADDR24_OFFSET _ULL(0x828)

#define VT2_CKGN_EFUSEATADDR24_POS 0
#define VT2_CKGN_EFUSEATADDR24_WID 16
#define VT2_CKGN_EFUSEATADDR24_MSK (((_ULL(1) << VT2_CKGN_EFUSEATADDR24_WID) - _ULL(1)) << VT2_CKGN_EFUSEATADDR24_POS)

#define VT2_CKGN_EFUSEATADDR24_VALUE_POS 0
#define VT2_CKGN_EFUSEATADDR24_VALUE_WID 16
#define VT2_CKGN_EFUSEATADDR24_VALUE_MSK (((_ULL(1) << VT2_CKGN_EFUSEATADDR24_VALUE_WID) - _ULL(1)) << VT2_CKGN_EFUSEATADDR24_VALUE_POS)

#define VT2_CKGN_EFUSEATADDR25_OFFSET _ULL(0x829)

#define VT2_CKGN_EFUSEATADDR25_POS 0
#define VT2_CKGN_EFUSEATADDR25_WID 16
#define VT2_CKGN_EFUSEATADDR25_MSK (((_ULL(1) << VT2_CKGN_EFUSEATADDR25_WID) - _ULL(1)) << VT2_CKGN_EFUSEATADDR25_POS)

#define VT2_CKGN_EFUSEATADDR25_VALUE_POS 0
#define VT2_CKGN_EFUSEATADDR25_VALUE_WID 16
#define VT2_CKGN_EFUSEATADDR25_VALUE_MSK (((_ULL(1) << VT2_CKGN_EFUSEATADDR25_VALUE_WID) - _ULL(1)) << VT2_CKGN_EFUSEATADDR25_VALUE_POS)

#define VT2_CKGN_EFUSEATADDR26_OFFSET _ULL(0x82a)

#define VT2_CKGN_EFUSEATADDR26_POS 0
#define VT2_CKGN_EFUSEATADDR26_WID 16
#define VT2_CKGN_EFUSEATADDR26_MSK (((_ULL(1) << VT2_CKGN_EFUSEATADDR26_WID) - _ULL(1)) << VT2_CKGN_EFUSEATADDR26_POS)

#define VT2_CKGN_EFUSEATADDR26_VALUE_POS 0
#define VT2_CKGN_EFUSEATADDR26_VALUE_WID 16
#define VT2_CKGN_EFUSEATADDR26_VALUE_MSK (((_ULL(1) << VT2_CKGN_EFUSEATADDR26_VALUE_WID) - _ULL(1)) << VT2_CKGN_EFUSEATADDR26_VALUE_POS)

#define VT2_CKGN_EFUSEATADDR27_OFFSET _ULL(0x82b)

#define VT2_CKGN_EFUSEATADDR27_POS 0
#define VT2_CKGN_EFUSEATADDR27_WID 16
#define VT2_CKGN_EFUSEATADDR27_MSK (((_ULL(1) << VT2_CKGN_EFUSEATADDR27_WID) - _ULL(1)) << VT2_CKGN_EFUSEATADDR27_POS)

#define VT2_CKGN_EFUSEATADDR27_VALUE_POS 0
#define VT2_CKGN_EFUSEATADDR27_VALUE_WID 16
#define VT2_CKGN_EFUSEATADDR27_VALUE_MSK (((_ULL(1) << VT2_CKGN_EFUSEATADDR27_VALUE_WID) - _ULL(1)) << VT2_CKGN_EFUSEATADDR27_VALUE_POS)

#define VT2_CKGN_EFUSEATADDR28_OFFSET _ULL(0x82c)

#define VT2_CKGN_EFUSEATADDR28_POS 0
#define VT2_CKGN_EFUSEATADDR28_WID 16
#define VT2_CKGN_EFUSEATADDR28_MSK (((_ULL(1) << VT2_CKGN_EFUSEATADDR28_WID) - _ULL(1)) << VT2_CKGN_EFUSEATADDR28_POS)

#define VT2_CKGN_EFUSEATADDR28_VALUE_POS 0
#define VT2_CKGN_EFUSEATADDR28_VALUE_WID 16
#define VT2_CKGN_EFUSEATADDR28_VALUE_MSK (((_ULL(1) << VT2_CKGN_EFUSEATADDR28_VALUE_WID) - _ULL(1)) << VT2_CKGN_EFUSEATADDR28_VALUE_POS)

#define VT2_CKGN_EFUSEATADDR29_OFFSET _ULL(0x82d)

#define VT2_CKGN_EFUSEATADDR29_POS 0
#define VT2_CKGN_EFUSEATADDR29_WID 16
#define VT2_CKGN_EFUSEATADDR29_MSK (((_ULL(1) << VT2_CKGN_EFUSEATADDR29_WID) - _ULL(1)) << VT2_CKGN_EFUSEATADDR29_POS)

#define VT2_CKGN_EFUSEATADDR29_VALUE_POS 0
#define VT2_CKGN_EFUSEATADDR29_VALUE_WID 16
#define VT2_CKGN_EFUSEATADDR29_VALUE_MSK (((_ULL(1) << VT2_CKGN_EFUSEATADDR29_VALUE_WID) - _ULL(1)) << VT2_CKGN_EFUSEATADDR29_VALUE_POS)

#define VT2_CKGN_EFUSEATADDR30_OFFSET _ULL(0x82e)

#define VT2_CKGN_EFUSEATADDR30_POS 0
#define VT2_CKGN_EFUSEATADDR30_WID 16
#define VT2_CKGN_EFUSEATADDR30_MSK (((_ULL(1) << VT2_CKGN_EFUSEATADDR30_WID) - _ULL(1)) << VT2_CKGN_EFUSEATADDR30_POS)

#define VT2_CKGN_EFUSEATADDR30_VALUE_POS 0
#define VT2_CKGN_EFUSEATADDR30_VALUE_WID 16
#define VT2_CKGN_EFUSEATADDR30_VALUE_MSK (((_ULL(1) << VT2_CKGN_EFUSEATADDR30_VALUE_WID) - _ULL(1)) << VT2_CKGN_EFUSEATADDR30_VALUE_POS)

#define VT2_CKGN_EFUSEATADDR31_OFFSET _ULL(0x82f)

#define VT2_CKGN_EFUSEATADDR31_POS 0
#define VT2_CKGN_EFUSEATADDR31_WID 16
#define VT2_CKGN_EFUSEATADDR31_MSK (((_ULL(1) << VT2_CKGN_EFUSEATADDR31_WID) - _ULL(1)) << VT2_CKGN_EFUSEATADDR31_POS)

#define VT2_CKGN_EFUSEATADDR31_VALUE_POS 0
#define VT2_CKGN_EFUSEATADDR31_VALUE_WID 16
#define VT2_CKGN_EFUSEATADDR31_VALUE_MSK (((_ULL(1) << VT2_CKGN_EFUSEATADDR31_VALUE_WID) - _ULL(1)) << VT2_CKGN_EFUSEATADDR31_VALUE_POS)

#define VT2_CKGN_GPIN0_OFFSET _ULL(0xc00)

#define VT2_CKGN_GPIN0_POS 0
#define VT2_CKGN_GPIN0_WID 1
#define VT2_CKGN_GPIN0_MSK (((_ULL(1) << VT2_CKGN_GPIN0_WID) - _ULL(1)) << VT2_CKGN_GPIN0_POS)

#define VT2_CKGN_GPIN0_GPIN_POS 0
#define VT2_CKGN_GPIN0_GPIN_WID 1
#define VT2_CKGN_GPIN0_GPIN_MSK (((_ULL(1) << VT2_CKGN_GPIN0_GPIN_WID) - _ULL(1)) << VT2_CKGN_GPIN0_GPIN_POS)

#define VT2_CKGN_GPIN1_OFFSET _ULL(0xc01)

#define VT2_CKGN_GPIN1_POS 0
#define VT2_CKGN_GPIN1_WID 1
#define VT2_CKGN_GPIN1_MSK (((_ULL(1) << VT2_CKGN_GPIN1_WID) - _ULL(1)) << VT2_CKGN_GPIN1_POS)

#define VT2_CKGN_GPIN1_GPIN_POS 0
#define VT2_CKGN_GPIN1_GPIN_WID 1
#define VT2_CKGN_GPIN1_GPIN_MSK (((_ULL(1) << VT2_CKGN_GPIN1_GPIN_WID) - _ULL(1)) << VT2_CKGN_GPIN1_GPIN_POS)

#define VT2_CKGN_GPOUT0_OFFSET _ULL(0xc02)

#define VT2_CKGN_GPOUT0_POS 0
#define VT2_CKGN_GPOUT0_WID 1
#define VT2_CKGN_GPOUT0_MSK (((_ULL(1) << VT2_CKGN_GPOUT0_WID) - _ULL(1)) << VT2_CKGN_GPOUT0_POS)

#define VT2_CKGN_GPOUT0_GPOUT_POS 0
#define VT2_CKGN_GPOUT0_GPOUT_WID 1
#define VT2_CKGN_GPOUT0_GPOUT_MSK (((_ULL(1) << VT2_CKGN_GPOUT0_GPOUT_WID) - _ULL(1)) << VT2_CKGN_GPOUT0_GPOUT_POS)

#define VT2_CKGN_GPOUT1_OFFSET _ULL(0xc03)

#define VT2_CKGN_GPOUT1_POS 0
#define VT2_CKGN_GPOUT1_WID 1
#define VT2_CKGN_GPOUT1_MSK (((_ULL(1) << VT2_CKGN_GPOUT1_WID) - _ULL(1)) << VT2_CKGN_GPOUT1_POS)

#define VT2_CKGN_GPOUT1_GPOUT_POS 0
#define VT2_CKGN_GPOUT1_GPOUT_WID 1
#define VT2_CKGN_GPOUT1_GPOUT_MSK (((_ULL(1) << VT2_CKGN_GPOUT1_GPOUT_WID) - _ULL(1)) << VT2_CKGN_GPOUT1_GPOUT_POS)
#endif /* VT2_CKGN_MMR_H */
