/* This file is auto-generated. Do not hand edit this file. */

#ifndef VT2_CHPL_MMR_H
#define VT2_CHPL_MMR_H

#ifndef _ULL

#ifdef __ASSEMBLER__
#define _AC(X,Y) X
#else
#define __AC(X,Y) (X##Y)
#define _AC(X,Y) __AC(X,Y)
#endif

#define _ULL(x)  (_AC(x, ULL))
#endif


#define VT2_CHPL_TXID_OFFSET _ULL(0x0)

#define VT2_CHPL_TXID_POS 0
#define VT2_CHPL_TXID_WID 28
#define VT2_CHPL_TXID_MSK (((_ULL(1) << VT2_CHPL_TXID_WID) - _ULL(1)) << VT2_CHPL_TXID_POS)

#define VT2_CHPL_TXID_VERSION_POS 0
#define VT2_CHPL_TXID_VERSION_WID 8
#define VT2_CHPL_TXID_VERSION_MSK (((_ULL(1) << VT2_CHPL_TXID_VERSION_WID) - _ULL(1)) << VT2_CHPL_TXID_VERSION_POS)
#define VT2_CHPL_TXID_IMPLEMENTATION_POS 8
#define VT2_CHPL_TXID_IMPLEMENTATION_WID 8
#define VT2_CHPL_TXID_IMPLEMENTATION_MSK (((_ULL(1) << VT2_CHPL_TXID_IMPLEMENTATION_WID) - _ULL(1)) << VT2_CHPL_TXID_IMPLEMENTATION_POS)
#define VT2_CHPL_TXID_FRAGMENTMAP_POS 16
#define VT2_CHPL_TXID_FRAGMENTMAP_WID 12
#define VT2_CHPL_TXID_FRAGMENTMAP_MSK (((_ULL(1) << VT2_CHPL_TXID_FRAGMENTMAP_WID) - _ULL(1)) << VT2_CHPL_TXID_FRAGMENTMAP_POS)

#define VT2_CHPL_TXINTERFACECONTROLSTATUS_OFFSET _ULL(0x1)

#define VT2_CHPL_TXINTERFACECONTROLSTATUS_POS 0
#define VT2_CHPL_TXINTERFACECONTROLSTATUS_WID 8
#define VT2_CHPL_TXINTERFACECONTROLSTATUS_MSK (((_ULL(1) << VT2_CHPL_TXINTERFACECONTROLSTATUS_WID) - _ULL(1)) << VT2_CHPL_TXINTERFACECONTROLSTATUS_POS)

#define VT2_CHPL_TXINTERFACECONTROLSTATUS_DATAWIDTH_POS 0
#define VT2_CHPL_TXINTERFACECONTROLSTATUS_DATAWIDTH_WID 2
#define VT2_CHPL_TXINTERFACECONTROLSTATUS_DATAWIDTH_MSK (((_ULL(1) << VT2_CHPL_TXINTERFACECONTROLSTATUS_DATAWIDTH_WID) - _ULL(1)) << VT2_CHPL_TXINTERFACECONTROLSTATUS_DATAWIDTH_POS)
#define VT2_CHPL_TXINTERFACECONTROLSTATUS_TXACTIVE_POS 2
#define VT2_CHPL_TXINTERFACECONTROLSTATUS_TXACTIVE_WID 1
#define VT2_CHPL_TXINTERFACECONTROLSTATUS_TXACTIVE_MSK (((_ULL(1) << VT2_CHPL_TXINTERFACECONTROLSTATUS_TXACTIVE_WID) - _ULL(1)) << VT2_CHPL_TXINTERFACECONTROLSTATUS_TXACTIVE_POS)
#define VT2_CHPL_TXINTERFACECONTROLSTATUS_COMPRESSIONDISABLE_POS 3
#define VT2_CHPL_TXINTERFACECONTROLSTATUS_COMPRESSIONDISABLE_WID 1
#define VT2_CHPL_TXINTERFACECONTROLSTATUS_COMPRESSIONDISABLE_MSK (((_ULL(1) << VT2_CHPL_TXINTERFACECONTROLSTATUS_COMPRESSIONDISABLE_WID) - _ULL(1)) << VT2_CHPL_TXINTERFACECONTROLSTATUS_COMPRESSIONDISABLE_POS)
#define VT2_CHPL_TXINTERFACECONTROLSTATUS_LINKRESET_POS 4
#define VT2_CHPL_TXINTERFACECONTROLSTATUS_LINKRESET_WID 1
#define VT2_CHPL_TXINTERFACECONTROLSTATUS_LINKRESET_MSK (((_ULL(1) << VT2_CHPL_TXINTERFACECONTROLSTATUS_LINKRESET_WID) - _ULL(1)) << VT2_CHPL_TXINTERFACECONTROLSTATUS_LINKRESET_POS)
#define VT2_CHPL_TXINTERFACECONTROLSTATUS_PHYRESET_POS 5
#define VT2_CHPL_TXINTERFACECONTROLSTATUS_PHYRESET_WID 1
#define VT2_CHPL_TXINTERFACECONTROLSTATUS_PHYRESET_MSK (((_ULL(1) << VT2_CHPL_TXINTERFACECONTROLSTATUS_PHYRESET_WID) - _ULL(1)) << VT2_CHPL_TXINTERFACECONTROLSTATUS_PHYRESET_POS)
#define VT2_CHPL_TXINTERFACECONTROLSTATUS_PHYREADY_POS 6
#define VT2_CHPL_TXINTERFACECONTROLSTATUS_PHYREADY_WID 2
#define VT2_CHPL_TXINTERFACECONTROLSTATUS_PHYREADY_MSK (((_ULL(1) << VT2_CHPL_TXINTERFACECONTROLSTATUS_PHYREADY_WID) - _ULL(1)) << VT2_CHPL_TXINTERFACECONTROLSTATUS_PHYREADY_POS)

#define VT2_CHPL_TXERRINJECTIONCONTROL_OFFSET _ULL(0x2)

#define VT2_CHPL_TXERRINJECTIONCONTROL_POS 0
#define VT2_CHPL_TXERRINJECTIONCONTROL_WID 11
#define VT2_CHPL_TXERRINJECTIONCONTROL_MSK (((_ULL(1) << VT2_CHPL_TXERRINJECTIONCONTROL_WID) - _ULL(1)) << VT2_CHPL_TXERRINJECTIONCONTROL_POS)

#define VT2_CHPL_TXERRINJECTIONCONTROL_CORRUPTLLPBITNUMBER_POS 0
#define VT2_CHPL_TXERRINJECTIONCONTROL_CORRUPTLLPBITNUMBER_WID 9
#define VT2_CHPL_TXERRINJECTIONCONTROL_CORRUPTLLPBITNUMBER_MSK (((_ULL(1) << VT2_CHPL_TXERRINJECTIONCONTROL_CORRUPTLLPBITNUMBER_WID) - _ULL(1)) << VT2_CHPL_TXERRINJECTIONCONTROL_CORRUPTLLPBITNUMBER_POS)
#define VT2_CHPL_TXERRINJECTIONCONTROL_CORRUPTLLPBITENABLE_POS 9
#define VT2_CHPL_TXERRINJECTIONCONTROL_CORRUPTLLPBITENABLE_WID 1
#define VT2_CHPL_TXERRINJECTIONCONTROL_CORRUPTLLPBITENABLE_MSK (((_ULL(1) << VT2_CHPL_TXERRINJECTIONCONTROL_CORRUPTLLPBITENABLE_WID) - _ULL(1)) << VT2_CHPL_TXERRINJECTIONCONTROL_CORRUPTLLPBITENABLE_POS)
#define VT2_CHPL_TXERRINJECTIONCONTROL_CORRUPTALLCODEWORDS_POS 10
#define VT2_CHPL_TXERRINJECTIONCONTROL_CORRUPTALLCODEWORDS_WID 1
#define VT2_CHPL_TXERRINJECTIONCONTROL_CORRUPTALLCODEWORDS_MSK (((_ULL(1) << VT2_CHPL_TXERRINJECTIONCONTROL_CORRUPTALLCODEWORDS_WID) - _ULL(1)) << VT2_CHPL_TXERRINJECTIONCONTROL_CORRUPTALLCODEWORDS_POS)

#define VT2_CHPL_TXHPMEVENT0_OFFSET _ULL(0x20)

#define VT2_CHPL_TXHPMEVENT0_POS 0
#define VT2_CHPL_TXHPMEVENT0_WID 16
#define VT2_CHPL_TXHPMEVENT0_MSK (((_ULL(1) << VT2_CHPL_TXHPMEVENT0_WID) - _ULL(1)) << VT2_CHPL_TXHPMEVENT0_POS)

#define VT2_CHPL_TXHPMEVENT0_EVENTSEL_POS 0
#define VT2_CHPL_TXHPMEVENT0_EVENTSEL_WID 8
#define VT2_CHPL_TXHPMEVENT0_EVENTSEL_MSK (((_ULL(1) << VT2_CHPL_TXHPMEVENT0_EVENTSEL_WID) - _ULL(1)) << VT2_CHPL_TXHPMEVENT0_EVENTSEL_POS)
#define VT2_CHPL_TXHPMEVENT0_EVENTFILT_POS 8
#define VT2_CHPL_TXHPMEVENT0_EVENTFILT_WID 8
#define VT2_CHPL_TXHPMEVENT0_EVENTFILT_MSK (((_ULL(1) << VT2_CHPL_TXHPMEVENT0_EVENTFILT_WID) - _ULL(1)) << VT2_CHPL_TXHPMEVENT0_EVENTFILT_POS)

#define VT2_CHPL_TXHPMEVENT1_OFFSET _ULL(0x21)

#define VT2_CHPL_TXHPMEVENT1_POS 0
#define VT2_CHPL_TXHPMEVENT1_WID 16
#define VT2_CHPL_TXHPMEVENT1_MSK (((_ULL(1) << VT2_CHPL_TXHPMEVENT1_WID) - _ULL(1)) << VT2_CHPL_TXHPMEVENT1_POS)

#define VT2_CHPL_TXHPMEVENT1_EVENTSEL_POS 0
#define VT2_CHPL_TXHPMEVENT1_EVENTSEL_WID 8
#define VT2_CHPL_TXHPMEVENT1_EVENTSEL_MSK (((_ULL(1) << VT2_CHPL_TXHPMEVENT1_EVENTSEL_WID) - _ULL(1)) << VT2_CHPL_TXHPMEVENT1_EVENTSEL_POS)
#define VT2_CHPL_TXHPMEVENT1_EVENTFILT_POS 8
#define VT2_CHPL_TXHPMEVENT1_EVENTFILT_WID 8
#define VT2_CHPL_TXHPMEVENT1_EVENTFILT_MSK (((_ULL(1) << VT2_CHPL_TXHPMEVENT1_EVENTFILT_WID) - _ULL(1)) << VT2_CHPL_TXHPMEVENT1_EVENTFILT_POS)

#define VT2_CHPL_TXHPMEVENT2_OFFSET _ULL(0x22)

#define VT2_CHPL_TXHPMEVENT2_POS 0
#define VT2_CHPL_TXHPMEVENT2_WID 16
#define VT2_CHPL_TXHPMEVENT2_MSK (((_ULL(1) << VT2_CHPL_TXHPMEVENT2_WID) - _ULL(1)) << VT2_CHPL_TXHPMEVENT2_POS)

#define VT2_CHPL_TXHPMEVENT2_EVENTSEL_POS 0
#define VT2_CHPL_TXHPMEVENT2_EVENTSEL_WID 8
#define VT2_CHPL_TXHPMEVENT2_EVENTSEL_MSK (((_ULL(1) << VT2_CHPL_TXHPMEVENT2_EVENTSEL_WID) - _ULL(1)) << VT2_CHPL_TXHPMEVENT2_EVENTSEL_POS)
#define VT2_CHPL_TXHPMEVENT2_EVENTFILT_POS 8
#define VT2_CHPL_TXHPMEVENT2_EVENTFILT_WID 8
#define VT2_CHPL_TXHPMEVENT2_EVENTFILT_MSK (((_ULL(1) << VT2_CHPL_TXHPMEVENT2_EVENTFILT_WID) - _ULL(1)) << VT2_CHPL_TXHPMEVENT2_EVENTFILT_POS)

#define VT2_CHPL_TXHPMEVENT3_OFFSET _ULL(0x23)

#define VT2_CHPL_TXHPMEVENT3_POS 0
#define VT2_CHPL_TXHPMEVENT3_WID 16
#define VT2_CHPL_TXHPMEVENT3_MSK (((_ULL(1) << VT2_CHPL_TXHPMEVENT3_WID) - _ULL(1)) << VT2_CHPL_TXHPMEVENT3_POS)

#define VT2_CHPL_TXHPMEVENT3_EVENTSEL_POS 0
#define VT2_CHPL_TXHPMEVENT3_EVENTSEL_WID 8
#define VT2_CHPL_TXHPMEVENT3_EVENTSEL_MSK (((_ULL(1) << VT2_CHPL_TXHPMEVENT3_EVENTSEL_WID) - _ULL(1)) << VT2_CHPL_TXHPMEVENT3_EVENTSEL_POS)
#define VT2_CHPL_TXHPMEVENT3_EVENTFILT_POS 8
#define VT2_CHPL_TXHPMEVENT3_EVENTFILT_WID 8
#define VT2_CHPL_TXHPMEVENT3_EVENTFILT_MSK (((_ULL(1) << VT2_CHPL_TXHPMEVENT3_EVENTFILT_WID) - _ULL(1)) << VT2_CHPL_TXHPMEVENT3_EVENTFILT_POS)

#define VT2_CHPL_TXHPMCOUNTLO0_OFFSET _ULL(0x28)

#define VT2_CHPL_TXHPMCOUNTLO0_POS 0
#define VT2_CHPL_TXHPMCOUNTLO0_WID 32
#define VT2_CHPL_TXHPMCOUNTLO0_MSK (((_ULL(1) << VT2_CHPL_TXHPMCOUNTLO0_WID) - _ULL(1)) << VT2_CHPL_TXHPMCOUNTLO0_POS)

#define VT2_CHPL_TXHPMCOUNTLO0_COUNT_POS 0
#define VT2_CHPL_TXHPMCOUNTLO0_COUNT_WID 32
#define VT2_CHPL_TXHPMCOUNTLO0_COUNT_MSK (((_ULL(1) << VT2_CHPL_TXHPMCOUNTLO0_COUNT_WID) - _ULL(1)) << VT2_CHPL_TXHPMCOUNTLO0_COUNT_POS)

#define VT2_CHPL_TXHPMCOUNTHI0_OFFSET _ULL(0x29)

#define VT2_CHPL_TXHPMCOUNTHI0_POS 0
#define VT2_CHPL_TXHPMCOUNTHI0_WID 16
#define VT2_CHPL_TXHPMCOUNTHI0_MSK (((_ULL(1) << VT2_CHPL_TXHPMCOUNTHI0_WID) - _ULL(1)) << VT2_CHPL_TXHPMCOUNTHI0_POS)

#define VT2_CHPL_TXHPMCOUNTHI0_COUNT_POS 0
#define VT2_CHPL_TXHPMCOUNTHI0_COUNT_WID 16
#define VT2_CHPL_TXHPMCOUNTHI0_COUNT_MSK (((_ULL(1) << VT2_CHPL_TXHPMCOUNTHI0_COUNT_WID) - _ULL(1)) << VT2_CHPL_TXHPMCOUNTHI0_COUNT_POS)

#define VT2_CHPL_TXHPMCOUNTLO1_OFFSET _ULL(0x2a)

#define VT2_CHPL_TXHPMCOUNTLO1_POS 0
#define VT2_CHPL_TXHPMCOUNTLO1_WID 32
#define VT2_CHPL_TXHPMCOUNTLO1_MSK (((_ULL(1) << VT2_CHPL_TXHPMCOUNTLO1_WID) - _ULL(1)) << VT2_CHPL_TXHPMCOUNTLO1_POS)

#define VT2_CHPL_TXHPMCOUNTLO1_COUNT_POS 0
#define VT2_CHPL_TXHPMCOUNTLO1_COUNT_WID 32
#define VT2_CHPL_TXHPMCOUNTLO1_COUNT_MSK (((_ULL(1) << VT2_CHPL_TXHPMCOUNTLO1_COUNT_WID) - _ULL(1)) << VT2_CHPL_TXHPMCOUNTLO1_COUNT_POS)

#define VT2_CHPL_TXHPMCOUNTHI1_OFFSET _ULL(0x2b)

#define VT2_CHPL_TXHPMCOUNTHI1_POS 0
#define VT2_CHPL_TXHPMCOUNTHI1_WID 16
#define VT2_CHPL_TXHPMCOUNTHI1_MSK (((_ULL(1) << VT2_CHPL_TXHPMCOUNTHI1_WID) - _ULL(1)) << VT2_CHPL_TXHPMCOUNTHI1_POS)

#define VT2_CHPL_TXHPMCOUNTHI1_COUNT_POS 0
#define VT2_CHPL_TXHPMCOUNTHI1_COUNT_WID 16
#define VT2_CHPL_TXHPMCOUNTHI1_COUNT_MSK (((_ULL(1) << VT2_CHPL_TXHPMCOUNTHI1_COUNT_WID) - _ULL(1)) << VT2_CHPL_TXHPMCOUNTHI1_COUNT_POS)

#define VT2_CHPL_TXHPMCOUNTLO2_OFFSET _ULL(0x2c)

#define VT2_CHPL_TXHPMCOUNTLO2_POS 0
#define VT2_CHPL_TXHPMCOUNTLO2_WID 32
#define VT2_CHPL_TXHPMCOUNTLO2_MSK (((_ULL(1) << VT2_CHPL_TXHPMCOUNTLO2_WID) - _ULL(1)) << VT2_CHPL_TXHPMCOUNTLO2_POS)

#define VT2_CHPL_TXHPMCOUNTLO2_COUNT_POS 0
#define VT2_CHPL_TXHPMCOUNTLO2_COUNT_WID 32
#define VT2_CHPL_TXHPMCOUNTLO2_COUNT_MSK (((_ULL(1) << VT2_CHPL_TXHPMCOUNTLO2_COUNT_WID) - _ULL(1)) << VT2_CHPL_TXHPMCOUNTLO2_COUNT_POS)

#define VT2_CHPL_TXHPMCOUNTHI2_OFFSET _ULL(0x2d)

#define VT2_CHPL_TXHPMCOUNTHI2_POS 0
#define VT2_CHPL_TXHPMCOUNTHI2_WID 16
#define VT2_CHPL_TXHPMCOUNTHI2_MSK (((_ULL(1) << VT2_CHPL_TXHPMCOUNTHI2_WID) - _ULL(1)) << VT2_CHPL_TXHPMCOUNTHI2_POS)

#define VT2_CHPL_TXHPMCOUNTHI2_COUNT_POS 0
#define VT2_CHPL_TXHPMCOUNTHI2_COUNT_WID 16
#define VT2_CHPL_TXHPMCOUNTHI2_COUNT_MSK (((_ULL(1) << VT2_CHPL_TXHPMCOUNTHI2_COUNT_WID) - _ULL(1)) << VT2_CHPL_TXHPMCOUNTHI2_COUNT_POS)

#define VT2_CHPL_TXHPMCOUNTLO3_OFFSET _ULL(0x2e)

#define VT2_CHPL_TXHPMCOUNTLO3_POS 0
#define VT2_CHPL_TXHPMCOUNTLO3_WID 32
#define VT2_CHPL_TXHPMCOUNTLO3_MSK (((_ULL(1) << VT2_CHPL_TXHPMCOUNTLO3_WID) - _ULL(1)) << VT2_CHPL_TXHPMCOUNTLO3_POS)

#define VT2_CHPL_TXHPMCOUNTLO3_COUNT_POS 0
#define VT2_CHPL_TXHPMCOUNTLO3_COUNT_WID 32
#define VT2_CHPL_TXHPMCOUNTLO3_COUNT_MSK (((_ULL(1) << VT2_CHPL_TXHPMCOUNTLO3_COUNT_WID) - _ULL(1)) << VT2_CHPL_TXHPMCOUNTLO3_COUNT_POS)

#define VT2_CHPL_TXHPMCOUNTHI3_OFFSET _ULL(0x2f)

#define VT2_CHPL_TXHPMCOUNTHI3_POS 0
#define VT2_CHPL_TXHPMCOUNTHI3_WID 16
#define VT2_CHPL_TXHPMCOUNTHI3_MSK (((_ULL(1) << VT2_CHPL_TXHPMCOUNTHI3_WID) - _ULL(1)) << VT2_CHPL_TXHPMCOUNTHI3_POS)

#define VT2_CHPL_TXHPMCOUNTHI3_COUNT_POS 0
#define VT2_CHPL_TXHPMCOUNTHI3_COUNT_WID 16
#define VT2_CHPL_TXHPMCOUNTHI3_COUNT_MSK (((_ULL(1) << VT2_CHPL_TXHPMCOUNTHI3_COUNT_WID) - _ULL(1)) << VT2_CHPL_TXHPMCOUNTHI3_COUNT_POS)

#define VT2_CHPL_TXTLPMSG0_OFFSET _ULL(0x40)

#define VT2_CHPL_TXTLPMSG0_POS 0
#define VT2_CHPL_TXTLPMSG0_WID 17
#define VT2_CHPL_TXTLPMSG0_MSK (((_ULL(1) << VT2_CHPL_TXTLPMSG0_WID) - _ULL(1)) << VT2_CHPL_TXTLPMSG0_POS)

#define VT2_CHPL_TXTLPMSG0_MESSAGEDATA_POS 0
#define VT2_CHPL_TXTLPMSG0_MESSAGEDATA_WID 16
#define VT2_CHPL_TXTLPMSG0_MESSAGEDATA_MSK (((_ULL(1) << VT2_CHPL_TXTLPMSG0_MESSAGEDATA_WID) - _ULL(1)) << VT2_CHPL_TXTLPMSG0_MESSAGEDATA_POS)
#define VT2_CHPL_TXTLPMSG0_PENDING_POS 16
#define VT2_CHPL_TXTLPMSG0_PENDING_WID 1
#define VT2_CHPL_TXTLPMSG0_PENDING_MSK (((_ULL(1) << VT2_CHPL_TXTLPMSG0_PENDING_WID) - _ULL(1)) << VT2_CHPL_TXTLPMSG0_PENDING_POS)

#define VT2_CHPL_TXVIRTUALWIREDISABLE00_OFFSET _ULL(0x200)

#define VT2_CHPL_TXVIRTUALWIREDISABLE00_POS 0
#define VT2_CHPL_TXVIRTUALWIREDISABLE00_WID 10
#define VT2_CHPL_TXVIRTUALWIREDISABLE00_MSK (((_ULL(1) << VT2_CHPL_TXVIRTUALWIREDISABLE00_WID) - _ULL(1)) << VT2_CHPL_TXVIRTUALWIREDISABLE00_POS)

#define VT2_CHPL_TXVIRTUALWIREDISABLE00_DISABLE_POS 0
#define VT2_CHPL_TXVIRTUALWIREDISABLE00_DISABLE_WID 10
#define VT2_CHPL_TXVIRTUALWIREDISABLE00_DISABLE_MSK (((_ULL(1) << VT2_CHPL_TXVIRTUALWIREDISABLE00_DISABLE_WID) - _ULL(1)) << VT2_CHPL_TXVIRTUALWIREDISABLE00_DISABLE_POS)

#define VT2_CHPL_TXVIRTUALWIRESET00_OFFSET _ULL(0x220)

#define VT2_CHPL_TXVIRTUALWIRESET00_POS 0
#define VT2_CHPL_TXVIRTUALWIRESET00_WID 10
#define VT2_CHPL_TXVIRTUALWIRESET00_MSK (((_ULL(1) << VT2_CHPL_TXVIRTUALWIRESET00_WID) - _ULL(1)) << VT2_CHPL_TXVIRTUALWIRESET00_POS)

#define VT2_CHPL_TXVIRTUALWIRESET00_WIRE_POS 0
#define VT2_CHPL_TXVIRTUALWIRESET00_WIRE_WID 10
#define VT2_CHPL_TXVIRTUALWIRESET00_WIRE_MSK (((_ULL(1) << VT2_CHPL_TXVIRTUALWIRESET00_WIRE_WID) - _ULL(1)) << VT2_CHPL_TXVIRTUALWIRESET00_WIRE_POS)

#define VT2_CHPL_TXVIRTUALWIRECLEAR00_OFFSET _ULL(0x240)

#define VT2_CHPL_TXVIRTUALWIRECLEAR00_POS 0
#define VT2_CHPL_TXVIRTUALWIRECLEAR00_WID 10
#define VT2_CHPL_TXVIRTUALWIRECLEAR00_MSK (((_ULL(1) << VT2_CHPL_TXVIRTUALWIRECLEAR00_WID) - _ULL(1)) << VT2_CHPL_TXVIRTUALWIRECLEAR00_POS)

#define VT2_CHPL_TXVIRTUALWIRECLEAR00_WIRE_POS 0
#define VT2_CHPL_TXVIRTUALWIRECLEAR00_WIRE_WID 10
#define VT2_CHPL_TXVIRTUALWIRECLEAR00_WIRE_MSK (((_ULL(1) << VT2_CHPL_TXVIRTUALWIRECLEAR00_WIRE_WID) - _ULL(1)) << VT2_CHPL_TXVIRTUALWIRECLEAR00_WIRE_POS)

#define VT2_CHPL_TXNEARCREDITTHRESHOLD08_OFFSET _ULL(0x348)

#define VT2_CHPL_TXNEARCREDITTHRESHOLD08_POS 0
#define VT2_CHPL_TXNEARCREDITTHRESHOLD08_WID 8
#define VT2_CHPL_TXNEARCREDITTHRESHOLD08_MSK (((_ULL(1) << VT2_CHPL_TXNEARCREDITTHRESHOLD08_WID) - _ULL(1)) << VT2_CHPL_TXNEARCREDITTHRESHOLD08_POS)

#define VT2_CHPL_TXNEARCREDITTHRESHOLD08_THRESHOLD_POS 0
#define VT2_CHPL_TXNEARCREDITTHRESHOLD08_THRESHOLD_WID 8
#define VT2_CHPL_TXNEARCREDITTHRESHOLD08_THRESHOLD_MSK (((_ULL(1) << VT2_CHPL_TXNEARCREDITTHRESHOLD08_THRESHOLD_WID) - _ULL(1)) << VT2_CHPL_TXNEARCREDITTHRESHOLD08_THRESHOLD_POS)

#define VT2_CHPL_TXNEARCREDITTHRESHOLD09_OFFSET _ULL(0x349)

#define VT2_CHPL_TXNEARCREDITTHRESHOLD09_POS 0
#define VT2_CHPL_TXNEARCREDITTHRESHOLD09_WID 8
#define VT2_CHPL_TXNEARCREDITTHRESHOLD09_MSK (((_ULL(1) << VT2_CHPL_TXNEARCREDITTHRESHOLD09_WID) - _ULL(1)) << VT2_CHPL_TXNEARCREDITTHRESHOLD09_POS)

#define VT2_CHPL_TXNEARCREDITTHRESHOLD09_THRESHOLD_POS 0
#define VT2_CHPL_TXNEARCREDITTHRESHOLD09_THRESHOLD_WID 8
#define VT2_CHPL_TXNEARCREDITTHRESHOLD09_THRESHOLD_MSK (((_ULL(1) << VT2_CHPL_TXNEARCREDITTHRESHOLD09_THRESHOLD_WID) - _ULL(1)) << VT2_CHPL_TXNEARCREDITTHRESHOLD09_THRESHOLD_POS)

#define VT2_CHPL_TXNEARCREDITTHRESHOLD0A_OFFSET _ULL(0x34a)

#define VT2_CHPL_TXNEARCREDITTHRESHOLD0A_POS 0
#define VT2_CHPL_TXNEARCREDITTHRESHOLD0A_WID 8
#define VT2_CHPL_TXNEARCREDITTHRESHOLD0A_MSK (((_ULL(1) << VT2_CHPL_TXNEARCREDITTHRESHOLD0A_WID) - _ULL(1)) << VT2_CHPL_TXNEARCREDITTHRESHOLD0A_POS)

#define VT2_CHPL_TXNEARCREDITTHRESHOLD0A_THRESHOLD_POS 0
#define VT2_CHPL_TXNEARCREDITTHRESHOLD0A_THRESHOLD_WID 8
#define VT2_CHPL_TXNEARCREDITTHRESHOLD0A_THRESHOLD_MSK (((_ULL(1) << VT2_CHPL_TXNEARCREDITTHRESHOLD0A_THRESHOLD_WID) - _ULL(1)) << VT2_CHPL_TXNEARCREDITTHRESHOLD0A_THRESHOLD_POS)

#define VT2_CHPL_TXNEARCREDITTHRESHOLD0B_OFFSET _ULL(0x34b)

#define VT2_CHPL_TXNEARCREDITTHRESHOLD0B_POS 0
#define VT2_CHPL_TXNEARCREDITTHRESHOLD0B_WID 8
#define VT2_CHPL_TXNEARCREDITTHRESHOLD0B_MSK (((_ULL(1) << VT2_CHPL_TXNEARCREDITTHRESHOLD0B_WID) - _ULL(1)) << VT2_CHPL_TXNEARCREDITTHRESHOLD0B_POS)

#define VT2_CHPL_TXNEARCREDITTHRESHOLD0B_THRESHOLD_POS 0
#define VT2_CHPL_TXNEARCREDITTHRESHOLD0B_THRESHOLD_WID 8
#define VT2_CHPL_TXNEARCREDITTHRESHOLD0B_THRESHOLD_MSK (((_ULL(1) << VT2_CHPL_TXNEARCREDITTHRESHOLD0B_THRESHOLD_WID) - _ULL(1)) << VT2_CHPL_TXNEARCREDITTHRESHOLD0B_THRESHOLD_POS)

#define VT2_CHPL_TXNEARCREDITTHRESHOLD22_OFFSET _ULL(0x362)

#define VT2_CHPL_TXNEARCREDITTHRESHOLD22_POS 0
#define VT2_CHPL_TXNEARCREDITTHRESHOLD22_WID 8
#define VT2_CHPL_TXNEARCREDITTHRESHOLD22_MSK (((_ULL(1) << VT2_CHPL_TXNEARCREDITTHRESHOLD22_WID) - _ULL(1)) << VT2_CHPL_TXNEARCREDITTHRESHOLD22_POS)

#define VT2_CHPL_TXNEARCREDITTHRESHOLD22_THRESHOLD_POS 0
#define VT2_CHPL_TXNEARCREDITTHRESHOLD22_THRESHOLD_WID 8
#define VT2_CHPL_TXNEARCREDITTHRESHOLD22_THRESHOLD_MSK (((_ULL(1) << VT2_CHPL_TXNEARCREDITTHRESHOLD22_THRESHOLD_WID) - _ULL(1)) << VT2_CHPL_TXNEARCREDITTHRESHOLD22_THRESHOLD_POS)

#define VT2_CHPL_TXNEARCREDITTHRESHOLD24_OFFSET _ULL(0x364)

#define VT2_CHPL_TXNEARCREDITTHRESHOLD24_POS 0
#define VT2_CHPL_TXNEARCREDITTHRESHOLD24_WID 8
#define VT2_CHPL_TXNEARCREDITTHRESHOLD24_MSK (((_ULL(1) << VT2_CHPL_TXNEARCREDITTHRESHOLD24_WID) - _ULL(1)) << VT2_CHPL_TXNEARCREDITTHRESHOLD24_POS)

#define VT2_CHPL_TXNEARCREDITTHRESHOLD24_THRESHOLD_POS 0
#define VT2_CHPL_TXNEARCREDITTHRESHOLD24_THRESHOLD_WID 8
#define VT2_CHPL_TXNEARCREDITTHRESHOLD24_THRESHOLD_MSK (((_ULL(1) << VT2_CHPL_TXNEARCREDITTHRESHOLD24_THRESHOLD_WID) - _ULL(1)) << VT2_CHPL_TXNEARCREDITTHRESHOLD24_THRESHOLD_POS)

#define VT2_CHPL_TXNEARCREDITTHRESHOLD26_OFFSET _ULL(0x366)

#define VT2_CHPL_TXNEARCREDITTHRESHOLD26_POS 0
#define VT2_CHPL_TXNEARCREDITTHRESHOLD26_WID 8
#define VT2_CHPL_TXNEARCREDITTHRESHOLD26_MSK (((_ULL(1) << VT2_CHPL_TXNEARCREDITTHRESHOLD26_WID) - _ULL(1)) << VT2_CHPL_TXNEARCREDITTHRESHOLD26_POS)

#define VT2_CHPL_TXNEARCREDITTHRESHOLD26_THRESHOLD_POS 0
#define VT2_CHPL_TXNEARCREDITTHRESHOLD26_THRESHOLD_WID 8
#define VT2_CHPL_TXNEARCREDITTHRESHOLD26_THRESHOLD_MSK (((_ULL(1) << VT2_CHPL_TXNEARCREDITTHRESHOLD26_THRESHOLD_WID) - _ULL(1)) << VT2_CHPL_TXNEARCREDITTHRESHOLD26_THRESHOLD_POS)

#define VT2_CHPL_TXNEARCREDITCOUNT08_OFFSET _ULL(0x388)

#define VT2_CHPL_TXNEARCREDITCOUNT08_POS 0
#define VT2_CHPL_TXNEARCREDITCOUNT08_WID 8
#define VT2_CHPL_TXNEARCREDITCOUNT08_MSK (((_ULL(1) << VT2_CHPL_TXNEARCREDITCOUNT08_WID) - _ULL(1)) << VT2_CHPL_TXNEARCREDITCOUNT08_POS)

#define VT2_CHPL_TXNEARCREDITCOUNT08_COUNT_POS 0
#define VT2_CHPL_TXNEARCREDITCOUNT08_COUNT_WID 8
#define VT2_CHPL_TXNEARCREDITCOUNT08_COUNT_MSK (((_ULL(1) << VT2_CHPL_TXNEARCREDITCOUNT08_COUNT_WID) - _ULL(1)) << VT2_CHPL_TXNEARCREDITCOUNT08_COUNT_POS)

#define VT2_CHPL_TXNEARCREDITCOUNT09_OFFSET _ULL(0x389)

#define VT2_CHPL_TXNEARCREDITCOUNT09_POS 0
#define VT2_CHPL_TXNEARCREDITCOUNT09_WID 8
#define VT2_CHPL_TXNEARCREDITCOUNT09_MSK (((_ULL(1) << VT2_CHPL_TXNEARCREDITCOUNT09_WID) - _ULL(1)) << VT2_CHPL_TXNEARCREDITCOUNT09_POS)

#define VT2_CHPL_TXNEARCREDITCOUNT09_COUNT_POS 0
#define VT2_CHPL_TXNEARCREDITCOUNT09_COUNT_WID 8
#define VT2_CHPL_TXNEARCREDITCOUNT09_COUNT_MSK (((_ULL(1) << VT2_CHPL_TXNEARCREDITCOUNT09_COUNT_WID) - _ULL(1)) << VT2_CHPL_TXNEARCREDITCOUNT09_COUNT_POS)

#define VT2_CHPL_TXNEARCREDITCOUNT0A_OFFSET _ULL(0x38a)

#define VT2_CHPL_TXNEARCREDITCOUNT0A_POS 0
#define VT2_CHPL_TXNEARCREDITCOUNT0A_WID 8
#define VT2_CHPL_TXNEARCREDITCOUNT0A_MSK (((_ULL(1) << VT2_CHPL_TXNEARCREDITCOUNT0A_WID) - _ULL(1)) << VT2_CHPL_TXNEARCREDITCOUNT0A_POS)

#define VT2_CHPL_TXNEARCREDITCOUNT0A_COUNT_POS 0
#define VT2_CHPL_TXNEARCREDITCOUNT0A_COUNT_WID 8
#define VT2_CHPL_TXNEARCREDITCOUNT0A_COUNT_MSK (((_ULL(1) << VT2_CHPL_TXNEARCREDITCOUNT0A_COUNT_WID) - _ULL(1)) << VT2_CHPL_TXNEARCREDITCOUNT0A_COUNT_POS)

#define VT2_CHPL_TXNEARCREDITCOUNT0B_OFFSET _ULL(0x38b)

#define VT2_CHPL_TXNEARCREDITCOUNT0B_POS 0
#define VT2_CHPL_TXNEARCREDITCOUNT0B_WID 8
#define VT2_CHPL_TXNEARCREDITCOUNT0B_MSK (((_ULL(1) << VT2_CHPL_TXNEARCREDITCOUNT0B_WID) - _ULL(1)) << VT2_CHPL_TXNEARCREDITCOUNT0B_POS)

#define VT2_CHPL_TXNEARCREDITCOUNT0B_COUNT_POS 0
#define VT2_CHPL_TXNEARCREDITCOUNT0B_COUNT_WID 8
#define VT2_CHPL_TXNEARCREDITCOUNT0B_COUNT_MSK (((_ULL(1) << VT2_CHPL_TXNEARCREDITCOUNT0B_COUNT_WID) - _ULL(1)) << VT2_CHPL_TXNEARCREDITCOUNT0B_COUNT_POS)

#define VT2_CHPL_TXNEARCREDITCOUNT22_OFFSET _ULL(0x3a2)

#define VT2_CHPL_TXNEARCREDITCOUNT22_POS 0
#define VT2_CHPL_TXNEARCREDITCOUNT22_WID 8
#define VT2_CHPL_TXNEARCREDITCOUNT22_MSK (((_ULL(1) << VT2_CHPL_TXNEARCREDITCOUNT22_WID) - _ULL(1)) << VT2_CHPL_TXNEARCREDITCOUNT22_POS)

#define VT2_CHPL_TXNEARCREDITCOUNT22_COUNT_POS 0
#define VT2_CHPL_TXNEARCREDITCOUNT22_COUNT_WID 8
#define VT2_CHPL_TXNEARCREDITCOUNT22_COUNT_MSK (((_ULL(1) << VT2_CHPL_TXNEARCREDITCOUNT22_COUNT_WID) - _ULL(1)) << VT2_CHPL_TXNEARCREDITCOUNT22_COUNT_POS)

#define VT2_CHPL_TXNEARCREDITCOUNT24_OFFSET _ULL(0x3a4)

#define VT2_CHPL_TXNEARCREDITCOUNT24_POS 0
#define VT2_CHPL_TXNEARCREDITCOUNT24_WID 8
#define VT2_CHPL_TXNEARCREDITCOUNT24_MSK (((_ULL(1) << VT2_CHPL_TXNEARCREDITCOUNT24_WID) - _ULL(1)) << VT2_CHPL_TXNEARCREDITCOUNT24_POS)

#define VT2_CHPL_TXNEARCREDITCOUNT24_COUNT_POS 0
#define VT2_CHPL_TXNEARCREDITCOUNT24_COUNT_WID 8
#define VT2_CHPL_TXNEARCREDITCOUNT24_COUNT_MSK (((_ULL(1) << VT2_CHPL_TXNEARCREDITCOUNT24_COUNT_WID) - _ULL(1)) << VT2_CHPL_TXNEARCREDITCOUNT24_COUNT_POS)

#define VT2_CHPL_TXNEARCREDITCOUNT26_OFFSET _ULL(0x3a6)

#define VT2_CHPL_TXNEARCREDITCOUNT26_POS 0
#define VT2_CHPL_TXNEARCREDITCOUNT26_WID 8
#define VT2_CHPL_TXNEARCREDITCOUNT26_MSK (((_ULL(1) << VT2_CHPL_TXNEARCREDITCOUNT26_WID) - _ULL(1)) << VT2_CHPL_TXNEARCREDITCOUNT26_POS)

#define VT2_CHPL_TXNEARCREDITCOUNT26_COUNT_POS 0
#define VT2_CHPL_TXNEARCREDITCOUNT26_COUNT_WID 8
#define VT2_CHPL_TXNEARCREDITCOUNT26_COUNT_MSK (((_ULL(1) << VT2_CHPL_TXNEARCREDITCOUNT26_COUNT_WID) - _ULL(1)) << VT2_CHPL_TXNEARCREDITCOUNT26_COUNT_POS)

#define VT2_CHPL_TXFARCREDITCOUNT08_OFFSET _ULL(0x3c8)

#define VT2_CHPL_TXFARCREDITCOUNT08_POS 0
#define VT2_CHPL_TXFARCREDITCOUNT08_WID 8
#define VT2_CHPL_TXFARCREDITCOUNT08_MSK (((_ULL(1) << VT2_CHPL_TXFARCREDITCOUNT08_WID) - _ULL(1)) << VT2_CHPL_TXFARCREDITCOUNT08_POS)

#define VT2_CHPL_TXFARCREDITCOUNT08_COUNT_POS 0
#define VT2_CHPL_TXFARCREDITCOUNT08_COUNT_WID 8
#define VT2_CHPL_TXFARCREDITCOUNT08_COUNT_MSK (((_ULL(1) << VT2_CHPL_TXFARCREDITCOUNT08_COUNT_WID) - _ULL(1)) << VT2_CHPL_TXFARCREDITCOUNT08_COUNT_POS)

#define VT2_CHPL_TXFARCREDITCOUNT09_OFFSET _ULL(0x3c9)

#define VT2_CHPL_TXFARCREDITCOUNT09_POS 0
#define VT2_CHPL_TXFARCREDITCOUNT09_WID 8
#define VT2_CHPL_TXFARCREDITCOUNT09_MSK (((_ULL(1) << VT2_CHPL_TXFARCREDITCOUNT09_WID) - _ULL(1)) << VT2_CHPL_TXFARCREDITCOUNT09_POS)

#define VT2_CHPL_TXFARCREDITCOUNT09_COUNT_POS 0
#define VT2_CHPL_TXFARCREDITCOUNT09_COUNT_WID 8
#define VT2_CHPL_TXFARCREDITCOUNT09_COUNT_MSK (((_ULL(1) << VT2_CHPL_TXFARCREDITCOUNT09_COUNT_WID) - _ULL(1)) << VT2_CHPL_TXFARCREDITCOUNT09_COUNT_POS)

#define VT2_CHPL_TXFARCREDITCOUNT0A_OFFSET _ULL(0x3ca)

#define VT2_CHPL_TXFARCREDITCOUNT0A_POS 0
#define VT2_CHPL_TXFARCREDITCOUNT0A_WID 8
#define VT2_CHPL_TXFARCREDITCOUNT0A_MSK (((_ULL(1) << VT2_CHPL_TXFARCREDITCOUNT0A_WID) - _ULL(1)) << VT2_CHPL_TXFARCREDITCOUNT0A_POS)

#define VT2_CHPL_TXFARCREDITCOUNT0A_COUNT_POS 0
#define VT2_CHPL_TXFARCREDITCOUNT0A_COUNT_WID 8
#define VT2_CHPL_TXFARCREDITCOUNT0A_COUNT_MSK (((_ULL(1) << VT2_CHPL_TXFARCREDITCOUNT0A_COUNT_WID) - _ULL(1)) << VT2_CHPL_TXFARCREDITCOUNT0A_COUNT_POS)

#define VT2_CHPL_TXFARCREDITCOUNT0B_OFFSET _ULL(0x3cb)

#define VT2_CHPL_TXFARCREDITCOUNT0B_POS 0
#define VT2_CHPL_TXFARCREDITCOUNT0B_WID 8
#define VT2_CHPL_TXFARCREDITCOUNT0B_MSK (((_ULL(1) << VT2_CHPL_TXFARCREDITCOUNT0B_WID) - _ULL(1)) << VT2_CHPL_TXFARCREDITCOUNT0B_POS)

#define VT2_CHPL_TXFARCREDITCOUNT0B_COUNT_POS 0
#define VT2_CHPL_TXFARCREDITCOUNT0B_COUNT_WID 8
#define VT2_CHPL_TXFARCREDITCOUNT0B_COUNT_MSK (((_ULL(1) << VT2_CHPL_TXFARCREDITCOUNT0B_COUNT_WID) - _ULL(1)) << VT2_CHPL_TXFARCREDITCOUNT0B_COUNT_POS)

#define VT2_CHPL_TXFARCREDITCOUNT20_OFFSET _ULL(0x3e0)

#define VT2_CHPL_TXFARCREDITCOUNT20_POS 0
#define VT2_CHPL_TXFARCREDITCOUNT20_WID 8
#define VT2_CHPL_TXFARCREDITCOUNT20_MSK (((_ULL(1) << VT2_CHPL_TXFARCREDITCOUNT20_WID) - _ULL(1)) << VT2_CHPL_TXFARCREDITCOUNT20_POS)

#define VT2_CHPL_TXFARCREDITCOUNT20_COUNT_POS 0
#define VT2_CHPL_TXFARCREDITCOUNT20_COUNT_WID 8
#define VT2_CHPL_TXFARCREDITCOUNT20_COUNT_MSK (((_ULL(1) << VT2_CHPL_TXFARCREDITCOUNT20_COUNT_WID) - _ULL(1)) << VT2_CHPL_TXFARCREDITCOUNT20_COUNT_POS)

#define VT2_CHPL_TXFARCREDITCOUNT24_OFFSET _ULL(0x3e4)

#define VT2_CHPL_TXFARCREDITCOUNT24_POS 0
#define VT2_CHPL_TXFARCREDITCOUNT24_WID 8
#define VT2_CHPL_TXFARCREDITCOUNT24_MSK (((_ULL(1) << VT2_CHPL_TXFARCREDITCOUNT24_WID) - _ULL(1)) << VT2_CHPL_TXFARCREDITCOUNT24_POS)

#define VT2_CHPL_TXFARCREDITCOUNT24_COUNT_POS 0
#define VT2_CHPL_TXFARCREDITCOUNT24_COUNT_WID 8
#define VT2_CHPL_TXFARCREDITCOUNT24_COUNT_MSK (((_ULL(1) << VT2_CHPL_TXFARCREDITCOUNT24_COUNT_WID) - _ULL(1)) << VT2_CHPL_TXFARCREDITCOUNT24_COUNT_POS)

#define VT2_CHPL_TXFARCREDITCOUNT26_OFFSET _ULL(0x3e6)

#define VT2_CHPL_TXFARCREDITCOUNT26_POS 0
#define VT2_CHPL_TXFARCREDITCOUNT26_WID 8
#define VT2_CHPL_TXFARCREDITCOUNT26_MSK (((_ULL(1) << VT2_CHPL_TXFARCREDITCOUNT26_WID) - _ULL(1)) << VT2_CHPL_TXFARCREDITCOUNT26_POS)

#define VT2_CHPL_TXFARCREDITCOUNT26_COUNT_POS 0
#define VT2_CHPL_TXFARCREDITCOUNT26_COUNT_WID 8
#define VT2_CHPL_TXFARCREDITCOUNT26_COUNT_MSK (((_ULL(1) << VT2_CHPL_TXFARCREDITCOUNT26_COUNT_WID) - _ULL(1)) << VT2_CHPL_TXFARCREDITCOUNT26_COUNT_POS)

#define VT2_CHPL_RXID_OFFSET _ULL(0x400)

#define VT2_CHPL_RXID_POS 0
#define VT2_CHPL_RXID_WID 28
#define VT2_CHPL_RXID_MSK (((_ULL(1) << VT2_CHPL_RXID_WID) - _ULL(1)) << VT2_CHPL_RXID_POS)

#define VT2_CHPL_RXID_VERSION_POS 0
#define VT2_CHPL_RXID_VERSION_WID 8
#define VT2_CHPL_RXID_VERSION_MSK (((_ULL(1) << VT2_CHPL_RXID_VERSION_WID) - _ULL(1)) << VT2_CHPL_RXID_VERSION_POS)
#define VT2_CHPL_RXID_IMPLEMENTATION_POS 8
#define VT2_CHPL_RXID_IMPLEMENTATION_WID 8
#define VT2_CHPL_RXID_IMPLEMENTATION_MSK (((_ULL(1) << VT2_CHPL_RXID_IMPLEMENTATION_WID) - _ULL(1)) << VT2_CHPL_RXID_IMPLEMENTATION_POS)
#define VT2_CHPL_RXID_FRAGMENTMAP_POS 16
#define VT2_CHPL_RXID_FRAGMENTMAP_WID 12
#define VT2_CHPL_RXID_FRAGMENTMAP_MSK (((_ULL(1) << VT2_CHPL_RXID_FRAGMENTMAP_WID) - _ULL(1)) << VT2_CHPL_RXID_FRAGMENTMAP_POS)

#define VT2_CHPL_RXINTERFACECONTROLSTATUS_OFFSET _ULL(0x401)

#define VT2_CHPL_RXINTERFACECONTROLSTATUS_POS 0
#define VT2_CHPL_RXINTERFACECONTROLSTATUS_WID 7
#define VT2_CHPL_RXINTERFACECONTROLSTATUS_MSK (((_ULL(1) << VT2_CHPL_RXINTERFACECONTROLSTATUS_WID) - _ULL(1)) << VT2_CHPL_RXINTERFACECONTROLSTATUS_POS)

#define VT2_CHPL_RXINTERFACECONTROLSTATUS_DATAWIDTH_POS 0
#define VT2_CHPL_RXINTERFACECONTROLSTATUS_DATAWIDTH_WID 2
#define VT2_CHPL_RXINTERFACECONTROLSTATUS_DATAWIDTH_MSK (((_ULL(1) << VT2_CHPL_RXINTERFACECONTROLSTATUS_DATAWIDTH_WID) - _ULL(1)) << VT2_CHPL_RXINTERFACECONTROLSTATUS_DATAWIDTH_POS)
#define VT2_CHPL_RXINTERFACECONTROLSTATUS_RXACTIVE_POS 2
#define VT2_CHPL_RXINTERFACECONTROLSTATUS_RXACTIVE_WID 1
#define VT2_CHPL_RXINTERFACECONTROLSTATUS_RXACTIVE_MSK (((_ULL(1) << VT2_CHPL_RXINTERFACECONTROLSTATUS_RXACTIVE_WID) - _ULL(1)) << VT2_CHPL_RXINTERFACECONTROLSTATUS_RXACTIVE_POS)
#define VT2_CHPL_RXINTERFACECONTROLSTATUS_PIPEFOLDINGDISABLE_POS 3
#define VT2_CHPL_RXINTERFACECONTROLSTATUS_PIPEFOLDINGDISABLE_WID 1
#define VT2_CHPL_RXINTERFACECONTROLSTATUS_PIPEFOLDINGDISABLE_MSK (((_ULL(1) << VT2_CHPL_RXINTERFACECONTROLSTATUS_PIPEFOLDINGDISABLE_WID) - _ULL(1)) << VT2_CHPL_RXINTERFACECONTROLSTATUS_PIPEFOLDINGDISABLE_POS)
#define VT2_CHPL_RXINTERFACECONTROLSTATUS_LINKRESET_POS 4
#define VT2_CHPL_RXINTERFACECONTROLSTATUS_LINKRESET_WID 1
#define VT2_CHPL_RXINTERFACECONTROLSTATUS_LINKRESET_MSK (((_ULL(1) << VT2_CHPL_RXINTERFACECONTROLSTATUS_LINKRESET_WID) - _ULL(1)) << VT2_CHPL_RXINTERFACECONTROLSTATUS_LINKRESET_POS)
#define VT2_CHPL_RXINTERFACECONTROLSTATUS_PHYREADY_POS 5
#define VT2_CHPL_RXINTERFACECONTROLSTATUS_PHYREADY_WID 2
#define VT2_CHPL_RXINTERFACECONTROLSTATUS_PHYREADY_MSK (((_ULL(1) << VT2_CHPL_RXINTERFACECONTROLSTATUS_PHYREADY_WID) - _ULL(1)) << VT2_CHPL_RXINTERFACECONTROLSTATUS_PHYREADY_POS)

#define VT2_CHPL_DDIFRASBANK0CTRL_OFFSET _ULL(0x408)

#define VT2_CHPL_DDIFRASBANK0CTRL_POS 0
#define VT2_CHPL_DDIFRASBANK0CTRL_WID 32
#define VT2_CHPL_DDIFRASBANK0CTRL_MSK (((_ULL(1) << VT2_CHPL_DDIFRASBANK0CTRL_WID) - _ULL(1)) << VT2_CHPL_DDIFRASBANK0CTRL_POS)

#define VT2_CHPL_DDIFRASBANK0CTRL_CORRRECOVDIS_POS 0
#define VT2_CHPL_DDIFRASBANK0CTRL_CORRRECOVDIS_WID 1
#define VT2_CHPL_DDIFRASBANK0CTRL_CORRRECOVDIS_MSK (((_ULL(1) << VT2_CHPL_DDIFRASBANK0CTRL_CORRRECOVDIS_WID) - _ULL(1)) << VT2_CHPL_DDIFRASBANK0CTRL_CORRRECOVDIS_POS)
#define VT2_CHPL_DDIFRASBANK0CTRL_LOGEN_POS 1
#define VT2_CHPL_DDIFRASBANK0CTRL_LOGEN_WID 1
#define VT2_CHPL_DDIFRASBANK0CTRL_LOGEN_MSK (((_ULL(1) << VT2_CHPL_DDIFRASBANK0CTRL_LOGEN_WID) - _ULL(1)) << VT2_CHPL_DDIFRASBANK0CTRL_LOGEN_POS)
#define VT2_CHPL_DDIFRASBANK0CTRL_NMIEN_POS 2
#define VT2_CHPL_DDIFRASBANK0CTRL_NMIEN_WID 1
#define VT2_CHPL_DDIFRASBANK0CTRL_NMIEN_MSK (((_ULL(1) << VT2_CHPL_DDIFRASBANK0CTRL_NMIEN_WID) - _ULL(1)) << VT2_CHPL_DDIFRASBANK0CTRL_NMIEN_POS)
#define VT2_CHPL_DDIFRASBANK0CTRL_FATALERRINTREN_POS 3
#define VT2_CHPL_DDIFRASBANK0CTRL_FATALERRINTREN_WID 1
#define VT2_CHPL_DDIFRASBANK0CTRL_FATALERRINTREN_MSK (((_ULL(1) << VT2_CHPL_DDIFRASBANK0CTRL_FATALERRINTREN_WID) - _ULL(1)) << VT2_CHPL_DDIFRASBANK0CTRL_FATALERRINTREN_POS)
#define VT2_CHPL_DDIFRASBANK0CTRL_NONCRITERRINTREN_POS 4
#define VT2_CHPL_DDIFRASBANK0CTRL_NONCRITERRINTREN_WID 1
#define VT2_CHPL_DDIFRASBANK0CTRL_NONCRITERRINTREN_MSK (((_ULL(1) << VT2_CHPL_DDIFRASBANK0CTRL_NONCRITERRINTREN_WID) - _ULL(1)) << VT2_CHPL_DDIFRASBANK0CTRL_NONCRITERRINTREN_POS)
#define VT2_CHPL_DDIFRASBANK0CTRL_RSVD_POS 5
#define VT2_CHPL_DDIFRASBANK0CTRL_RSVD_WID 6
#define VT2_CHPL_DDIFRASBANK0CTRL_RSVD_MSK (((_ULL(1) << VT2_CHPL_DDIFRASBANK0CTRL_RSVD_WID) - _ULL(1)) << VT2_CHPL_DDIFRASBANK0CTRL_RSVD_POS)
#define VT2_CHPL_DDIFRASBANK0CTRL_TOTALBANKS_POS 11
#define VT2_CHPL_DDIFRASBANK0CTRL_TOTALBANKS_WID 5
#define VT2_CHPL_DDIFRASBANK0CTRL_TOTALBANKS_MSK (((_ULL(1) << VT2_CHPL_DDIFRASBANK0CTRL_TOTALBANKS_WID) - _ULL(1)) << VT2_CHPL_DDIFRASBANK0CTRL_TOTALBANKS_POS)
#define VT2_CHPL_DDIFRASBANK0CTRL_ERRINJECTDLY_POS 16
#define VT2_CHPL_DDIFRASBANK0CTRL_ERRINJECTDLY_WID 16
#define VT2_CHPL_DDIFRASBANK0CTRL_ERRINJECTDLY_MSK (((_ULL(1) << VT2_CHPL_DDIFRASBANK0CTRL_ERRINJECTDLY_WID) - _ULL(1)) << VT2_CHPL_DDIFRASBANK0CTRL_ERRINJECTDLY_POS)

#define VT2_CHPL_DDIFRASBANK0STATUS_OFFSET _ULL(0x409)

#define VT2_CHPL_DDIFRASBANK0STATUS_POS 0
#define VT2_CHPL_DDIFRASBANK0STATUS_WID 32
#define VT2_CHPL_DDIFRASBANK0STATUS_MSK (((_ULL(1) << VT2_CHPL_DDIFRASBANK0STATUS_WID) - _ULL(1)) << VT2_CHPL_DDIFRASBANK0STATUS_POS)

#define VT2_CHPL_DDIFRASBANK0STATUS_VALID_POS 0
#define VT2_CHPL_DDIFRASBANK0STATUS_VALID_WID 1
#define VT2_CHPL_DDIFRASBANK0STATUS_VALID_MSK (((_ULL(1) << VT2_CHPL_DDIFRASBANK0STATUS_VALID_WID) - _ULL(1)) << VT2_CHPL_DDIFRASBANK0STATUS_VALID_POS)
#define VT2_CHPL_DDIFRASBANK0STATUS_RECENTERR_POS 1
#define VT2_CHPL_DDIFRASBANK0STATUS_RECENTERR_WID 1
#define VT2_CHPL_DDIFRASBANK0STATUS_RECENTERR_MSK (((_ULL(1) << VT2_CHPL_DDIFRASBANK0STATUS_RECENTERR_WID) - _ULL(1)) << VT2_CHPL_DDIFRASBANK0STATUS_RECENTERR_POS)
#define VT2_CHPL_DDIFRASBANK0STATUS_NMIPEND_POS 2
#define VT2_CHPL_DDIFRASBANK0STATUS_NMIPEND_WID 1
#define VT2_CHPL_DDIFRASBANK0STATUS_NMIPEND_MSK (((_ULL(1) << VT2_CHPL_DDIFRASBANK0STATUS_NMIPEND_WID) - _ULL(1)) << VT2_CHPL_DDIFRASBANK0STATUS_NMIPEND_POS)
#define VT2_CHPL_DDIFRASBANK0STATUS_FATALERRINTRPEND_POS 3
#define VT2_CHPL_DDIFRASBANK0STATUS_FATALERRINTRPEND_WID 1
#define VT2_CHPL_DDIFRASBANK0STATUS_FATALERRINTRPEND_MSK (((_ULL(1) << VT2_CHPL_DDIFRASBANK0STATUS_FATALERRINTRPEND_WID) - _ULL(1)) << VT2_CHPL_DDIFRASBANK0STATUS_FATALERRINTRPEND_POS)
#define VT2_CHPL_DDIFRASBANK0STATUS_NONCRITERRINTRPEND_POS 4
#define VT2_CHPL_DDIFRASBANK0STATUS_NONCRITERRINTRPEND_WID 1
#define VT2_CHPL_DDIFRASBANK0STATUS_NONCRITERRINTRPEND_MSK (((_ULL(1) << VT2_CHPL_DDIFRASBANK0STATUS_NONCRITERRINTRPEND_WID) - _ULL(1)) << VT2_CHPL_DDIFRASBANK0STATUS_NONCRITERRINTRPEND_POS)
#define VT2_CHPL_DDIFRASBANK0STATUS_BANKSTATUS_POS 5
#define VT2_CHPL_DDIFRASBANK0STATUS_BANKSTATUS_WID 27
#define VT2_CHPL_DDIFRASBANK0STATUS_BANKSTATUS_MSK (((_ULL(1) << VT2_CHPL_DDIFRASBANK0STATUS_BANKSTATUS_WID) - _ULL(1)) << VT2_CHPL_DDIFRASBANK0STATUS_BANKSTATUS_POS)

#define VT2_CHPL_DDIFRASBANK1CTRL_OFFSET _ULL(0x40a)

#define VT2_CHPL_DDIFRASBANK1CTRL_POS 0
#define VT2_CHPL_DDIFRASBANK1CTRL_WID 6
#define VT2_CHPL_DDIFRASBANK1CTRL_MSK (((_ULL(1) << VT2_CHPL_DDIFRASBANK1CTRL_WID) - _ULL(1)) << VT2_CHPL_DDIFRASBANK1CTRL_POS)

#define VT2_CHPL_DDIFRASBANK1CTRL_CORRRECOVDIS_POS 0
#define VT2_CHPL_DDIFRASBANK1CTRL_CORRRECOVDIS_WID 1
#define VT2_CHPL_DDIFRASBANK1CTRL_CORRRECOVDIS_MSK (((_ULL(1) << VT2_CHPL_DDIFRASBANK1CTRL_CORRRECOVDIS_WID) - _ULL(1)) << VT2_CHPL_DDIFRASBANK1CTRL_CORRRECOVDIS_POS)
#define VT2_CHPL_DDIFRASBANK1CTRL_LOGEN_POS 1
#define VT2_CHPL_DDIFRASBANK1CTRL_LOGEN_WID 1
#define VT2_CHPL_DDIFRASBANK1CTRL_LOGEN_MSK (((_ULL(1) << VT2_CHPL_DDIFRASBANK1CTRL_LOGEN_WID) - _ULL(1)) << VT2_CHPL_DDIFRASBANK1CTRL_LOGEN_POS)
#define VT2_CHPL_DDIFRASBANK1CTRL_NMIEN_POS 2
#define VT2_CHPL_DDIFRASBANK1CTRL_NMIEN_WID 1
#define VT2_CHPL_DDIFRASBANK1CTRL_NMIEN_MSK (((_ULL(1) << VT2_CHPL_DDIFRASBANK1CTRL_NMIEN_WID) - _ULL(1)) << VT2_CHPL_DDIFRASBANK1CTRL_NMIEN_POS)
#define VT2_CHPL_DDIFRASBANK1CTRL_FATALERRINTREN_POS 3
#define VT2_CHPL_DDIFRASBANK1CTRL_FATALERRINTREN_WID 1
#define VT2_CHPL_DDIFRASBANK1CTRL_FATALERRINTREN_MSK (((_ULL(1) << VT2_CHPL_DDIFRASBANK1CTRL_FATALERRINTREN_WID) - _ULL(1)) << VT2_CHPL_DDIFRASBANK1CTRL_FATALERRINTREN_POS)
#define VT2_CHPL_DDIFRASBANK1CTRL_NONCRITDERRINTREN_POS 4
#define VT2_CHPL_DDIFRASBANK1CTRL_NONCRITDERRINTREN_WID 1
#define VT2_CHPL_DDIFRASBANK1CTRL_NONCRITDERRINTREN_MSK (((_ULL(1) << VT2_CHPL_DDIFRASBANK1CTRL_NONCRITDERRINTREN_WID) - _ULL(1)) << VT2_CHPL_DDIFRASBANK1CTRL_NONCRITDERRINTREN_POS)
#define VT2_CHPL_DDIFRASBANK1CTRL_NONCRITCERRINTREN_POS 5
#define VT2_CHPL_DDIFRASBANK1CTRL_NONCRITCERRINTREN_WID 1
#define VT2_CHPL_DDIFRASBANK1CTRL_NONCRITCERRINTREN_MSK (((_ULL(1) << VT2_CHPL_DDIFRASBANK1CTRL_NONCRITCERRINTREN_WID) - _ULL(1)) << VT2_CHPL_DDIFRASBANK1CTRL_NONCRITCERRINTREN_POS)

#define VT2_CHPL_DDIFRASBANK1STATUS_OFFSET _ULL(0x40b)

#define VT2_CHPL_DDIFRASBANK1STATUS_POS 0
#define VT2_CHPL_DDIFRASBANK1STATUS_WID 32
#define VT2_CHPL_DDIFRASBANK1STATUS_MSK (((_ULL(1) << VT2_CHPL_DDIFRASBANK1STATUS_WID) - _ULL(1)) << VT2_CHPL_DDIFRASBANK1STATUS_POS)

#define VT2_CHPL_DDIFRASBANK1STATUS_VALID_POS 0
#define VT2_CHPL_DDIFRASBANK1STATUS_VALID_WID 1
#define VT2_CHPL_DDIFRASBANK1STATUS_VALID_MSK (((_ULL(1) << VT2_CHPL_DDIFRASBANK1STATUS_VALID_WID) - _ULL(1)) << VT2_CHPL_DDIFRASBANK1STATUS_VALID_POS)
#define VT2_CHPL_DDIFRASBANK1STATUS_ERRDETLOGGED_POS 1
#define VT2_CHPL_DDIFRASBANK1STATUS_ERRDETLOGGED_WID 1
#define VT2_CHPL_DDIFRASBANK1STATUS_ERRDETLOGGED_MSK (((_ULL(1) << VT2_CHPL_DDIFRASBANK1STATUS_ERRDETLOGGED_WID) - _ULL(1)) << VT2_CHPL_DDIFRASBANK1STATUS_ERRDETLOGGED_POS)
#define VT2_CHPL_DDIFRASBANK1STATUS_CRITICALERR_POS 2
#define VT2_CHPL_DDIFRASBANK1STATUS_CRITICALERR_WID 1
#define VT2_CHPL_DDIFRASBANK1STATUS_CRITICALERR_MSK (((_ULL(1) << VT2_CHPL_DDIFRASBANK1STATUS_CRITICALERR_WID) - _ULL(1)) << VT2_CHPL_DDIFRASBANK1STATUS_CRITICALERR_POS)
#define VT2_CHPL_DDIFRASBANK1STATUS_DEFERREDERR_POS 3
#define VT2_CHPL_DDIFRASBANK1STATUS_DEFERREDERR_WID 1
#define VT2_CHPL_DDIFRASBANK1STATUS_DEFERREDERR_MSK (((_ULL(1) << VT2_CHPL_DDIFRASBANK1STATUS_DEFERREDERR_WID) - _ULL(1)) << VT2_CHPL_DDIFRASBANK1STATUS_DEFERREDERR_POS)
#define VT2_CHPL_DDIFRASBANK1STATUS_CECOVERFLOW_POS 4
#define VT2_CHPL_DDIFRASBANK1STATUS_CECOVERFLOW_WID 1
#define VT2_CHPL_DDIFRASBANK1STATUS_CECOVERFLOW_MSK (((_ULL(1) << VT2_CHPL_DDIFRASBANK1STATUS_CECOVERFLOW_WID) - _ULL(1)) << VT2_CHPL_DDIFRASBANK1STATUS_CECOVERFLOW_POS)
#define VT2_CHPL_DDIFRASBANK1STATUS_ERRLOGOVERFLOW_POS 5
#define VT2_CHPL_DDIFRASBANK1STATUS_ERRLOGOVERFLOW_WID 1
#define VT2_CHPL_DDIFRASBANK1STATUS_ERRLOGOVERFLOW_MSK (((_ULL(1) << VT2_CHPL_DDIFRASBANK1STATUS_ERRLOGOVERFLOW_WID) - _ULL(1)) << VT2_CHPL_DDIFRASBANK1STATUS_ERRLOGOVERFLOW_POS)
#define VT2_CHPL_DDIFRASBANK1STATUS_ADDRVLD_POS 6
#define VT2_CHPL_DDIFRASBANK1STATUS_ADDRVLD_WID 1
#define VT2_CHPL_DDIFRASBANK1STATUS_ADDRVLD_MSK (((_ULL(1) << VT2_CHPL_DDIFRASBANK1STATUS_ADDRVLD_WID) - _ULL(1)) << VT2_CHPL_DDIFRASBANK1STATUS_ADDRVLD_POS)
#define VT2_CHPL_DDIFRASBANK1STATUS_INFOVLD_POS 7
#define VT2_CHPL_DDIFRASBANK1STATUS_INFOVLD_WID 1
#define VT2_CHPL_DDIFRASBANK1STATUS_INFOVLD_MSK (((_ULL(1) << VT2_CHPL_DDIFRASBANK1STATUS_INFOVLD_WID) - _ULL(1)) << VT2_CHPL_DDIFRASBANK1STATUS_INFOVLD_POS)
#define VT2_CHPL_DDIFRASBANK1STATUS_ERRTYPE_POS 8
#define VT2_CHPL_DDIFRASBANK1STATUS_ERRTYPE_WID 3
#define VT2_CHPL_DDIFRASBANK1STATUS_ERRTYPE_MSK (((_ULL(1) << VT2_CHPL_DDIFRASBANK1STATUS_ERRTYPE_WID) - _ULL(1)) << VT2_CHPL_DDIFRASBANK1STATUS_ERRTYPE_POS)
#define VT2_CHPL_DDIFRASBANK1STATUS_RESERVED_POS 11
#define VT2_CHPL_DDIFRASBANK1STATUS_RESERVED_WID 5
#define VT2_CHPL_DDIFRASBANK1STATUS_RESERVED_MSK (((_ULL(1) << VT2_CHPL_DDIFRASBANK1STATUS_RESERVED_WID) - _ULL(1)) << VT2_CHPL_DDIFRASBANK1STATUS_RESERVED_POS)
#define VT2_CHPL_DDIFRASBANK1STATUS_ACCESSTYPE_POS 16
#define VT2_CHPL_DDIFRASBANK1STATUS_ACCESSTYPE_WID 4
#define VT2_CHPL_DDIFRASBANK1STATUS_ACCESSTYPE_MSK (((_ULL(1) << VT2_CHPL_DDIFRASBANK1STATUS_ACCESSTYPE_WID) - _ULL(1)) << VT2_CHPL_DDIFRASBANK1STATUS_ACCESSTYPE_POS)
#define VT2_CHPL_DDIFRASBANK1STATUS_CORRERRCNT_POS 20
#define VT2_CHPL_DDIFRASBANK1STATUS_CORRERRCNT_WID 12
#define VT2_CHPL_DDIFRASBANK1STATUS_CORRERRCNT_MSK (((_ULL(1) << VT2_CHPL_DDIFRASBANK1STATUS_CORRERRCNT_WID) - _ULL(1)) << VT2_CHPL_DDIFRASBANK1STATUS_CORRERRCNT_POS)

#define VT2_CHPL_DDIFRASBANK1INFOL_OFFSET _ULL(0x40e)

#define VT2_CHPL_DDIFRASBANK1INFOL_POS 0
#define VT2_CHPL_DDIFRASBANK1INFOL_WID 16
#define VT2_CHPL_DDIFRASBANK1INFOL_MSK (((_ULL(1) << VT2_CHPL_DDIFRASBANK1INFOL_WID) - _ULL(1)) << VT2_CHPL_DDIFRASBANK1INFOL_POS)

#define VT2_CHPL_DDIFRASBANK1INFOL_INFO_POS 0
#define VT2_CHPL_DDIFRASBANK1INFOL_INFO_WID 16
#define VT2_CHPL_DDIFRASBANK1INFOL_INFO_MSK (((_ULL(1) << VT2_CHPL_DDIFRASBANK1INFOL_INFO_WID) - _ULL(1)) << VT2_CHPL_DDIFRASBANK1INFOL_INFO_POS)

#define VT2_CHPL_DDIFRASBANK1INFOH_OFFSET _ULL(0x40f)

#define VT2_CHPL_DDIFRASBANK1INFOH_POS 0
#define VT2_CHPL_DDIFRASBANK1INFOH_WID 32
#define VT2_CHPL_DDIFRASBANK1INFOH_MSK (((_ULL(1) << VT2_CHPL_DDIFRASBANK1INFOH_WID) - _ULL(1)) << VT2_CHPL_DDIFRASBANK1INFOH_POS)

#define VT2_CHPL_DDIFRASBANK1INFOH_SYNDROME0_POS 0
#define VT2_CHPL_DDIFRASBANK1INFOH_SYNDROME0_WID 6
#define VT2_CHPL_DDIFRASBANK1INFOH_SYNDROME0_MSK (((_ULL(1) << VT2_CHPL_DDIFRASBANK1INFOH_SYNDROME0_WID) - _ULL(1)) << VT2_CHPL_DDIFRASBANK1INFOH_SYNDROME0_POS)
#define VT2_CHPL_DDIFRASBANK1INFOH_RESERVED0_POS 6
#define VT2_CHPL_DDIFRASBANK1INFOH_RESERVED0_WID 2
#define VT2_CHPL_DDIFRASBANK1INFOH_RESERVED0_MSK (((_ULL(1) << VT2_CHPL_DDIFRASBANK1INFOH_RESERVED0_WID) - _ULL(1)) << VT2_CHPL_DDIFRASBANK1INFOH_RESERVED0_POS)
#define VT2_CHPL_DDIFRASBANK1INFOH_SYNDROME1_POS 8
#define VT2_CHPL_DDIFRASBANK1INFOH_SYNDROME1_WID 6
#define VT2_CHPL_DDIFRASBANK1INFOH_SYNDROME1_MSK (((_ULL(1) << VT2_CHPL_DDIFRASBANK1INFOH_SYNDROME1_WID) - _ULL(1)) << VT2_CHPL_DDIFRASBANK1INFOH_SYNDROME1_POS)
#define VT2_CHPL_DDIFRASBANK1INFOH_RESERVED1_POS 14
#define VT2_CHPL_DDIFRASBANK1INFOH_RESERVED1_WID 2
#define VT2_CHPL_DDIFRASBANK1INFOH_RESERVED1_MSK (((_ULL(1) << VT2_CHPL_DDIFRASBANK1INFOH_RESERVED1_WID) - _ULL(1)) << VT2_CHPL_DDIFRASBANK1INFOH_RESERVED1_POS)
#define VT2_CHPL_DDIFRASBANK1INFOH_SYNDROME2_POS 16
#define VT2_CHPL_DDIFRASBANK1INFOH_SYNDROME2_WID 8
#define VT2_CHPL_DDIFRASBANK1INFOH_SYNDROME2_MSK (((_ULL(1) << VT2_CHPL_DDIFRASBANK1INFOH_SYNDROME2_WID) - _ULL(1)) << VT2_CHPL_DDIFRASBANK1INFOH_SYNDROME2_POS)
#define VT2_CHPL_DDIFRASBANK1INFOH_SYNDROME3_POS 24
#define VT2_CHPL_DDIFRASBANK1INFOH_SYNDROME3_WID 8
#define VT2_CHPL_DDIFRASBANK1INFOH_SYNDROME3_MSK (((_ULL(1) << VT2_CHPL_DDIFRASBANK1INFOH_SYNDROME3_WID) - _ULL(1)) << VT2_CHPL_DDIFRASBANK1INFOH_SYNDROME3_POS)

#define VT2_CHPL_DDIFRASBANK2CTRL_OFFSET _ULL(0x410)

#define VT2_CHPL_DDIFRASBANK2CTRL_POS 0
#define VT2_CHPL_DDIFRASBANK2CTRL_WID 6
#define VT2_CHPL_DDIFRASBANK2CTRL_MSK (((_ULL(1) << VT2_CHPL_DDIFRASBANK2CTRL_WID) - _ULL(1)) << VT2_CHPL_DDIFRASBANK2CTRL_POS)

#define VT2_CHPL_DDIFRASBANK2CTRL_CORRRECOVDIS_POS 0
#define VT2_CHPL_DDIFRASBANK2CTRL_CORRRECOVDIS_WID 1
#define VT2_CHPL_DDIFRASBANK2CTRL_CORRRECOVDIS_MSK (((_ULL(1) << VT2_CHPL_DDIFRASBANK2CTRL_CORRRECOVDIS_WID) - _ULL(1)) << VT2_CHPL_DDIFRASBANK2CTRL_CORRRECOVDIS_POS)
#define VT2_CHPL_DDIFRASBANK2CTRL_LOGEN_POS 1
#define VT2_CHPL_DDIFRASBANK2CTRL_LOGEN_WID 1
#define VT2_CHPL_DDIFRASBANK2CTRL_LOGEN_MSK (((_ULL(1) << VT2_CHPL_DDIFRASBANK2CTRL_LOGEN_WID) - _ULL(1)) << VT2_CHPL_DDIFRASBANK2CTRL_LOGEN_POS)
#define VT2_CHPL_DDIFRASBANK2CTRL_NMIEN_POS 2
#define VT2_CHPL_DDIFRASBANK2CTRL_NMIEN_WID 1
#define VT2_CHPL_DDIFRASBANK2CTRL_NMIEN_MSK (((_ULL(1) << VT2_CHPL_DDIFRASBANK2CTRL_NMIEN_WID) - _ULL(1)) << VT2_CHPL_DDIFRASBANK2CTRL_NMIEN_POS)
#define VT2_CHPL_DDIFRASBANK2CTRL_FATALERRINTREN_POS 3
#define VT2_CHPL_DDIFRASBANK2CTRL_FATALERRINTREN_WID 1
#define VT2_CHPL_DDIFRASBANK2CTRL_FATALERRINTREN_MSK (((_ULL(1) << VT2_CHPL_DDIFRASBANK2CTRL_FATALERRINTREN_WID) - _ULL(1)) << VT2_CHPL_DDIFRASBANK2CTRL_FATALERRINTREN_POS)
#define VT2_CHPL_DDIFRASBANK2CTRL_NONCRITDERRINTREN_POS 4
#define VT2_CHPL_DDIFRASBANK2CTRL_NONCRITDERRINTREN_WID 1
#define VT2_CHPL_DDIFRASBANK2CTRL_NONCRITDERRINTREN_MSK (((_ULL(1) << VT2_CHPL_DDIFRASBANK2CTRL_NONCRITDERRINTREN_WID) - _ULL(1)) << VT2_CHPL_DDIFRASBANK2CTRL_NONCRITDERRINTREN_POS)
#define VT2_CHPL_DDIFRASBANK2CTRL_NONCRITCERRINTREN_POS 5
#define VT2_CHPL_DDIFRASBANK2CTRL_NONCRITCERRINTREN_WID 1
#define VT2_CHPL_DDIFRASBANK2CTRL_NONCRITCERRINTREN_MSK (((_ULL(1) << VT2_CHPL_DDIFRASBANK2CTRL_NONCRITCERRINTREN_WID) - _ULL(1)) << VT2_CHPL_DDIFRASBANK2CTRL_NONCRITCERRINTREN_POS)

#define VT2_CHPL_DDIFRASBANK2STATUS_OFFSET _ULL(0x411)

#define VT2_CHPL_DDIFRASBANK2STATUS_POS 0
#define VT2_CHPL_DDIFRASBANK2STATUS_WID 32
#define VT2_CHPL_DDIFRASBANK2STATUS_MSK (((_ULL(1) << VT2_CHPL_DDIFRASBANK2STATUS_WID) - _ULL(1)) << VT2_CHPL_DDIFRASBANK2STATUS_POS)

#define VT2_CHPL_DDIFRASBANK2STATUS_VALID_POS 0
#define VT2_CHPL_DDIFRASBANK2STATUS_VALID_WID 1
#define VT2_CHPL_DDIFRASBANK2STATUS_VALID_MSK (((_ULL(1) << VT2_CHPL_DDIFRASBANK2STATUS_VALID_WID) - _ULL(1)) << VT2_CHPL_DDIFRASBANK2STATUS_VALID_POS)
#define VT2_CHPL_DDIFRASBANK2STATUS_ERRDETLOGGED_POS 1
#define VT2_CHPL_DDIFRASBANK2STATUS_ERRDETLOGGED_WID 1
#define VT2_CHPL_DDIFRASBANK2STATUS_ERRDETLOGGED_MSK (((_ULL(1) << VT2_CHPL_DDIFRASBANK2STATUS_ERRDETLOGGED_WID) - _ULL(1)) << VT2_CHPL_DDIFRASBANK2STATUS_ERRDETLOGGED_POS)
#define VT2_CHPL_DDIFRASBANK2STATUS_CRITICALERR_POS 2
#define VT2_CHPL_DDIFRASBANK2STATUS_CRITICALERR_WID 1
#define VT2_CHPL_DDIFRASBANK2STATUS_CRITICALERR_MSK (((_ULL(1) << VT2_CHPL_DDIFRASBANK2STATUS_CRITICALERR_WID) - _ULL(1)) << VT2_CHPL_DDIFRASBANK2STATUS_CRITICALERR_POS)
#define VT2_CHPL_DDIFRASBANK2STATUS_DEFERREDERR_POS 3
#define VT2_CHPL_DDIFRASBANK2STATUS_DEFERREDERR_WID 1
#define VT2_CHPL_DDIFRASBANK2STATUS_DEFERREDERR_MSK (((_ULL(1) << VT2_CHPL_DDIFRASBANK2STATUS_DEFERREDERR_WID) - _ULL(1)) << VT2_CHPL_DDIFRASBANK2STATUS_DEFERREDERR_POS)
#define VT2_CHPL_DDIFRASBANK2STATUS_CECOVERFLOW_POS 4
#define VT2_CHPL_DDIFRASBANK2STATUS_CECOVERFLOW_WID 1
#define VT2_CHPL_DDIFRASBANK2STATUS_CECOVERFLOW_MSK (((_ULL(1) << VT2_CHPL_DDIFRASBANK2STATUS_CECOVERFLOW_WID) - _ULL(1)) << VT2_CHPL_DDIFRASBANK2STATUS_CECOVERFLOW_POS)
#define VT2_CHPL_DDIFRASBANK2STATUS_ERRLOGOVERFLOW_POS 5
#define VT2_CHPL_DDIFRASBANK2STATUS_ERRLOGOVERFLOW_WID 1
#define VT2_CHPL_DDIFRASBANK2STATUS_ERRLOGOVERFLOW_MSK (((_ULL(1) << VT2_CHPL_DDIFRASBANK2STATUS_ERRLOGOVERFLOW_WID) - _ULL(1)) << VT2_CHPL_DDIFRASBANK2STATUS_ERRLOGOVERFLOW_POS)
#define VT2_CHPL_DDIFRASBANK2STATUS_ADDRVLD_POS 6
#define VT2_CHPL_DDIFRASBANK2STATUS_ADDRVLD_WID 1
#define VT2_CHPL_DDIFRASBANK2STATUS_ADDRVLD_MSK (((_ULL(1) << VT2_CHPL_DDIFRASBANK2STATUS_ADDRVLD_WID) - _ULL(1)) << VT2_CHPL_DDIFRASBANK2STATUS_ADDRVLD_POS)
#define VT2_CHPL_DDIFRASBANK2STATUS_INFOVLD_POS 7
#define VT2_CHPL_DDIFRASBANK2STATUS_INFOVLD_WID 1
#define VT2_CHPL_DDIFRASBANK2STATUS_INFOVLD_MSK (((_ULL(1) << VT2_CHPL_DDIFRASBANK2STATUS_INFOVLD_WID) - _ULL(1)) << VT2_CHPL_DDIFRASBANK2STATUS_INFOVLD_POS)
#define VT2_CHPL_DDIFRASBANK2STATUS_ERRTYPE_POS 8
#define VT2_CHPL_DDIFRASBANK2STATUS_ERRTYPE_WID 3
#define VT2_CHPL_DDIFRASBANK2STATUS_ERRTYPE_MSK (((_ULL(1) << VT2_CHPL_DDIFRASBANK2STATUS_ERRTYPE_WID) - _ULL(1)) << VT2_CHPL_DDIFRASBANK2STATUS_ERRTYPE_POS)
#define VT2_CHPL_DDIFRASBANK2STATUS_RESERVED_POS 11
#define VT2_CHPL_DDIFRASBANK2STATUS_RESERVED_WID 5
#define VT2_CHPL_DDIFRASBANK2STATUS_RESERVED_MSK (((_ULL(1) << VT2_CHPL_DDIFRASBANK2STATUS_RESERVED_WID) - _ULL(1)) << VT2_CHPL_DDIFRASBANK2STATUS_RESERVED_POS)
#define VT2_CHPL_DDIFRASBANK2STATUS_ACCESSTYPE_POS 16
#define VT2_CHPL_DDIFRASBANK2STATUS_ACCESSTYPE_WID 4
#define VT2_CHPL_DDIFRASBANK2STATUS_ACCESSTYPE_MSK (((_ULL(1) << VT2_CHPL_DDIFRASBANK2STATUS_ACCESSTYPE_WID) - _ULL(1)) << VT2_CHPL_DDIFRASBANK2STATUS_ACCESSTYPE_POS)
#define VT2_CHPL_DDIFRASBANK2STATUS_CORRERRCNT_POS 20
#define VT2_CHPL_DDIFRASBANK2STATUS_CORRERRCNT_WID 12
#define VT2_CHPL_DDIFRASBANK2STATUS_CORRERRCNT_MSK (((_ULL(1) << VT2_CHPL_DDIFRASBANK2STATUS_CORRERRCNT_WID) - _ULL(1)) << VT2_CHPL_DDIFRASBANK2STATUS_CORRERRCNT_POS)

#define VT2_CHPL_DDIFRASBANK2INFOL_OFFSET _ULL(0x414)

#define VT2_CHPL_DDIFRASBANK2INFOL_POS 0
#define VT2_CHPL_DDIFRASBANK2INFOL_WID 32
#define VT2_CHPL_DDIFRASBANK2INFOL_MSK (((_ULL(1) << VT2_CHPL_DDIFRASBANK2INFOL_WID) - _ULL(1)) << VT2_CHPL_DDIFRASBANK2INFOL_POS)

#define VT2_CHPL_DDIFRASBANK2INFOL_TLPTYPE_POS 0
#define VT2_CHPL_DDIFRASBANK2INFOL_TLPTYPE_WID 6
#define VT2_CHPL_DDIFRASBANK2INFOL_TLPTYPE_MSK (((_ULL(1) << VT2_CHPL_DDIFRASBANK2INFOL_TLPTYPE_WID) - _ULL(1)) << VT2_CHPL_DDIFRASBANK2INFOL_TLPTYPE_POS)
#define VT2_CHPL_DDIFRASBANK2INFOL_RESERVED0_POS 6
#define VT2_CHPL_DDIFRASBANK2INFOL_RESERVED0_WID 2
#define VT2_CHPL_DDIFRASBANK2INFOL_RESERVED0_MSK (((_ULL(1) << VT2_CHPL_DDIFRASBANK2INFOL_RESERVED0_WID) - _ULL(1)) << VT2_CHPL_DDIFRASBANK2INFOL_RESERVED0_POS)
#define VT2_CHPL_DDIFRASBANK2INFOL_TLPHDRGRANULE_POS 8
#define VT2_CHPL_DDIFRASBANK2INFOL_TLPHDRGRANULE_WID 7
#define VT2_CHPL_DDIFRASBANK2INFOL_TLPHDRGRANULE_MSK (((_ULL(1) << VT2_CHPL_DDIFRASBANK2INFOL_TLPHDRGRANULE_WID) - _ULL(1)) << VT2_CHPL_DDIFRASBANK2INFOL_TLPHDRGRANULE_POS)
#define VT2_CHPL_DDIFRASBANK2INFOL_RESERVED1_POS 15
#define VT2_CHPL_DDIFRASBANK2INFOL_RESERVED1_WID 1
#define VT2_CHPL_DDIFRASBANK2INFOL_RESERVED1_MSK (((_ULL(1) << VT2_CHPL_DDIFRASBANK2INFOL_RESERVED1_WID) - _ULL(1)) << VT2_CHPL_DDIFRASBANK2INFOL_RESERVED1_POS)
#define VT2_CHPL_DDIFRASBANK2INFOL_TLPCODEWORD_POS 16
#define VT2_CHPL_DDIFRASBANK2INFOL_TLPCODEWORD_WID 2
#define VT2_CHPL_DDIFRASBANK2INFOL_TLPCODEWORD_MSK (((_ULL(1) << VT2_CHPL_DDIFRASBANK2INFOL_TLPCODEWORD_WID) - _ULL(1)) << VT2_CHPL_DDIFRASBANK2INFOL_TLPCODEWORD_POS)
#define VT2_CHPL_DDIFRASBANK2INFOL_RESERVED2_POS 18
#define VT2_CHPL_DDIFRASBANK2INFOL_RESERVED2_WID 5
#define VT2_CHPL_DDIFRASBANK2INFOL_RESERVED2_MSK (((_ULL(1) << VT2_CHPL_DDIFRASBANK2INFOL_RESERVED2_WID) - _ULL(1)) << VT2_CHPL_DDIFRASBANK2INFOL_RESERVED2_POS)
#define VT2_CHPL_DDIFRASBANK2INFOL_TLPSYNDROME_POS 23
#define VT2_CHPL_DDIFRASBANK2INFOL_TLPSYNDROME_WID 9
#define VT2_CHPL_DDIFRASBANK2INFOL_TLPSYNDROME_MSK (((_ULL(1) << VT2_CHPL_DDIFRASBANK2INFOL_TLPSYNDROME_WID) - _ULL(1)) << VT2_CHPL_DDIFRASBANK2INFOL_TLPSYNDROME_POS)

#define VT2_CHPL_RXTLPMSG0_OFFSET _ULL(0x440)

#define VT2_CHPL_RXTLPMSG0_POS 0
#define VT2_CHPL_RXTLPMSG0_WID 18
#define VT2_CHPL_RXTLPMSG0_MSK (((_ULL(1) << VT2_CHPL_RXTLPMSG0_WID) - _ULL(1)) << VT2_CHPL_RXTLPMSG0_POS)

#define VT2_CHPL_RXTLPMSG0_MESSAGEDATA_POS 0
#define VT2_CHPL_RXTLPMSG0_MESSAGEDATA_WID 16
#define VT2_CHPL_RXTLPMSG0_MESSAGEDATA_MSK (((_ULL(1) << VT2_CHPL_RXTLPMSG0_MESSAGEDATA_WID) - _ULL(1)) << VT2_CHPL_RXTLPMSG0_MESSAGEDATA_POS)
#define VT2_CHPL_RXTLPMSG0_RECEIVED_POS 16
#define VT2_CHPL_RXTLPMSG0_RECEIVED_WID 1
#define VT2_CHPL_RXTLPMSG0_RECEIVED_MSK (((_ULL(1) << VT2_CHPL_RXTLPMSG0_RECEIVED_WID) - _ULL(1)) << VT2_CHPL_RXTLPMSG0_RECEIVED_POS)
#define VT2_CHPL_RXTLPMSG0_CLEARRECEIVED_POS 17
#define VT2_CHPL_RXTLPMSG0_CLEARRECEIVED_WID 1
#define VT2_CHPL_RXTLPMSG0_CLEARRECEIVED_MSK (((_ULL(1) << VT2_CHPL_RXTLPMSG0_CLEARRECEIVED_WID) - _ULL(1)) << VT2_CHPL_RXTLPMSG0_CLEARRECEIVED_POS)

#define VT2_CHPL_RXTRAINTRIGSAMPLE_OFFSET _ULL(0x450)

#define VT2_CHPL_RXTRAINTRIGSAMPLE_POS 0
#define VT2_CHPL_RXTRAINTRIGSAMPLE_WID 1
#define VT2_CHPL_RXTRAINTRIGSAMPLE_MSK (((_ULL(1) << VT2_CHPL_RXTRAINTRIGSAMPLE_WID) - _ULL(1)) << VT2_CHPL_RXTRAINTRIGSAMPLE_POS)

#define VT2_CHPL_RXTRAINTRIGSAMPLE_TRAINTRIGSAMPLE_POS 0
#define VT2_CHPL_RXTRAINTRIGSAMPLE_TRAINTRIGSAMPLE_WID 1
#define VT2_CHPL_RXTRAINTRIGSAMPLE_TRAINTRIGSAMPLE_MSK (((_ULL(1) << VT2_CHPL_RXTRAINTRIGSAMPLE_TRAINTRIGSAMPLE_WID) - _ULL(1)) << VT2_CHPL_RXTRAINTRIGSAMPLE_TRAINTRIGSAMPLE_POS)

#define VT2_CHPL_DDIFFLITSAMPLE00_OFFSET _ULL(0x500)

#define VT2_CHPL_DDIFFLITSAMPLE00_POS 0
#define VT2_CHPL_DDIFFLITSAMPLE00_WID 32
#define VT2_CHPL_DDIFFLITSAMPLE00_MSK (((_ULL(1) << VT2_CHPL_DDIFFLITSAMPLE00_WID) - _ULL(1)) << VT2_CHPL_DDIFFLITSAMPLE00_POS)

#define VT2_CHPL_DDIFFLITSAMPLE00_DATA_POS 0
#define VT2_CHPL_DDIFFLITSAMPLE00_DATA_WID 32
#define VT2_CHPL_DDIFFLITSAMPLE00_DATA_MSK (((_ULL(1) << VT2_CHPL_DDIFFLITSAMPLE00_DATA_WID) - _ULL(1)) << VT2_CHPL_DDIFFLITSAMPLE00_DATA_POS)

#define VT2_CHPL_DDIFFLITSAMPLE01_OFFSET _ULL(0x501)

#define VT2_CHPL_DDIFFLITSAMPLE01_POS 0
#define VT2_CHPL_DDIFFLITSAMPLE01_WID 32
#define VT2_CHPL_DDIFFLITSAMPLE01_MSK (((_ULL(1) << VT2_CHPL_DDIFFLITSAMPLE01_WID) - _ULL(1)) << VT2_CHPL_DDIFFLITSAMPLE01_POS)

#define VT2_CHPL_DDIFFLITSAMPLE01_DATA_POS 0
#define VT2_CHPL_DDIFFLITSAMPLE01_DATA_WID 32
#define VT2_CHPL_DDIFFLITSAMPLE01_DATA_MSK (((_ULL(1) << VT2_CHPL_DDIFFLITSAMPLE01_DATA_WID) - _ULL(1)) << VT2_CHPL_DDIFFLITSAMPLE01_DATA_POS)

#define VT2_CHPL_DDIFFLITSAMPLE02_OFFSET _ULL(0x502)

#define VT2_CHPL_DDIFFLITSAMPLE02_POS 0
#define VT2_CHPL_DDIFFLITSAMPLE02_WID 32
#define VT2_CHPL_DDIFFLITSAMPLE02_MSK (((_ULL(1) << VT2_CHPL_DDIFFLITSAMPLE02_WID) - _ULL(1)) << VT2_CHPL_DDIFFLITSAMPLE02_POS)

#define VT2_CHPL_DDIFFLITSAMPLE02_DATA_POS 0
#define VT2_CHPL_DDIFFLITSAMPLE02_DATA_WID 32
#define VT2_CHPL_DDIFFLITSAMPLE02_DATA_MSK (((_ULL(1) << VT2_CHPL_DDIFFLITSAMPLE02_DATA_WID) - _ULL(1)) << VT2_CHPL_DDIFFLITSAMPLE02_DATA_POS)

#define VT2_CHPL_DDIFFLITSAMPLE03_OFFSET _ULL(0x503)

#define VT2_CHPL_DDIFFLITSAMPLE03_POS 0
#define VT2_CHPL_DDIFFLITSAMPLE03_WID 32
#define VT2_CHPL_DDIFFLITSAMPLE03_MSK (((_ULL(1) << VT2_CHPL_DDIFFLITSAMPLE03_WID) - _ULL(1)) << VT2_CHPL_DDIFFLITSAMPLE03_POS)

#define VT2_CHPL_DDIFFLITSAMPLE03_DATA_POS 0
#define VT2_CHPL_DDIFFLITSAMPLE03_DATA_WID 32
#define VT2_CHPL_DDIFFLITSAMPLE03_DATA_MSK (((_ULL(1) << VT2_CHPL_DDIFFLITSAMPLE03_DATA_WID) - _ULL(1)) << VT2_CHPL_DDIFFLITSAMPLE03_DATA_POS)

#define VT2_CHPL_DDIFFLITSAMPLE04_OFFSET _ULL(0x504)

#define VT2_CHPL_DDIFFLITSAMPLE04_POS 0
#define VT2_CHPL_DDIFFLITSAMPLE04_WID 32
#define VT2_CHPL_DDIFFLITSAMPLE04_MSK (((_ULL(1) << VT2_CHPL_DDIFFLITSAMPLE04_WID) - _ULL(1)) << VT2_CHPL_DDIFFLITSAMPLE04_POS)

#define VT2_CHPL_DDIFFLITSAMPLE04_DATA_POS 0
#define VT2_CHPL_DDIFFLITSAMPLE04_DATA_WID 32
#define VT2_CHPL_DDIFFLITSAMPLE04_DATA_MSK (((_ULL(1) << VT2_CHPL_DDIFFLITSAMPLE04_DATA_WID) - _ULL(1)) << VT2_CHPL_DDIFFLITSAMPLE04_DATA_POS)

#define VT2_CHPL_DDIFFLITSAMPLE05_OFFSET _ULL(0x505)

#define VT2_CHPL_DDIFFLITSAMPLE05_POS 0
#define VT2_CHPL_DDIFFLITSAMPLE05_WID 32
#define VT2_CHPL_DDIFFLITSAMPLE05_MSK (((_ULL(1) << VT2_CHPL_DDIFFLITSAMPLE05_WID) - _ULL(1)) << VT2_CHPL_DDIFFLITSAMPLE05_POS)

#define VT2_CHPL_DDIFFLITSAMPLE05_DATA_POS 0
#define VT2_CHPL_DDIFFLITSAMPLE05_DATA_WID 32
#define VT2_CHPL_DDIFFLITSAMPLE05_DATA_MSK (((_ULL(1) << VT2_CHPL_DDIFFLITSAMPLE05_DATA_WID) - _ULL(1)) << VT2_CHPL_DDIFFLITSAMPLE05_DATA_POS)

#define VT2_CHPL_DDIFFLITSAMPLE06_OFFSET _ULL(0x506)

#define VT2_CHPL_DDIFFLITSAMPLE06_POS 0
#define VT2_CHPL_DDIFFLITSAMPLE06_WID 32
#define VT2_CHPL_DDIFFLITSAMPLE06_MSK (((_ULL(1) << VT2_CHPL_DDIFFLITSAMPLE06_WID) - _ULL(1)) << VT2_CHPL_DDIFFLITSAMPLE06_POS)

#define VT2_CHPL_DDIFFLITSAMPLE06_DATA_POS 0
#define VT2_CHPL_DDIFFLITSAMPLE06_DATA_WID 32
#define VT2_CHPL_DDIFFLITSAMPLE06_DATA_MSK (((_ULL(1) << VT2_CHPL_DDIFFLITSAMPLE06_DATA_WID) - _ULL(1)) << VT2_CHPL_DDIFFLITSAMPLE06_DATA_POS)

#define VT2_CHPL_DDIFFLITSAMPLE07_OFFSET _ULL(0x507)

#define VT2_CHPL_DDIFFLITSAMPLE07_POS 0
#define VT2_CHPL_DDIFFLITSAMPLE07_WID 32
#define VT2_CHPL_DDIFFLITSAMPLE07_MSK (((_ULL(1) << VT2_CHPL_DDIFFLITSAMPLE07_WID) - _ULL(1)) << VT2_CHPL_DDIFFLITSAMPLE07_POS)

#define VT2_CHPL_DDIFFLITSAMPLE07_DATA_POS 0
#define VT2_CHPL_DDIFFLITSAMPLE07_DATA_WID 32
#define VT2_CHPL_DDIFFLITSAMPLE07_DATA_MSK (((_ULL(1) << VT2_CHPL_DDIFFLITSAMPLE07_DATA_WID) - _ULL(1)) << VT2_CHPL_DDIFFLITSAMPLE07_DATA_POS)

#define VT2_CHPL_DDIFFLITSAMPLE08_OFFSET _ULL(0x508)

#define VT2_CHPL_DDIFFLITSAMPLE08_POS 0
#define VT2_CHPL_DDIFFLITSAMPLE08_WID 32
#define VT2_CHPL_DDIFFLITSAMPLE08_MSK (((_ULL(1) << VT2_CHPL_DDIFFLITSAMPLE08_WID) - _ULL(1)) << VT2_CHPL_DDIFFLITSAMPLE08_POS)

#define VT2_CHPL_DDIFFLITSAMPLE08_DATA_POS 0
#define VT2_CHPL_DDIFFLITSAMPLE08_DATA_WID 32
#define VT2_CHPL_DDIFFLITSAMPLE08_DATA_MSK (((_ULL(1) << VT2_CHPL_DDIFFLITSAMPLE08_DATA_WID) - _ULL(1)) << VT2_CHPL_DDIFFLITSAMPLE08_DATA_POS)

#define VT2_CHPL_DDIFFLITSAMPLE09_OFFSET _ULL(0x509)

#define VT2_CHPL_DDIFFLITSAMPLE09_POS 0
#define VT2_CHPL_DDIFFLITSAMPLE09_WID 32
#define VT2_CHPL_DDIFFLITSAMPLE09_MSK (((_ULL(1) << VT2_CHPL_DDIFFLITSAMPLE09_WID) - _ULL(1)) << VT2_CHPL_DDIFFLITSAMPLE09_POS)

#define VT2_CHPL_DDIFFLITSAMPLE09_DATA_POS 0
#define VT2_CHPL_DDIFFLITSAMPLE09_DATA_WID 32
#define VT2_CHPL_DDIFFLITSAMPLE09_DATA_MSK (((_ULL(1) << VT2_CHPL_DDIFFLITSAMPLE09_DATA_WID) - _ULL(1)) << VT2_CHPL_DDIFFLITSAMPLE09_DATA_POS)

#define VT2_CHPL_DDIFFLITSAMPLE0A_OFFSET _ULL(0x50a)

#define VT2_CHPL_DDIFFLITSAMPLE0A_POS 0
#define VT2_CHPL_DDIFFLITSAMPLE0A_WID 32
#define VT2_CHPL_DDIFFLITSAMPLE0A_MSK (((_ULL(1) << VT2_CHPL_DDIFFLITSAMPLE0A_WID) - _ULL(1)) << VT2_CHPL_DDIFFLITSAMPLE0A_POS)

#define VT2_CHPL_DDIFFLITSAMPLE0A_DATA_POS 0
#define VT2_CHPL_DDIFFLITSAMPLE0A_DATA_WID 32
#define VT2_CHPL_DDIFFLITSAMPLE0A_DATA_MSK (((_ULL(1) << VT2_CHPL_DDIFFLITSAMPLE0A_DATA_WID) - _ULL(1)) << VT2_CHPL_DDIFFLITSAMPLE0A_DATA_POS)

#define VT2_CHPL_DDIFFLITSAMPLE0B_OFFSET _ULL(0x50b)

#define VT2_CHPL_DDIFFLITSAMPLE0B_POS 0
#define VT2_CHPL_DDIFFLITSAMPLE0B_WID 32
#define VT2_CHPL_DDIFFLITSAMPLE0B_MSK (((_ULL(1) << VT2_CHPL_DDIFFLITSAMPLE0B_WID) - _ULL(1)) << VT2_CHPL_DDIFFLITSAMPLE0B_POS)

#define VT2_CHPL_DDIFFLITSAMPLE0B_DATA_POS 0
#define VT2_CHPL_DDIFFLITSAMPLE0B_DATA_WID 32
#define VT2_CHPL_DDIFFLITSAMPLE0B_DATA_MSK (((_ULL(1) << VT2_CHPL_DDIFFLITSAMPLE0B_DATA_WID) - _ULL(1)) << VT2_CHPL_DDIFFLITSAMPLE0B_DATA_POS)

#define VT2_CHPL_DDIFFLITSAMPLE0C_OFFSET _ULL(0x50c)

#define VT2_CHPL_DDIFFLITSAMPLE0C_POS 0
#define VT2_CHPL_DDIFFLITSAMPLE0C_WID 32
#define VT2_CHPL_DDIFFLITSAMPLE0C_MSK (((_ULL(1) << VT2_CHPL_DDIFFLITSAMPLE0C_WID) - _ULL(1)) << VT2_CHPL_DDIFFLITSAMPLE0C_POS)

#define VT2_CHPL_DDIFFLITSAMPLE0C_DATA_POS 0
#define VT2_CHPL_DDIFFLITSAMPLE0C_DATA_WID 32
#define VT2_CHPL_DDIFFLITSAMPLE0C_DATA_MSK (((_ULL(1) << VT2_CHPL_DDIFFLITSAMPLE0C_DATA_WID) - _ULL(1)) << VT2_CHPL_DDIFFLITSAMPLE0C_DATA_POS)

#define VT2_CHPL_DDIFFLITSAMPLE0D_OFFSET _ULL(0x50d)

#define VT2_CHPL_DDIFFLITSAMPLE0D_POS 0
#define VT2_CHPL_DDIFFLITSAMPLE0D_WID 32
#define VT2_CHPL_DDIFFLITSAMPLE0D_MSK (((_ULL(1) << VT2_CHPL_DDIFFLITSAMPLE0D_WID) - _ULL(1)) << VT2_CHPL_DDIFFLITSAMPLE0D_POS)

#define VT2_CHPL_DDIFFLITSAMPLE0D_DATA_POS 0
#define VT2_CHPL_DDIFFLITSAMPLE0D_DATA_WID 32
#define VT2_CHPL_DDIFFLITSAMPLE0D_DATA_MSK (((_ULL(1) << VT2_CHPL_DDIFFLITSAMPLE0D_DATA_WID) - _ULL(1)) << VT2_CHPL_DDIFFLITSAMPLE0D_DATA_POS)

#define VT2_CHPL_DDIFFLITSAMPLE0E_OFFSET _ULL(0x50e)

#define VT2_CHPL_DDIFFLITSAMPLE0E_POS 0
#define VT2_CHPL_DDIFFLITSAMPLE0E_WID 32
#define VT2_CHPL_DDIFFLITSAMPLE0E_MSK (((_ULL(1) << VT2_CHPL_DDIFFLITSAMPLE0E_WID) - _ULL(1)) << VT2_CHPL_DDIFFLITSAMPLE0E_POS)

#define VT2_CHPL_DDIFFLITSAMPLE0E_DATA_POS 0
#define VT2_CHPL_DDIFFLITSAMPLE0E_DATA_WID 32
#define VT2_CHPL_DDIFFLITSAMPLE0E_DATA_MSK (((_ULL(1) << VT2_CHPL_DDIFFLITSAMPLE0E_DATA_WID) - _ULL(1)) << VT2_CHPL_DDIFFLITSAMPLE0E_DATA_POS)

#define VT2_CHPL_DDIFFLITSAMPLE0F_OFFSET _ULL(0x50f)

#define VT2_CHPL_DDIFFLITSAMPLE0F_POS 0
#define VT2_CHPL_DDIFFLITSAMPLE0F_WID 32
#define VT2_CHPL_DDIFFLITSAMPLE0F_MSK (((_ULL(1) << VT2_CHPL_DDIFFLITSAMPLE0F_WID) - _ULL(1)) << VT2_CHPL_DDIFFLITSAMPLE0F_POS)

#define VT2_CHPL_DDIFFLITSAMPLE0F_DATA_POS 0
#define VT2_CHPL_DDIFFLITSAMPLE0F_DATA_WID 32
#define VT2_CHPL_DDIFFLITSAMPLE0F_DATA_MSK (((_ULL(1) << VT2_CHPL_DDIFFLITSAMPLE0F_DATA_WID) - _ULL(1)) << VT2_CHPL_DDIFFLITSAMPLE0F_DATA_POS)

#define VT2_CHPL_DDIFFLITSAMPLE10_OFFSET _ULL(0x510)

#define VT2_CHPL_DDIFFLITSAMPLE10_POS 0
#define VT2_CHPL_DDIFFLITSAMPLE10_WID 32
#define VT2_CHPL_DDIFFLITSAMPLE10_MSK (((_ULL(1) << VT2_CHPL_DDIFFLITSAMPLE10_WID) - _ULL(1)) << VT2_CHPL_DDIFFLITSAMPLE10_POS)

#define VT2_CHPL_DDIFFLITSAMPLE10_DATA_POS 0
#define VT2_CHPL_DDIFFLITSAMPLE10_DATA_WID 32
#define VT2_CHPL_DDIFFLITSAMPLE10_DATA_MSK (((_ULL(1) << VT2_CHPL_DDIFFLITSAMPLE10_DATA_WID) - _ULL(1)) << VT2_CHPL_DDIFFLITSAMPLE10_DATA_POS)

#define VT2_CHPL_DDIFFLITSAMPLE11_OFFSET _ULL(0x511)

#define VT2_CHPL_DDIFFLITSAMPLE11_POS 0
#define VT2_CHPL_DDIFFLITSAMPLE11_WID 32
#define VT2_CHPL_DDIFFLITSAMPLE11_MSK (((_ULL(1) << VT2_CHPL_DDIFFLITSAMPLE11_WID) - _ULL(1)) << VT2_CHPL_DDIFFLITSAMPLE11_POS)

#define VT2_CHPL_DDIFFLITSAMPLE11_DATA_POS 0
#define VT2_CHPL_DDIFFLITSAMPLE11_DATA_WID 32
#define VT2_CHPL_DDIFFLITSAMPLE11_DATA_MSK (((_ULL(1) << VT2_CHPL_DDIFFLITSAMPLE11_DATA_WID) - _ULL(1)) << VT2_CHPL_DDIFFLITSAMPLE11_DATA_POS)

#define VT2_CHPL_DDIFFLITSAMPLE12_OFFSET _ULL(0x512)

#define VT2_CHPL_DDIFFLITSAMPLE12_POS 0
#define VT2_CHPL_DDIFFLITSAMPLE12_WID 32
#define VT2_CHPL_DDIFFLITSAMPLE12_MSK (((_ULL(1) << VT2_CHPL_DDIFFLITSAMPLE12_WID) - _ULL(1)) << VT2_CHPL_DDIFFLITSAMPLE12_POS)

#define VT2_CHPL_DDIFFLITSAMPLE12_DATA_POS 0
#define VT2_CHPL_DDIFFLITSAMPLE12_DATA_WID 32
#define VT2_CHPL_DDIFFLITSAMPLE12_DATA_MSK (((_ULL(1) << VT2_CHPL_DDIFFLITSAMPLE12_DATA_WID) - _ULL(1)) << VT2_CHPL_DDIFFLITSAMPLE12_DATA_POS)

#define VT2_CHPL_DDIFFLITSAMPLE13_OFFSET _ULL(0x513)

#define VT2_CHPL_DDIFFLITSAMPLE13_POS 0
#define VT2_CHPL_DDIFFLITSAMPLE13_WID 32
#define VT2_CHPL_DDIFFLITSAMPLE13_MSK (((_ULL(1) << VT2_CHPL_DDIFFLITSAMPLE13_WID) - _ULL(1)) << VT2_CHPL_DDIFFLITSAMPLE13_POS)

#define VT2_CHPL_DDIFFLITSAMPLE13_DATA_POS 0
#define VT2_CHPL_DDIFFLITSAMPLE13_DATA_WID 32
#define VT2_CHPL_DDIFFLITSAMPLE13_DATA_MSK (((_ULL(1) << VT2_CHPL_DDIFFLITSAMPLE13_DATA_WID) - _ULL(1)) << VT2_CHPL_DDIFFLITSAMPLE13_DATA_POS)

#define VT2_CHPL_DDIFFLITSAMPLE14_OFFSET _ULL(0x514)

#define VT2_CHPL_DDIFFLITSAMPLE14_POS 0
#define VT2_CHPL_DDIFFLITSAMPLE14_WID 32
#define VT2_CHPL_DDIFFLITSAMPLE14_MSK (((_ULL(1) << VT2_CHPL_DDIFFLITSAMPLE14_WID) - _ULL(1)) << VT2_CHPL_DDIFFLITSAMPLE14_POS)

#define VT2_CHPL_DDIFFLITSAMPLE14_DATA_POS 0
#define VT2_CHPL_DDIFFLITSAMPLE14_DATA_WID 32
#define VT2_CHPL_DDIFFLITSAMPLE14_DATA_MSK (((_ULL(1) << VT2_CHPL_DDIFFLITSAMPLE14_DATA_WID) - _ULL(1)) << VT2_CHPL_DDIFFLITSAMPLE14_DATA_POS)

#define VT2_CHPL_DDIFFLITSAMPLE15_OFFSET _ULL(0x515)

#define VT2_CHPL_DDIFFLITSAMPLE15_POS 0
#define VT2_CHPL_DDIFFLITSAMPLE15_WID 32
#define VT2_CHPL_DDIFFLITSAMPLE15_MSK (((_ULL(1) << VT2_CHPL_DDIFFLITSAMPLE15_WID) - _ULL(1)) << VT2_CHPL_DDIFFLITSAMPLE15_POS)

#define VT2_CHPL_DDIFFLITSAMPLE15_DATA_POS 0
#define VT2_CHPL_DDIFFLITSAMPLE15_DATA_WID 32
#define VT2_CHPL_DDIFFLITSAMPLE15_DATA_MSK (((_ULL(1) << VT2_CHPL_DDIFFLITSAMPLE15_DATA_WID) - _ULL(1)) << VT2_CHPL_DDIFFLITSAMPLE15_DATA_POS)

#define VT2_CHPL_DDIFFLITSAMPLE16_OFFSET _ULL(0x516)

#define VT2_CHPL_DDIFFLITSAMPLE16_POS 0
#define VT2_CHPL_DDIFFLITSAMPLE16_WID 32
#define VT2_CHPL_DDIFFLITSAMPLE16_MSK (((_ULL(1) << VT2_CHPL_DDIFFLITSAMPLE16_WID) - _ULL(1)) << VT2_CHPL_DDIFFLITSAMPLE16_POS)

#define VT2_CHPL_DDIFFLITSAMPLE16_DATA_POS 0
#define VT2_CHPL_DDIFFLITSAMPLE16_DATA_WID 32
#define VT2_CHPL_DDIFFLITSAMPLE16_DATA_MSK (((_ULL(1) << VT2_CHPL_DDIFFLITSAMPLE16_DATA_WID) - _ULL(1)) << VT2_CHPL_DDIFFLITSAMPLE16_DATA_POS)

#define VT2_CHPL_DDIFFLITSAMPLE17_OFFSET _ULL(0x517)

#define VT2_CHPL_DDIFFLITSAMPLE17_POS 0
#define VT2_CHPL_DDIFFLITSAMPLE17_WID 32
#define VT2_CHPL_DDIFFLITSAMPLE17_MSK (((_ULL(1) << VT2_CHPL_DDIFFLITSAMPLE17_WID) - _ULL(1)) << VT2_CHPL_DDIFFLITSAMPLE17_POS)

#define VT2_CHPL_DDIFFLITSAMPLE17_DATA_POS 0
#define VT2_CHPL_DDIFFLITSAMPLE17_DATA_WID 32
#define VT2_CHPL_DDIFFLITSAMPLE17_DATA_MSK (((_ULL(1) << VT2_CHPL_DDIFFLITSAMPLE17_DATA_WID) - _ULL(1)) << VT2_CHPL_DDIFFLITSAMPLE17_DATA_POS)

#define VT2_CHPL_DDIFFLITSAMPLE18_OFFSET _ULL(0x518)

#define VT2_CHPL_DDIFFLITSAMPLE18_POS 0
#define VT2_CHPL_DDIFFLITSAMPLE18_WID 32
#define VT2_CHPL_DDIFFLITSAMPLE18_MSK (((_ULL(1) << VT2_CHPL_DDIFFLITSAMPLE18_WID) - _ULL(1)) << VT2_CHPL_DDIFFLITSAMPLE18_POS)

#define VT2_CHPL_DDIFFLITSAMPLE18_DATA_POS 0
#define VT2_CHPL_DDIFFLITSAMPLE18_DATA_WID 32
#define VT2_CHPL_DDIFFLITSAMPLE18_DATA_MSK (((_ULL(1) << VT2_CHPL_DDIFFLITSAMPLE18_DATA_WID) - _ULL(1)) << VT2_CHPL_DDIFFLITSAMPLE18_DATA_POS)

#define VT2_CHPL_DDIFFLITSAMPLE19_OFFSET _ULL(0x519)

#define VT2_CHPL_DDIFFLITSAMPLE19_POS 0
#define VT2_CHPL_DDIFFLITSAMPLE19_WID 32
#define VT2_CHPL_DDIFFLITSAMPLE19_MSK (((_ULL(1) << VT2_CHPL_DDIFFLITSAMPLE19_WID) - _ULL(1)) << VT2_CHPL_DDIFFLITSAMPLE19_POS)

#define VT2_CHPL_DDIFFLITSAMPLE19_DATA_POS 0
#define VT2_CHPL_DDIFFLITSAMPLE19_DATA_WID 32
#define VT2_CHPL_DDIFFLITSAMPLE19_DATA_MSK (((_ULL(1) << VT2_CHPL_DDIFFLITSAMPLE19_DATA_WID) - _ULL(1)) << VT2_CHPL_DDIFFLITSAMPLE19_DATA_POS)

#define VT2_CHPL_DDIFFLITSAMPLE1A_OFFSET _ULL(0x51a)

#define VT2_CHPL_DDIFFLITSAMPLE1A_POS 0
#define VT2_CHPL_DDIFFLITSAMPLE1A_WID 32
#define VT2_CHPL_DDIFFLITSAMPLE1A_MSK (((_ULL(1) << VT2_CHPL_DDIFFLITSAMPLE1A_WID) - _ULL(1)) << VT2_CHPL_DDIFFLITSAMPLE1A_POS)

#define VT2_CHPL_DDIFFLITSAMPLE1A_DATA_POS 0
#define VT2_CHPL_DDIFFLITSAMPLE1A_DATA_WID 32
#define VT2_CHPL_DDIFFLITSAMPLE1A_DATA_MSK (((_ULL(1) << VT2_CHPL_DDIFFLITSAMPLE1A_DATA_WID) - _ULL(1)) << VT2_CHPL_DDIFFLITSAMPLE1A_DATA_POS)

#define VT2_CHPL_DDIFFLITSAMPLE1B_OFFSET _ULL(0x51b)

#define VT2_CHPL_DDIFFLITSAMPLE1B_POS 0
#define VT2_CHPL_DDIFFLITSAMPLE1B_WID 32
#define VT2_CHPL_DDIFFLITSAMPLE1B_MSK (((_ULL(1) << VT2_CHPL_DDIFFLITSAMPLE1B_WID) - _ULL(1)) << VT2_CHPL_DDIFFLITSAMPLE1B_POS)

#define VT2_CHPL_DDIFFLITSAMPLE1B_DATA_POS 0
#define VT2_CHPL_DDIFFLITSAMPLE1B_DATA_WID 32
#define VT2_CHPL_DDIFFLITSAMPLE1B_DATA_MSK (((_ULL(1) << VT2_CHPL_DDIFFLITSAMPLE1B_DATA_WID) - _ULL(1)) << VT2_CHPL_DDIFFLITSAMPLE1B_DATA_POS)

#define VT2_CHPL_DDIFFLITSAMPLE1C_OFFSET _ULL(0x51c)

#define VT2_CHPL_DDIFFLITSAMPLE1C_POS 0
#define VT2_CHPL_DDIFFLITSAMPLE1C_WID 32
#define VT2_CHPL_DDIFFLITSAMPLE1C_MSK (((_ULL(1) << VT2_CHPL_DDIFFLITSAMPLE1C_WID) - _ULL(1)) << VT2_CHPL_DDIFFLITSAMPLE1C_POS)

#define VT2_CHPL_DDIFFLITSAMPLE1C_DATA_POS 0
#define VT2_CHPL_DDIFFLITSAMPLE1C_DATA_WID 32
#define VT2_CHPL_DDIFFLITSAMPLE1C_DATA_MSK (((_ULL(1) << VT2_CHPL_DDIFFLITSAMPLE1C_DATA_WID) - _ULL(1)) << VT2_CHPL_DDIFFLITSAMPLE1C_DATA_POS)

#define VT2_CHPL_DDIFFLITSAMPLE1D_OFFSET _ULL(0x51d)

#define VT2_CHPL_DDIFFLITSAMPLE1D_POS 0
#define VT2_CHPL_DDIFFLITSAMPLE1D_WID 32
#define VT2_CHPL_DDIFFLITSAMPLE1D_MSK (((_ULL(1) << VT2_CHPL_DDIFFLITSAMPLE1D_WID) - _ULL(1)) << VT2_CHPL_DDIFFLITSAMPLE1D_POS)

#define VT2_CHPL_DDIFFLITSAMPLE1D_DATA_POS 0
#define VT2_CHPL_DDIFFLITSAMPLE1D_DATA_WID 32
#define VT2_CHPL_DDIFFLITSAMPLE1D_DATA_MSK (((_ULL(1) << VT2_CHPL_DDIFFLITSAMPLE1D_DATA_WID) - _ULL(1)) << VT2_CHPL_DDIFFLITSAMPLE1D_DATA_POS)

#define VT2_CHPL_DDIFFLITSAMPLE1E_OFFSET _ULL(0x51e)

#define VT2_CHPL_DDIFFLITSAMPLE1E_POS 0
#define VT2_CHPL_DDIFFLITSAMPLE1E_WID 32
#define VT2_CHPL_DDIFFLITSAMPLE1E_MSK (((_ULL(1) << VT2_CHPL_DDIFFLITSAMPLE1E_WID) - _ULL(1)) << VT2_CHPL_DDIFFLITSAMPLE1E_POS)

#define VT2_CHPL_DDIFFLITSAMPLE1E_DATA_POS 0
#define VT2_CHPL_DDIFFLITSAMPLE1E_DATA_WID 32
#define VT2_CHPL_DDIFFLITSAMPLE1E_DATA_MSK (((_ULL(1) << VT2_CHPL_DDIFFLITSAMPLE1E_DATA_WID) - _ULL(1)) << VT2_CHPL_DDIFFLITSAMPLE1E_DATA_POS)

#define VT2_CHPL_DDIFFLITSAMPLE1F_OFFSET _ULL(0x51f)

#define VT2_CHPL_DDIFFLITSAMPLE1F_POS 0
#define VT2_CHPL_DDIFFLITSAMPLE1F_WID 32
#define VT2_CHPL_DDIFFLITSAMPLE1F_MSK (((_ULL(1) << VT2_CHPL_DDIFFLITSAMPLE1F_WID) - _ULL(1)) << VT2_CHPL_DDIFFLITSAMPLE1F_POS)

#define VT2_CHPL_DDIFFLITSAMPLE1F_DATA_POS 0
#define VT2_CHPL_DDIFFLITSAMPLE1F_DATA_WID 32
#define VT2_CHPL_DDIFFLITSAMPLE1F_DATA_MSK (((_ULL(1) << VT2_CHPL_DDIFFLITSAMPLE1F_DATA_WID) - _ULL(1)) << VT2_CHPL_DDIFFLITSAMPLE1F_DATA_POS)

#define VT2_CHPL_RXVIRTUALWIREDISABLE00_OFFSET _ULL(0x600)

#define VT2_CHPL_RXVIRTUALWIREDISABLE00_POS 0
#define VT2_CHPL_RXVIRTUALWIREDISABLE00_WID 14
#define VT2_CHPL_RXVIRTUALWIREDISABLE00_MSK (((_ULL(1) << VT2_CHPL_RXVIRTUALWIREDISABLE00_WID) - _ULL(1)) << VT2_CHPL_RXVIRTUALWIREDISABLE00_POS)

#define VT2_CHPL_RXVIRTUALWIREDISABLE00_DISABLE_POS 0
#define VT2_CHPL_RXVIRTUALWIREDISABLE00_DISABLE_WID 14
#define VT2_CHPL_RXVIRTUALWIREDISABLE00_DISABLE_MSK (((_ULL(1) << VT2_CHPL_RXVIRTUALWIREDISABLE00_DISABLE_WID) - _ULL(1)) << VT2_CHPL_RXVIRTUALWIREDISABLE00_DISABLE_POS)

#define VT2_CHPL_RXVIRTUALWIRESET00_OFFSET _ULL(0x620)

#define VT2_CHPL_RXVIRTUALWIRESET00_POS 0
#define VT2_CHPL_RXVIRTUALWIRESET00_WID 14
#define VT2_CHPL_RXVIRTUALWIRESET00_MSK (((_ULL(1) << VT2_CHPL_RXVIRTUALWIRESET00_WID) - _ULL(1)) << VT2_CHPL_RXVIRTUALWIRESET00_POS)

#define VT2_CHPL_RXVIRTUALWIRESET00_WIRE_POS 0
#define VT2_CHPL_RXVIRTUALWIRESET00_WIRE_WID 14
#define VT2_CHPL_RXVIRTUALWIRESET00_WIRE_MSK (((_ULL(1) << VT2_CHPL_RXVIRTUALWIRESET00_WIRE_WID) - _ULL(1)) << VT2_CHPL_RXVIRTUALWIRESET00_WIRE_POS)

#define VT2_CHPL_RXVIRTUALWIRECLEAR00_OFFSET _ULL(0x640)

#define VT2_CHPL_RXVIRTUALWIRECLEAR00_POS 0
#define VT2_CHPL_RXVIRTUALWIRECLEAR00_WID 14
#define VT2_CHPL_RXVIRTUALWIRECLEAR00_MSK (((_ULL(1) << VT2_CHPL_RXVIRTUALWIRECLEAR00_WID) - _ULL(1)) << VT2_CHPL_RXVIRTUALWIRECLEAR00_POS)

#define VT2_CHPL_RXVIRTUALWIRECLEAR00_WIRE_POS 0
#define VT2_CHPL_RXVIRTUALWIRECLEAR00_WIRE_WID 14
#define VT2_CHPL_RXVIRTUALWIRECLEAR00_WIRE_MSK (((_ULL(1) << VT2_CHPL_RXVIRTUALWIRECLEAR00_WIRE_WID) - _ULL(1)) << VT2_CHPL_RXVIRTUALWIRECLEAR00_WIRE_POS)

#define VT2_CHPL_RXNEARCREDITCONFIG08_OFFSET _ULL(0x708)

#define VT2_CHPL_RXNEARCREDITCONFIG08_POS 0
#define VT2_CHPL_RXNEARCREDITCONFIG08_WID 8
#define VT2_CHPL_RXNEARCREDITCONFIG08_MSK (((_ULL(1) << VT2_CHPL_RXNEARCREDITCONFIG08_WID) - _ULL(1)) << VT2_CHPL_RXNEARCREDITCONFIG08_POS)

#define VT2_CHPL_RXNEARCREDITCONFIG08_COUNT_POS 0
#define VT2_CHPL_RXNEARCREDITCONFIG08_COUNT_WID 8
#define VT2_CHPL_RXNEARCREDITCONFIG08_COUNT_MSK (((_ULL(1) << VT2_CHPL_RXNEARCREDITCONFIG08_COUNT_WID) - _ULL(1)) << VT2_CHPL_RXNEARCREDITCONFIG08_COUNT_POS)

#define VT2_CHPL_RXNEARCREDITCONFIG09_OFFSET _ULL(0x709)

#define VT2_CHPL_RXNEARCREDITCONFIG09_POS 0
#define VT2_CHPL_RXNEARCREDITCONFIG09_WID 8
#define VT2_CHPL_RXNEARCREDITCONFIG09_MSK (((_ULL(1) << VT2_CHPL_RXNEARCREDITCONFIG09_WID) - _ULL(1)) << VT2_CHPL_RXNEARCREDITCONFIG09_POS)

#define VT2_CHPL_RXNEARCREDITCONFIG09_COUNT_POS 0
#define VT2_CHPL_RXNEARCREDITCONFIG09_COUNT_WID 8
#define VT2_CHPL_RXNEARCREDITCONFIG09_COUNT_MSK (((_ULL(1) << VT2_CHPL_RXNEARCREDITCONFIG09_COUNT_WID) - _ULL(1)) << VT2_CHPL_RXNEARCREDITCONFIG09_COUNT_POS)

#define VT2_CHPL_RXNEARCREDITCONFIG0A_OFFSET _ULL(0x70a)

#define VT2_CHPL_RXNEARCREDITCONFIG0A_POS 0
#define VT2_CHPL_RXNEARCREDITCONFIG0A_WID 8
#define VT2_CHPL_RXNEARCREDITCONFIG0A_MSK (((_ULL(1) << VT2_CHPL_RXNEARCREDITCONFIG0A_WID) - _ULL(1)) << VT2_CHPL_RXNEARCREDITCONFIG0A_POS)

#define VT2_CHPL_RXNEARCREDITCONFIG0A_COUNT_POS 0
#define VT2_CHPL_RXNEARCREDITCONFIG0A_COUNT_WID 8
#define VT2_CHPL_RXNEARCREDITCONFIG0A_COUNT_MSK (((_ULL(1) << VT2_CHPL_RXNEARCREDITCONFIG0A_COUNT_WID) - _ULL(1)) << VT2_CHPL_RXNEARCREDITCONFIG0A_COUNT_POS)

#define VT2_CHPL_RXNEARCREDITCONFIG0B_OFFSET _ULL(0x70b)

#define VT2_CHPL_RXNEARCREDITCONFIG0B_POS 0
#define VT2_CHPL_RXNEARCREDITCONFIG0B_WID 8
#define VT2_CHPL_RXNEARCREDITCONFIG0B_MSK (((_ULL(1) << VT2_CHPL_RXNEARCREDITCONFIG0B_WID) - _ULL(1)) << VT2_CHPL_RXNEARCREDITCONFIG0B_POS)

#define VT2_CHPL_RXNEARCREDITCONFIG0B_COUNT_POS 0
#define VT2_CHPL_RXNEARCREDITCONFIG0B_COUNT_WID 8
#define VT2_CHPL_RXNEARCREDITCONFIG0B_COUNT_MSK (((_ULL(1) << VT2_CHPL_RXNEARCREDITCONFIG0B_COUNT_WID) - _ULL(1)) << VT2_CHPL_RXNEARCREDITCONFIG0B_COUNT_POS)

#define VT2_CHPL_RXNEARCREDITCONFIG22_OFFSET _ULL(0x722)

#define VT2_CHPL_RXNEARCREDITCONFIG22_POS 0
#define VT2_CHPL_RXNEARCREDITCONFIG22_WID 8
#define VT2_CHPL_RXNEARCREDITCONFIG22_MSK (((_ULL(1) << VT2_CHPL_RXNEARCREDITCONFIG22_WID) - _ULL(1)) << VT2_CHPL_RXNEARCREDITCONFIG22_POS)

#define VT2_CHPL_RXNEARCREDITCONFIG22_COUNT_POS 0
#define VT2_CHPL_RXNEARCREDITCONFIG22_COUNT_WID 8
#define VT2_CHPL_RXNEARCREDITCONFIG22_COUNT_MSK (((_ULL(1) << VT2_CHPL_RXNEARCREDITCONFIG22_COUNT_WID) - _ULL(1)) << VT2_CHPL_RXNEARCREDITCONFIG22_COUNT_POS)

#define VT2_CHPL_RXNEARCREDITCONFIG24_OFFSET _ULL(0x724)

#define VT2_CHPL_RXNEARCREDITCONFIG24_POS 0
#define VT2_CHPL_RXNEARCREDITCONFIG24_WID 8
#define VT2_CHPL_RXNEARCREDITCONFIG24_MSK (((_ULL(1) << VT2_CHPL_RXNEARCREDITCONFIG24_WID) - _ULL(1)) << VT2_CHPL_RXNEARCREDITCONFIG24_POS)

#define VT2_CHPL_RXNEARCREDITCONFIG24_COUNT_POS 0
#define VT2_CHPL_RXNEARCREDITCONFIG24_COUNT_WID 8
#define VT2_CHPL_RXNEARCREDITCONFIG24_COUNT_MSK (((_ULL(1) << VT2_CHPL_RXNEARCREDITCONFIG24_COUNT_WID) - _ULL(1)) << VT2_CHPL_RXNEARCREDITCONFIG24_COUNT_POS)

#define VT2_CHPL_RXNEARCREDITCONFIG26_OFFSET _ULL(0x726)

#define VT2_CHPL_RXNEARCREDITCONFIG26_POS 0
#define VT2_CHPL_RXNEARCREDITCONFIG26_WID 8
#define VT2_CHPL_RXNEARCREDITCONFIG26_MSK (((_ULL(1) << VT2_CHPL_RXNEARCREDITCONFIG26_WID) - _ULL(1)) << VT2_CHPL_RXNEARCREDITCONFIG26_POS)

#define VT2_CHPL_RXNEARCREDITCONFIG26_COUNT_POS 0
#define VT2_CHPL_RXNEARCREDITCONFIG26_COUNT_WID 8
#define VT2_CHPL_RXNEARCREDITCONFIG26_COUNT_MSK (((_ULL(1) << VT2_CHPL_RXNEARCREDITCONFIG26_COUNT_WID) - _ULL(1)) << VT2_CHPL_RXNEARCREDITCONFIG26_COUNT_POS)

#define VT2_CHPL_RXNEARCREDITLIMIT08_OFFSET _ULL(0x748)

#define VT2_CHPL_RXNEARCREDITLIMIT08_POS 0
#define VT2_CHPL_RXNEARCREDITLIMIT08_WID 8
#define VT2_CHPL_RXNEARCREDITLIMIT08_MSK (((_ULL(1) << VT2_CHPL_RXNEARCREDITLIMIT08_WID) - _ULL(1)) << VT2_CHPL_RXNEARCREDITLIMIT08_POS)

#define VT2_CHPL_RXNEARCREDITLIMIT08_COUNT_POS 0
#define VT2_CHPL_RXNEARCREDITLIMIT08_COUNT_WID 8
#define VT2_CHPL_RXNEARCREDITLIMIT08_COUNT_MSK (((_ULL(1) << VT2_CHPL_RXNEARCREDITLIMIT08_COUNT_WID) - _ULL(1)) << VT2_CHPL_RXNEARCREDITLIMIT08_COUNT_POS)

#define VT2_CHPL_RXNEARCREDITLIMIT09_OFFSET _ULL(0x749)

#define VT2_CHPL_RXNEARCREDITLIMIT09_POS 0
#define VT2_CHPL_RXNEARCREDITLIMIT09_WID 8
#define VT2_CHPL_RXNEARCREDITLIMIT09_MSK (((_ULL(1) << VT2_CHPL_RXNEARCREDITLIMIT09_WID) - _ULL(1)) << VT2_CHPL_RXNEARCREDITLIMIT09_POS)

#define VT2_CHPL_RXNEARCREDITLIMIT09_COUNT_POS 0
#define VT2_CHPL_RXNEARCREDITLIMIT09_COUNT_WID 8
#define VT2_CHPL_RXNEARCREDITLIMIT09_COUNT_MSK (((_ULL(1) << VT2_CHPL_RXNEARCREDITLIMIT09_COUNT_WID) - _ULL(1)) << VT2_CHPL_RXNEARCREDITLIMIT09_COUNT_POS)

#define VT2_CHPL_RXNEARCREDITLIMIT0A_OFFSET _ULL(0x74a)

#define VT2_CHPL_RXNEARCREDITLIMIT0A_POS 0
#define VT2_CHPL_RXNEARCREDITLIMIT0A_WID 8
#define VT2_CHPL_RXNEARCREDITLIMIT0A_MSK (((_ULL(1) << VT2_CHPL_RXNEARCREDITLIMIT0A_WID) - _ULL(1)) << VT2_CHPL_RXNEARCREDITLIMIT0A_POS)

#define VT2_CHPL_RXNEARCREDITLIMIT0A_COUNT_POS 0
#define VT2_CHPL_RXNEARCREDITLIMIT0A_COUNT_WID 8
#define VT2_CHPL_RXNEARCREDITLIMIT0A_COUNT_MSK (((_ULL(1) << VT2_CHPL_RXNEARCREDITLIMIT0A_COUNT_WID) - _ULL(1)) << VT2_CHPL_RXNEARCREDITLIMIT0A_COUNT_POS)

#define VT2_CHPL_RXNEARCREDITLIMIT0B_OFFSET _ULL(0x74b)

#define VT2_CHPL_RXNEARCREDITLIMIT0B_POS 0
#define VT2_CHPL_RXNEARCREDITLIMIT0B_WID 8
#define VT2_CHPL_RXNEARCREDITLIMIT0B_MSK (((_ULL(1) << VT2_CHPL_RXNEARCREDITLIMIT0B_WID) - _ULL(1)) << VT2_CHPL_RXNEARCREDITLIMIT0B_POS)

#define VT2_CHPL_RXNEARCREDITLIMIT0B_COUNT_POS 0
#define VT2_CHPL_RXNEARCREDITLIMIT0B_COUNT_WID 8
#define VT2_CHPL_RXNEARCREDITLIMIT0B_COUNT_MSK (((_ULL(1) << VT2_CHPL_RXNEARCREDITLIMIT0B_COUNT_WID) - _ULL(1)) << VT2_CHPL_RXNEARCREDITLIMIT0B_COUNT_POS)

#define VT2_CHPL_RXNEARCREDITLIMIT22_OFFSET _ULL(0x762)

#define VT2_CHPL_RXNEARCREDITLIMIT22_POS 0
#define VT2_CHPL_RXNEARCREDITLIMIT22_WID 8
#define VT2_CHPL_RXNEARCREDITLIMIT22_MSK (((_ULL(1) << VT2_CHPL_RXNEARCREDITLIMIT22_WID) - _ULL(1)) << VT2_CHPL_RXNEARCREDITLIMIT22_POS)

#define VT2_CHPL_RXNEARCREDITLIMIT22_COUNT_POS 0
#define VT2_CHPL_RXNEARCREDITLIMIT22_COUNT_WID 8
#define VT2_CHPL_RXNEARCREDITLIMIT22_COUNT_MSK (((_ULL(1) << VT2_CHPL_RXNEARCREDITLIMIT22_COUNT_WID) - _ULL(1)) << VT2_CHPL_RXNEARCREDITLIMIT22_COUNT_POS)

#define VT2_CHPL_RXNEARCREDITLIMIT24_OFFSET _ULL(0x764)

#define VT2_CHPL_RXNEARCREDITLIMIT24_POS 0
#define VT2_CHPL_RXNEARCREDITLIMIT24_WID 8
#define VT2_CHPL_RXNEARCREDITLIMIT24_MSK (((_ULL(1) << VT2_CHPL_RXNEARCREDITLIMIT24_WID) - _ULL(1)) << VT2_CHPL_RXNEARCREDITLIMIT24_POS)

#define VT2_CHPL_RXNEARCREDITLIMIT24_COUNT_POS 0
#define VT2_CHPL_RXNEARCREDITLIMIT24_COUNT_WID 8
#define VT2_CHPL_RXNEARCREDITLIMIT24_COUNT_MSK (((_ULL(1) << VT2_CHPL_RXNEARCREDITLIMIT24_COUNT_WID) - _ULL(1)) << VT2_CHPL_RXNEARCREDITLIMIT24_COUNT_POS)

#define VT2_CHPL_RXNEARCREDITLIMIT26_OFFSET _ULL(0x766)

#define VT2_CHPL_RXNEARCREDITLIMIT26_POS 0
#define VT2_CHPL_RXNEARCREDITLIMIT26_WID 8
#define VT2_CHPL_RXNEARCREDITLIMIT26_MSK (((_ULL(1) << VT2_CHPL_RXNEARCREDITLIMIT26_WID) - _ULL(1)) << VT2_CHPL_RXNEARCREDITLIMIT26_POS)

#define VT2_CHPL_RXNEARCREDITLIMIT26_COUNT_POS 0
#define VT2_CHPL_RXNEARCREDITLIMIT26_COUNT_WID 8
#define VT2_CHPL_RXNEARCREDITLIMIT26_COUNT_MSK (((_ULL(1) << VT2_CHPL_RXNEARCREDITLIMIT26_COUNT_WID) - _ULL(1)) << VT2_CHPL_RXNEARCREDITLIMIT26_COUNT_POS)

#define VT2_CHPL_RXNEARCREDITCOUNT08_OFFSET _ULL(0x788)

#define VT2_CHPL_RXNEARCREDITCOUNT08_POS 0
#define VT2_CHPL_RXNEARCREDITCOUNT08_WID 8
#define VT2_CHPL_RXNEARCREDITCOUNT08_MSK (((_ULL(1) << VT2_CHPL_RXNEARCREDITCOUNT08_WID) - _ULL(1)) << VT2_CHPL_RXNEARCREDITCOUNT08_POS)

#define VT2_CHPL_RXNEARCREDITCOUNT08_COUNT_POS 0
#define VT2_CHPL_RXNEARCREDITCOUNT08_COUNT_WID 8
#define VT2_CHPL_RXNEARCREDITCOUNT08_COUNT_MSK (((_ULL(1) << VT2_CHPL_RXNEARCREDITCOUNT08_COUNT_WID) - _ULL(1)) << VT2_CHPL_RXNEARCREDITCOUNT08_COUNT_POS)

#define VT2_CHPL_RXNEARCREDITCOUNT09_OFFSET _ULL(0x789)

#define VT2_CHPL_RXNEARCREDITCOUNT09_POS 0
#define VT2_CHPL_RXNEARCREDITCOUNT09_WID 8
#define VT2_CHPL_RXNEARCREDITCOUNT09_MSK (((_ULL(1) << VT2_CHPL_RXNEARCREDITCOUNT09_WID) - _ULL(1)) << VT2_CHPL_RXNEARCREDITCOUNT09_POS)

#define VT2_CHPL_RXNEARCREDITCOUNT09_COUNT_POS 0
#define VT2_CHPL_RXNEARCREDITCOUNT09_COUNT_WID 8
#define VT2_CHPL_RXNEARCREDITCOUNT09_COUNT_MSK (((_ULL(1) << VT2_CHPL_RXNEARCREDITCOUNT09_COUNT_WID) - _ULL(1)) << VT2_CHPL_RXNEARCREDITCOUNT09_COUNT_POS)

#define VT2_CHPL_RXNEARCREDITCOUNT0A_OFFSET _ULL(0x78a)

#define VT2_CHPL_RXNEARCREDITCOUNT0A_POS 0
#define VT2_CHPL_RXNEARCREDITCOUNT0A_WID 8
#define VT2_CHPL_RXNEARCREDITCOUNT0A_MSK (((_ULL(1) << VT2_CHPL_RXNEARCREDITCOUNT0A_WID) - _ULL(1)) << VT2_CHPL_RXNEARCREDITCOUNT0A_POS)

#define VT2_CHPL_RXNEARCREDITCOUNT0A_COUNT_POS 0
#define VT2_CHPL_RXNEARCREDITCOUNT0A_COUNT_WID 8
#define VT2_CHPL_RXNEARCREDITCOUNT0A_COUNT_MSK (((_ULL(1) << VT2_CHPL_RXNEARCREDITCOUNT0A_COUNT_WID) - _ULL(1)) << VT2_CHPL_RXNEARCREDITCOUNT0A_COUNT_POS)

#define VT2_CHPL_RXNEARCREDITCOUNT0B_OFFSET _ULL(0x78b)

#define VT2_CHPL_RXNEARCREDITCOUNT0B_POS 0
#define VT2_CHPL_RXNEARCREDITCOUNT0B_WID 8
#define VT2_CHPL_RXNEARCREDITCOUNT0B_MSK (((_ULL(1) << VT2_CHPL_RXNEARCREDITCOUNT0B_WID) - _ULL(1)) << VT2_CHPL_RXNEARCREDITCOUNT0B_POS)

#define VT2_CHPL_RXNEARCREDITCOUNT0B_COUNT_POS 0
#define VT2_CHPL_RXNEARCREDITCOUNT0B_COUNT_WID 8
#define VT2_CHPL_RXNEARCREDITCOUNT0B_COUNT_MSK (((_ULL(1) << VT2_CHPL_RXNEARCREDITCOUNT0B_COUNT_WID) - _ULL(1)) << VT2_CHPL_RXNEARCREDITCOUNT0B_COUNT_POS)

#define VT2_CHPL_RXNEARCREDITCOUNT22_OFFSET _ULL(0x7a2)

#define VT2_CHPL_RXNEARCREDITCOUNT22_POS 0
#define VT2_CHPL_RXNEARCREDITCOUNT22_WID 8
#define VT2_CHPL_RXNEARCREDITCOUNT22_MSK (((_ULL(1) << VT2_CHPL_RXNEARCREDITCOUNT22_WID) - _ULL(1)) << VT2_CHPL_RXNEARCREDITCOUNT22_POS)

#define VT2_CHPL_RXNEARCREDITCOUNT22_COUNT_POS 0
#define VT2_CHPL_RXNEARCREDITCOUNT22_COUNT_WID 8
#define VT2_CHPL_RXNEARCREDITCOUNT22_COUNT_MSK (((_ULL(1) << VT2_CHPL_RXNEARCREDITCOUNT22_COUNT_WID) - _ULL(1)) << VT2_CHPL_RXNEARCREDITCOUNT22_COUNT_POS)

#define VT2_CHPL_RXNEARCREDITCOUNT24_OFFSET _ULL(0x7a4)

#define VT2_CHPL_RXNEARCREDITCOUNT24_POS 0
#define VT2_CHPL_RXNEARCREDITCOUNT24_WID 8
#define VT2_CHPL_RXNEARCREDITCOUNT24_MSK (((_ULL(1) << VT2_CHPL_RXNEARCREDITCOUNT24_WID) - _ULL(1)) << VT2_CHPL_RXNEARCREDITCOUNT24_POS)

#define VT2_CHPL_RXNEARCREDITCOUNT24_COUNT_POS 0
#define VT2_CHPL_RXNEARCREDITCOUNT24_COUNT_WID 8
#define VT2_CHPL_RXNEARCREDITCOUNT24_COUNT_MSK (((_ULL(1) << VT2_CHPL_RXNEARCREDITCOUNT24_COUNT_WID) - _ULL(1)) << VT2_CHPL_RXNEARCREDITCOUNT24_COUNT_POS)

#define VT2_CHPL_RXNEARCREDITCOUNT26_OFFSET _ULL(0x7a6)

#define VT2_CHPL_RXNEARCREDITCOUNT26_POS 0
#define VT2_CHPL_RXNEARCREDITCOUNT26_WID 8
#define VT2_CHPL_RXNEARCREDITCOUNT26_MSK (((_ULL(1) << VT2_CHPL_RXNEARCREDITCOUNT26_WID) - _ULL(1)) << VT2_CHPL_RXNEARCREDITCOUNT26_POS)

#define VT2_CHPL_RXNEARCREDITCOUNT26_COUNT_POS 0
#define VT2_CHPL_RXNEARCREDITCOUNT26_COUNT_WID 8
#define VT2_CHPL_RXNEARCREDITCOUNT26_COUNT_MSK (((_ULL(1) << VT2_CHPL_RXNEARCREDITCOUNT26_COUNT_WID) - _ULL(1)) << VT2_CHPL_RXNEARCREDITCOUNT26_COUNT_POS)

#define VT2_CHPL_RXFARCREDITCOUNT08_OFFSET _ULL(0x7c8)

#define VT2_CHPL_RXFARCREDITCOUNT08_POS 0
#define VT2_CHPL_RXFARCREDITCOUNT08_WID 8
#define VT2_CHPL_RXFARCREDITCOUNT08_MSK (((_ULL(1) << VT2_CHPL_RXFARCREDITCOUNT08_WID) - _ULL(1)) << VT2_CHPL_RXFARCREDITCOUNT08_POS)

#define VT2_CHPL_RXFARCREDITCOUNT08_COUNT_POS 0
#define VT2_CHPL_RXFARCREDITCOUNT08_COUNT_WID 8
#define VT2_CHPL_RXFARCREDITCOUNT08_COUNT_MSK (((_ULL(1) << VT2_CHPL_RXFARCREDITCOUNT08_COUNT_WID) - _ULL(1)) << VT2_CHPL_RXFARCREDITCOUNT08_COUNT_POS)

#define VT2_CHPL_RXFARCREDITCOUNT09_OFFSET _ULL(0x7c9)

#define VT2_CHPL_RXFARCREDITCOUNT09_POS 0
#define VT2_CHPL_RXFARCREDITCOUNT09_WID 8
#define VT2_CHPL_RXFARCREDITCOUNT09_MSK (((_ULL(1) << VT2_CHPL_RXFARCREDITCOUNT09_WID) - _ULL(1)) << VT2_CHPL_RXFARCREDITCOUNT09_POS)

#define VT2_CHPL_RXFARCREDITCOUNT09_COUNT_POS 0
#define VT2_CHPL_RXFARCREDITCOUNT09_COUNT_WID 8
#define VT2_CHPL_RXFARCREDITCOUNT09_COUNT_MSK (((_ULL(1) << VT2_CHPL_RXFARCREDITCOUNT09_COUNT_WID) - _ULL(1)) << VT2_CHPL_RXFARCREDITCOUNT09_COUNT_POS)

#define VT2_CHPL_RXFARCREDITCOUNT0A_OFFSET _ULL(0x7ca)

#define VT2_CHPL_RXFARCREDITCOUNT0A_POS 0
#define VT2_CHPL_RXFARCREDITCOUNT0A_WID 8
#define VT2_CHPL_RXFARCREDITCOUNT0A_MSK (((_ULL(1) << VT2_CHPL_RXFARCREDITCOUNT0A_WID) - _ULL(1)) << VT2_CHPL_RXFARCREDITCOUNT0A_POS)

#define VT2_CHPL_RXFARCREDITCOUNT0A_COUNT_POS 0
#define VT2_CHPL_RXFARCREDITCOUNT0A_COUNT_WID 8
#define VT2_CHPL_RXFARCREDITCOUNT0A_COUNT_MSK (((_ULL(1) << VT2_CHPL_RXFARCREDITCOUNT0A_COUNT_WID) - _ULL(1)) << VT2_CHPL_RXFARCREDITCOUNT0A_COUNT_POS)

#define VT2_CHPL_RXFARCREDITCOUNT0B_OFFSET _ULL(0x7cb)

#define VT2_CHPL_RXFARCREDITCOUNT0B_POS 0
#define VT2_CHPL_RXFARCREDITCOUNT0B_WID 8
#define VT2_CHPL_RXFARCREDITCOUNT0B_MSK (((_ULL(1) << VT2_CHPL_RXFARCREDITCOUNT0B_WID) - _ULL(1)) << VT2_CHPL_RXFARCREDITCOUNT0B_POS)

#define VT2_CHPL_RXFARCREDITCOUNT0B_COUNT_POS 0
#define VT2_CHPL_RXFARCREDITCOUNT0B_COUNT_WID 8
#define VT2_CHPL_RXFARCREDITCOUNT0B_COUNT_MSK (((_ULL(1) << VT2_CHPL_RXFARCREDITCOUNT0B_COUNT_WID) - _ULL(1)) << VT2_CHPL_RXFARCREDITCOUNT0B_COUNT_POS)

#define VT2_CHPL_RXFARCREDITCOUNT20_OFFSET _ULL(0x7e0)

#define VT2_CHPL_RXFARCREDITCOUNT20_POS 0
#define VT2_CHPL_RXFARCREDITCOUNT20_WID 8
#define VT2_CHPL_RXFARCREDITCOUNT20_MSK (((_ULL(1) << VT2_CHPL_RXFARCREDITCOUNT20_WID) - _ULL(1)) << VT2_CHPL_RXFARCREDITCOUNT20_POS)

#define VT2_CHPL_RXFARCREDITCOUNT20_COUNT_POS 0
#define VT2_CHPL_RXFARCREDITCOUNT20_COUNT_WID 8
#define VT2_CHPL_RXFARCREDITCOUNT20_COUNT_MSK (((_ULL(1) << VT2_CHPL_RXFARCREDITCOUNT20_COUNT_WID) - _ULL(1)) << VT2_CHPL_RXFARCREDITCOUNT20_COUNT_POS)

#define VT2_CHPL_RXFARCREDITCOUNT24_OFFSET _ULL(0x7e4)

#define VT2_CHPL_RXFARCREDITCOUNT24_POS 0
#define VT2_CHPL_RXFARCREDITCOUNT24_WID 8
#define VT2_CHPL_RXFARCREDITCOUNT24_MSK (((_ULL(1) << VT2_CHPL_RXFARCREDITCOUNT24_WID) - _ULL(1)) << VT2_CHPL_RXFARCREDITCOUNT24_POS)

#define VT2_CHPL_RXFARCREDITCOUNT24_COUNT_POS 0
#define VT2_CHPL_RXFARCREDITCOUNT24_COUNT_WID 8
#define VT2_CHPL_RXFARCREDITCOUNT24_COUNT_MSK (((_ULL(1) << VT2_CHPL_RXFARCREDITCOUNT24_COUNT_WID) - _ULL(1)) << VT2_CHPL_RXFARCREDITCOUNT24_COUNT_POS)

#define VT2_CHPL_RXFARCREDITCOUNT26_OFFSET _ULL(0x7e6)

#define VT2_CHPL_RXFARCREDITCOUNT26_POS 0
#define VT2_CHPL_RXFARCREDITCOUNT26_WID 8
#define VT2_CHPL_RXFARCREDITCOUNT26_MSK (((_ULL(1) << VT2_CHPL_RXFARCREDITCOUNT26_WID) - _ULL(1)) << VT2_CHPL_RXFARCREDITCOUNT26_POS)

#define VT2_CHPL_RXFARCREDITCOUNT26_COUNT_POS 0
#define VT2_CHPL_RXFARCREDITCOUNT26_COUNT_WID 8
#define VT2_CHPL_RXFARCREDITCOUNT26_COUNT_MSK (((_ULL(1) << VT2_CHPL_RXFARCREDITCOUNT26_COUNT_WID) - _ULL(1)) << VT2_CHPL_RXFARCREDITCOUNT26_COUNT_POS)
#endif /* VT2_CHPL_MMR_H */
