/* This file is auto-generated. Do not hand edit this file. */

#ifndef VT2_CHIB_MMR_H
#define VT2_CHIB_MMR_H

#ifndef _ULL

#ifdef __ASSEMBLER__
#define _AC(X,Y) X
#else
#define __AC(X,Y) (X##Y)
#define _AC(X,Y) __AC(X,Y)
#endif

#define _ULL(x)  (_AC(x, ULL))
#endif


#define VT2_CHIB_CHICONFIGLOW_OFFSET _ULL(0x0)

#define VT2_CHIB_CHICONFIGLOW_POS 0
#define VT2_CHIB_CHICONFIGLOW_WID 24
#define VT2_CHIB_CHICONFIGLOW_MSK (((_ULL(1) << VT2_CHIB_CHICONFIGLOW_WID) - _ULL(1)) << VT2_CHIB_CHICONFIGLOW_POS)

#define VT2_CHIB_CHICONFIGLOW_HNINODEID_POS 0
#define VT2_CHIB_CHICONFIGLOW_HNINODEID_WID 11
#define VT2_CHIB_CHICONFIGLOW_HNINODEID_MSK (((_ULL(1) << VT2_CHIB_CHICONFIGLOW_HNINODEID_WID) - _ULL(1)) << VT2_CHIB_CHICONFIGLOW_HNINODEID_POS)
#define VT2_CHIB_CHICONFIGLOW_RNITXNID_POS 11
#define VT2_CHIB_CHICONFIGLOW_RNITXNID_WID 12
#define VT2_CHIB_CHICONFIGLOW_RNITXNID_MSK (((_ULL(1) << VT2_CHIB_CHICONFIGLOW_RNITXNID_WID) - _ULL(1)) << VT2_CHIB_CHICONFIGLOW_RNITXNID_POS)
#define VT2_CHIB_CHICONFIGLOW_ENABLERNI_POS 23
#define VT2_CHIB_CHICONFIGLOW_ENABLERNI_WID 1
#define VT2_CHIB_CHICONFIGLOW_ENABLERNI_MSK (((_ULL(1) << VT2_CHIB_CHICONFIGLOW_ENABLERNI_WID) - _ULL(1)) << VT2_CHIB_CHICONFIGLOW_ENABLERNI_POS)

#define VT2_CHIB_CHICONFIGHIGH_OFFSET _ULL(0x1)

#define VT2_CHIB_CHICONFIGHIGH_POS 0
#define VT2_CHIB_CHICONFIGHIGH_WID 12
#define VT2_CHIB_CHICONFIGHIGH_MSK (((_ULL(1) << VT2_CHIB_CHICONFIGHIGH_WID) - _ULL(1)) << VT2_CHIB_CHICONFIGHIGH_POS)

#define VT2_CHIB_CHICONFIGHIGH_CLUSTERNODEID_POS 0
#define VT2_CHIB_CHICONFIGHIGH_CLUSTERNODEID_WID 11
#define VT2_CHIB_CHICONFIGHIGH_CLUSTERNODEID_MSK (((_ULL(1) << VT2_CHIB_CHICONFIGHIGH_CLUSTERNODEID_WID) - _ULL(1)) << VT2_CHIB_CHICONFIGHIGH_CLUSTERNODEID_POS)
#define VT2_CHIB_CHICONFIGHIGH_CLUSTERNS_POS 11
#define VT2_CHIB_CHICONFIGHIGH_CLUSTERNS_WID 1
#define VT2_CHIB_CHICONFIGHIGH_CLUSTERNS_MSK (((_ULL(1) << VT2_CHIB_CHICONFIGHIGH_CLUSTERNS_WID) - _ULL(1)) << VT2_CHIB_CHICONFIGHIGH_CLUSTERNS_POS)

#define VT2_CHIB_PCLLINK_OFFSET _ULL(0x2)

#define VT2_CHIB_PCLLINK_POS 0
#define VT2_CHIB_PCLLINK_WID 5
#define VT2_CHIB_PCLLINK_MSK (((_ULL(1) << VT2_CHIB_PCLLINK_WID) - _ULL(1)) << VT2_CHIB_PCLLINK_POS)

#define VT2_CHIB_PCLLINK_TXLINKACTIVATE_POS 0
#define VT2_CHIB_PCLLINK_TXLINKACTIVATE_WID 1
#define VT2_CHIB_PCLLINK_TXLINKACTIVATE_MSK (((_ULL(1) << VT2_CHIB_PCLLINK_TXLINKACTIVATE_WID) - _ULL(1)) << VT2_CHIB_PCLLINK_TXLINKACTIVATE_POS)
#define VT2_CHIB_PCLLINK_TXLINKREQ_POS 1
#define VT2_CHIB_PCLLINK_TXLINKREQ_WID 1
#define VT2_CHIB_PCLLINK_TXLINKREQ_MSK (((_ULL(1) << VT2_CHIB_PCLLINK_TXLINKREQ_WID) - _ULL(1)) << VT2_CHIB_PCLLINK_TXLINKREQ_POS)
#define VT2_CHIB_PCLLINK_TXLINKACK_POS 2
#define VT2_CHIB_PCLLINK_TXLINKACK_WID 1
#define VT2_CHIB_PCLLINK_TXLINKACK_MSK (((_ULL(1) << VT2_CHIB_PCLLINK_TXLINKACK_WID) - _ULL(1)) << VT2_CHIB_PCLLINK_TXLINKACK_POS)
#define VT2_CHIB_PCLLINK_RXLINKREQ_POS 3
#define VT2_CHIB_PCLLINK_RXLINKREQ_WID 1
#define VT2_CHIB_PCLLINK_RXLINKREQ_MSK (((_ULL(1) << VT2_CHIB_PCLLINK_RXLINKREQ_WID) - _ULL(1)) << VT2_CHIB_PCLLINK_RXLINKREQ_POS)
#define VT2_CHIB_PCLLINK_RXLINKACK_POS 4
#define VT2_CHIB_PCLLINK_RXLINKACK_WID 1
#define VT2_CHIB_PCLLINK_RXLINKACK_MSK (((_ULL(1) << VT2_CHIB_PCLLINK_RXLINKACK_WID) - _ULL(1)) << VT2_CHIB_PCLLINK_RXLINKACK_POS)

#define VT2_CHIB_SDDILINK_OFFSET _ULL(0x3)

#define VT2_CHIB_SDDILINK_POS 0
#define VT2_CHIB_SDDILINK_WID 5
#define VT2_CHIB_SDDILINK_MSK (((_ULL(1) << VT2_CHIB_SDDILINK_WID) - _ULL(1)) << VT2_CHIB_SDDILINK_POS)

#define VT2_CHIB_SDDILINK_TXLINKACTIVATE_POS 0
#define VT2_CHIB_SDDILINK_TXLINKACTIVATE_WID 1
#define VT2_CHIB_SDDILINK_TXLINKACTIVATE_MSK (((_ULL(1) << VT2_CHIB_SDDILINK_TXLINKACTIVATE_WID) - _ULL(1)) << VT2_CHIB_SDDILINK_TXLINKACTIVATE_POS)
#define VT2_CHIB_SDDILINK_TXLINKREQ_POS 1
#define VT2_CHIB_SDDILINK_TXLINKREQ_WID 1
#define VT2_CHIB_SDDILINK_TXLINKREQ_MSK (((_ULL(1) << VT2_CHIB_SDDILINK_TXLINKREQ_WID) - _ULL(1)) << VT2_CHIB_SDDILINK_TXLINKREQ_POS)
#define VT2_CHIB_SDDILINK_TXLINKACK_POS 2
#define VT2_CHIB_SDDILINK_TXLINKACK_WID 1
#define VT2_CHIB_SDDILINK_TXLINKACK_MSK (((_ULL(1) << VT2_CHIB_SDDILINK_TXLINKACK_WID) - _ULL(1)) << VT2_CHIB_SDDILINK_TXLINKACK_POS)
#define VT2_CHIB_SDDILINK_RXLINKREQ_POS 3
#define VT2_CHIB_SDDILINK_RXLINKREQ_WID 1
#define VT2_CHIB_SDDILINK_RXLINKREQ_MSK (((_ULL(1) << VT2_CHIB_SDDILINK_RXLINKREQ_WID) - _ULL(1)) << VT2_CHIB_SDDILINK_RXLINKREQ_POS)
#define VT2_CHIB_SDDILINK_RXLINKACK_POS 4
#define VT2_CHIB_SDDILINK_RXLINKACK_WID 1
#define VT2_CHIB_SDDILINK_RXLINKACK_MSK (((_ULL(1) << VT2_CHIB_SDDILINK_RXLINKACK_WID) - _ULL(1)) << VT2_CHIB_SDDILINK_RXLINKACK_POS)

#define VT2_CHIB_RNIADDRLOW_OFFSET _ULL(0x4)

#define VT2_CHIB_RNIADDRLOW_POS 0
#define VT2_CHIB_RNIADDRLOW_WID 30
#define VT2_CHIB_RNIADDRLOW_MSK (((_ULL(1) << VT2_CHIB_RNIADDRLOW_WID) - _ULL(1)) << VT2_CHIB_RNIADDRLOW_POS)

#define VT2_CHIB_RNIADDRLOW_ADDRLOW_POS 0
#define VT2_CHIB_RNIADDRLOW_ADDRLOW_WID 30
#define VT2_CHIB_RNIADDRLOW_ADDRLOW_MSK (((_ULL(1) << VT2_CHIB_RNIADDRLOW_ADDRLOW_WID) - _ULL(1)) << VT2_CHIB_RNIADDRLOW_ADDRLOW_POS)

#define VT2_CHIB_RNIADDRHIGH_OFFSET _ULL(0x5)

#define VT2_CHIB_RNIADDRHIGH_POS 0
#define VT2_CHIB_RNIADDRHIGH_WID 25
#define VT2_CHIB_RNIADDRHIGH_MSK (((_ULL(1) << VT2_CHIB_RNIADDRHIGH_WID) - _ULL(1)) << VT2_CHIB_RNIADDRHIGH_POS)

#define VT2_CHIB_RNIADDRHIGH_ADDRHIGH_POS 0
#define VT2_CHIB_RNIADDRHIGH_ADDRHIGH_WID 16
#define VT2_CHIB_RNIADDRHIGH_ADDRHIGH_MSK (((_ULL(1) << VT2_CHIB_RNIADDRHIGH_ADDRHIGH_WID) - _ULL(1)) << VT2_CHIB_RNIADDRHIGH_ADDRHIGH_POS)
#define VT2_CHIB_RNIADDRHIGH_RESERVED_POS 16
#define VT2_CHIB_RNIADDRHIGH_RESERVED_WID 4
#define VT2_CHIB_RNIADDRHIGH_RESERVED_MSK (((_ULL(1) << VT2_CHIB_RNIADDRHIGH_RESERVED_WID) - _ULL(1)) << VT2_CHIB_RNIADDRHIGH_RESERVED_POS)
#define VT2_CHIB_RNIADDRHIGH_NS_POS 20
#define VT2_CHIB_RNIADDRHIGH_NS_WID 1
#define VT2_CHIB_RNIADDRHIGH_NS_MSK (((_ULL(1) << VT2_CHIB_RNIADDRHIGH_NS_WID) - _ULL(1)) << VT2_CHIB_RNIADDRHIGH_NS_POS)
#define VT2_CHIB_RNIADDRHIGH_OPCODE_POS 21
#define VT2_CHIB_RNIADDRHIGH_OPCODE_WID 1
#define VT2_CHIB_RNIADDRHIGH_OPCODE_MSK (((_ULL(1) << VT2_CHIB_RNIADDRHIGH_OPCODE_WID) - _ULL(1)) << VT2_CHIB_RNIADDRHIGH_OPCODE_POS)
#define VT2_CHIB_RNIADDRHIGH_SIZE_POS 22
#define VT2_CHIB_RNIADDRHIGH_SIZE_WID 1
#define VT2_CHIB_RNIADDRHIGH_SIZE_MSK (((_ULL(1) << VT2_CHIB_RNIADDRHIGH_SIZE_WID) - _ULL(1)) << VT2_CHIB_RNIADDRHIGH_SIZE_POS)
#define VT2_CHIB_RNIADDRHIGH_GENREQ_POS 23
#define VT2_CHIB_RNIADDRHIGH_GENREQ_WID 1
#define VT2_CHIB_RNIADDRHIGH_GENREQ_MSK (((_ULL(1) << VT2_CHIB_RNIADDRHIGH_GENREQ_WID) - _ULL(1)) << VT2_CHIB_RNIADDRHIGH_GENREQ_POS)
#define VT2_CHIB_RNIADDRHIGH_REQCOMPLETED_POS 24
#define VT2_CHIB_RNIADDRHIGH_REQCOMPLETED_WID 1
#define VT2_CHIB_RNIADDRHIGH_REQCOMPLETED_MSK (((_ULL(1) << VT2_CHIB_RNIADDRHIGH_REQCOMPLETED_WID) - _ULL(1)) << VT2_CHIB_RNIADDRHIGH_REQCOMPLETED_POS)

#define VT2_CHIB_RNIDATALOW_OFFSET _ULL(0x6)

#define VT2_CHIB_RNIDATALOW_POS 0
#define VT2_CHIB_RNIDATALOW_WID 32
#define VT2_CHIB_RNIDATALOW_MSK (((_ULL(1) << VT2_CHIB_RNIDATALOW_WID) - _ULL(1)) << VT2_CHIB_RNIDATALOW_POS)

#define VT2_CHIB_RNIDATALOW_DATALOW_POS 0
#define VT2_CHIB_RNIDATALOW_DATALOW_WID 32
#define VT2_CHIB_RNIDATALOW_DATALOW_MSK (((_ULL(1) << VT2_CHIB_RNIDATALOW_DATALOW_WID) - _ULL(1)) << VT2_CHIB_RNIDATALOW_DATALOW_POS)

#define VT2_CHIB_RNIDATAHIGH_OFFSET _ULL(0x7)

#define VT2_CHIB_RNIDATAHIGH_POS 0
#define VT2_CHIB_RNIDATAHIGH_WID 32
#define VT2_CHIB_RNIDATAHIGH_MSK (((_ULL(1) << VT2_CHIB_RNIDATAHIGH_WID) - _ULL(1)) << VT2_CHIB_RNIDATAHIGH_POS)

#define VT2_CHIB_RNIDATAHIGH_DATAHIGH_POS 0
#define VT2_CHIB_RNIDATAHIGH_DATAHIGH_WID 32
#define VT2_CHIB_RNIDATAHIGH_DATAHIGH_MSK (((_ULL(1) << VT2_CHIB_RNIDATAHIGH_DATAHIGH_WID) - _ULL(1)) << VT2_CHIB_RNIDATAHIGH_DATAHIGH_POS)
#endif /* VT2_CHIB_MMR_H */
