/* This file is auto-generated. Do not hand edit this file. */

#ifndef VT2_CPU_CSR_H
#define VT2_CPU_CSR_H

#ifndef _ULL

#ifdef __ASSEMBLER__
#define _AC(X,Y) X
#else
#define __AC(X,Y) (X##Y)
#define _AC(X,Y) __AC(X,Y)
#endif

#define _ULL(x)  (_AC(x, ULL))
#endif


#define VT2_CPU_CPURSTCTL_OFFSET _ULL(0xc00)

#define VT2_CPU_CPURSTCTL_POS 0
#define VT2_CPU_CPURSTCTL_WID 9
#define VT2_CPU_CPURSTCTL_MSK (((_ULL(1) << VT2_CPU_CPURSTCTL_WID) - _ULL(1)) << VT2_CPU_CPURSTCTL_POS)

#define VT2_CPU_CPURSTCTL_HARDRESET_POS 0
#define VT2_CPU_CPURSTCTL_HARDRESET_WID 1
#define VT2_CPU_CPURSTCTL_HARDRESET_MSK (((_ULL(1) << VT2_CPU_CPURSTCTL_HARDRESET_WID) - _ULL(1)) << VT2_CPU_CPURSTCTL_HARDRESET_POS)
#define VT2_CPU_CPURSTCTL_HARDRESETDONE_POS 1
#define VT2_CPU_CPURSTCTL_HARDRESETDONE_WID 1
#define VT2_CPU_CPURSTCTL_HARDRESETDONE_MSK (((_ULL(1) << VT2_CPU_CPURSTCTL_HARDRESETDONE_WID) - _ULL(1)) << VT2_CPU_CPURSTCTL_HARDRESETDONE_POS)
#define VT2_CPU_CPURSTCTL_SOFTRESETREQUEST_POS 2
#define VT2_CPU_CPURSTCTL_SOFTRESETREQUEST_WID 1
#define VT2_CPU_CPURSTCTL_SOFTRESETREQUEST_MSK (((_ULL(1) << VT2_CPU_CPURSTCTL_SOFTRESETREQUEST_WID) - _ULL(1)) << VT2_CPU_CPURSTCTL_SOFTRESETREQUEST_POS)
#define VT2_CPU_CPURSTCTL_SOFTRESETDONE_POS 3
#define VT2_CPU_CPURSTCTL_SOFTRESETDONE_WID 1
#define VT2_CPU_CPURSTCTL_SOFTRESETDONE_MSK (((_ULL(1) << VT2_CPU_CPURSTCTL_SOFTRESETDONE_WID) - _ULL(1)) << VT2_CPU_CPURSTCTL_SOFTRESETDONE_POS)
#define VT2_CPU_CPURSTCTL_STARTRAMINIT_POS 4
#define VT2_CPU_CPURSTCTL_STARTRAMINIT_WID 1
#define VT2_CPU_CPURSTCTL_STARTRAMINIT_MSK (((_ULL(1) << VT2_CPU_CPURSTCTL_STARTRAMINIT_WID) - _ULL(1)) << VT2_CPU_CPURSTCTL_STARTRAMINIT_POS)
#define VT2_CPU_CPURSTCTL_RAMINTDONE_POS 5
#define VT2_CPU_CPURSTCTL_RAMINTDONE_WID 1
#define VT2_CPU_CPURSTCTL_RAMINTDONE_MSK (((_ULL(1) << VT2_CPU_CPURSTCTL_RAMINTDONE_WID) - _ULL(1)) << VT2_CPU_CPURSTCTL_RAMINTDONE_POS)
#define VT2_CPU_CPURSTCTL_START_POS 6
#define VT2_CPU_CPURSTCTL_START_WID 1
#define VT2_CPU_CPURSTCTL_START_MSK (((_ULL(1) << VT2_CPU_CPURSTCTL_START_WID) - _ULL(1)) << VT2_CPU_CPURSTCTL_START_POS)
#define VT2_CPU_CPURSTCTL_REGBUSENABLE_POS 7
#define VT2_CPU_CPURSTCTL_REGBUSENABLE_WID 1
#define VT2_CPU_CPURSTCTL_REGBUSENABLE_MSK (((_ULL(1) << VT2_CPU_CPURSTCTL_REGBUSENABLE_WID) - _ULL(1)) << VT2_CPU_CPURSTCTL_REGBUSENABLE_POS)
#define VT2_CPU_CPURSTCTL_NMIENABLE_POS 8
#define VT2_CPU_CPURSTCTL_NMIENABLE_WID 1
#define VT2_CPU_CPURSTCTL_NMIENABLE_MSK (((_ULL(1) << VT2_CPU_CPURSTCTL_NMIENABLE_WID) - _ULL(1)) << VT2_CPU_CPURSTCTL_NMIENABLE_POS)

#define VT2_CPU_CPUCLKCTL_OFFSET _ULL(0xc01)

#define VT2_CPU_CPUCLKCTL_POS 0
#define VT2_CPU_CPUCLKCTL_WID 16
#define VT2_CPU_CPUCLKCTL_MSK (((_ULL(1) << VT2_CPU_CPUCLKCTL_WID) - _ULL(1)) << VT2_CPU_CPUCLKCTL_POS)

#define VT2_CPU_CPUCLKCTL_CLKGATEREN_POS 0
#define VT2_CPU_CPUCLKCTL_CLKGATEREN_WID 1
#define VT2_CPU_CPUCLKCTL_CLKGATEREN_MSK (((_ULL(1) << VT2_CPU_CPUCLKCTL_CLKGATEREN_WID) - _ULL(1)) << VT2_CPU_CPUCLKCTL_CLKGATEREN_POS)
#define VT2_CPU_CPUCLKCTL_CLKGATEROVRD_POS 1
#define VT2_CPU_CPUCLKCTL_CLKGATEROVRD_WID 1
#define VT2_CPU_CPUCLKCTL_CLKGATEROVRD_MSK (((_ULL(1) << VT2_CPU_CPUCLKCTL_CLKGATEROVRD_WID) - _ULL(1)) << VT2_CPU_CPUCLKCTL_CLKGATEROVRD_POS)
#define VT2_CPU_CPUCLKCTL_CLKFREQDIV_POS 2
#define VT2_CPU_CPUCLKCTL_CLKFREQDIV_WID 5
#define VT2_CPU_CPUCLKCTL_CLKFREQDIV_MSK (((_ULL(1) << VT2_CPU_CPUCLKCTL_CLKFREQDIV_WID) - _ULL(1)) << VT2_CPU_CPUCLKCTL_CLKFREQDIV_POS)
#define VT2_CPU_CPUCLKCTL_CLKFREQRAMPUPSTEPDLY_POS 7
#define VT2_CPU_CPUCLKCTL_CLKFREQRAMPUPSTEPDLY_WID 4
#define VT2_CPU_CPUCLKCTL_CLKFREQRAMPUPSTEPDLY_MSK (((_ULL(1) << VT2_CPU_CPUCLKCTL_CLKFREQRAMPUPSTEPDLY_WID) - _ULL(1)) << VT2_CPU_CPUCLKCTL_CLKFREQRAMPUPSTEPDLY_POS)
#define VT2_CPU_CPUCLKCTL_CLKFREQRAMPDNSTEPDLY_POS 11
#define VT2_CPU_CPUCLKCTL_CLKFREQRAMPDNSTEPDLY_WID 4
#define VT2_CPU_CPUCLKCTL_CLKFREQRAMPDNSTEPDLY_MSK (((_ULL(1) << VT2_CPU_CPUCLKCTL_CLKFREQRAMPDNSTEPDLY_WID) - _ULL(1)) << VT2_CPU_CPUCLKCTL_CLKFREQRAMPDNSTEPDLY_POS)
#define VT2_CPU_CPUCLKCTL_QUIESCEDOVRD_POS 15
#define VT2_CPU_CPUCLKCTL_QUIESCEDOVRD_WID 1
#define VT2_CPU_CPUCLKCTL_QUIESCEDOVRD_MSK (((_ULL(1) << VT2_CPU_CPUCLKCTL_QUIESCEDOVRD_WID) - _ULL(1)) << VT2_CPU_CPUCLKCTL_QUIESCEDOVRD_POS)

#define VT2_CPU_CPUCLKSTAT_OFFSET _ULL(0xc02)

#define VT2_CPU_CPUCLKSTAT_POS 0
#define VT2_CPU_CPUCLKSTAT_WID 5
#define VT2_CPU_CPUCLKSTAT_MSK (((_ULL(1) << VT2_CPU_CPUCLKSTAT_WID) - _ULL(1)) << VT2_CPU_CPUCLKSTAT_POS)

#define VT2_CPU_CPUCLKSTAT_CPUQUIESCED_POS 0
#define VT2_CPU_CPUCLKSTAT_CPUQUIESCED_WID 1
#define VT2_CPU_CPUCLKSTAT_CPUQUIESCED_MSK (((_ULL(1) << VT2_CPU_CPUCLKSTAT_CPUQUIESCED_WID) - _ULL(1)) << VT2_CPU_CPUCLKSTAT_CPUQUIESCED_POS)
#define VT2_CPU_CPUCLKSTAT_ICRQUIESCED_POS 1
#define VT2_CPU_CPUCLKSTAT_ICRQUIESCED_WID 1
#define VT2_CPU_CPUCLKSTAT_ICRQUIESCED_MSK (((_ULL(1) << VT2_CPU_CPUCLKSTAT_ICRQUIESCED_WID) - _ULL(1)) << VT2_CPU_CPUCLKSTAT_ICRQUIESCED_POS)
#define VT2_CPU_CPUCLKSTAT_WAKEEVENT_POS 2
#define VT2_CPU_CPUCLKSTAT_WAKEEVENT_WID 1
#define VT2_CPU_CPUCLKSTAT_WAKEEVENT_MSK (((_ULL(1) << VT2_CPU_CPUCLKSTAT_WAKEEVENT_WID) - _ULL(1)) << VT2_CPU_CPUCLKSTAT_WAKEEVENT_POS)
#define VT2_CPU_CPUCLKSTAT_RUNEVENT_POS 3
#define VT2_CPU_CPUCLKSTAT_RUNEVENT_WID 1
#define VT2_CPU_CPUCLKSTAT_RUNEVENT_MSK (((_ULL(1) << VT2_CPU_CPUCLKSTAT_RUNEVENT_WID) - _ULL(1)) << VT2_CPU_CPUCLKSTAT_RUNEVENT_POS)
#define VT2_CPU_CPUCLKSTAT_CPUCLKSTATECGE_POS 4
#define VT2_CPU_CPUCLKSTAT_CPUCLKSTATECGE_WID 1
#define VT2_CPU_CPUCLKSTAT_CPUCLKSTATECGE_MSK (((_ULL(1) << VT2_CPU_CPUCLKSTAT_CPUCLKSTATECGE_WID) - _ULL(1)) << VT2_CPU_CPUCLKSTAT_CPUCLKSTATECGE_POS)

#define VT2_CPU_CPUPWRCFG_OFFSET _ULL(0xc03)

#define VT2_CPU_CPUPWRCFG_POS 0
#define VT2_CPU_CPUPWRCFG_WID 1
#define VT2_CPU_CPUPWRCFG_MSK (((_ULL(1) << VT2_CPU_CPUPWRCFG_WID) - _ULL(1)) << VT2_CPU_CPUPWRCFG_POS)

#define VT2_CPU_CPUPWRCFG_LSDIS_POS 0
#define VT2_CPU_CPUPWRCFG_LSDIS_WID 1
#define VT2_CPU_CPUPWRCFG_LSDIS_MSK (((_ULL(1) << VT2_CPU_CPUPWRCFG_LSDIS_WID) - _ULL(1)) << VT2_CPU_CPUPWRCFG_LSDIS_POS)

#define VT2_CPU_PRIDROOPCTL_OFFSET _ULL(0xc04)

#define VT2_CPU_PRIDROOPCTL_POS 0
#define VT2_CPU_PRIDROOPCTL_WID 14
#define VT2_CPU_PRIDROOPCTL_MSK (((_ULL(1) << VT2_CPU_PRIDROOPCTL_WID) - _ULL(1)) << VT2_CPU_PRIDROOPCTL_POS)

#define VT2_CPU_PRIDROOPCTL_ENABLE_POS 0
#define VT2_CPU_PRIDROOPCTL_ENABLE_WID 1
#define VT2_CPU_PRIDROOPCTL_ENABLE_MSK (((_ULL(1) << VT2_CPU_PRIDROOPCTL_ENABLE_WID) - _ULL(1)) << VT2_CPU_PRIDROOPCTL_ENABLE_POS)
#define VT2_CPU_PRIDROOPCTL_DROOPEVENTENABLE_POS 1
#define VT2_CPU_PRIDROOPCTL_DROOPEVENTENABLE_WID 1
#define VT2_CPU_PRIDROOPCTL_DROOPEVENTENABLE_MSK (((_ULL(1) << VT2_CPU_PRIDROOPCTL_DROOPEVENTENABLE_WID) - _ULL(1)) << VT2_CPU_PRIDROOPCTL_DROOPEVENTENABLE_POS)
#define VT2_CPU_PRIDROOPCTL_CLOCKCONTROLENABLE_POS 2
#define VT2_CPU_PRIDROOPCTL_CLOCKCONTROLENABLE_WID 1
#define VT2_CPU_PRIDROOPCTL_CLOCKCONTROLENABLE_MSK (((_ULL(1) << VT2_CPU_PRIDROOPCTL_CLOCKCONTROLENABLE_WID) - _ULL(1)) << VT2_CPU_PRIDROOPCTL_CLOCKCONTROLENABLE_POS)
#define VT2_CPU_PRIDROOPCTL_THRESHOLD_POS 3
#define VT2_CPU_PRIDROOPCTL_THRESHOLD_WID 8
#define VT2_CPU_PRIDROOPCTL_THRESHOLD_MSK (((_ULL(1) << VT2_CPU_PRIDROOPCTL_THRESHOLD_WID) - _ULL(1)) << VT2_CPU_PRIDROOPCTL_THRESHOLD_POS)
#define VT2_CPU_PRIDROOPCTL_FILTERBW_POS 11
#define VT2_CPU_PRIDROOPCTL_FILTERBW_WID 3
#define VT2_CPU_PRIDROOPCTL_FILTERBW_MSK (((_ULL(1) << VT2_CPU_PRIDROOPCTL_FILTERBW_WID) - _ULL(1)) << VT2_CPU_PRIDROOPCTL_FILTERBW_POS)

#define VT2_CPU_SECDROOPCTL_OFFSET _ULL(0xc05)

#define VT2_CPU_SECDROOPCTL_POS 0
#define VT2_CPU_SECDROOPCTL_WID 14
#define VT2_CPU_SECDROOPCTL_MSK (((_ULL(1) << VT2_CPU_SECDROOPCTL_WID) - _ULL(1)) << VT2_CPU_SECDROOPCTL_POS)

#define VT2_CPU_SECDROOPCTL_ENABLE_POS 0
#define VT2_CPU_SECDROOPCTL_ENABLE_WID 1
#define VT2_CPU_SECDROOPCTL_ENABLE_MSK (((_ULL(1) << VT2_CPU_SECDROOPCTL_ENABLE_WID) - _ULL(1)) << VT2_CPU_SECDROOPCTL_ENABLE_POS)
#define VT2_CPU_SECDROOPCTL_DROOPEVENTENABLE_POS 1
#define VT2_CPU_SECDROOPCTL_DROOPEVENTENABLE_WID 1
#define VT2_CPU_SECDROOPCTL_DROOPEVENTENABLE_MSK (((_ULL(1) << VT2_CPU_SECDROOPCTL_DROOPEVENTENABLE_WID) - _ULL(1)) << VT2_CPU_SECDROOPCTL_DROOPEVENTENABLE_POS)
#define VT2_CPU_SECDROOPCTL_CLOCKCONTROLENABLE_POS 2
#define VT2_CPU_SECDROOPCTL_CLOCKCONTROLENABLE_WID 1
#define VT2_CPU_SECDROOPCTL_CLOCKCONTROLENABLE_MSK (((_ULL(1) << VT2_CPU_SECDROOPCTL_CLOCKCONTROLENABLE_WID) - _ULL(1)) << VT2_CPU_SECDROOPCTL_CLOCKCONTROLENABLE_POS)
#define VT2_CPU_SECDROOPCTL_THRESHOLD_POS 3
#define VT2_CPU_SECDROOPCTL_THRESHOLD_WID 8
#define VT2_CPU_SECDROOPCTL_THRESHOLD_MSK (((_ULL(1) << VT2_CPU_SECDROOPCTL_THRESHOLD_WID) - _ULL(1)) << VT2_CPU_SECDROOPCTL_THRESHOLD_POS)
#define VT2_CPU_SECDROOPCTL_FILTERBW_POS 11
#define VT2_CPU_SECDROOPCTL_FILTERBW_WID 3
#define VT2_CPU_SECDROOPCTL_FILTERBW_MSK (((_ULL(1) << VT2_CPU_SECDROOPCTL_FILTERBW_WID) - _ULL(1)) << VT2_CPU_SECDROOPCTL_FILTERBW_POS)

#define VT2_CPU_PRIDROOPSTAT_OFFSET _ULL(0xc06)

#define VT2_CPU_PRIDROOPSTAT_POS 0
#define VT2_CPU_PRIDROOPSTAT_WID 1
#define VT2_CPU_PRIDROOPSTAT_MSK (((_ULL(1) << VT2_CPU_PRIDROOPSTAT_WID) - _ULL(1)) << VT2_CPU_PRIDROOPSTAT_POS)

#define VT2_CPU_PRIDROOPSTAT_DROOPOUT_POS 0
#define VT2_CPU_PRIDROOPSTAT_DROOPOUT_WID 1
#define VT2_CPU_PRIDROOPSTAT_DROOPOUT_MSK (((_ULL(1) << VT2_CPU_PRIDROOPSTAT_DROOPOUT_WID) - _ULL(1)) << VT2_CPU_PRIDROOPSTAT_DROOPOUT_POS)

#define VT2_CPU_SECDROOPSTAT_OFFSET _ULL(0xc07)

#define VT2_CPU_SECDROOPSTAT_POS 0
#define VT2_CPU_SECDROOPSTAT_WID 1
#define VT2_CPU_SECDROOPSTAT_MSK (((_ULL(1) << VT2_CPU_SECDROOPSTAT_WID) - _ULL(1)) << VT2_CPU_SECDROOPSTAT_POS)

#define VT2_CPU_SECDROOPSTAT_DROOPOUT_POS 0
#define VT2_CPU_SECDROOPSTAT_DROOPOUT_WID 1
#define VT2_CPU_SECDROOPSTAT_DROOPOUT_MSK (((_ULL(1) << VT2_CPU_SECDROOPSTAT_DROOPOUT_WID) - _ULL(1)) << VT2_CPU_SECDROOPSTAT_DROOPOUT_POS)

#define VT2_CPU_DROOPRECCTL_OFFSET _ULL(0xc08)

#define VT2_CPU_DROOPRECCTL_POS 0
#define VT2_CPU_DROOPRECCTL_WID 16
#define VT2_CPU_DROOPRECCTL_MSK (((_ULL(1) << VT2_CPU_DROOPRECCTL_WID) - _ULL(1)) << VT2_CPU_DROOPRECCTL_POS)

#define VT2_CPU_DROOPRECCTL_RECOVERYDELAY_POS 0
#define VT2_CPU_DROOPRECCTL_RECOVERYDELAY_WID 16
#define VT2_CPU_DROOPRECCTL_RECOVERYDELAY_MSK (((_ULL(1) << VT2_CPU_DROOPRECCTL_RECOVERYDELAY_WID) - _ULL(1)) << VT2_CPU_DROOPRECCTL_RECOVERYDELAY_POS)

#define VT2_CPU_DROOPRECSTAT_OFFSET _ULL(0xc09)

#define VT2_CPU_DROOPRECSTAT_POS 0
#define VT2_CPU_DROOPRECSTAT_WID 16
#define VT2_CPU_DROOPRECSTAT_MSK (((_ULL(1) << VT2_CPU_DROOPRECSTAT_WID) - _ULL(1)) << VT2_CPU_DROOPRECSTAT_POS)

#define VT2_CPU_DROOPRECSTAT_RECOVERYCTR_POS 0
#define VT2_CPU_DROOPRECSTAT_RECOVERYCTR_WID 16
#define VT2_CPU_DROOPRECSTAT_RECOVERYCTR_MSK (((_ULL(1) << VT2_CPU_DROOPRECSTAT_RECOVERYCTR_WID) - _ULL(1)) << VT2_CPU_DROOPRECSTAT_RECOVERYCTR_POS)

#define VT2_CPU_PRIDROOPEVENTCTR_OFFSET _ULL(0xc0a)

#define VT2_CPU_PRIDROOPEVENTCTR_POS 0
#define VT2_CPU_PRIDROOPEVENTCTR_WID 32
#define VT2_CPU_PRIDROOPEVENTCTR_MSK (((_ULL(1) << VT2_CPU_PRIDROOPEVENTCTR_WID) - _ULL(1)) << VT2_CPU_PRIDROOPEVENTCTR_POS)

#define VT2_CPU_PRIDROOPEVENTCTR_EVENTS_POS 0
#define VT2_CPU_PRIDROOPEVENTCTR_EVENTS_WID 20
#define VT2_CPU_PRIDROOPEVENTCTR_EVENTS_MSK (((_ULL(1) << VT2_CPU_PRIDROOPEVENTCTR_EVENTS_WID) - _ULL(1)) << VT2_CPU_PRIDROOPEVENTCTR_EVENTS_POS)
#define VT2_CPU_PRIDROOPEVENTCTR_OVERFLOW_POS 31
#define VT2_CPU_PRIDROOPEVENTCTR_OVERFLOW_WID 1
#define VT2_CPU_PRIDROOPEVENTCTR_OVERFLOW_MSK (((_ULL(1) << VT2_CPU_PRIDROOPEVENTCTR_OVERFLOW_WID) - _ULL(1)) << VT2_CPU_PRIDROOPEVENTCTR_OVERFLOW_POS)

#define VT2_CPU_SECDROOPEVENTCTR_OFFSET _ULL(0xc0b)

#define VT2_CPU_SECDROOPEVENTCTR_POS 0
#define VT2_CPU_SECDROOPEVENTCTR_WID 32
#define VT2_CPU_SECDROOPEVENTCTR_MSK (((_ULL(1) << VT2_CPU_SECDROOPEVENTCTR_WID) - _ULL(1)) << VT2_CPU_SECDROOPEVENTCTR_POS)

#define VT2_CPU_SECDROOPEVENTCTR_EVENTS_POS 0
#define VT2_CPU_SECDROOPEVENTCTR_EVENTS_WID 20
#define VT2_CPU_SECDROOPEVENTCTR_EVENTS_MSK (((_ULL(1) << VT2_CPU_SECDROOPEVENTCTR_EVENTS_WID) - _ULL(1)) << VT2_CPU_SECDROOPEVENTCTR_EVENTS_POS)
#define VT2_CPU_SECDROOPEVENTCTR_OVERFLOW_POS 31
#define VT2_CPU_SECDROOPEVENTCTR_OVERFLOW_WID 1
#define VT2_CPU_SECDROOPEVENTCTR_OVERFLOW_MSK (((_ULL(1) << VT2_CPU_SECDROOPEVENTCTR_OVERFLOW_WID) - _ULL(1)) << VT2_CPU_SECDROOPEVENTCTR_OVERFLOW_POS)

#define VT2_CPU_PRIDROOPCYCLECTR_OFFSET _ULL(0xc0c)

#define VT2_CPU_PRIDROOPCYCLECTR_POS 0
#define VT2_CPU_PRIDROOPCYCLECTR_WID 32
#define VT2_CPU_PRIDROOPCYCLECTR_MSK (((_ULL(1) << VT2_CPU_PRIDROOPCYCLECTR_WID) - _ULL(1)) << VT2_CPU_PRIDROOPCYCLECTR_POS)

#define VT2_CPU_PRIDROOPCYCLECTR_CYCLES_POS 0
#define VT2_CPU_PRIDROOPCYCLECTR_CYCLES_WID 30
#define VT2_CPU_PRIDROOPCYCLECTR_CYCLES_MSK (((_ULL(1) << VT2_CPU_PRIDROOPCYCLECTR_CYCLES_WID) - _ULL(1)) << VT2_CPU_PRIDROOPCYCLECTR_CYCLES_POS)
#define VT2_CPU_PRIDROOPCYCLECTR_OVERFLOW_POS 31
#define VT2_CPU_PRIDROOPCYCLECTR_OVERFLOW_WID 1
#define VT2_CPU_PRIDROOPCYCLECTR_OVERFLOW_MSK (((_ULL(1) << VT2_CPU_PRIDROOPCYCLECTR_OVERFLOW_WID) - _ULL(1)) << VT2_CPU_PRIDROOPCYCLECTR_OVERFLOW_POS)

#define VT2_CPU_SECDROOPCYCLECTR_OFFSET _ULL(0xc0d)

#define VT2_CPU_SECDROOPCYCLECTR_POS 0
#define VT2_CPU_SECDROOPCYCLECTR_WID 32
#define VT2_CPU_SECDROOPCYCLECTR_MSK (((_ULL(1) << VT2_CPU_SECDROOPCYCLECTR_WID) - _ULL(1)) << VT2_CPU_SECDROOPCYCLECTR_POS)

#define VT2_CPU_SECDROOPCYCLECTR_CYCLES_POS 0
#define VT2_CPU_SECDROOPCYCLECTR_CYCLES_WID 30
#define VT2_CPU_SECDROOPCYCLECTR_CYCLES_MSK (((_ULL(1) << VT2_CPU_SECDROOPCYCLECTR_CYCLES_WID) - _ULL(1)) << VT2_CPU_SECDROOPCYCLECTR_CYCLES_POS)
#define VT2_CPU_SECDROOPCYCLECTR_OVERFLOW_POS 31
#define VT2_CPU_SECDROOPCYCLECTR_OVERFLOW_WID 1
#define VT2_CPU_SECDROOPCYCLECTR_OVERFLOW_MSK (((_ULL(1) << VT2_CPU_SECDROOPCYCLECTR_OVERFLOW_WID) - _ULL(1)) << VT2_CPU_SECDROOPCYCLECTR_OVERFLOW_POS)

#define VT2_CPU_DROOPMITEVENTCTR_OFFSET _ULL(0xc0e)

#define VT2_CPU_DROOPMITEVENTCTR_POS 0
#define VT2_CPU_DROOPMITEVENTCTR_WID 32
#define VT2_CPU_DROOPMITEVENTCTR_MSK (((_ULL(1) << VT2_CPU_DROOPMITEVENTCTR_WID) - _ULL(1)) << VT2_CPU_DROOPMITEVENTCTR_POS)

#define VT2_CPU_DROOPMITEVENTCTR_EVENTS_POS 0
#define VT2_CPU_DROOPMITEVENTCTR_EVENTS_WID 20
#define VT2_CPU_DROOPMITEVENTCTR_EVENTS_MSK (((_ULL(1) << VT2_CPU_DROOPMITEVENTCTR_EVENTS_WID) - _ULL(1)) << VT2_CPU_DROOPMITEVENTCTR_EVENTS_POS)
#define VT2_CPU_DROOPMITEVENTCTR_OVERFLOW_POS 31
#define VT2_CPU_DROOPMITEVENTCTR_OVERFLOW_WID 1
#define VT2_CPU_DROOPMITEVENTCTR_OVERFLOW_MSK (((_ULL(1) << VT2_CPU_DROOPMITEVENTCTR_OVERFLOW_WID) - _ULL(1)) << VT2_CPU_DROOPMITEVENTCTR_OVERFLOW_POS)

#define VT2_CPU_DROOPMITCYCLECTR_OFFSET _ULL(0xc0f)

#define VT2_CPU_DROOPMITCYCLECTR_POS 0
#define VT2_CPU_DROOPMITCYCLECTR_WID 32
#define VT2_CPU_DROOPMITCYCLECTR_MSK (((_ULL(1) << VT2_CPU_DROOPMITCYCLECTR_WID) - _ULL(1)) << VT2_CPU_DROOPMITCYCLECTR_POS)

#define VT2_CPU_DROOPMITCYCLECTR_CYCLES_POS 0
#define VT2_CPU_DROOPMITCYCLECTR_CYCLES_WID 30
#define VT2_CPU_DROOPMITCYCLECTR_CYCLES_MSK (((_ULL(1) << VT2_CPU_DROOPMITCYCLECTR_CYCLES_WID) - _ULL(1)) << VT2_CPU_DROOPMITCYCLECTR_CYCLES_POS)
#define VT2_CPU_DROOPMITCYCLECTR_OVERFLOW_POS 31
#define VT2_CPU_DROOPMITCYCLECTR_OVERFLOW_WID 1
#define VT2_CPU_DROOPMITCYCLECTR_OVERFLOW_MSK (((_ULL(1) << VT2_CPU_DROOPMITCYCLECTR_OVERFLOW_WID) - _ULL(1)) << VT2_CPU_DROOPMITCYCLECTR_OVERFLOW_POS)
#endif /* VT2_CPU_CSR_H */
