/* This file is auto-generated. Do not hand edit this file. */

#ifndef VT2_LWIC_MMR_H
#define VT2_LWIC_MMR_H

#ifndef _ULL

#ifdef __ASSEMBLER__
#define _AC(X,Y) X
#else
#define __AC(X,Y) (X##Y)
#define _AC(X,Y) __AC(X,Y)
#endif

#define _ULL(x)  (_AC(x, ULL))
#endif


#define VT2_LWIC_MMODETIMECMP0_OFFSET _ULL(0x0)

#define VT2_LWIC_MMODETIMECMP0_POS 0
#define VT2_LWIC_MMODETIMECMP0_WID 64
#define VT2_LWIC_MMODETIMECMP0_MSK (((_ULL(1) << VT2_LWIC_MMODETIMECMP0_WID) - _ULL(1)) << VT2_LWIC_MMODETIMECMP0_POS)

#define VT2_LWIC_MMODETIMECMP0_COMPARE_POS 0
#define VT2_LWIC_MMODETIMECMP0_COMPARE_WID 64
#define VT2_LWIC_MMODETIMECMP0_COMPARE_MSK (((_ULL(1) << VT2_LWIC_MMODETIMECMP0_COMPARE_WID) - _ULL(1)) << VT2_LWIC_MMODETIMECMP0_COMPARE_POS)

#define VT2_LWIC_MMODETIMECMP1_OFFSET _ULL(0x1)

#define VT2_LWIC_MMODETIMECMP1_POS 0
#define VT2_LWIC_MMODETIMECMP1_WID 64
#define VT2_LWIC_MMODETIMECMP1_MSK (((_ULL(1) << VT2_LWIC_MMODETIMECMP1_WID) - _ULL(1)) << VT2_LWIC_MMODETIMECMP1_POS)

#define VT2_LWIC_MMODETIMECMP1_COMPARE_POS 0
#define VT2_LWIC_MMODETIMECMP1_COMPARE_WID 64
#define VT2_LWIC_MMODETIMECMP1_COMPARE_MSK (((_ULL(1) << VT2_LWIC_MMODETIMECMP1_COMPARE_WID) - _ULL(1)) << VT2_LWIC_MMODETIMECMP1_COMPARE_POS)

#define VT2_LWIC_MMODETIMECMP2_OFFSET _ULL(0x2)

#define VT2_LWIC_MMODETIMECMP2_POS 0
#define VT2_LWIC_MMODETIMECMP2_WID 64
#define VT2_LWIC_MMODETIMECMP2_MSK (((_ULL(1) << VT2_LWIC_MMODETIMECMP2_WID) - _ULL(1)) << VT2_LWIC_MMODETIMECMP2_POS)

#define VT2_LWIC_MMODETIMECMP2_COMPARE_POS 0
#define VT2_LWIC_MMODETIMECMP2_COMPARE_WID 64
#define VT2_LWIC_MMODETIMECMP2_COMPARE_MSK (((_ULL(1) << VT2_LWIC_MMODETIMECMP2_COMPARE_WID) - _ULL(1)) << VT2_LWIC_MMODETIMECMP2_COMPARE_POS)

#define VT2_LWIC_MMODETIMECMP3_OFFSET _ULL(0x3)

#define VT2_LWIC_MMODETIMECMP3_POS 0
#define VT2_LWIC_MMODETIMECMP3_WID 64
#define VT2_LWIC_MMODETIMECMP3_MSK (((_ULL(1) << VT2_LWIC_MMODETIMECMP3_WID) - _ULL(1)) << VT2_LWIC_MMODETIMECMP3_POS)

#define VT2_LWIC_MMODETIMECMP3_COMPARE_POS 0
#define VT2_LWIC_MMODETIMECMP3_COMPARE_WID 64
#define VT2_LWIC_MMODETIMECMP3_COMPARE_MSK (((_ULL(1) << VT2_LWIC_MMODETIMECMP3_COMPARE_WID) - _ULL(1)) << VT2_LWIC_MMODETIMECMP3_COMPARE_POS)

#define VT2_LWIC_MMODETIMECMP4_OFFSET _ULL(0x4)

#define VT2_LWIC_MMODETIMECMP4_POS 0
#define VT2_LWIC_MMODETIMECMP4_WID 64
#define VT2_LWIC_MMODETIMECMP4_MSK (((_ULL(1) << VT2_LWIC_MMODETIMECMP4_WID) - _ULL(1)) << VT2_LWIC_MMODETIMECMP4_POS)

#define VT2_LWIC_MMODETIMECMP4_COMPARE_POS 0
#define VT2_LWIC_MMODETIMECMP4_COMPARE_WID 64
#define VT2_LWIC_MMODETIMECMP4_COMPARE_MSK (((_ULL(1) << VT2_LWIC_MMODETIMECMP4_COMPARE_WID) - _ULL(1)) << VT2_LWIC_MMODETIMECMP4_COMPARE_POS)

#define VT2_LWIC_MMODETIMECMP5_OFFSET _ULL(0x5)

#define VT2_LWIC_MMODETIMECMP5_POS 0
#define VT2_LWIC_MMODETIMECMP5_WID 64
#define VT2_LWIC_MMODETIMECMP5_MSK (((_ULL(1) << VT2_LWIC_MMODETIMECMP5_WID) - _ULL(1)) << VT2_LWIC_MMODETIMECMP5_POS)

#define VT2_LWIC_MMODETIMECMP5_COMPARE_POS 0
#define VT2_LWIC_MMODETIMECMP5_COMPARE_WID 64
#define VT2_LWIC_MMODETIMECMP5_COMPARE_MSK (((_ULL(1) << VT2_LWIC_MMODETIMECMP5_COMPARE_WID) - _ULL(1)) << VT2_LWIC_MMODETIMECMP5_COMPARE_POS)

#define VT2_LWIC_MMODETIMECMP6_OFFSET _ULL(0x6)

#define VT2_LWIC_MMODETIMECMP6_POS 0
#define VT2_LWIC_MMODETIMECMP6_WID 64
#define VT2_LWIC_MMODETIMECMP6_MSK (((_ULL(1) << VT2_LWIC_MMODETIMECMP6_WID) - _ULL(1)) << VT2_LWIC_MMODETIMECMP6_POS)

#define VT2_LWIC_MMODETIMECMP6_COMPARE_POS 0
#define VT2_LWIC_MMODETIMECMP6_COMPARE_WID 64
#define VT2_LWIC_MMODETIMECMP6_COMPARE_MSK (((_ULL(1) << VT2_LWIC_MMODETIMECMP6_COMPARE_WID) - _ULL(1)) << VT2_LWIC_MMODETIMECMP6_COMPARE_POS)

#define VT2_LWIC_MMODETIMECMP7_OFFSET _ULL(0x7)

#define VT2_LWIC_MMODETIMECMP7_POS 0
#define VT2_LWIC_MMODETIMECMP7_WID 64
#define VT2_LWIC_MMODETIMECMP7_MSK (((_ULL(1) << VT2_LWIC_MMODETIMECMP7_WID) - _ULL(1)) << VT2_LWIC_MMODETIMECMP7_POS)

#define VT2_LWIC_MMODETIMECMP7_COMPARE_POS 0
#define VT2_LWIC_MMODETIMECMP7_COMPARE_WID 64
#define VT2_LWIC_MMODETIMECMP7_COMPARE_MSK (((_ULL(1) << VT2_LWIC_MMODETIMECMP7_COMPARE_WID) - _ULL(1)) << VT2_LWIC_MMODETIMECMP7_COMPARE_POS)

#define VT2_LWIC_MMODETIMECMP8_OFFSET _ULL(0x8)

#define VT2_LWIC_MMODETIMECMP8_POS 0
#define VT2_LWIC_MMODETIMECMP8_WID 64
#define VT2_LWIC_MMODETIMECMP8_MSK (((_ULL(1) << VT2_LWIC_MMODETIMECMP8_WID) - _ULL(1)) << VT2_LWIC_MMODETIMECMP8_POS)

#define VT2_LWIC_MMODETIMECMP8_COMPARE_POS 0
#define VT2_LWIC_MMODETIMECMP8_COMPARE_WID 64
#define VT2_LWIC_MMODETIMECMP8_COMPARE_MSK (((_ULL(1) << VT2_LWIC_MMODETIMECMP8_COMPARE_WID) - _ULL(1)) << VT2_LWIC_MMODETIMECMP8_COMPARE_POS)

#define VT2_LWIC_MMODETIMECMP9_OFFSET _ULL(0x9)

#define VT2_LWIC_MMODETIMECMP9_POS 0
#define VT2_LWIC_MMODETIMECMP9_WID 64
#define VT2_LWIC_MMODETIMECMP9_MSK (((_ULL(1) << VT2_LWIC_MMODETIMECMP9_WID) - _ULL(1)) << VT2_LWIC_MMODETIMECMP9_POS)

#define VT2_LWIC_MMODETIMECMP9_COMPARE_POS 0
#define VT2_LWIC_MMODETIMECMP9_COMPARE_WID 64
#define VT2_LWIC_MMODETIMECMP9_COMPARE_MSK (((_ULL(1) << VT2_LWIC_MMODETIMECMP9_COMPARE_WID) - _ULL(1)) << VT2_LWIC_MMODETIMECMP9_COMPARE_POS)

#define VT2_LWIC_MMODETIMECMP10_OFFSET _ULL(0xa)

#define VT2_LWIC_MMODETIMECMP10_POS 0
#define VT2_LWIC_MMODETIMECMP10_WID 64
#define VT2_LWIC_MMODETIMECMP10_MSK (((_ULL(1) << VT2_LWIC_MMODETIMECMP10_WID) - _ULL(1)) << VT2_LWIC_MMODETIMECMP10_POS)

#define VT2_LWIC_MMODETIMECMP10_COMPARE_POS 0
#define VT2_LWIC_MMODETIMECMP10_COMPARE_WID 64
#define VT2_LWIC_MMODETIMECMP10_COMPARE_MSK (((_ULL(1) << VT2_LWIC_MMODETIMECMP10_COMPARE_WID) - _ULL(1)) << VT2_LWIC_MMODETIMECMP10_COMPARE_POS)

#define VT2_LWIC_MMODETIMECMP11_OFFSET _ULL(0xb)

#define VT2_LWIC_MMODETIMECMP11_POS 0
#define VT2_LWIC_MMODETIMECMP11_WID 64
#define VT2_LWIC_MMODETIMECMP11_MSK (((_ULL(1) << VT2_LWIC_MMODETIMECMP11_WID) - _ULL(1)) << VT2_LWIC_MMODETIMECMP11_POS)

#define VT2_LWIC_MMODETIMECMP11_COMPARE_POS 0
#define VT2_LWIC_MMODETIMECMP11_COMPARE_WID 64
#define VT2_LWIC_MMODETIMECMP11_COMPARE_MSK (((_ULL(1) << VT2_LWIC_MMODETIMECMP11_COMPARE_WID) - _ULL(1)) << VT2_LWIC_MMODETIMECMP11_COMPARE_POS)

#define VT2_LWIC_MMODETIMECMP12_OFFSET _ULL(0xc)

#define VT2_LWIC_MMODETIMECMP12_POS 0
#define VT2_LWIC_MMODETIMECMP12_WID 64
#define VT2_LWIC_MMODETIMECMP12_MSK (((_ULL(1) << VT2_LWIC_MMODETIMECMP12_WID) - _ULL(1)) << VT2_LWIC_MMODETIMECMP12_POS)

#define VT2_LWIC_MMODETIMECMP12_COMPARE_POS 0
#define VT2_LWIC_MMODETIMECMP12_COMPARE_WID 64
#define VT2_LWIC_MMODETIMECMP12_COMPARE_MSK (((_ULL(1) << VT2_LWIC_MMODETIMECMP12_COMPARE_WID) - _ULL(1)) << VT2_LWIC_MMODETIMECMP12_COMPARE_POS)

#define VT2_LWIC_MMODETIMECMP13_OFFSET _ULL(0xd)

#define VT2_LWIC_MMODETIMECMP13_POS 0
#define VT2_LWIC_MMODETIMECMP13_WID 64
#define VT2_LWIC_MMODETIMECMP13_MSK (((_ULL(1) << VT2_LWIC_MMODETIMECMP13_WID) - _ULL(1)) << VT2_LWIC_MMODETIMECMP13_POS)

#define VT2_LWIC_MMODETIMECMP13_COMPARE_POS 0
#define VT2_LWIC_MMODETIMECMP13_COMPARE_WID 64
#define VT2_LWIC_MMODETIMECMP13_COMPARE_MSK (((_ULL(1) << VT2_LWIC_MMODETIMECMP13_COMPARE_WID) - _ULL(1)) << VT2_LWIC_MMODETIMECMP13_COMPARE_POS)

#define VT2_LWIC_MMODETIMECMP14_OFFSET _ULL(0xe)

#define VT2_LWIC_MMODETIMECMP14_POS 0
#define VT2_LWIC_MMODETIMECMP14_WID 64
#define VT2_LWIC_MMODETIMECMP14_MSK (((_ULL(1) << VT2_LWIC_MMODETIMECMP14_WID) - _ULL(1)) << VT2_LWIC_MMODETIMECMP14_POS)

#define VT2_LWIC_MMODETIMECMP14_COMPARE_POS 0
#define VT2_LWIC_MMODETIMECMP14_COMPARE_WID 64
#define VT2_LWIC_MMODETIMECMP14_COMPARE_MSK (((_ULL(1) << VT2_LWIC_MMODETIMECMP14_COMPARE_WID) - _ULL(1)) << VT2_LWIC_MMODETIMECMP14_COMPARE_POS)

#define VT2_LWIC_MMODETIMECMP15_OFFSET _ULL(0xf)

#define VT2_LWIC_MMODETIMECMP15_POS 0
#define VT2_LWIC_MMODETIMECMP15_WID 64
#define VT2_LWIC_MMODETIMECMP15_MSK (((_ULL(1) << VT2_LWIC_MMODETIMECMP15_WID) - _ULL(1)) << VT2_LWIC_MMODETIMECMP15_POS)

#define VT2_LWIC_MMODETIMECMP15_COMPARE_POS 0
#define VT2_LWIC_MMODETIMECMP15_COMPARE_WID 64
#define VT2_LWIC_MMODETIMECMP15_COMPARE_MSK (((_ULL(1) << VT2_LWIC_MMODETIMECMP15_COMPARE_WID) - _ULL(1)) << VT2_LWIC_MMODETIMECMP15_COMPARE_POS)

#define VT2_LWIC_MMODETIMECMP16_OFFSET _ULL(0x10)

#define VT2_LWIC_MMODETIMECMP16_POS 0
#define VT2_LWIC_MMODETIMECMP16_WID 64
#define VT2_LWIC_MMODETIMECMP16_MSK (((_ULL(1) << VT2_LWIC_MMODETIMECMP16_WID) - _ULL(1)) << VT2_LWIC_MMODETIMECMP16_POS)

#define VT2_LWIC_MMODETIMECMP16_COMPARE_POS 0
#define VT2_LWIC_MMODETIMECMP16_COMPARE_WID 64
#define VT2_LWIC_MMODETIMECMP16_COMPARE_MSK (((_ULL(1) << VT2_LWIC_MMODETIMECMP16_COMPARE_WID) - _ULL(1)) << VT2_LWIC_MMODETIMECMP16_COMPARE_POS)

#define VT2_LWIC_MMODETIMECMP17_OFFSET _ULL(0x11)

#define VT2_LWIC_MMODETIMECMP17_POS 0
#define VT2_LWIC_MMODETIMECMP17_WID 64
#define VT2_LWIC_MMODETIMECMP17_MSK (((_ULL(1) << VT2_LWIC_MMODETIMECMP17_WID) - _ULL(1)) << VT2_LWIC_MMODETIMECMP17_POS)

#define VT2_LWIC_MMODETIMECMP17_COMPARE_POS 0
#define VT2_LWIC_MMODETIMECMP17_COMPARE_WID 64
#define VT2_LWIC_MMODETIMECMP17_COMPARE_MSK (((_ULL(1) << VT2_LWIC_MMODETIMECMP17_COMPARE_WID) - _ULL(1)) << VT2_LWIC_MMODETIMECMP17_COMPARE_POS)

#define VT2_LWIC_MMODETIMECMP18_OFFSET _ULL(0x12)

#define VT2_LWIC_MMODETIMECMP18_POS 0
#define VT2_LWIC_MMODETIMECMP18_WID 64
#define VT2_LWIC_MMODETIMECMP18_MSK (((_ULL(1) << VT2_LWIC_MMODETIMECMP18_WID) - _ULL(1)) << VT2_LWIC_MMODETIMECMP18_POS)

#define VT2_LWIC_MMODETIMECMP18_COMPARE_POS 0
#define VT2_LWIC_MMODETIMECMP18_COMPARE_WID 64
#define VT2_LWIC_MMODETIMECMP18_COMPARE_MSK (((_ULL(1) << VT2_LWIC_MMODETIMECMP18_COMPARE_WID) - _ULL(1)) << VT2_LWIC_MMODETIMECMP18_COMPARE_POS)

#define VT2_LWIC_MMODETIMECMP19_OFFSET _ULL(0x13)

#define VT2_LWIC_MMODETIMECMP19_POS 0
#define VT2_LWIC_MMODETIMECMP19_WID 64
#define VT2_LWIC_MMODETIMECMP19_MSK (((_ULL(1) << VT2_LWIC_MMODETIMECMP19_WID) - _ULL(1)) << VT2_LWIC_MMODETIMECMP19_POS)

#define VT2_LWIC_MMODETIMECMP19_COMPARE_POS 0
#define VT2_LWIC_MMODETIMECMP19_COMPARE_WID 64
#define VT2_LWIC_MMODETIMECMP19_COMPARE_MSK (((_ULL(1) << VT2_LWIC_MMODETIMECMP19_COMPARE_WID) - _ULL(1)) << VT2_LWIC_MMODETIMECMP19_COMPARE_POS)

#define VT2_LWIC_MMODETIMECMP20_OFFSET _ULL(0x14)

#define VT2_LWIC_MMODETIMECMP20_POS 0
#define VT2_LWIC_MMODETIMECMP20_WID 64
#define VT2_LWIC_MMODETIMECMP20_MSK (((_ULL(1) << VT2_LWIC_MMODETIMECMP20_WID) - _ULL(1)) << VT2_LWIC_MMODETIMECMP20_POS)

#define VT2_LWIC_MMODETIMECMP20_COMPARE_POS 0
#define VT2_LWIC_MMODETIMECMP20_COMPARE_WID 64
#define VT2_LWIC_MMODETIMECMP20_COMPARE_MSK (((_ULL(1) << VT2_LWIC_MMODETIMECMP20_COMPARE_WID) - _ULL(1)) << VT2_LWIC_MMODETIMECMP20_COMPARE_POS)

#define VT2_LWIC_MMODETIMECMP21_OFFSET _ULL(0x15)

#define VT2_LWIC_MMODETIMECMP21_POS 0
#define VT2_LWIC_MMODETIMECMP21_WID 64
#define VT2_LWIC_MMODETIMECMP21_MSK (((_ULL(1) << VT2_LWIC_MMODETIMECMP21_WID) - _ULL(1)) << VT2_LWIC_MMODETIMECMP21_POS)

#define VT2_LWIC_MMODETIMECMP21_COMPARE_POS 0
#define VT2_LWIC_MMODETIMECMP21_COMPARE_WID 64
#define VT2_LWIC_MMODETIMECMP21_COMPARE_MSK (((_ULL(1) << VT2_LWIC_MMODETIMECMP21_COMPARE_WID) - _ULL(1)) << VT2_LWIC_MMODETIMECMP21_COMPARE_POS)

#define VT2_LWIC_MMODETIMECMP22_OFFSET _ULL(0x16)

#define VT2_LWIC_MMODETIMECMP22_POS 0
#define VT2_LWIC_MMODETIMECMP22_WID 64
#define VT2_LWIC_MMODETIMECMP22_MSK (((_ULL(1) << VT2_LWIC_MMODETIMECMP22_WID) - _ULL(1)) << VT2_LWIC_MMODETIMECMP22_POS)

#define VT2_LWIC_MMODETIMECMP22_COMPARE_POS 0
#define VT2_LWIC_MMODETIMECMP22_COMPARE_WID 64
#define VT2_LWIC_MMODETIMECMP22_COMPARE_MSK (((_ULL(1) << VT2_LWIC_MMODETIMECMP22_COMPARE_WID) - _ULL(1)) << VT2_LWIC_MMODETIMECMP22_COMPARE_POS)

#define VT2_LWIC_MMODETIMECMP23_OFFSET _ULL(0x17)

#define VT2_LWIC_MMODETIMECMP23_POS 0
#define VT2_LWIC_MMODETIMECMP23_WID 64
#define VT2_LWIC_MMODETIMECMP23_MSK (((_ULL(1) << VT2_LWIC_MMODETIMECMP23_WID) - _ULL(1)) << VT2_LWIC_MMODETIMECMP23_POS)

#define VT2_LWIC_MMODETIMECMP23_COMPARE_POS 0
#define VT2_LWIC_MMODETIMECMP23_COMPARE_WID 64
#define VT2_LWIC_MMODETIMECMP23_COMPARE_MSK (((_ULL(1) << VT2_LWIC_MMODETIMECMP23_COMPARE_WID) - _ULL(1)) << VT2_LWIC_MMODETIMECMP23_COMPARE_POS)

#define VT2_LWIC_MMODETIMECMP24_OFFSET _ULL(0x18)

#define VT2_LWIC_MMODETIMECMP24_POS 0
#define VT2_LWIC_MMODETIMECMP24_WID 64
#define VT2_LWIC_MMODETIMECMP24_MSK (((_ULL(1) << VT2_LWIC_MMODETIMECMP24_WID) - _ULL(1)) << VT2_LWIC_MMODETIMECMP24_POS)

#define VT2_LWIC_MMODETIMECMP24_COMPARE_POS 0
#define VT2_LWIC_MMODETIMECMP24_COMPARE_WID 64
#define VT2_LWIC_MMODETIMECMP24_COMPARE_MSK (((_ULL(1) << VT2_LWIC_MMODETIMECMP24_COMPARE_WID) - _ULL(1)) << VT2_LWIC_MMODETIMECMP24_COMPARE_POS)

#define VT2_LWIC_MMODETIMECMP25_OFFSET _ULL(0x19)

#define VT2_LWIC_MMODETIMECMP25_POS 0
#define VT2_LWIC_MMODETIMECMP25_WID 64
#define VT2_LWIC_MMODETIMECMP25_MSK (((_ULL(1) << VT2_LWIC_MMODETIMECMP25_WID) - _ULL(1)) << VT2_LWIC_MMODETIMECMP25_POS)

#define VT2_LWIC_MMODETIMECMP25_COMPARE_POS 0
#define VT2_LWIC_MMODETIMECMP25_COMPARE_WID 64
#define VT2_LWIC_MMODETIMECMP25_COMPARE_MSK (((_ULL(1) << VT2_LWIC_MMODETIMECMP25_COMPARE_WID) - _ULL(1)) << VT2_LWIC_MMODETIMECMP25_COMPARE_POS)

#define VT2_LWIC_MMODETIMECMP26_OFFSET _ULL(0x1a)

#define VT2_LWIC_MMODETIMECMP26_POS 0
#define VT2_LWIC_MMODETIMECMP26_WID 64
#define VT2_LWIC_MMODETIMECMP26_MSK (((_ULL(1) << VT2_LWIC_MMODETIMECMP26_WID) - _ULL(1)) << VT2_LWIC_MMODETIMECMP26_POS)

#define VT2_LWIC_MMODETIMECMP26_COMPARE_POS 0
#define VT2_LWIC_MMODETIMECMP26_COMPARE_WID 64
#define VT2_LWIC_MMODETIMECMP26_COMPARE_MSK (((_ULL(1) << VT2_LWIC_MMODETIMECMP26_COMPARE_WID) - _ULL(1)) << VT2_LWIC_MMODETIMECMP26_COMPARE_POS)

#define VT2_LWIC_MMODETIMECMP27_OFFSET _ULL(0x1b)

#define VT2_LWIC_MMODETIMECMP27_POS 0
#define VT2_LWIC_MMODETIMECMP27_WID 64
#define VT2_LWIC_MMODETIMECMP27_MSK (((_ULL(1) << VT2_LWIC_MMODETIMECMP27_WID) - _ULL(1)) << VT2_LWIC_MMODETIMECMP27_POS)

#define VT2_LWIC_MMODETIMECMP27_COMPARE_POS 0
#define VT2_LWIC_MMODETIMECMP27_COMPARE_WID 64
#define VT2_LWIC_MMODETIMECMP27_COMPARE_MSK (((_ULL(1) << VT2_LWIC_MMODETIMECMP27_COMPARE_WID) - _ULL(1)) << VT2_LWIC_MMODETIMECMP27_COMPARE_POS)

#define VT2_LWIC_MMODETIMECMP28_OFFSET _ULL(0x1c)

#define VT2_LWIC_MMODETIMECMP28_POS 0
#define VT2_LWIC_MMODETIMECMP28_WID 64
#define VT2_LWIC_MMODETIMECMP28_MSK (((_ULL(1) << VT2_LWIC_MMODETIMECMP28_WID) - _ULL(1)) << VT2_LWIC_MMODETIMECMP28_POS)

#define VT2_LWIC_MMODETIMECMP28_COMPARE_POS 0
#define VT2_LWIC_MMODETIMECMP28_COMPARE_WID 64
#define VT2_LWIC_MMODETIMECMP28_COMPARE_MSK (((_ULL(1) << VT2_LWIC_MMODETIMECMP28_COMPARE_WID) - _ULL(1)) << VT2_LWIC_MMODETIMECMP28_COMPARE_POS)

#define VT2_LWIC_MMODETIMECMP29_OFFSET _ULL(0x1d)

#define VT2_LWIC_MMODETIMECMP29_POS 0
#define VT2_LWIC_MMODETIMECMP29_WID 64
#define VT2_LWIC_MMODETIMECMP29_MSK (((_ULL(1) << VT2_LWIC_MMODETIMECMP29_WID) - _ULL(1)) << VT2_LWIC_MMODETIMECMP29_POS)

#define VT2_LWIC_MMODETIMECMP29_COMPARE_POS 0
#define VT2_LWIC_MMODETIMECMP29_COMPARE_WID 64
#define VT2_LWIC_MMODETIMECMP29_COMPARE_MSK (((_ULL(1) << VT2_LWIC_MMODETIMECMP29_COMPARE_WID) - _ULL(1)) << VT2_LWIC_MMODETIMECMP29_COMPARE_POS)

#define VT2_LWIC_MMODETIMECMP30_OFFSET _ULL(0x1e)

#define VT2_LWIC_MMODETIMECMP30_POS 0
#define VT2_LWIC_MMODETIMECMP30_WID 64
#define VT2_LWIC_MMODETIMECMP30_MSK (((_ULL(1) << VT2_LWIC_MMODETIMECMP30_WID) - _ULL(1)) << VT2_LWIC_MMODETIMECMP30_POS)

#define VT2_LWIC_MMODETIMECMP30_COMPARE_POS 0
#define VT2_LWIC_MMODETIMECMP30_COMPARE_WID 64
#define VT2_LWIC_MMODETIMECMP30_COMPARE_MSK (((_ULL(1) << VT2_LWIC_MMODETIMECMP30_COMPARE_WID) - _ULL(1)) << VT2_LWIC_MMODETIMECMP30_COMPARE_POS)

#define VT2_LWIC_MMODETIMECMP31_OFFSET _ULL(0x1f)

#define VT2_LWIC_MMODETIMECMP31_POS 0
#define VT2_LWIC_MMODETIMECMP31_WID 64
#define VT2_LWIC_MMODETIMECMP31_MSK (((_ULL(1) << VT2_LWIC_MMODETIMECMP31_WID) - _ULL(1)) << VT2_LWIC_MMODETIMECMP31_POS)

#define VT2_LWIC_MMODETIMECMP31_COMPARE_POS 0
#define VT2_LWIC_MMODETIMECMP31_COMPARE_WID 64
#define VT2_LWIC_MMODETIMECMP31_COMPARE_MSK (((_ULL(1) << VT2_LWIC_MMODETIMECMP31_COMPARE_WID) - _ULL(1)) << VT2_LWIC_MMODETIMECMP31_COMPARE_POS)

#define VT2_LWIC_MTIME_OFFSET _ULL(0x1ff)

#define VT2_LWIC_MTIME_POS 0
#define VT2_LWIC_MTIME_WID 64
#define VT2_LWIC_MTIME_MSK (((_ULL(1) << VT2_LWIC_MTIME_WID) - _ULL(1)) << VT2_LWIC_MTIME_POS)

#define VT2_LWIC_MTIME_TIME_POS 0
#define VT2_LWIC_MTIME_TIME_WID 64
#define VT2_LWIC_MTIME_TIME_MSK (((_ULL(1) << VT2_LWIC_MTIME_TIME_WID) - _ULL(1)) << VT2_LWIC_MTIME_TIME_POS)

#define VT2_LWIC_TIMERINCEN_OFFSET _ULL(0x200)

#define VT2_LWIC_TIMERINCEN_POS 0
#define VT2_LWIC_TIMERINCEN_WID 1
#define VT2_LWIC_TIMERINCEN_MSK (((_ULL(1) << VT2_LWIC_TIMERINCEN_WID) - _ULL(1)) << VT2_LWIC_TIMERINCEN_POS)

#define VT2_LWIC_TIMERINCEN_ENABLE_POS 0
#define VT2_LWIC_TIMERINCEN_ENABLE_WID 1
#define VT2_LWIC_TIMERINCEN_ENABLE_MSK (((_ULL(1) << VT2_LWIC_TIMERINCEN_ENABLE_WID) - _ULL(1)) << VT2_LWIC_TIMERINCEN_ENABLE_POS)

#define VT2_LWIC_TIMERINCDIV_OFFSET _ULL(0x201)

#define VT2_LWIC_TIMERINCDIV_POS 0
#define VT2_LWIC_TIMERINCDIV_WID 2
#define VT2_LWIC_TIMERINCDIV_MSK (((_ULL(1) << VT2_LWIC_TIMERINCDIV_WID) - _ULL(1)) << VT2_LWIC_TIMERINCDIV_POS)

#define VT2_LWIC_TIMERINCDIV_DIVIDE_POS 0
#define VT2_LWIC_TIMERINCDIV_DIVIDE_WID 2
#define VT2_LWIC_TIMERINCDIV_DIVIDE_MSK (((_ULL(1) << VT2_LWIC_TIMERINCDIV_DIVIDE_WID) - _ULL(1)) << VT2_LWIC_TIMERINCDIV_DIVIDE_POS)
#endif /* VT2_LWIC_MMR_H */
