/* This file is auto-generated. Do not hand edit this file. */

#ifndef VT2_SMRC_MMR_H
#define VT2_SMRC_MMR_H

#ifndef _ULL

#ifdef __ASSEMBLER__
#define _AC(X,Y) X
#else
#define __AC(X,Y) (X##Y)
#define _AC(X,Y) __AC(X,Y)
#endif

#define _ULL(x)  (_AC(x, ULL))
#endif


#define VT2_SMRC_CLUSTERRESET_OFFSET _ULL(0x0)

#define VT2_SMRC_CLUSTERRESET_POS 0
#define VT2_SMRC_CLUSTERRESET_WID 3
#define VT2_SMRC_CLUSTERRESET_MSK (((_ULL(1) << VT2_SMRC_CLUSTERRESET_WID) - _ULL(1)) << VT2_SMRC_CLUSTERRESET_POS)

#define VT2_SMRC_CLUSTERRESET_NONCORERESET_POS 0
#define VT2_SMRC_CLUSTERRESET_NONCORERESET_WID 1
#define VT2_SMRC_CLUSTERRESET_NONCORERESET_MSK (((_ULL(1) << VT2_SMRC_CLUSTERRESET_NONCORERESET_WID) - _ULL(1)) << VT2_SMRC_CLUSTERRESET_NONCORERESET_POS)
#define VT2_SMRC_CLUSTERRESET_PCLREGBUSACTIVE_POS 1
#define VT2_SMRC_CLUSTERRESET_PCLREGBUSACTIVE_WID 1
#define VT2_SMRC_CLUSTERRESET_PCLREGBUSACTIVE_MSK (((_ULL(1) << VT2_SMRC_CLUSTERRESET_PCLREGBUSACTIVE_WID) - _ULL(1)) << VT2_SMRC_CLUSTERRESET_PCLREGBUSACTIVE_POS)
#define VT2_SMRC_CLUSTERRESET_PCLRSPBRIDGEENABLE_POS 2
#define VT2_SMRC_CLUSTERRESET_PCLRSPBRIDGEENABLE_WID 1
#define VT2_SMRC_CLUSTERRESET_PCLRSPBRIDGEENABLE_MSK (((_ULL(1) << VT2_SMRC_CLUSTERRESET_PCLRSPBRIDGEENABLE_WID) - _ULL(1)) << VT2_SMRC_CLUSTERRESET_PCLRSPBRIDGEENABLE_POS)

#define VT2_SMRC_CLUSTERCONFIG_OFFSET _ULL(0x1)

#define VT2_SMRC_CLUSTERCONFIG_POS 0
#define VT2_SMRC_CLUSTERCONFIG_WID 32
#define VT2_SMRC_CLUSTERCONFIG_MSK (((_ULL(1) << VT2_SMRC_CLUSTERCONFIG_WID) - _ULL(1)) << VT2_SMRC_CLUSTERCONFIG_POS)

#define VT2_SMRC_CLUSTERCONFIG_CLUSTERID_POS 0
#define VT2_SMRC_CLUSTERCONFIG_CLUSTERID_WID 4
#define VT2_SMRC_CLUSTERCONFIG_CLUSTERID_MSK (((_ULL(1) << VT2_SMRC_CLUSTERCONFIG_CLUSTERID_WID) - _ULL(1)) << VT2_SMRC_CLUSTERCONFIG_CLUSTERID_POS)
#define VT2_SMRC_CLUSTERCONFIG_CPUVECTOR_POS 4
#define VT2_SMRC_CLUSTERCONFIG_CPUVECTOR_WID 16
#define VT2_SMRC_CLUSTERCONFIG_CPUVECTOR_MSK (((_ULL(1) << VT2_SMRC_CLUSTERCONFIG_CPUVECTOR_WID) - _ULL(1)) << VT2_SMRC_CLUSTERCONFIG_CPUVECTOR_POS)
#define VT2_SMRC_CLUSTERCONFIG_NUMBERL3MSLICE_POS 20
#define VT2_SMRC_CLUSTERCONFIG_NUMBERL3MSLICE_WID 5
#define VT2_SMRC_CLUSTERCONFIG_NUMBERL3MSLICE_MSK (((_ULL(1) << VT2_SMRC_CLUSTERCONFIG_NUMBERL3MSLICE_WID) - _ULL(1)) << VT2_SMRC_CLUSTERCONFIG_NUMBERL3MSLICE_POS)
#define VT2_SMRC_CLUSTERCONFIG_L3MSLICECAP_POS 25
#define VT2_SMRC_CLUSTERCONFIG_L3MSLICECAP_WID 3
#define VT2_SMRC_CLUSTERCONFIG_L3MSLICECAP_MSK (((_ULL(1) << VT2_SMRC_CLUSTERCONFIG_L3MSLICECAP_WID) - _ULL(1)) << VT2_SMRC_CLUSTERCONFIG_L3MSLICECAP_POS)
#define VT2_SMRC_CLUSTERCONFIG_LOCK_POS 31
#define VT2_SMRC_CLUSTERCONFIG_LOCK_WID 1
#define VT2_SMRC_CLUSTERCONFIG_LOCK_MSK (((_ULL(1) << VT2_SMRC_CLUSTERCONFIG_LOCK_WID) - _ULL(1)) << VT2_SMRC_CLUSTERCONFIG_LOCK_POS)

#define VT2_SMRC_CLUSTERISOLATION_OFFSET _ULL(0x2)

#define VT2_SMRC_CLUSTERISOLATION_POS 0
#define VT2_SMRC_CLUSTERISOLATION_WID 1
#define VT2_SMRC_CLUSTERISOLATION_MSK (((_ULL(1) << VT2_SMRC_CLUSTERISOLATION_WID) - _ULL(1)) << VT2_SMRC_CLUSTERISOLATION_POS)

#define VT2_SMRC_CLUSTERISOLATION_ENABLE_POS 0
#define VT2_SMRC_CLUSTERISOLATION_ENABLE_WID 1
#define VT2_SMRC_CLUSTERISOLATION_ENABLE_MSK (((_ULL(1) << VT2_SMRC_CLUSTERISOLATION_ENABLE_WID) - _ULL(1)) << VT2_SMRC_CLUSTERISOLATION_ENABLE_POS)

#define VT2_SMRC_BISRCONTROLSTATUS_OFFSET _ULL(0x3)

#define VT2_SMRC_BISRCONTROLSTATUS_POS 0
#define VT2_SMRC_BISRCONTROLSTATUS_WID 6
#define VT2_SMRC_BISRCONTROLSTATUS_MSK (((_ULL(1) << VT2_SMRC_BISRCONTROLSTATUS_WID) - _ULL(1)) << VT2_SMRC_BISRCONTROLSTATUS_POS)

#define VT2_SMRC_BISRCONTROLSTATUS_BISRGO_POS 0
#define VT2_SMRC_BISRCONTROLSTATUS_BISRGO_WID 1
#define VT2_SMRC_BISRCONTROLSTATUS_BISRGO_MSK (((_ULL(1) << VT2_SMRC_BISRCONTROLSTATUS_BISRGO_WID) - _ULL(1)) << VT2_SMRC_BISRCONTROLSTATUS_BISRGO_POS)
#define VT2_SMRC_BISRCONTROLSTATUS_BISRDONE_POS 1
#define VT2_SMRC_BISRCONTROLSTATUS_BISRDONE_WID 1
#define VT2_SMRC_BISRCONTROLSTATUS_BISRDONE_MSK (((_ULL(1) << VT2_SMRC_BISRCONTROLSTATUS_BISRDONE_WID) - _ULL(1)) << VT2_SMRC_BISRCONTROLSTATUS_BISRDONE_POS)
#define VT2_SMRC_BISRCONTROLSTATUS_BISRCLKFREQ_POS 2
#define VT2_SMRC_BISRCONTROLSTATUS_BISRCLKFREQ_WID 1
#define VT2_SMRC_BISRCONTROLSTATUS_BISRCLKFREQ_MSK (((_ULL(1) << VT2_SMRC_BISRCONTROLSTATUS_BISRCLKFREQ_WID) - _ULL(1)) << VT2_SMRC_BISRCONTROLSTATUS_BISRCLKFREQ_POS)
#define VT2_SMRC_BISRCONTROLSTATUS_BISRRUN_POS 3
#define VT2_SMRC_BISRCONTROLSTATUS_BISRRUN_WID 1
#define VT2_SMRC_BISRCONTROLSTATUS_BISRRUN_MSK (((_ULL(1) << VT2_SMRC_BISRCONTROLSTATUS_BISRRUN_WID) - _ULL(1)) << VT2_SMRC_BISRCONTROLSTATUS_BISRRUN_POS)
#define VT2_SMRC_BISRCONTROLSTATUS_BISRENPCL_POS 4
#define VT2_SMRC_BISRCONTROLSTATUS_BISRENPCL_WID 1
#define VT2_SMRC_BISRCONTROLSTATUS_BISRENPCL_MSK (((_ULL(1) << VT2_SMRC_BISRCONTROLSTATUS_BISRENPCL_WID) - _ULL(1)) << VT2_SMRC_BISRCONTROLSTATUS_BISRENPCL_POS)
#define VT2_SMRC_BISRCONTROLSTATUS_BISRENSPX_POS 5
#define VT2_SMRC_BISRCONTROLSTATUS_BISRENSPX_WID 1
#define VT2_SMRC_BISRCONTROLSTATUS_BISRENSPX_MSK (((_ULL(1) << VT2_SMRC_BISRCONTROLSTATUS_BISRENSPX_WID) - _ULL(1)) << VT2_SMRC_BISRCONTROLSTATUS_BISRENSPX_POS)

#define VT2_SMRC_SPXCONFIG_OFFSET _ULL(0x4)

#define VT2_SMRC_SPXCONFIG_POS 1
#define VT2_SMRC_SPXCONFIG_WID 31
#define VT2_SMRC_SPXCONFIG_MSK (((_ULL(1) << VT2_SMRC_SPXCONFIG_WID) - _ULL(1)) << VT2_SMRC_SPXCONFIG_POS)

#define VT2_SMRC_SPXCONFIG_DBMDAUTHENTICATED_POS 1
#define VT2_SMRC_SPXCONFIG_DBMDAUTHENTICATED_WID 1
#define VT2_SMRC_SPXCONFIG_DBMDAUTHENTICATED_MSK (((_ULL(1) << VT2_SMRC_SPXCONFIG_DBMDAUTHENTICATED_WID) - _ULL(1)) << VT2_SMRC_SPXCONFIG_DBMDAUTHENTICATED_POS)
#define VT2_SMRC_SPXCONFIG_DBMDEXTERNALENABLE_POS 2
#define VT2_SMRC_SPXCONFIG_DBMDEXTERNALENABLE_WID 1
#define VT2_SMRC_SPXCONFIG_DBMDEXTERNALENABLE_MSK (((_ULL(1) << VT2_SMRC_SPXCONFIG_DBMDEXTERNALENABLE_WID) - _ULL(1)) << VT2_SMRC_SPXCONFIG_DBMDEXTERNALENABLE_POS)
#define VT2_SMRC_SPXCONFIG_LOCK_POS 31
#define VT2_SMRC_SPXCONFIG_LOCK_WID 1
#define VT2_SMRC_SPXCONFIG_LOCK_MSK (((_ULL(1) << VT2_SMRC_SPXCONFIG_LOCK_WID) - _ULL(1)) << VT2_SMRC_SPXCONFIG_LOCK_POS)

#define VT2_SMRC_SPXINTSTATUS_OFFSET _ULL(0x5)

#define VT2_SMRC_SPXINTSTATUS_POS 0
#define VT2_SMRC_SPXINTSTATUS_WID 5
#define VT2_SMRC_SPXINTSTATUS_MSK (((_ULL(1) << VT2_SMRC_SPXINTSTATUS_WID) - _ULL(1)) << VT2_SMRC_SPXINTSTATUS_POS)

#define VT2_SMRC_SPXINTSTATUS_D2DERRINTST0_POS 0
#define VT2_SMRC_SPXINTSTATUS_D2DERRINTST0_WID 1
#define VT2_SMRC_SPXINTSTATUS_D2DERRINTST0_MSK (((_ULL(1) << VT2_SMRC_SPXINTSTATUS_D2DERRINTST0_WID) - _ULL(1)) << VT2_SMRC_SPXINTSTATUS_D2DERRINTST0_POS)
#define VT2_SMRC_SPXINTSTATUS_D2DERRINTST1_POS 1
#define VT2_SMRC_SPXINTSTATUS_D2DERRINTST1_WID 1
#define VT2_SMRC_SPXINTSTATUS_D2DERRINTST1_MSK (((_ULL(1) << VT2_SMRC_SPXINTSTATUS_D2DERRINTST1_WID) - _ULL(1)) << VT2_SMRC_SPXINTSTATUS_D2DERRINTST1_POS)
#define VT2_SMRC_SPXINTSTATUS_D2DMCUERRINTST0_POS 2
#define VT2_SMRC_SPXINTSTATUS_D2DMCUERRINTST0_WID 1
#define VT2_SMRC_SPXINTSTATUS_D2DMCUERRINTST0_MSK (((_ULL(1) << VT2_SMRC_SPXINTSTATUS_D2DMCUERRINTST0_WID) - _ULL(1)) << VT2_SMRC_SPXINTSTATUS_D2DMCUERRINTST0_POS)
#define VT2_SMRC_SPXINTSTATUS_D2DMCUERRINTST1_POS 3
#define VT2_SMRC_SPXINTSTATUS_D2DMCUERRINTST1_WID 1
#define VT2_SMRC_SPXINTSTATUS_D2DMCUERRINTST1_MSK (((_ULL(1) << VT2_SMRC_SPXINTSTATUS_D2DMCUERRINTST1_WID) - _ULL(1)) << VT2_SMRC_SPXINTSTATUS_D2DMCUERRINTST1_POS)
#define VT2_SMRC_SPXINTSTATUS_I3CINTST_POS 4
#define VT2_SMRC_SPXINTSTATUS_I3CINTST_WID 1
#define VT2_SMRC_SPXINTSTATUS_I3CINTST_MSK (((_ULL(1) << VT2_SMRC_SPXINTSTATUS_I3CINTST_WID) - _ULL(1)) << VT2_SMRC_SPXINTSTATUS_I3CINTST_POS)

#define VT2_SMRC_SPXINTCONFIG_OFFSET _ULL(0x6)

#define VT2_SMRC_SPXINTCONFIG_POS 0
#define VT2_SMRC_SPXINTCONFIG_WID 10
#define VT2_SMRC_SPXINTCONFIG_MSK (((_ULL(1) << VT2_SMRC_SPXINTCONFIG_WID) - _ULL(1)) << VT2_SMRC_SPXINTCONFIG_POS)

#define VT2_SMRC_SPXINTCONFIG_NMILOOPBACKEN_POS 0
#define VT2_SMRC_SPXINTCONFIG_NMILOOPBACKEN_WID 1
#define VT2_SMRC_SPXINTCONFIG_NMILOOPBACKEN_MSK (((_ULL(1) << VT2_SMRC_SPXINTCONFIG_NMILOOPBACKEN_WID) - _ULL(1)) << VT2_SMRC_SPXINTCONFIG_NMILOOPBACKEN_POS)
#define VT2_SMRC_SPXINTCONFIG_D2DNMIEN_POS 1
#define VT2_SMRC_SPXINTCONFIG_D2DNMIEN_WID 1
#define VT2_SMRC_SPXINTCONFIG_D2DNMIEN_MSK (((_ULL(1) << VT2_SMRC_SPXINTCONFIG_D2DNMIEN_WID) - _ULL(1)) << VT2_SMRC_SPXINTCONFIG_D2DNMIEN_POS)
#define VT2_SMRC_SPXINTCONFIG_D2DHIPRIINTEN_POS 2
#define VT2_SMRC_SPXINTCONFIG_D2DHIPRIINTEN_WID 1
#define VT2_SMRC_SPXINTCONFIG_D2DHIPRIINTEN_MSK (((_ULL(1) << VT2_SMRC_SPXINTCONFIG_D2DHIPRIINTEN_WID) - _ULL(1)) << VT2_SMRC_SPXINTCONFIG_D2DHIPRIINTEN_POS)
#define VT2_SMRC_SPXINTCONFIG_D2DLOPRIINTEN_POS 3
#define VT2_SMRC_SPXINTCONFIG_D2DLOPRIINTEN_WID 1
#define VT2_SMRC_SPXINTCONFIG_D2DLOPRIINTEN_MSK (((_ULL(1) << VT2_SMRC_SPXINTCONFIG_D2DLOPRIINTEN_WID) - _ULL(1)) << VT2_SMRC_SPXINTCONFIG_D2DLOPRIINTEN_POS)
#define VT2_SMRC_SPXINTCONFIG_MCUNMIEN_POS 4
#define VT2_SMRC_SPXINTCONFIG_MCUNMIEN_WID 1
#define VT2_SMRC_SPXINTCONFIG_MCUNMIEN_MSK (((_ULL(1) << VT2_SMRC_SPXINTCONFIG_MCUNMIEN_WID) - _ULL(1)) << VT2_SMRC_SPXINTCONFIG_MCUNMIEN_POS)
#define VT2_SMRC_SPXINTCONFIG_MCUHIPRIINTEN_POS 5
#define VT2_SMRC_SPXINTCONFIG_MCUHIPRIINTEN_WID 1
#define VT2_SMRC_SPXINTCONFIG_MCUHIPRIINTEN_MSK (((_ULL(1) << VT2_SMRC_SPXINTCONFIG_MCUHIPRIINTEN_WID) - _ULL(1)) << VT2_SMRC_SPXINTCONFIG_MCUHIPRIINTEN_POS)
#define VT2_SMRC_SPXINTCONFIG_MCULOPRIINTEN_POS 6
#define VT2_SMRC_SPXINTCONFIG_MCULOPRIINTEN_WID 1
#define VT2_SMRC_SPXINTCONFIG_MCULOPRIINTEN_MSK (((_ULL(1) << VT2_SMRC_SPXINTCONFIG_MCULOPRIINTEN_WID) - _ULL(1)) << VT2_SMRC_SPXINTCONFIG_MCULOPRIINTEN_POS)
#define VT2_SMRC_SPXINTCONFIG_I3CNMIEN_POS 7
#define VT2_SMRC_SPXINTCONFIG_I3CNMIEN_WID 1
#define VT2_SMRC_SPXINTCONFIG_I3CNMIEN_MSK (((_ULL(1) << VT2_SMRC_SPXINTCONFIG_I3CNMIEN_WID) - _ULL(1)) << VT2_SMRC_SPXINTCONFIG_I3CNMIEN_POS)
#define VT2_SMRC_SPXINTCONFIG_I3CHIPRIINTEN_POS 8
#define VT2_SMRC_SPXINTCONFIG_I3CHIPRIINTEN_WID 1
#define VT2_SMRC_SPXINTCONFIG_I3CHIPRIINTEN_MSK (((_ULL(1) << VT2_SMRC_SPXINTCONFIG_I3CHIPRIINTEN_WID) - _ULL(1)) << VT2_SMRC_SPXINTCONFIG_I3CHIPRIINTEN_POS)
#define VT2_SMRC_SPXINTCONFIG_I3CLOPRIINTEN_POS 9
#define VT2_SMRC_SPXINTCONFIG_I3CLOPRIINTEN_WID 1
#define VT2_SMRC_SPXINTCONFIG_I3CLOPRIINTEN_MSK (((_ULL(1) << VT2_SMRC_SPXINTCONFIG_I3CLOPRIINTEN_WID) - _ULL(1)) << VT2_SMRC_SPXINTCONFIG_I3CLOPRIINTEN_POS)

#define VT2_SMRC_RNFSELVEC0LO_OFFSET _ULL(0x8)

#define VT2_SMRC_RNFSELVEC0LO_POS 6
#define VT2_SMRC_RNFSELVEC0LO_WID 26
#define VT2_SMRC_RNFSELVEC0LO_MSK (((_ULL(1) << VT2_SMRC_RNFSELVEC0LO_WID) - _ULL(1)) << VT2_SMRC_RNFSELVEC0LO_POS)

#define VT2_SMRC_RNFSELVEC0LO_RNFVECLO_POS 6
#define VT2_SMRC_RNFSELVEC0LO_RNFVECLO_WID 26
#define VT2_SMRC_RNFSELVEC0LO_RNFVECLO_MSK (((_ULL(1) << VT2_SMRC_RNFSELVEC0LO_RNFVECLO_WID) - _ULL(1)) << VT2_SMRC_RNFSELVEC0LO_RNFVECLO_POS)

#define VT2_SMRC_RNFSELVEC0HI_OFFSET _ULL(0x9)

#define VT2_SMRC_RNFSELVEC0HI_POS 0
#define VT2_SMRC_RNFSELVEC0HI_WID 16
#define VT2_SMRC_RNFSELVEC0HI_MSK (((_ULL(1) << VT2_SMRC_RNFSELVEC0HI_WID) - _ULL(1)) << VT2_SMRC_RNFSELVEC0HI_POS)

#define VT2_SMRC_RNFSELVEC0HI_RNFVECHI_POS 0
#define VT2_SMRC_RNFSELVEC0HI_RNFVECHI_WID 16
#define VT2_SMRC_RNFSELVEC0HI_RNFVECHI_MSK (((_ULL(1) << VT2_SMRC_RNFSELVEC0HI_RNFVECHI_WID) - _ULL(1)) << VT2_SMRC_RNFSELVEC0HI_RNFVECHI_POS)

#define VT2_SMRC_RNFSELVEC1LO_OFFSET _ULL(0xa)

#define VT2_SMRC_RNFSELVEC1LO_POS 6
#define VT2_SMRC_RNFSELVEC1LO_WID 26
#define VT2_SMRC_RNFSELVEC1LO_MSK (((_ULL(1) << VT2_SMRC_RNFSELVEC1LO_WID) - _ULL(1)) << VT2_SMRC_RNFSELVEC1LO_POS)

#define VT2_SMRC_RNFSELVEC1LO_RNFVECLO_POS 6
#define VT2_SMRC_RNFSELVEC1LO_RNFVECLO_WID 26
#define VT2_SMRC_RNFSELVEC1LO_RNFVECLO_MSK (((_ULL(1) << VT2_SMRC_RNFSELVEC1LO_RNFVECLO_WID) - _ULL(1)) << VT2_SMRC_RNFSELVEC1LO_RNFVECLO_POS)

#define VT2_SMRC_RNFSELVEC1HI_OFFSET _ULL(0xb)

#define VT2_SMRC_RNFSELVEC1HI_POS 0
#define VT2_SMRC_RNFSELVEC1HI_WID 16
#define VT2_SMRC_RNFSELVEC1HI_MSK (((_ULL(1) << VT2_SMRC_RNFSELVEC1HI_WID) - _ULL(1)) << VT2_SMRC_RNFSELVEC1HI_POS)

#define VT2_SMRC_RNFSELVEC1HI_RNFVECHI_POS 0
#define VT2_SMRC_RNFSELVEC1HI_RNFVECHI_WID 16
#define VT2_SMRC_RNFSELVEC1HI_RNFVECHI_MSK (((_ULL(1) << VT2_SMRC_RNFSELVEC1HI_RNFVECHI_WID) - _ULL(1)) << VT2_SMRC_RNFSELVEC1HI_RNFVECHI_POS)

#define VT2_SMRC_DBIDDVECBASE_OFFSET _ULL(0x200)

#define VT2_SMRC_DBIDDVECBASE_POS 12
#define VT2_SMRC_DBIDDVECBASE_WID 51
#define VT2_SMRC_DBIDDVECBASE_MSK (((_ULL(1) << VT2_SMRC_DBIDDVECBASE_WID) - _ULL(1)) << VT2_SMRC_DBIDDVECBASE_POS)

#define VT2_SMRC_DBIDDVECBASE_BASE_POS 12
#define VT2_SMRC_DBIDDVECBASE_BASE_WID 36
#define VT2_SMRC_DBIDDVECBASE_BASE_MSK (((_ULL(1) << VT2_SMRC_DBIDDVECBASE_BASE_WID) - _ULL(1)) << VT2_SMRC_DBIDDVECBASE_BASE_POS)
#define VT2_SMRC_DBIDDVECBASE_ENABLE_POS 62
#define VT2_SMRC_DBIDDVECBASE_ENABLE_WID 1
#define VT2_SMRC_DBIDDVECBASE_ENABLE_MSK (((_ULL(1) << VT2_SMRC_DBIDDVECBASE_ENABLE_WID) - _ULL(1)) << VT2_SMRC_DBIDDVECBASE_ENABLE_POS)

#define VT2_SMRC_DBIDDREGBASE_OFFSET _ULL(0x201)

#define VT2_SMRC_DBIDDREGBASE_POS 12
#define VT2_SMRC_DBIDDREGBASE_WID 51
#define VT2_SMRC_DBIDDREGBASE_MSK (((_ULL(1) << VT2_SMRC_DBIDDREGBASE_WID) - _ULL(1)) << VT2_SMRC_DBIDDREGBASE_POS)

#define VT2_SMRC_DBIDDREGBASE_BASE_POS 12
#define VT2_SMRC_DBIDDREGBASE_BASE_WID 36
#define VT2_SMRC_DBIDDREGBASE_BASE_MSK (((_ULL(1) << VT2_SMRC_DBIDDREGBASE_BASE_WID) - _ULL(1)) << VT2_SMRC_DBIDDREGBASE_BASE_POS)
#define VT2_SMRC_DBIDDREGBASE_ENABLE_POS 62
#define VT2_SMRC_DBIDDREGBASE_ENABLE_WID 1
#define VT2_SMRC_DBIDDREGBASE_ENABLE_MSK (((_ULL(1) << VT2_SMRC_DBIDDREGBASE_ENABLE_WID) - _ULL(1)) << VT2_SMRC_DBIDDREGBASE_ENABLE_POS)

#define VT2_SMRC_DBIDPUCBASE_OFFSET _ULL(0x202)

#define VT2_SMRC_DBIDPUCBASE_POS 12
#define VT2_SMRC_DBIDPUCBASE_WID 51
#define VT2_SMRC_DBIDPUCBASE_MSK (((_ULL(1) << VT2_SMRC_DBIDPUCBASE_WID) - _ULL(1)) << VT2_SMRC_DBIDPUCBASE_POS)

#define VT2_SMRC_DBIDPUCBASE_BASE_POS 12
#define VT2_SMRC_DBIDPUCBASE_BASE_WID 36
#define VT2_SMRC_DBIDPUCBASE_BASE_MSK (((_ULL(1) << VT2_SMRC_DBIDPUCBASE_BASE_WID) - _ULL(1)) << VT2_SMRC_DBIDPUCBASE_BASE_POS)
#define VT2_SMRC_DBIDPUCBASE_ENABLE_POS 62
#define VT2_SMRC_DBIDPUCBASE_ENABLE_WID 1
#define VT2_SMRC_DBIDPUCBASE_ENABLE_MSK (((_ULL(1) << VT2_SMRC_DBIDPUCBASE_ENABLE_WID) - _ULL(1)) << VT2_SMRC_DBIDPUCBASE_ENABLE_POS)

#define VT2_SMRC_LWICMMODETIMERBASE_OFFSET _ULL(0x204)

#define VT2_SMRC_LWICMMODETIMERBASE_POS 14
#define VT2_SMRC_LWICMMODETIMERBASE_WID 49
#define VT2_SMRC_LWICMMODETIMERBASE_MSK (((_ULL(1) << VT2_SMRC_LWICMMODETIMERBASE_WID) - _ULL(1)) << VT2_SMRC_LWICMMODETIMERBASE_POS)

#define VT2_SMRC_LWICMMODETIMERBASE_BASE_POS 14
#define VT2_SMRC_LWICMMODETIMERBASE_BASE_WID 34
#define VT2_SMRC_LWICMMODETIMERBASE_BASE_MSK (((_ULL(1) << VT2_SMRC_LWICMMODETIMERBASE_BASE_WID) - _ULL(1)) << VT2_SMRC_LWICMMODETIMERBASE_BASE_POS)
#define VT2_SMRC_LWICMMODETIMERBASE_ENABLE_POS 62
#define VT2_SMRC_LWICMMODETIMERBASE_ENABLE_WID 1
#define VT2_SMRC_LWICMMODETIMERBASE_ENABLE_MSK (((_ULL(1) << VT2_SMRC_LWICMMODETIMERBASE_ENABLE_WID) - _ULL(1)) << VT2_SMRC_LWICMMODETIMERBASE_ENABLE_POS)

#define VT2_SMRC_SMRCBASE_OFFSET _ULL(0x208)

#define VT2_SMRC_SMRCBASE_POS 14
#define VT2_SMRC_SMRCBASE_WID 49
#define VT2_SMRC_SMRCBASE_MSK (((_ULL(1) << VT2_SMRC_SMRCBASE_WID) - _ULL(1)) << VT2_SMRC_SMRCBASE_POS)

#define VT2_SMRC_SMRCBASE_BASE_POS 14
#define VT2_SMRC_SMRCBASE_BASE_WID 34
#define VT2_SMRC_SMRCBASE_BASE_MSK (((_ULL(1) << VT2_SMRC_SMRCBASE_BASE_WID) - _ULL(1)) << VT2_SMRC_SMRCBASE_BASE_POS)
#define VT2_SMRC_SMRCBASE_ENABLE_POS 62
#define VT2_SMRC_SMRCBASE_ENABLE_WID 1
#define VT2_SMRC_SMRCBASE_ENABLE_MSK (((_ULL(1) << VT2_SMRC_SMRCBASE_ENABLE_WID) - _ULL(1)) << VT2_SMRC_SMRCBASE_ENABLE_POS)

#define VT2_SMRC_CHIBBASE_OFFSET _ULL(0x20c)

#define VT2_SMRC_CHIBBASE_POS 14
#define VT2_SMRC_CHIBBASE_WID 49
#define VT2_SMRC_CHIBBASE_MSK (((_ULL(1) << VT2_SMRC_CHIBBASE_WID) - _ULL(1)) << VT2_SMRC_CHIBBASE_POS)

#define VT2_SMRC_CHIBBASE_BASE_POS 14
#define VT2_SMRC_CHIBBASE_BASE_WID 34
#define VT2_SMRC_CHIBBASE_BASE_MSK (((_ULL(1) << VT2_SMRC_CHIBBASE_BASE_WID) - _ULL(1)) << VT2_SMRC_CHIBBASE_BASE_POS)
#define VT2_SMRC_CHIBBASE_ENABLE_POS 62
#define VT2_SMRC_CHIBBASE_ENABLE_WID 1
#define VT2_SMRC_CHIBBASE_ENABLE_MSK (((_ULL(1) << VT2_SMRC_CHIBBASE_ENABLE_WID) - _ULL(1)) << VT2_SMRC_CHIBBASE_ENABLE_POS)

#define VT2_SMRC_CHPLBASE_OFFSET _ULL(0x280)

#define VT2_SMRC_CHPLBASE_POS 18
#define VT2_SMRC_CHPLBASE_WID 45
#define VT2_SMRC_CHPLBASE_MSK (((_ULL(1) << VT2_SMRC_CHPLBASE_WID) - _ULL(1)) << VT2_SMRC_CHPLBASE_POS)

#define VT2_SMRC_CHPLBASE_BASE_POS 18
#define VT2_SMRC_CHPLBASE_BASE_WID 30
#define VT2_SMRC_CHPLBASE_BASE_MSK (((_ULL(1) << VT2_SMRC_CHPLBASE_BASE_WID) - _ULL(1)) << VT2_SMRC_CHPLBASE_BASE_POS)
#define VT2_SMRC_CHPLBASE_ENABLE_POS 62
#define VT2_SMRC_CHPLBASE_ENABLE_WID 1
#define VT2_SMRC_CHPLBASE_ENABLE_MSK (((_ULL(1) << VT2_SMRC_CHPLBASE_ENABLE_WID) - _ULL(1)) << VT2_SMRC_CHPLBASE_ENABLE_POS)

#define VT2_SMRC_CKGNBASE_OFFSET _ULL(0x2c0)

#define VT2_SMRC_CKGNBASE_POS 14
#define VT2_SMRC_CKGNBASE_WID 49
#define VT2_SMRC_CKGNBASE_MSK (((_ULL(1) << VT2_SMRC_CKGNBASE_WID) - _ULL(1)) << VT2_SMRC_CKGNBASE_POS)

#define VT2_SMRC_CKGNBASE_BASE_POS 14
#define VT2_SMRC_CKGNBASE_BASE_WID 34
#define VT2_SMRC_CKGNBASE_BASE_MSK (((_ULL(1) << VT2_SMRC_CKGNBASE_BASE_WID) - _ULL(1)) << VT2_SMRC_CKGNBASE_BASE_POS)
#define VT2_SMRC_CKGNBASE_ENABLE_POS 62
#define VT2_SMRC_CKGNBASE_ENABLE_WID 1
#define VT2_SMRC_CKGNBASE_ENABLE_MSK (((_ULL(1) << VT2_SMRC_CKGNBASE_ENABLE_WID) - _ULL(1)) << VT2_SMRC_CKGNBASE_ENABLE_POS)

#define VT2_SMRC_I3CBASE_OFFSET _ULL(0x2d0)

#define VT2_SMRC_I3CBASE_POS 12
#define VT2_SMRC_I3CBASE_WID 51
#define VT2_SMRC_I3CBASE_MSK (((_ULL(1) << VT2_SMRC_I3CBASE_WID) - _ULL(1)) << VT2_SMRC_I3CBASE_POS)

#define VT2_SMRC_I3CBASE_BASE_POS 12
#define VT2_SMRC_I3CBASE_BASE_WID 36
#define VT2_SMRC_I3CBASE_BASE_MSK (((_ULL(1) << VT2_SMRC_I3CBASE_BASE_WID) - _ULL(1)) << VT2_SMRC_I3CBASE_BASE_POS)
#define VT2_SMRC_I3CBASE_ENABLE_POS 62
#define VT2_SMRC_I3CBASE_ENABLE_WID 1
#define VT2_SMRC_I3CBASE_ENABLE_MSK (((_ULL(1) << VT2_SMRC_I3CBASE_ENABLE_WID) - _ULL(1)) << VT2_SMRC_I3CBASE_ENABLE_POS)

#define VT2_SMRC_D2DMCUBASE_OFFSET _ULL(0x2d1)

#define VT2_SMRC_D2DMCUBASE_POS 12
#define VT2_SMRC_D2DMCUBASE_WID 51
#define VT2_SMRC_D2DMCUBASE_MSK (((_ULL(1) << VT2_SMRC_D2DMCUBASE_WID) - _ULL(1)) << VT2_SMRC_D2DMCUBASE_POS)

#define VT2_SMRC_D2DMCUBASE_BASE_POS 12
#define VT2_SMRC_D2DMCUBASE_BASE_WID 36
#define VT2_SMRC_D2DMCUBASE_BASE_MSK (((_ULL(1) << VT2_SMRC_D2DMCUBASE_BASE_WID) - _ULL(1)) << VT2_SMRC_D2DMCUBASE_BASE_POS)
#define VT2_SMRC_D2DMCUBASE_ENABLE_POS 62
#define VT2_SMRC_D2DMCUBASE_ENABLE_WID 1
#define VT2_SMRC_D2DMCUBASE_ENABLE_MSK (((_ULL(1) << VT2_SMRC_D2DMCUBASE_ENABLE_WID) - _ULL(1)) << VT2_SMRC_D2DMCUBASE_ENABLE_POS)

#define VT2_SMRC_PCLBASE_OFFSET _ULL(0x2ff)

#define VT2_SMRC_PCLBASE_POS 24
#define VT2_SMRC_PCLBASE_WID 39
#define VT2_SMRC_PCLBASE_MSK (((_ULL(1) << VT2_SMRC_PCLBASE_WID) - _ULL(1)) << VT2_SMRC_PCLBASE_POS)

#define VT2_SMRC_PCLBASE_BASE_POS 24
#define VT2_SMRC_PCLBASE_BASE_WID 24
#define VT2_SMRC_PCLBASE_BASE_MSK (((_ULL(1) << VT2_SMRC_PCLBASE_BASE_WID) - _ULL(1)) << VT2_SMRC_PCLBASE_BASE_POS)
#define VT2_SMRC_PCLBASE_ENABLE_POS 62
#define VT2_SMRC_PCLBASE_ENABLE_WID 1
#define VT2_SMRC_PCLBASE_ENABLE_MSK (((_ULL(1) << VT2_SMRC_PCLBASE_ENABLE_WID) - _ULL(1)) << VT2_SMRC_PCLBASE_ENABLE_POS)

#define VT2_SMRC_DBIDDVECSTAGING_OFFSET _ULL(0x300)

#define VT2_SMRC_DBIDDVECSTAGING_POS 12
#define VT2_SMRC_DBIDDVECSTAGING_WID 52
#define VT2_SMRC_DBIDDVECSTAGING_MSK (((_ULL(1) << VT2_SMRC_DBIDDVECSTAGING_WID) - _ULL(1)) << VT2_SMRC_DBIDDVECSTAGING_POS)

#define VT2_SMRC_DBIDDVECSTAGING_BASE_POS 12
#define VT2_SMRC_DBIDDVECSTAGING_BASE_WID 36
#define VT2_SMRC_DBIDDVECSTAGING_BASE_MSK (((_ULL(1) << VT2_SMRC_DBIDDVECSTAGING_BASE_WID) - _ULL(1)) << VT2_SMRC_DBIDDVECSTAGING_BASE_POS)
#define VT2_SMRC_DBIDDVECSTAGING_ENABLE_POS 62
#define VT2_SMRC_DBIDDVECSTAGING_ENABLE_WID 1
#define VT2_SMRC_DBIDDVECSTAGING_ENABLE_MSK (((_ULL(1) << VT2_SMRC_DBIDDVECSTAGING_ENABLE_WID) - _ULL(1)) << VT2_SMRC_DBIDDVECSTAGING_ENABLE_POS)
#define VT2_SMRC_DBIDDVECSTAGING_LOAD_POS 63
#define VT2_SMRC_DBIDDVECSTAGING_LOAD_WID 1
#define VT2_SMRC_DBIDDVECSTAGING_LOAD_MSK (((_ULL(1) << VT2_SMRC_DBIDDVECSTAGING_LOAD_WID) - _ULL(1)) << VT2_SMRC_DBIDDVECSTAGING_LOAD_POS)

#define VT2_SMRC_DBIDDREGSTAGING_OFFSET _ULL(0x301)

#define VT2_SMRC_DBIDDREGSTAGING_POS 12
#define VT2_SMRC_DBIDDREGSTAGING_WID 52
#define VT2_SMRC_DBIDDREGSTAGING_MSK (((_ULL(1) << VT2_SMRC_DBIDDREGSTAGING_WID) - _ULL(1)) << VT2_SMRC_DBIDDREGSTAGING_POS)

#define VT2_SMRC_DBIDDREGSTAGING_BASE_POS 12
#define VT2_SMRC_DBIDDREGSTAGING_BASE_WID 36
#define VT2_SMRC_DBIDDREGSTAGING_BASE_MSK (((_ULL(1) << VT2_SMRC_DBIDDREGSTAGING_BASE_WID) - _ULL(1)) << VT2_SMRC_DBIDDREGSTAGING_BASE_POS)
#define VT2_SMRC_DBIDDREGSTAGING_ENABLE_POS 62
#define VT2_SMRC_DBIDDREGSTAGING_ENABLE_WID 1
#define VT2_SMRC_DBIDDREGSTAGING_ENABLE_MSK (((_ULL(1) << VT2_SMRC_DBIDDREGSTAGING_ENABLE_WID) - _ULL(1)) << VT2_SMRC_DBIDDREGSTAGING_ENABLE_POS)
#define VT2_SMRC_DBIDDREGSTAGING_LOAD_POS 63
#define VT2_SMRC_DBIDDREGSTAGING_LOAD_WID 1
#define VT2_SMRC_DBIDDREGSTAGING_LOAD_MSK (((_ULL(1) << VT2_SMRC_DBIDDREGSTAGING_LOAD_WID) - _ULL(1)) << VT2_SMRC_DBIDDREGSTAGING_LOAD_POS)

#define VT2_SMRC_DBIDPUCSTAGING_OFFSET _ULL(0x302)

#define VT2_SMRC_DBIDPUCSTAGING_POS 12
#define VT2_SMRC_DBIDPUCSTAGING_WID 52
#define VT2_SMRC_DBIDPUCSTAGING_MSK (((_ULL(1) << VT2_SMRC_DBIDPUCSTAGING_WID) - _ULL(1)) << VT2_SMRC_DBIDPUCSTAGING_POS)

#define VT2_SMRC_DBIDPUCSTAGING_BASE_POS 12
#define VT2_SMRC_DBIDPUCSTAGING_BASE_WID 36
#define VT2_SMRC_DBIDPUCSTAGING_BASE_MSK (((_ULL(1) << VT2_SMRC_DBIDPUCSTAGING_BASE_WID) - _ULL(1)) << VT2_SMRC_DBIDPUCSTAGING_BASE_POS)
#define VT2_SMRC_DBIDPUCSTAGING_ENABLE_POS 62
#define VT2_SMRC_DBIDPUCSTAGING_ENABLE_WID 1
#define VT2_SMRC_DBIDPUCSTAGING_ENABLE_MSK (((_ULL(1) << VT2_SMRC_DBIDPUCSTAGING_ENABLE_WID) - _ULL(1)) << VT2_SMRC_DBIDPUCSTAGING_ENABLE_POS)
#define VT2_SMRC_DBIDPUCSTAGING_LOAD_POS 63
#define VT2_SMRC_DBIDPUCSTAGING_LOAD_WID 1
#define VT2_SMRC_DBIDPUCSTAGING_LOAD_MSK (((_ULL(1) << VT2_SMRC_DBIDPUCSTAGING_LOAD_WID) - _ULL(1)) << VT2_SMRC_DBIDPUCSTAGING_LOAD_POS)

#define VT2_SMRC_LWICMMODETIMERSTAGING_OFFSET _ULL(0x304)

#define VT2_SMRC_LWICMMODETIMERSTAGING_POS 14
#define VT2_SMRC_LWICMMODETIMERSTAGING_WID 50
#define VT2_SMRC_LWICMMODETIMERSTAGING_MSK (((_ULL(1) << VT2_SMRC_LWICMMODETIMERSTAGING_WID) - _ULL(1)) << VT2_SMRC_LWICMMODETIMERSTAGING_POS)

#define VT2_SMRC_LWICMMODETIMERSTAGING_BASE_POS 14
#define VT2_SMRC_LWICMMODETIMERSTAGING_BASE_WID 34
#define VT2_SMRC_LWICMMODETIMERSTAGING_BASE_MSK (((_ULL(1) << VT2_SMRC_LWICMMODETIMERSTAGING_BASE_WID) - _ULL(1)) << VT2_SMRC_LWICMMODETIMERSTAGING_BASE_POS)
#define VT2_SMRC_LWICMMODETIMERSTAGING_ENABLE_POS 62
#define VT2_SMRC_LWICMMODETIMERSTAGING_ENABLE_WID 1
#define VT2_SMRC_LWICMMODETIMERSTAGING_ENABLE_MSK (((_ULL(1) << VT2_SMRC_LWICMMODETIMERSTAGING_ENABLE_WID) - _ULL(1)) << VT2_SMRC_LWICMMODETIMERSTAGING_ENABLE_POS)
#define VT2_SMRC_LWICMMODETIMERSTAGING_LOAD_POS 63
#define VT2_SMRC_LWICMMODETIMERSTAGING_LOAD_WID 1
#define VT2_SMRC_LWICMMODETIMERSTAGING_LOAD_MSK (((_ULL(1) << VT2_SMRC_LWICMMODETIMERSTAGING_LOAD_WID) - _ULL(1)) << VT2_SMRC_LWICMMODETIMERSTAGING_LOAD_POS)

#define VT2_SMRC_SMRCSTAGING_OFFSET _ULL(0x308)

#define VT2_SMRC_SMRCSTAGING_POS 14
#define VT2_SMRC_SMRCSTAGING_WID 50
#define VT2_SMRC_SMRCSTAGING_MSK (((_ULL(1) << VT2_SMRC_SMRCSTAGING_WID) - _ULL(1)) << VT2_SMRC_SMRCSTAGING_POS)

#define VT2_SMRC_SMRCSTAGING_BASE_POS 14
#define VT2_SMRC_SMRCSTAGING_BASE_WID 34
#define VT2_SMRC_SMRCSTAGING_BASE_MSK (((_ULL(1) << VT2_SMRC_SMRCSTAGING_BASE_WID) - _ULL(1)) << VT2_SMRC_SMRCSTAGING_BASE_POS)
#define VT2_SMRC_SMRCSTAGING_ENABLE_POS 62
#define VT2_SMRC_SMRCSTAGING_ENABLE_WID 1
#define VT2_SMRC_SMRCSTAGING_ENABLE_MSK (((_ULL(1) << VT2_SMRC_SMRCSTAGING_ENABLE_WID) - _ULL(1)) << VT2_SMRC_SMRCSTAGING_ENABLE_POS)
#define VT2_SMRC_SMRCSTAGING_LOAD_POS 63
#define VT2_SMRC_SMRCSTAGING_LOAD_WID 1
#define VT2_SMRC_SMRCSTAGING_LOAD_MSK (((_ULL(1) << VT2_SMRC_SMRCSTAGING_LOAD_WID) - _ULL(1)) << VT2_SMRC_SMRCSTAGING_LOAD_POS)

#define VT2_SMRC_CHIBSTAGING_OFFSET _ULL(0x30c)

#define VT2_SMRC_CHIBSTAGING_POS 14
#define VT2_SMRC_CHIBSTAGING_WID 50
#define VT2_SMRC_CHIBSTAGING_MSK (((_ULL(1) << VT2_SMRC_CHIBSTAGING_WID) - _ULL(1)) << VT2_SMRC_CHIBSTAGING_POS)

#define VT2_SMRC_CHIBSTAGING_BASE_POS 14
#define VT2_SMRC_CHIBSTAGING_BASE_WID 34
#define VT2_SMRC_CHIBSTAGING_BASE_MSK (((_ULL(1) << VT2_SMRC_CHIBSTAGING_BASE_WID) - _ULL(1)) << VT2_SMRC_CHIBSTAGING_BASE_POS)
#define VT2_SMRC_CHIBSTAGING_ENABLE_POS 62
#define VT2_SMRC_CHIBSTAGING_ENABLE_WID 1
#define VT2_SMRC_CHIBSTAGING_ENABLE_MSK (((_ULL(1) << VT2_SMRC_CHIBSTAGING_ENABLE_WID) - _ULL(1)) << VT2_SMRC_CHIBSTAGING_ENABLE_POS)
#define VT2_SMRC_CHIBSTAGING_LOAD_POS 63
#define VT2_SMRC_CHIBSTAGING_LOAD_WID 1
#define VT2_SMRC_CHIBSTAGING_LOAD_MSK (((_ULL(1) << VT2_SMRC_CHIBSTAGING_LOAD_WID) - _ULL(1)) << VT2_SMRC_CHIBSTAGING_LOAD_POS)

#define VT2_SMRC_CHPLSTAGING_OFFSET _ULL(0x380)

#define VT2_SMRC_CHPLSTAGING_POS 18
#define VT2_SMRC_CHPLSTAGING_WID 46
#define VT2_SMRC_CHPLSTAGING_MSK (((_ULL(1) << VT2_SMRC_CHPLSTAGING_WID) - _ULL(1)) << VT2_SMRC_CHPLSTAGING_POS)

#define VT2_SMRC_CHPLSTAGING_BASE_POS 18
#define VT2_SMRC_CHPLSTAGING_BASE_WID 30
#define VT2_SMRC_CHPLSTAGING_BASE_MSK (((_ULL(1) << VT2_SMRC_CHPLSTAGING_BASE_WID) - _ULL(1)) << VT2_SMRC_CHPLSTAGING_BASE_POS)
#define VT2_SMRC_CHPLSTAGING_ENABLE_POS 62
#define VT2_SMRC_CHPLSTAGING_ENABLE_WID 1
#define VT2_SMRC_CHPLSTAGING_ENABLE_MSK (((_ULL(1) << VT2_SMRC_CHPLSTAGING_ENABLE_WID) - _ULL(1)) << VT2_SMRC_CHPLSTAGING_ENABLE_POS)
#define VT2_SMRC_CHPLSTAGING_LOAD_POS 63
#define VT2_SMRC_CHPLSTAGING_LOAD_WID 1
#define VT2_SMRC_CHPLSTAGING_LOAD_MSK (((_ULL(1) << VT2_SMRC_CHPLSTAGING_LOAD_WID) - _ULL(1)) << VT2_SMRC_CHPLSTAGING_LOAD_POS)

#define VT2_SMRC_CKGNSTAGING_OFFSET _ULL(0x3c0)

#define VT2_SMRC_CKGNSTAGING_POS 14
#define VT2_SMRC_CKGNSTAGING_WID 50
#define VT2_SMRC_CKGNSTAGING_MSK (((_ULL(1) << VT2_SMRC_CKGNSTAGING_WID) - _ULL(1)) << VT2_SMRC_CKGNSTAGING_POS)

#define VT2_SMRC_CKGNSTAGING_BASE_POS 14
#define VT2_SMRC_CKGNSTAGING_BASE_WID 34
#define VT2_SMRC_CKGNSTAGING_BASE_MSK (((_ULL(1) << VT2_SMRC_CKGNSTAGING_BASE_WID) - _ULL(1)) << VT2_SMRC_CKGNSTAGING_BASE_POS)
#define VT2_SMRC_CKGNSTAGING_ENABLE_POS 62
#define VT2_SMRC_CKGNSTAGING_ENABLE_WID 1
#define VT2_SMRC_CKGNSTAGING_ENABLE_MSK (((_ULL(1) << VT2_SMRC_CKGNSTAGING_ENABLE_WID) - _ULL(1)) << VT2_SMRC_CKGNSTAGING_ENABLE_POS)
#define VT2_SMRC_CKGNSTAGING_LOAD_POS 63
#define VT2_SMRC_CKGNSTAGING_LOAD_WID 1
#define VT2_SMRC_CKGNSTAGING_LOAD_MSK (((_ULL(1) << VT2_SMRC_CKGNSTAGING_LOAD_WID) - _ULL(1)) << VT2_SMRC_CKGNSTAGING_LOAD_POS)

#define VT2_SMRC_I3CSTAGING_OFFSET _ULL(0x3d0)

#define VT2_SMRC_I3CSTAGING_POS 12
#define VT2_SMRC_I3CSTAGING_WID 52
#define VT2_SMRC_I3CSTAGING_MSK (((_ULL(1) << VT2_SMRC_I3CSTAGING_WID) - _ULL(1)) << VT2_SMRC_I3CSTAGING_POS)

#define VT2_SMRC_I3CSTAGING_BASE_POS 12
#define VT2_SMRC_I3CSTAGING_BASE_WID 36
#define VT2_SMRC_I3CSTAGING_BASE_MSK (((_ULL(1) << VT2_SMRC_I3CSTAGING_BASE_WID) - _ULL(1)) << VT2_SMRC_I3CSTAGING_BASE_POS)
#define VT2_SMRC_I3CSTAGING_ENABLE_POS 62
#define VT2_SMRC_I3CSTAGING_ENABLE_WID 1
#define VT2_SMRC_I3CSTAGING_ENABLE_MSK (((_ULL(1) << VT2_SMRC_I3CSTAGING_ENABLE_WID) - _ULL(1)) << VT2_SMRC_I3CSTAGING_ENABLE_POS)
#define VT2_SMRC_I3CSTAGING_LOAD_POS 63
#define VT2_SMRC_I3CSTAGING_LOAD_WID 1
#define VT2_SMRC_I3CSTAGING_LOAD_MSK (((_ULL(1) << VT2_SMRC_I3CSTAGING_LOAD_WID) - _ULL(1)) << VT2_SMRC_I3CSTAGING_LOAD_POS)

#define VT2_SMRC_D2DMCUSTAGING_OFFSET _ULL(0x3d1)

#define VT2_SMRC_D2DMCUSTAGING_POS 12
#define VT2_SMRC_D2DMCUSTAGING_WID 52
#define VT2_SMRC_D2DMCUSTAGING_MSK (((_ULL(1) << VT2_SMRC_D2DMCUSTAGING_WID) - _ULL(1)) << VT2_SMRC_D2DMCUSTAGING_POS)

#define VT2_SMRC_D2DMCUSTAGING_BASE_POS 12
#define VT2_SMRC_D2DMCUSTAGING_BASE_WID 36
#define VT2_SMRC_D2DMCUSTAGING_BASE_MSK (((_ULL(1) << VT2_SMRC_D2DMCUSTAGING_BASE_WID) - _ULL(1)) << VT2_SMRC_D2DMCUSTAGING_BASE_POS)
#define VT2_SMRC_D2DMCUSTAGING_ENABLE_POS 62
#define VT2_SMRC_D2DMCUSTAGING_ENABLE_WID 1
#define VT2_SMRC_D2DMCUSTAGING_ENABLE_MSK (((_ULL(1) << VT2_SMRC_D2DMCUSTAGING_ENABLE_WID) - _ULL(1)) << VT2_SMRC_D2DMCUSTAGING_ENABLE_POS)
#define VT2_SMRC_D2DMCUSTAGING_LOAD_POS 63
#define VT2_SMRC_D2DMCUSTAGING_LOAD_WID 1
#define VT2_SMRC_D2DMCUSTAGING_LOAD_MSK (((_ULL(1) << VT2_SMRC_D2DMCUSTAGING_LOAD_WID) - _ULL(1)) << VT2_SMRC_D2DMCUSTAGING_LOAD_POS)

#define VT2_SMRC_PCLSTAGING_OFFSET _ULL(0x3ff)

#define VT2_SMRC_PCLSTAGING_POS 24
#define VT2_SMRC_PCLSTAGING_WID 40
#define VT2_SMRC_PCLSTAGING_MSK (((_ULL(1) << VT2_SMRC_PCLSTAGING_WID) - _ULL(1)) << VT2_SMRC_PCLSTAGING_POS)

#define VT2_SMRC_PCLSTAGING_BASE_POS 24
#define VT2_SMRC_PCLSTAGING_BASE_WID 24
#define VT2_SMRC_PCLSTAGING_BASE_MSK (((_ULL(1) << VT2_SMRC_PCLSTAGING_BASE_WID) - _ULL(1)) << VT2_SMRC_PCLSTAGING_BASE_POS)
#define VT2_SMRC_PCLSTAGING_ENABLE_POS 62
#define VT2_SMRC_PCLSTAGING_ENABLE_WID 1
#define VT2_SMRC_PCLSTAGING_ENABLE_MSK (((_ULL(1) << VT2_SMRC_PCLSTAGING_ENABLE_WID) - _ULL(1)) << VT2_SMRC_PCLSTAGING_ENABLE_POS)
#define VT2_SMRC_PCLSTAGING_LOAD_POS 63
#define VT2_SMRC_PCLSTAGING_LOAD_WID 1
#define VT2_SMRC_PCLSTAGING_LOAD_MSK (((_ULL(1) << VT2_SMRC_PCLSTAGING_LOAD_WID) - _ULL(1)) << VT2_SMRC_PCLSTAGING_LOAD_POS)
#endif /* VT2_SMRC_MMR_H */
